// Code generated by gen_rdstats_neon.py. DO NOT EDIT.
// SPDX-License-Identifier: BSD-2-Clause
//
// See LICENSE for the BSD-2-Clause grant.

//go:build arm64 && !purego

#include "textflag.h"

// Residual extraction: dst[r*w+c] = src[row+c] - pred[r*predStride+c]
// over w x h bytes into int16, sixteen columns per step (w is 8, 16, or
// 32; the 8-wide tail uses the low half).

#define R_SRC 0
#define R_SRCSTRIDE 8
#define R_PRED 16
#define R_PREDSTRIDE 24
#define R_DST 32
#define R_W 40
#define R_H 48

// func residualNEONAsm(ctx *rdNEONCtx)
TEXT ·residualNEONAsm(SB), NOSPLIT, $0-8
	MOVD ctx+0(FP), R0
	MOVD R_SRC(R0), R1
	MOVD R_SRCSTRIDE(R0), R2
	MOVD R_PRED(R0), R3
	MOVD R_PREDSTRIDE(R0), R4
	MOVD R_DST(R0), R5
	MOVD R_W(R0), R6
	MOVD R_H(R0), R7
rrow:
	MOVD R1, R8
	MOVD R3, R9
	MOVD R6, R10
rcol16:
	CMP $16, R10
	BLT rcol8
	VLD1.P 16(R8), [V0.B16]
	VLD1.P 16(R9), [V1.B16]
	WORD $0x2e212002 // usubl v2.8h, v0.8b, v1.8b
	WORD $0x6e212003 // usubl2 v3.8h, v0.16b, v1.16b
	VST1.P [V2.H8, V3.H8], 32(R5)
	SUB $16, R10
	B rcol16
rcol8:
	CBZ R10, rnext
	VLD1 (R8), [V0.B8]
	VLD1 (R9), [V1.B8]
	WORD $0x2e212002 // usubl v2.8h, v0.8b, v1.8b
	VST1.P [V2.H8], 16(R5)
rnext:
	ADD R2, R1
	ADD R4, R3
	SUB $1, R7
	CBNZ R7, rrow
	RET

// RD statistics over a quantized transform block, eight coefficients per
// iteration with the AC step applied to every lane (the caller redoes the
// DC coefficient with the DC step):
//   dskip += c*c
//   dcode += (c - ((q*step)>>ts))^2
//   rate  += 2 + bits.Len16(|q|) over non-zero q (unshifted bit count)
//   zero  |= q lanes

#define S_TRAN 0
#define S_QCOEFF 8
#define S_COUNT 16
#define S_STEP 24
#define S_NSHIFT 32
#define S_DSKIP 40
#define S_DCODE 48
#define S_RATE 56
#define S_NONZERO 64

// func rdStatsNEONAsm(ctx *rdStatsNEONCtx)
TEXT ·rdStatsNEONAsm(SB), NOSPLIT, $0-8
	MOVD ctx+0(FP), R0
	MOVD S_TRAN(R0), R1
	MOVD S_QCOEFF(R0), R2
	MOVD S_COUNT(R0), R3
	MOVD S_STEP(R0), R4
	WORD $0x4e040c94 // dup v20.4s, w4
	MOVD S_NSHIFT(R0), R4
	WORD $0x4e040c95 // dup v21.4s, w4
	MOVD $2, R4
	WORD $0x4e020c9c // dup v28.8h, w4
	MOVD $16, R4
	WORD $0x4e020c9d // dup v29.8h, w4
	// zeroed accumulators: v22/v23 dskip, v24/v25 dcode (2d), v26 rate
	// (8h), v27 nonzero-or (16b)
	WORD $0x6e361ed6 // eor v22.16b, v22.16b, v22.16b
	WORD $0x6e371ef7 // eor v23.16b, v23.16b, v23.16b
	WORD $0x6e381f18 // eor v24.16b, v24.16b, v24.16b
	WORD $0x6e391f39 // eor v25.16b, v25.16b, v25.16b
	WORD $0x6e3a1f5a // eor v26.16b, v26.16b, v26.16b
	WORD $0x6e3b1f7b // eor v27.16b, v27.16b, v27.16b
	LSR $3, R3 // eight lanes per iteration
sloop:
	VLD1.P 32(R1), [V0.S4, V1.S4] // c lo/hi
	VLD1.P 16(R2), [V2.H8]        // q
	WORD $0x4ea21f7b // orr v27.16b, v27.16b, v2.16b
	// dskip += c*c
	WORD $0x0ea08016 // smlal v22.2d, v0.2s, v0.2s
	WORD $0x4ea08017 // smlal2 v23.2d, v0.4s, v0.4s
	WORD $0x0ea18036 // smlal v22.2d, v1.2s, v1.2s
	WORD $0x4ea18037 // smlal2 v23.2d, v1.4s, v1.4s
	// dq = (q*step) >> ts, e = c - dq
	WORD $0x0f10a443 // sshll v3.4s, v2.4h, #0
	WORD $0x4f10a444 // sshll2 v4.4s, v2.8h, #0
	WORD $0x4f948063 // mul v3.4s, v3.4s, v20.s[0]
	WORD $0x4f948084 // mul v4.4s, v4.4s, v20.s[0]
	WORD $0x4eb54463 // sshl v3.4s, v3.4s, v21.4s
	WORD $0x4eb54484 // sshl v4.4s, v4.4s, v21.4s
	WORD $0x6ea38403 // sub v3.4s, v0.4s, v3.4s
	WORD $0x6ea48424 // sub v4.4s, v1.4s, v4.4s
	// dcode += e*e
	WORD $0x0ea38078 // smlal v24.2d, v3.2s, v3.2s
	WORD $0x4ea38079 // smlal2 v25.2d, v3.4s, v3.4s
	WORD $0x0ea48098 // smlal v24.2d, v4.2s, v4.2s
	WORD $0x4ea48099 // smlal2 v25.2d, v4.4s, v4.4s
	// rate += (2 + 16 - clz(|q|)) on non-zero lanes
	WORD $0x4e60b845 // abs v5.8h, v2.8h
	WORD $0x6e6048a6 // clz v6.8h, v5.8h
	WORD $0x6e6687a6 // sub v6.8h, v29.8h, v6.8h
	WORD $0x4e7c84c6 // add v6.8h, v6.8h, v28.8h
	WORD $0x4e609847 // cmeq v7.8h, v2.8h, #0
	WORD $0x4e671cc6 // bic v6.16b, v6.16b, v7.16b
	WORD $0x4e66875a // add v26.8h, v26.8h, v6.8h
	SUB $1, R3
	CBNZ R3, sloop
	// reduce and store
	WORD $0x4ef786d6 // add v22.2d, v22.2d, v23.2d
	WORD $0x5ef1bad6 // addp d22, v22.2d
	VMOV V22.D[0], R4
	MOVD R4, S_DSKIP(R0)
	WORD $0x4ef98718 // add v24.2d, v24.2d, v25.2d
	WORD $0x5ef1bb18 // addp d24, v24.2d
	VMOV V24.D[0], R4
	MOVD R4, S_DCODE(R0)
	WORD $0x6e703b40 // uaddlv s0, v26.8h
	VMOV V0.S[0], R4
	MOVD R4, S_RATE(R0)
	WORD $0x6e30ab61 // umaxv b1, v27.16b
	VMOV V1.B[0], R4
	MOVD R4, S_NONZERO(R0)
	RET
