package goav1

import (
	internalloopfilter "github.com/thesyncim/goav1/internal/av1/loopfilter"
	internalrestoration "github.com/thesyncim/goav1/internal/av1/restoration"
	internaltile "github.com/thesyncim/goav1/internal/av1/tile"
)

type LoopFilterPlane = internalloopfilter.Plane
type LoopFilterEdge = internalloopfilter.Edge

type TileTransformSize = internaltile.TransformSize

type TileRestorationSGRProjInfo = internaltile.SGRProjInfo
type TileRestorationUnit = internaltile.RestorationUnit
type TileRestorationUnitRect = internaltile.RestorationUnitRect
type TileRestorationProcessingStripe = internaltile.RestorationProcessingStripe
type TileRestorationProcessingUnit = internaltile.RestorationProcessingUnit
type TileRestorationPlaneGrid = internaltile.RestorationPlaneGrid
type TileRestorationUnitRange = internaltile.RestorationUnitRange
type TileRestorationUnitRecord = internaltile.RestorationUnitRecord
type TileRestorationFramePlan = internaltile.RestorationFramePlan
type TileRestorationStripeBoundaries = internaltile.RestorationStripeBoundaries
type TileRestorationFrameBoundaryPlane = internaltile.RestorationFrameBoundaryPlane
type TileRestorationStripeBoundaryScratchSize = internaltile.RestorationStripeBoundaryScratchSize
type TileRestorationStripeBoundaryScratch = internaltile.RestorationStripeBoundaryScratch
type TileRestorationStripeBoundaryBufferSize = internaltile.RestorationStripeBoundaryBufferSize
type TileRestorationUnitScratchSize = internaltile.RestorationUnitScratchSize
type TileRestorationUnitScratch = internaltile.RestorationUnitScratch
type TileRestorationUnitApplyResult = internaltile.RestorationUnitApplyResult
type TileRestorationUnitRecordApplyResult = internaltile.RestorationUnitRecordApplyResult
type TileRestorationPlaneApplyResult = internaltile.RestorationPlaneApplyResult
type TileRestorationFramePlane = internaltile.RestorationFramePlane
type TileRestorationFrameApplyResult = internaltile.RestorationFrameApplyResult
type TileRestorationUnitRecordBoundaryScratchSize = internaltile.RestorationUnitRecordBoundaryScratchSize
type TileRestorationUnitRecordBoundaryScratch = internaltile.RestorationUnitRecordBoundaryScratch
type TileRestorationFrameSampleScratchSize = internaltile.RestorationFrameSampleScratchSize

type RestorationWienerFilter = internalrestoration.WienerFilter
type RestorationWienerInfo = internalrestoration.WienerInfo
type RestorationSGRParams = internalrestoration.SGRParams

const (
	LoopFilterPlaneY LoopFilterPlane = internalloopfilter.PlaneY
	LoopFilterPlaneU LoopFilterPlane = internalloopfilter.PlaneU
	LoopFilterPlaneV LoopFilterPlane = internalloopfilter.PlaneV

	LoopFilterEdgeVertical   LoopFilterEdge = internalloopfilter.EdgeVertical
	LoopFilterEdgeHorizontal LoopFilterEdge = internalloopfilter.EdgeHorizontal

	TileTransformSize4x4   TileTransformSize = internaltile.TransformSize4x4
	TileTransformSize8x8   TileTransformSize = internaltile.TransformSize8x8
	TileTransformSize16x16 TileTransformSize = internaltile.TransformSize16x16
	TileTransformSize32x32 TileTransformSize = internaltile.TransformSize32x32
	TileTransformSize64x64 TileTransformSize = internaltile.TransformSize64x64
	TileTransformSize4x8   TileTransformSize = internaltile.TransformSize4x8
	TileTransformSize8x4   TileTransformSize = internaltile.TransformSize8x4
	TileTransformSize8x16  TileTransformSize = internaltile.TransformSize8x16
	TileTransformSize16x8  TileTransformSize = internaltile.TransformSize16x8
	TileTransformSize16x32 TileTransformSize = internaltile.TransformSize16x32
	TileTransformSize32x16 TileTransformSize = internaltile.TransformSize32x16
	TileTransformSize32x64 TileTransformSize = internaltile.TransformSize32x64
	TileTransformSize64x32 TileTransformSize = internaltile.TransformSize64x32
	TileTransformSize4x16  TileTransformSize = internaltile.TransformSize4x16
	TileTransformSize16x4  TileTransformSize = internaltile.TransformSize16x4
	TileTransformSize8x32  TileTransformSize = internaltile.TransformSize8x32
	TileTransformSize32x8  TileTransformSize = internaltile.TransformSize32x8
	TileTransformSize16x64 TileTransformSize = internaltile.TransformSize16x64
	TileTransformSize64x16 TileTransformSize = internaltile.TransformSize64x16
)
