// SPDX-License-Identifier: BSD-2-Clause
//
// See LICENSE for the BSD-2-Clause grant.

// Code generated by an offline NEON encoder; do not edit by hand.
// Every WORD below is the little-endian encoding of the mnemonic in its
// trailing comment, assembled and verified with the system assembler. The
// kernel is bit-exact with filter4EdgePureGo (see filter4.go); the Go wrapper
// in filter4_neon_arm64.go restricts it to 8-bit horizontal edges processed in
// groups of eight positions.

//go:build arm64 && !purego

#include "textflag.h"

#define P1 0
#define P0 8
#define Q0 16
#define Q1 24
#define OUTER 32
#define COUNT 40
#define LIMIT 48
#define BLIMIT 56
#define HEV 64

// func filter4EdgeNEONAsm(ctx *filter4NEONCtx)
TEXT ·filter4EdgeNEONAsm(SB), NOSPLIT, $0-8
	MOVD ctx+0(FP), R0
	MOVD P1(R0), R9
	MOVD P0(R0), R10
	MOVD Q0(R0), R11
	MOVD Q1(R0), R12
	MOVD COUNT(R0), R13

	MOVD LIMIT(R0), R6
	WORD $0x4e020cc0 // dup v0.8h, w6
	MOVD BLIMIT(R0), R7
	WORD $0x4e020ce1 // dup v1.8h, w7
	MOVD HEV(R0), R8
	WORD $0x4e020d02 // dup v2.8h, w8
	WORD $0x4f048403 // movi v3.8h, #128
	WORD $0x6f0387e4 // mvni v4.8h, #127   (-128)
	WORD $0x4f0387e5 // movi v5.8h, #127
	WORD $0x4f008466 // movi v6.8h, #3
	WORD $0x4f008487 // movi v7.8h, #4

loop:
	CBZ R13, done

	WORD $0x0c407130 // ld1 {v16.8b}, [x9]
	WORD $0x0c407151 // ld1 {v17.8b}, [x10]
	WORD $0x0c407172 // ld1 {v18.8b}, [x11]
	WORD $0x0c407193 // ld1 {v19.8b}, [x12]
	WORD $0x2f08a610 // uxtl v16.8h, v16.8b
	WORD $0x2f08a631 // uxtl v17.8h, v17.8b
	WORD $0x2f08a652 // uxtl v18.8h, v18.8b
	WORD $0x2f08a673 // uxtl v19.8h, v19.8b

	WORD $0x6e638614 // sub v20.8h, v16.8h, v3.8h  (ps1)
	WORD $0x6e638635 // sub v21.8h, v17.8h, v3.8h  (ps0)
	WORD $0x6e638656 // sub v22.8h, v18.8h, v3.8h  (qs0)
	WORD $0x6e638677 // sub v23.8h, v19.8h, v3.8h  (qs1)

	WORD $0x6e718618 // sub v24.8h, v16.8h, v17.8h
	WORD $0x4e60bb18 // abs v24.8h, v24.8h          (|p1-p0|)
	WORD $0x6e728679 // sub v25.8h, v19.8h, v18.8h
	WORD $0x4e60bb39 // abs v25.8h, v25.8h          (|q1-q0|)
	WORD $0x6e72863a // sub v26.8h, v17.8h, v18.8h
	WORD $0x4e60bb5a // abs v26.8h, v26.8h          (|p0-q0|)
	WORD $0x6e73861b // sub v27.8h, v16.8h, v19.8h
	WORD $0x4e60bb7b // abs v27.8h, v27.8h          (|p1-q1|)

	WORD $0x4e783c1c // cmge v28.8h, v0.8h, v24.8h  (limit>=|p1-p0|)
	WORD $0x4e793c1d // cmge v29.8h, v0.8h, v25.8h  (limit>=|q1-q0|)
	WORD $0x4e3d1f9c // and v28.16b, v28.16b, v29.16b
	WORD $0x4f11575e // shl v30.8h, v26.8h, #1      (|p0-q0|*2)
	WORD $0x4f1f077f // sshr v31.8h, v27.8h, #1     (|p1-q1|/2)
	WORD $0x4e7f87de // add v30.8h, v30.8h, v31.8h
	WORD $0x4e7e3c3d // cmge v29.8h, v1.8h, v30.8h  (blimit>=sum)
	WORD $0x4e3d1f9c // and v28.16b, v28.16b, v29.16b  (needMask)

	WORD $0x4e62371d // cmgt v29.8h, v24.8h, v2.8h  (|p1-p0|>hev)
	WORD $0x4e62373e // cmgt v30.8h, v25.8h, v2.8h  (|q1-q0|>hev)
	WORD $0x4ebe1fbd // orr v29.16b, v29.16b, v30.16b  (hevMask)

	WORD $0x6e778698 // sub v24.8h, v20.8h, v23.8h  (ps1-qs1)
	WORD $0x4e656f18 // smin v24.8h, v24.8h, v5.8h
	WORD $0x4e646718 // smax v24.8h, v24.8h, v4.8h  (clamp)
	WORD $0x4e3d1f18 // and v24.16b, v24.16b, v29.16b (hev? :0)
	WORD $0x6e7586d9 // sub v25.8h, v22.8h, v21.8h  (qs0-ps0)
	WORD $0x4e669f39 // mul v25.8h, v25.8h, v6.8h   (*3)
	WORD $0x4e798718 // add v24.8h, v24.8h, v25.8h
	WORD $0x4e656f18 // smin v24.8h, v24.8h, v5.8h
	WORD $0x4e646718 // smax v24.8h, v24.8h, v4.8h  (filter)

	WORD $0x4e678719 // add v25.8h, v24.8h, v7.8h   (filter+4)
	WORD $0x4e656f39 // smin v25.8h, v25.8h, v5.8h
	WORD $0x4e646739 // smax v25.8h, v25.8h, v4.8h
	WORD $0x4f1d0739 // sshr v25.8h, v25.8h, #3     (filter1)
	WORD $0x4e66871a // add v26.8h, v24.8h, v6.8h   (filter+3)
	WORD $0x4e656f5a // smin v26.8h, v26.8h, v5.8h
	WORD $0x4e64675a // smax v26.8h, v26.8h, v4.8h
	WORD $0x4f1d075a // sshr v26.8h, v26.8h, #3     (filter2)

	WORD $0x4f1f2738 // srshr v24.8h, v25.8h, #1    (outer=(filter1+1)>>1)

	WORD $0x4e7a86bb // add v27.8h, v21.8h, v26.8h  (ps0+filter2)
	WORD $0x4e656f7b // smin v27.8h, v27.8h, v5.8h
	WORD $0x4e64677b // smax v27.8h, v27.8h, v4.8h
	WORD $0x4e63877b // add v27.8h, v27.8h, v3.8h   (p0')

	WORD $0x6e7986de // sub v30.8h, v22.8h, v25.8h  (qs0-filter1)
	WORD $0x4e656fde // smin v30.8h, v30.8h, v5.8h
	WORD $0x4e6467de // smax v30.8h, v30.8h, v4.8h
	WORD $0x4e6387de // add v30.8h, v30.8h, v3.8h   (q0')

	WORD $0x4e78869f // add v31.8h, v20.8h, v24.8h  (ps1+outer)
	WORD $0x4e656fff // smin v31.8h, v31.8h, v5.8h
	WORD $0x4e6467ff // smax v31.8h, v31.8h, v4.8h
	WORD $0x4e6387ff // add v31.8h, v31.8h, v3.8h   (p1')

	WORD $0x6e7886f9 // sub v25.8h, v23.8h, v24.8h  (qs1-outer)
	WORD $0x4e656f39 // smin v25.8h, v25.8h, v5.8h
	WORD $0x4e646739 // smax v25.8h, v25.8h, v4.8h
	WORD $0x4e638739 // add v25.8h, v25.8h, v3.8h   (q1')

	WORD $0x4e7d1f9a // bic v26.16b, v28.16b, v29.16b (needMask & ~hev)

	WORD $0x4ebc1f94 // mov v20.16b, v28.16b
	WORD $0x6e711f74 // bsl v20.16b, v27.16b, v17.16b (need?p0':p0)
	WORD $0x4ebc1f95 // mov v21.16b, v28.16b
	WORD $0x6e721fd5 // bsl v21.16b, v30.16b, v18.16b (need?q0':q0)
	WORD $0x4eba1f56 // mov v22.16b, v26.16b
	WORD $0x6e701ff6 // bsl v22.16b, v31.16b, v16.16b (nh?p1':p1)
	WORD $0x4eba1f57 // mov v23.16b, v26.16b
	WORD $0x6e731f37 // bsl v23.16b, v25.16b, v19.16b (nh?q1':q1)

	WORD $0x0e212a94 // xtn v20.8b, v20.8h
	WORD $0x0e212ab5 // xtn v21.8b, v21.8h
	WORD $0x0e212ad6 // xtn v22.8b, v22.8h
	WORD $0x0e212af7 // xtn v23.8b, v23.8h

	WORD $0x0c007136 // st1 {v22.8b}, [x9]   (p1)
	WORD $0x0c007154 // st1 {v20.8b}, [x10]  (p0)
	WORD $0x0c007175 // st1 {v21.8b}, [x11]  (q0)
	WORD $0x0c007197 // st1 {v23.8b}, [x12]  (q1)

	ADD $8, R9, R9
	ADD $8, R10, R10
	ADD $8, R11, R11
	ADD $8, R12, R12
	SUB $1, R13, R13
	B   loop

done:
	RET
