// SPDX-License-Identifier: BSD-2-Clause
//
// See LICENSE for the BSD-2-Clause grant.

// Code generated by an offline NEON encoder; do not edit by hand.
// Every WORD below is the little-endian encoding of the mnemonic in its
// trailing comment, assembled and verified with the system assembler. The
// kernels are bit-exact with filter6EdgePureGo / filter8EdgePureGo (see
// filter6.go / filter8.go); the Go wrappers in filter_wide_neon_arm64.go
// restrict them to 8-bit horizontal edges processed in groups of eight.

//go:build arm64 && !purego

#include "textflag.h"

// ---- filter6 context offsets ----
#define F6_P2 0
#define F6_P1 8
#define F6_P0 16
#define F6_Q0 24
#define F6_Q1 32
#define F6_Q2 40
#define F6_COUNT 48
#define F6_LIMIT 56
#define F6_BLIMIT 64
#define F6_HEV 72
#define F6_THR 80

// func filter6EdgeNEONAsm(ctx *filter6NEONCtx)
TEXT ·filter6EdgeNEONAsm(SB), NOSPLIT, $0-8
	MOVD ctx+0(FP), R0
	MOVD F6_P2(R0), R9
	MOVD F6_P1(R0), R10
	MOVD F6_P0(R0), R11
	MOVD F6_Q0(R0), R12
	MOVD F6_Q1(R0), R13
	MOVD F6_Q2(R0), R14
	MOVD F6_COUNT(R0), R15

	MOVD F6_LIMIT(R0), R6
	WORD $0x4e020cc0 // dup v0.8h, w6
	MOVD F6_BLIMIT(R0), R7
	WORD $0x4e020ce1 // dup v1.8h, w7
	MOVD F6_HEV(R0), R8
	WORD $0x4e020d02 // dup v2.8h, w8
	MOVD F6_THR(R0), R5
	WORD $0x4e020ca3 // dup v3.8h, w5
	WORD $0x4f048404 // movi v4.8h, #128
	WORD $0x6f0387e5 // mvni v5.8h, #127  (-128)
	WORD $0x4f0387e6 // movi v6.8h, #127
	WORD $0x4f008467 // movi v7.8h, #3

loop6:
	CBZ R15, done6
	WORD $0x0c407130 // ld1 {v16.8b}, [x9]
	WORD $0x0c407151 // ld1 {v17.8b}, [x10]
	WORD $0x0c407172 // ld1 {v18.8b}, [x11]
	WORD $0x0c407193 // ld1 {v19.8b}, [x12]
	WORD $0x0c4071b4 // ld1 {v20.8b}, [x13]
	WORD $0x0c4071d5 // ld1 {v21.8b}, [x14]
	WORD $0x2f08a610 // uxtl v16.8h, v16.8b
	WORD $0x2f08a631 // uxtl v17.8h, v17.8b
	WORD $0x2f08a652 // uxtl v18.8h, v18.8b
	WORD $0x2f08a673 // uxtl v19.8h, v19.8b
	WORD $0x2f08a694 // uxtl v20.8h, v20.8b
	WORD $0x2f08a6b5 // uxtl v21.8h, v21.8b
	WORD $0x6e718616 // sub v22.8h, v16.8h, v17.8h
	WORD $0x4e60bad6 // abs v22.8h, v22.8h
	WORD $0x6e728637 // sub v23.8h, v17.8h, v18.8h
	WORD $0x4e60baf7 // abs v23.8h, v23.8h
	WORD $0x6e738698 // sub v24.8h, v20.8h, v19.8h
	WORD $0x4e60bb18 // abs v24.8h, v24.8h
	WORD $0x6e7486b9 // sub v25.8h, v21.8h, v20.8h
	WORD $0x4e60bb39 // abs v25.8h, v25.8h
	WORD $0x6e73865a // sub v26.8h, v18.8h, v19.8h
	WORD $0x4e60bb5a // abs v26.8h, v26.8h
	WORD $0x6e74863b // sub v27.8h, v17.8h, v20.8h
	WORD $0x4e60bb7b // abs v27.8h, v27.8h
	WORD $0x4e763c1c // cmge v28.8h, v0.8h, v22.8h
	WORD $0x4e773c1e // cmge v30.8h, v0.8h, v23.8h
	WORD $0x4e3e1f9c // and v28.16b, v28.16b, v30.16b
	WORD $0x4e783c1e // cmge v30.8h, v0.8h, v24.8h
	WORD $0x4e3e1f9c // and v28.16b, v28.16b, v30.16b
	WORD $0x4e793c1e // cmge v30.8h, v0.8h, v25.8h
	WORD $0x4e3e1f9c // and v28.16b, v28.16b, v30.16b
	WORD $0x4f11575e // shl v30.8h, v26.8h, #1
	WORD $0x4f1f077f // sshr v31.8h, v27.8h, #1
	WORD $0x4e7f87de // add v30.8h, v30.8h, v31.8h
	WORD $0x4e7e3c3e // cmge v30.8h, v1.8h, v30.8h
	WORD $0x4e3e1f9c // and v28.16b, v28.16b, v30.16b
	WORD $0x4e773c7d // cmge v29.8h, v3.8h, v23.8h
	WORD $0x4e783c7e // cmge v30.8h, v3.8h, v24.8h
	WORD $0x4e3e1fbd // and v29.16b, v29.16b, v30.16b
	WORD $0x6e72861e // sub v30.8h, v16.8h, v18.8h
	WORD $0x4e60bbde // abs v30.8h, v30.8h
	WORD $0x4e7e3c7e // cmge v30.8h, v3.8h, v30.8h
	WORD $0x4e3e1fbd // and v29.16b, v29.16b, v30.16b
	WORD $0x6e7386be // sub v30.8h, v21.8h, v19.8h
	WORD $0x4e60bbde // abs v30.8h, v30.8h
	WORD $0x4e7e3c7e // cmge v30.8h, v3.8h, v30.8h
	WORD $0x4e3e1fbd // and v29.16b, v29.16b, v30.16b
	WORD $0x6e64863a // sub v26.8h, v17.8h, v4.8h
	WORD $0x6e64869b // sub v27.8h, v20.8h, v4.8h
	WORD $0x6e64867e // sub v30.8h, v19.8h, v4.8h
	WORD $0x6e64865f // sub v31.8h, v18.8h, v4.8h
	WORD $0x6e728636 // sub v22.8h, v17.8h, v18.8h
	WORD $0x4e60bad6 // abs v22.8h, v22.8h
	WORD $0x4e6236d9 // cmgt v25.8h, v22.8h, v2.8h
	WORD $0x6e738696 // sub v22.8h, v20.8h, v19.8h
	WORD $0x4e60bad6 // abs v22.8h, v22.8h
	WORD $0x4e6236d6 // cmgt v22.8h, v22.8h, v2.8h
	WORD $0x4eb61f39 // orr v25.16b, v25.16b, v22.16b
	WORD $0x6e7b8756 // sub v22.8h, v26.8h, v27.8h
	WORD $0x4e666ed6 // smin v22.8h, v22.8h, v6.8h
	WORD $0x4e6566d6 // smax v22.8h, v22.8h, v5.8h
	WORD $0x4e391ed6 // and v22.16b, v22.16b, v25.16b
	WORD $0x6e7f87d7 // sub v23.8h, v30.8h, v31.8h
	WORD $0x4e679ef7 // mul v23.8h, v23.8h, v7.8h
	WORD $0x4e7786d6 // add v22.8h, v22.8h, v23.8h
	WORD $0x4e666ed6 // smin v22.8h, v22.8h, v6.8h
	WORD $0x4e6566d6 // smax v22.8h, v22.8h, v5.8h
	WORD $0x4f008498 // movi v24.8h, #4
	WORD $0x4e7886d7 // add v23.8h, v22.8h, v24.8h
	WORD $0x4e666ef7 // smin v23.8h, v23.8h, v6.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4f1d06f7 // sshr v23.8h, v23.8h, #3
	WORD $0x4e6786d8 // add v24.8h, v22.8h, v7.8h
	WORD $0x4e666f18 // smin v24.8h, v24.8h, v6.8h
	WORD $0x4e656718 // smax v24.8h, v24.8h, v5.8h
	WORD $0x4f1d0718 // sshr v24.8h, v24.8h, #3
	WORD $0x4f1f26f6 // srshr v22.8h, v23.8h, #1
	WORD $0x6e64863a // sub v26.8h, v17.8h, v4.8h
	WORD $0x4e76875a // add v26.8h, v26.8h, v22.8h
	WORD $0x4e666f5a // smin v26.8h, v26.8h, v6.8h
	WORD $0x4e65675a // smax v26.8h, v26.8h, v5.8h
	WORD $0x4e64875a // add v26.8h, v26.8h, v4.8h
	WORD $0x4eb91f3e // mov v30.16b, v25.16b
	WORD $0x6e7a1e3e // bsl v30.16b, v17.16b, v26.16b
	WORD $0x4e679e1f // mul v31.8h, v16.8h, v7.8h
	WORD $0x4f11563a // shl v26.8h, v17.8h, #1
	WORD $0x4e7a87ff // add v31.8h, v31.8h, v26.8h
	WORD $0x4f11565a // shl v26.8h, v18.8h, #1
	WORD $0x4e7a87ff // add v31.8h, v31.8h, v26.8h
	WORD $0x4e7387ff // add v31.8h, v31.8h, v19.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4ebd1fba // mov v26.16b, v29.16b
	WORD $0x6e7e1ffa // bsl v26.16b, v31.16b, v30.16b
	WORD $0x4ebc1f9b // mov v27.16b, v28.16b
	WORD $0x6e711f5b // bsl v27.16b, v26.16b, v17.16b
	WORD $0x0e212b7b // xtn v27.8b, v27.8h
	WORD $0x0c00715b // st1 {v27.8b}, [x10]
	WORD $0x6e64865a // sub v26.8h, v18.8h, v4.8h
	WORD $0x4e78875a // add v26.8h, v26.8h, v24.8h
	WORD $0x4e666f5a // smin v26.8h, v26.8h, v6.8h
	WORD $0x4e65675a // smax v26.8h, v26.8h, v5.8h
	WORD $0x4e64875a // add v26.8h, v26.8h, v4.8h
	WORD $0x4e74861f // add v31.8h, v16.8h, v20.8h
	WORD $0x4f11563e // shl v30.8h, v17.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f11565e // shl v30.8h, v18.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f11567e // shl v30.8h, v19.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4ebd1fbe // mov v30.16b, v29.16b
	WORD $0x6e7a1ffe // bsl v30.16b, v31.16b, v26.16b
	WORD $0x4ebc1f9b // mov v27.16b, v28.16b
	WORD $0x6e721fdb // bsl v27.16b, v30.16b, v18.16b
	WORD $0x0e212b7b // xtn v27.8b, v27.8h
	WORD $0x0c00717b // st1 {v27.8b}, [x11]
	WORD $0x6e64867a // sub v26.8h, v19.8h, v4.8h
	WORD $0x6e77875a // sub v26.8h, v26.8h, v23.8h
	WORD $0x4e666f5a // smin v26.8h, v26.8h, v6.8h
	WORD $0x4e65675a // smax v26.8h, v26.8h, v5.8h
	WORD $0x4e64875a // add v26.8h, v26.8h, v4.8h
	WORD $0x4e75863f // add v31.8h, v17.8h, v21.8h
	WORD $0x4f11565e // shl v30.8h, v18.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f11567e // shl v30.8h, v19.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f11569e // shl v30.8h, v20.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4ebd1fbe // mov v30.16b, v29.16b
	WORD $0x6e7a1ffe // bsl v30.16b, v31.16b, v26.16b
	WORD $0x4ebc1f9b // mov v27.16b, v28.16b
	WORD $0x6e731fdb // bsl v27.16b, v30.16b, v19.16b
	WORD $0x0e212b7b // xtn v27.8b, v27.8h
	WORD $0x0c00719b // st1 {v27.8b}, [x12]
	WORD $0x6e64869a // sub v26.8h, v20.8h, v4.8h
	WORD $0x6e76875a // sub v26.8h, v26.8h, v22.8h
	WORD $0x4e666f5a // smin v26.8h, v26.8h, v6.8h
	WORD $0x4e65675a // smax v26.8h, v26.8h, v5.8h
	WORD $0x4e64875a // add v26.8h, v26.8h, v4.8h
	WORD $0x4eb91f3e // mov v30.16b, v25.16b
	WORD $0x6e7a1e9e // bsl v30.16b, v20.16b, v26.16b
	WORD $0x4e679ebf // mul v31.8h, v21.8h, v7.8h
	WORD $0x4f11569a // shl v26.8h, v20.8h, #1
	WORD $0x4e7a87ff // add v31.8h, v31.8h, v26.8h
	WORD $0x4f11567a // shl v26.8h, v19.8h, #1
	WORD $0x4e7a87ff // add v31.8h, v31.8h, v26.8h
	WORD $0x4e7287ff // add v31.8h, v31.8h, v18.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4ebd1fba // mov v26.16b, v29.16b
	WORD $0x6e7e1ffa // bsl v26.16b, v31.16b, v30.16b
	WORD $0x4ebc1f9b // mov v27.16b, v28.16b
	WORD $0x6e741f5b // bsl v27.16b, v26.16b, v20.16b
	WORD $0x0e212b7b // xtn v27.8b, v27.8h
	WORD $0x0c0071bb // st1 {v27.8b}, [x13]
	ADD $8, R9, R9
	ADD $8, R10, R10
	ADD $8, R11, R11
	ADD $8, R12, R12
	ADD $8, R13, R13
	ADD $8, R14, R14
	SUB $1, R15, R15
	B   loop6

done6:
	RET

// ---- filter8 context offsets ----
#define F8_P3 0
#define F8_P2 8
#define F8_P1 16
#define F8_P0 24
#define F8_Q0 32
#define F8_Q1 40
#define F8_Q2 48
#define F8_Q3 56
#define F8_COUNT 64
#define F8_LIMIT 72
#define F8_BLIMIT 80
#define F8_HEV 88
#define F8_THR 96

// func filter8EdgeNEONAsm(ctx *filter8NEONCtx)
TEXT ·filter8EdgeNEONAsm(SB), NOSPLIT, $0-8
	MOVD ctx+0(FP), R0
	MOVD F8_P3(R0), R9
	MOVD F8_P2(R0), R10
	MOVD F8_P1(R0), R11
	MOVD F8_P0(R0), R12
	MOVD F8_Q0(R0), R13
	MOVD F8_Q1(R0), R14
	MOVD F8_Q2(R0), R15
	MOVD F8_Q3(R0), R16
	MOVD F8_COUNT(R0), R17

	MOVD F8_LIMIT(R0), R6
	WORD $0x4e020cc0 // dup v0.8h, w6
	MOVD F8_BLIMIT(R0), R7
	WORD $0x4e020ce1 // dup v1.8h, w7
	MOVD F8_HEV(R0), R8
	WORD $0x4e020d02 // dup v2.8h, w8
	MOVD F8_THR(R0), R5
	WORD $0x4e020ca3 // dup v3.8h, w5
	WORD $0x4f048404 // movi v4.8h, #128
	WORD $0x6f0387e5 // mvni v5.8h, #127  (-128)
	WORD $0x4f0387e6 // movi v6.8h, #127
	WORD $0x4f008467 // movi v7.8h, #3

loop8:
	CBZ R17, done8
	WORD $0x0c407130 // ld1 {v16.8b}, [x9]
	WORD $0x0c407151 // ld1 {v17.8b}, [x10]
	WORD $0x0c407172 // ld1 {v18.8b}, [x11]
	WORD $0x0c407193 // ld1 {v19.8b}, [x12]
	WORD $0x0c4071b4 // ld1 {v20.8b}, [x13]
	WORD $0x0c4071d5 // ld1 {v21.8b}, [x14]
	WORD $0x0c4071f6 // ld1 {v22.8b}, [x15]
	WORD $0x0c407217 // ld1 {v23.8b}, [x16]
	WORD $0x2f08a610 // uxtl v16.8h, v16.8b
	WORD $0x2f08a631 // uxtl v17.8h, v17.8b
	WORD $0x2f08a652 // uxtl v18.8h, v18.8b
	WORD $0x2f08a673 // uxtl v19.8h, v19.8b
	WORD $0x2f08a694 // uxtl v20.8h, v20.8b
	WORD $0x2f08a6b5 // uxtl v21.8h, v21.8b
	WORD $0x2f08a6d6 // uxtl v22.8h, v22.8b
	WORD $0x2f08a6f7 // uxtl v23.8h, v23.8b
	WORD $0x6e71861d // sub v29.8h, v16.8h, v17.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c18 // cmge v24.8h, v0.8h, v29.8h
	WORD $0x6e72863d // sub v29.8h, v17.8h, v18.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c1e // cmge v30.8h, v0.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e73865d // sub v29.8h, v18.8h, v19.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c1e // cmge v30.8h, v0.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e7486bd // sub v29.8h, v21.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c1e // cmge v30.8h, v0.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e7586dd // sub v29.8h, v22.8h, v21.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c1e // cmge v30.8h, v0.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e7686fd // sub v29.8h, v23.8h, v22.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c1e // cmge v30.8h, v0.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e74867d // sub v29.8h, v19.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4f1157bd // shl v29.8h, v29.8h, #1
	WORD $0x6e75865e // sub v30.8h, v18.8h, v21.8h
	WORD $0x4e60bbde // abs v30.8h, v30.8h
	WORD $0x4f1f07de // sshr v30.8h, v30.8h, #1
	WORD $0x4e7e87bd // add v29.8h, v29.8h, v30.8h
	WORD $0x4e7d3c3e // cmge v30.8h, v1.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e73865d // sub v29.8h, v18.8h, v19.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c79 // cmge v25.8h, v3.8h, v29.8h
	WORD $0x6e7486bd // sub v29.8h, v21.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c7e // cmge v30.8h, v3.8h, v29.8h
	WORD $0x4e3e1f39 // and v25.16b, v25.16b, v30.16b
	WORD $0x6e73863d // sub v29.8h, v17.8h, v19.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c7e // cmge v30.8h, v3.8h, v29.8h
	WORD $0x4e3e1f39 // and v25.16b, v25.16b, v30.16b
	WORD $0x6e7486dd // sub v29.8h, v22.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c7e // cmge v30.8h, v3.8h, v29.8h
	WORD $0x4e3e1f39 // and v25.16b, v25.16b, v30.16b
	WORD $0x6e73861d // sub v29.8h, v16.8h, v19.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c7e // cmge v30.8h, v3.8h, v29.8h
	WORD $0x4e3e1f39 // and v25.16b, v25.16b, v30.16b
	WORD $0x6e7486fd // sub v29.8h, v23.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c7e // cmge v30.8h, v3.8h, v29.8h
	WORD $0x4e3e1f39 // and v25.16b, v25.16b, v30.16b
	WORD $0x6e73865d // sub v29.8h, v18.8h, v19.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e6237ba // cmgt v26.8h, v29.8h, v2.8h
	WORD $0x6e7486bd // sub v29.8h, v21.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e6237bd // cmgt v29.8h, v29.8h, v2.8h
	WORD $0x4ebd1f5a // orr v26.16b, v26.16b, v29.16b
	WORD $0x6e64865d // sub v29.8h, v18.8h, v4.8h
	WORD $0x6e6486be // sub v30.8h, v21.8h, v4.8h
	WORD $0x6e7e87bf // sub v31.8h, v29.8h, v30.8h
	WORD $0x4e666fff // smin v31.8h, v31.8h, v6.8h
	WORD $0x4e6567ff // smax v31.8h, v31.8h, v5.8h
	WORD $0x4e3a1fff // and v31.16b, v31.16b, v26.16b
	WORD $0x6e73869d // sub v29.8h, v20.8h, v19.8h
	WORD $0x4e679fbd // mul v29.8h, v29.8h, v7.8h
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e666fff // smin v31.8h, v31.8h, v6.8h
	WORD $0x4e6567ff // smax v31.8h, v31.8h, v5.8h
	WORD $0x4f00849d // movi v29.8h, #4
	WORD $0x4e7d87fb // add v27.8h, v31.8h, v29.8h
	WORD $0x4e666f7b // smin v27.8h, v27.8h, v6.8h
	WORD $0x4e65677b // smax v27.8h, v27.8h, v5.8h
	WORD $0x4f1d077b // sshr v27.8h, v27.8h, #3
	WORD $0x4e6787fc // add v28.8h, v31.8h, v7.8h
	WORD $0x4e666f9c // smin v28.8h, v28.8h, v6.8h
	WORD $0x4e65679c // smax v28.8h, v28.8h, v5.8h
	WORD $0x4f1d079c // sshr v28.8h, v28.8h, #3
	WORD $0x4e73865f // add v31.8h, v18.8h, v19.8h
	WORD $0x4e7487ff // add v31.8h, v31.8h, v20.8h
	WORD $0x4f11563e // shl v30.8h, v17.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4e679e1e // mul v30.8h, v16.8h, v7.8h
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3e // mov v30.16b, v25.16b
	WORD $0x6e711ffe // bsl v30.16b, v31.16b, v17.16b
	WORD $0x4eb81f1d // mov v29.16b, v24.16b
	WORD $0x6e711fdd // bsl v29.16b, v30.16b, v17.16b
	WORD $0x0e212bbd // xtn v29.8b, v29.8h
	WORD $0x0c00715d // st1 {v29.8b}, [x10]
	WORD $0x4f1f277e // srshr v30.8h, v27.8h, #1
	WORD $0x6e64865d // sub v29.8h, v18.8h, v4.8h
	WORD $0x4e7e87bd // add v29.8h, v29.8h, v30.8h
	WORD $0x4e666fbd // smin v29.8h, v29.8h, v6.8h
	WORD $0x4e6567bd // smax v29.8h, v29.8h, v5.8h
	WORD $0x4e6487bd // add v29.8h, v29.8h, v4.8h
	WORD $0x4eba1f5e // mov v30.16b, v26.16b
	WORD $0x6e7d1e5e // bsl v30.16b, v18.16b, v29.16b
	WORD $0x4f11561f // shl v31.8h, v16.8h, #1
	WORD $0x4e7187ff // add v31.8h, v31.8h, v17.8h
	WORD $0x4f11565d // shl v29.8h, v18.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e7387ff // add v31.8h, v31.8h, v19.8h
	WORD $0x4e7487ff // add v31.8h, v31.8h, v20.8h
	WORD $0x4e7587ff // add v31.8h, v31.8h, v21.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3d // mov v29.16b, v25.16b
	WORD $0x6e7e1ffd // bsl v29.16b, v31.16b, v30.16b
	WORD $0x4eb81f1e // mov v30.16b, v24.16b
	WORD $0x6e721fbe // bsl v30.16b, v29.16b, v18.16b
	WORD $0x0e212bde // xtn v30.8b, v30.8h
	WORD $0x0c00717e // st1 {v30.8b}, [x11]
	WORD $0x6e64867d // sub v29.8h, v19.8h, v4.8h
	WORD $0x4e7c87bd // add v29.8h, v29.8h, v28.8h
	WORD $0x4e666fbd // smin v29.8h, v29.8h, v6.8h
	WORD $0x4e6567bd // smax v29.8h, v29.8h, v5.8h
	WORD $0x4e6487bd // add v29.8h, v29.8h, v4.8h
	WORD $0x4ebd1fbe // mov v30.16b, v29.16b
	WORD $0x4e71861f // add v31.8h, v16.8h, v17.8h
	WORD $0x4e7287ff // add v31.8h, v31.8h, v18.8h
	WORD $0x4f11567d // shl v29.8h, v19.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e7487ff // add v31.8h, v31.8h, v20.8h
	WORD $0x4e7587ff // add v31.8h, v31.8h, v21.8h
	WORD $0x4e7687ff // add v31.8h, v31.8h, v22.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3d // mov v29.16b, v25.16b
	WORD $0x6e7e1ffd // bsl v29.16b, v31.16b, v30.16b
	WORD $0x4eb81f1e // mov v30.16b, v24.16b
	WORD $0x6e731fbe // bsl v30.16b, v29.16b, v19.16b
	WORD $0x0e212bde // xtn v30.8b, v30.8h
	WORD $0x0c00719e // st1 {v30.8b}, [x12]
	WORD $0x6e64869d // sub v29.8h, v20.8h, v4.8h
	WORD $0x6e7b87bd // sub v29.8h, v29.8h, v27.8h
	WORD $0x4e666fbd // smin v29.8h, v29.8h, v6.8h
	WORD $0x4e6567bd // smax v29.8h, v29.8h, v5.8h
	WORD $0x4e6487bd // add v29.8h, v29.8h, v4.8h
	WORD $0x4ebd1fbe // mov v30.16b, v29.16b
	WORD $0x4e72863f // add v31.8h, v17.8h, v18.8h
	WORD $0x4e7387ff // add v31.8h, v31.8h, v19.8h
	WORD $0x4f11569d // shl v29.8h, v20.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e7587ff // add v31.8h, v31.8h, v21.8h
	WORD $0x4e7687ff // add v31.8h, v31.8h, v22.8h
	WORD $0x4e7787ff // add v31.8h, v31.8h, v23.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3d // mov v29.16b, v25.16b
	WORD $0x6e7e1ffd // bsl v29.16b, v31.16b, v30.16b
	WORD $0x4eb81f1e // mov v30.16b, v24.16b
	WORD $0x6e741fbe // bsl v30.16b, v29.16b, v20.16b
	WORD $0x0e212bde // xtn v30.8b, v30.8h
	WORD $0x0c0071be // st1 {v30.8b}, [x13]
	WORD $0x4f1f277e // srshr v30.8h, v27.8h, #1
	WORD $0x6e6486bd // sub v29.8h, v21.8h, v4.8h
	WORD $0x6e7e87bd // sub v29.8h, v29.8h, v30.8h
	WORD $0x4e666fbd // smin v29.8h, v29.8h, v6.8h
	WORD $0x4e6567bd // smax v29.8h, v29.8h, v5.8h
	WORD $0x4e6487bd // add v29.8h, v29.8h, v4.8h
	WORD $0x4eba1f5e // mov v30.16b, v26.16b
	WORD $0x6e7d1ebe // bsl v30.16b, v21.16b, v29.16b
	WORD $0x4e73865f // add v31.8h, v18.8h, v19.8h
	WORD $0x4e7487ff // add v31.8h, v31.8h, v20.8h
	WORD $0x4f1156bd // shl v29.8h, v21.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e7687ff // add v31.8h, v31.8h, v22.8h
	WORD $0x4f1156fd // shl v29.8h, v23.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3d // mov v29.16b, v25.16b
	WORD $0x6e7e1ffd // bsl v29.16b, v31.16b, v30.16b
	WORD $0x4eb81f1e // mov v30.16b, v24.16b
	WORD $0x6e751fbe // bsl v30.16b, v29.16b, v21.16b
	WORD $0x0e212bde // xtn v30.8b, v30.8h
	WORD $0x0c0071de // st1 {v30.8b}, [x14]
	WORD $0x4e74867f // add v31.8h, v19.8h, v20.8h
	WORD $0x4e7587ff // add v31.8h, v31.8h, v21.8h
	WORD $0x4f1156dd // shl v29.8h, v22.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e679efd // mul v29.8h, v23.8h, v7.8h
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3e // mov v30.16b, v25.16b
	WORD $0x6e761ffe // bsl v30.16b, v31.16b, v22.16b
	WORD $0x4eb81f1d // mov v29.16b, v24.16b
	WORD $0x6e761fdd // bsl v29.16b, v30.16b, v22.16b
	WORD $0x0e212bbd // xtn v29.8b, v29.8h
	WORD $0x0c0071fd // st1 {v29.8b}, [x15]
	ADD $8, R9, R9
	ADD $8, R10, R10
	ADD $8, R11, R11
	ADD $8, R12, R12
	ADD $8, R13, R13
	ADD $8, R14, R14
	ADD $8, R15, R15
	ADD $8, R16, R16
	SUB $1, R17, R17
	B   loop8

done8:
	RET
