// SPDX-License-Identifier: BSD-2-Clause
//
// See LICENSE for the BSD-2-Clause grant.

// Code generated by an offline NEON encoder; do not edit by hand.
// Every WORD below is the little-endian encoding of the mnemonic in its
// trailing comment, assembled and verified with the system assembler. The
// kernels are bit-exact with filter6EdgePureGo / filter8EdgePureGo (see
// filter6.go / filter8.go); the Go wrappers in filter_wide_neon_arm64.go
// restrict them to 8-bit horizontal edges processed in groups of eight.

//go:build arm64 && !purego

#include "textflag.h"

// ---- filter6 context offsets ----
#define F6_P2 0
#define F6_P1 8
#define F6_P0 16
#define F6_Q0 24
#define F6_Q1 32
#define F6_Q2 40
#define F6_COUNT 48
#define F6_LIMIT 56
#define F6_BLIMIT 64
#define F6_HEV 72
#define F6_THR 80

// func filter6EdgeNEONAsm(ctx *filter6NEONCtx)
TEXT ·filter6EdgeNEONAsm(SB), NOSPLIT, $0-8
	MOVD ctx+0(FP), R0
	MOVD F6_P2(R0), R9
	MOVD F6_P1(R0), R10
	MOVD F6_P0(R0), R11
	MOVD F6_Q0(R0), R12
	MOVD F6_Q1(R0), R13
	MOVD F6_Q2(R0), R14
	MOVD F6_COUNT(R0), R15

	MOVD F6_LIMIT(R0), R6
	WORD $0x4e020cc0 // dup v0.8h, w6
	MOVD F6_BLIMIT(R0), R7
	WORD $0x4e020ce1 // dup v1.8h, w7
	MOVD F6_HEV(R0), R8
	WORD $0x4e020d02 // dup v2.8h, w8
	MOVD F6_THR(R0), R5
	WORD $0x4e020ca3 // dup v3.8h, w5
	WORD $0x4f048404 // movi v4.8h, #128
	WORD $0x6f0387e5 // mvni v5.8h, #127  (-128)
	WORD $0x4f0387e6 // movi v6.8h, #127
	WORD $0x4f008467 // movi v7.8h, #3

loop6:
	CBZ R15, done6
	WORD $0x0c407130 // ld1 {v16.8b}, [x9]
	WORD $0x0c407151 // ld1 {v17.8b}, [x10]
	WORD $0x0c407172 // ld1 {v18.8b}, [x11]
	WORD $0x0c407193 // ld1 {v19.8b}, [x12]
	WORD $0x0c4071b4 // ld1 {v20.8b}, [x13]
	WORD $0x0c4071d5 // ld1 {v21.8b}, [x14]
	WORD $0x2f08a610 // uxtl v16.8h, v16.8b
	WORD $0x2f08a631 // uxtl v17.8h, v17.8b
	WORD $0x2f08a652 // uxtl v18.8h, v18.8b
	WORD $0x2f08a673 // uxtl v19.8h, v19.8b
	WORD $0x2f08a694 // uxtl v20.8h, v20.8b
	WORD $0x2f08a6b5 // uxtl v21.8h, v21.8b
	WORD $0x6e718616 // sub v22.8h, v16.8h, v17.8h
	WORD $0x4e60bad6 // abs v22.8h, v22.8h
	WORD $0x6e728637 // sub v23.8h, v17.8h, v18.8h
	WORD $0x4e60baf7 // abs v23.8h, v23.8h
	WORD $0x6e738698 // sub v24.8h, v20.8h, v19.8h
	WORD $0x4e60bb18 // abs v24.8h, v24.8h
	WORD $0x6e7486b9 // sub v25.8h, v21.8h, v20.8h
	WORD $0x4e60bb39 // abs v25.8h, v25.8h
	WORD $0x6e73865a // sub v26.8h, v18.8h, v19.8h
	WORD $0x4e60bb5a // abs v26.8h, v26.8h
	WORD $0x6e74863b // sub v27.8h, v17.8h, v20.8h
	WORD $0x4e60bb7b // abs v27.8h, v27.8h
	WORD $0x4e763c1c // cmge v28.8h, v0.8h, v22.8h
	WORD $0x4e773c1e // cmge v30.8h, v0.8h, v23.8h
	WORD $0x4e3e1f9c // and v28.16b, v28.16b, v30.16b
	WORD $0x4e783c1e // cmge v30.8h, v0.8h, v24.8h
	WORD $0x4e3e1f9c // and v28.16b, v28.16b, v30.16b
	WORD $0x4e793c1e // cmge v30.8h, v0.8h, v25.8h
	WORD $0x4e3e1f9c // and v28.16b, v28.16b, v30.16b
	WORD $0x4f11575e // shl v30.8h, v26.8h, #1
	WORD $0x4f1f077f // sshr v31.8h, v27.8h, #1
	WORD $0x4e7f87de // add v30.8h, v30.8h, v31.8h
	WORD $0x4e7e3c3e // cmge v30.8h, v1.8h, v30.8h
	WORD $0x4e3e1f9c // and v28.16b, v28.16b, v30.16b
	WORD $0x4e773c7d // cmge v29.8h, v3.8h, v23.8h
	WORD $0x4e783c7e // cmge v30.8h, v3.8h, v24.8h
	WORD $0x4e3e1fbd // and v29.16b, v29.16b, v30.16b
	WORD $0x6e72861e // sub v30.8h, v16.8h, v18.8h
	WORD $0x4e60bbde // abs v30.8h, v30.8h
	WORD $0x4e7e3c7e // cmge v30.8h, v3.8h, v30.8h
	WORD $0x4e3e1fbd // and v29.16b, v29.16b, v30.16b
	WORD $0x6e7386be // sub v30.8h, v21.8h, v19.8h
	WORD $0x4e60bbde // abs v30.8h, v30.8h
	WORD $0x4e7e3c7e // cmge v30.8h, v3.8h, v30.8h
	WORD $0x4e3e1fbd // and v29.16b, v29.16b, v30.16b
	WORD $0x6e64863a // sub v26.8h, v17.8h, v4.8h
	WORD $0x6e64869b // sub v27.8h, v20.8h, v4.8h
	WORD $0x6e64867e // sub v30.8h, v19.8h, v4.8h
	WORD $0x6e64865f // sub v31.8h, v18.8h, v4.8h
	WORD $0x6e728636 // sub v22.8h, v17.8h, v18.8h
	WORD $0x4e60bad6 // abs v22.8h, v22.8h
	WORD $0x4e6236d9 // cmgt v25.8h, v22.8h, v2.8h
	WORD $0x6e738696 // sub v22.8h, v20.8h, v19.8h
	WORD $0x4e60bad6 // abs v22.8h, v22.8h
	WORD $0x4e6236d6 // cmgt v22.8h, v22.8h, v2.8h
	WORD $0x4eb61f39 // orr v25.16b, v25.16b, v22.16b
	WORD $0x6e7b8756 // sub v22.8h, v26.8h, v27.8h
	WORD $0x4e666ed6 // smin v22.8h, v22.8h, v6.8h
	WORD $0x4e6566d6 // smax v22.8h, v22.8h, v5.8h
	WORD $0x4e391ed6 // and v22.16b, v22.16b, v25.16b
	WORD $0x6e7f87d7 // sub v23.8h, v30.8h, v31.8h
	WORD $0x4e679ef7 // mul v23.8h, v23.8h, v7.8h
	WORD $0x4e7786d6 // add v22.8h, v22.8h, v23.8h
	WORD $0x4e666ed6 // smin v22.8h, v22.8h, v6.8h
	WORD $0x4e6566d6 // smax v22.8h, v22.8h, v5.8h
	WORD $0x4f008498 // movi v24.8h, #4
	WORD $0x4e7886d7 // add v23.8h, v22.8h, v24.8h
	WORD $0x4e666ef7 // smin v23.8h, v23.8h, v6.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4f1d06f7 // sshr v23.8h, v23.8h, #3
	WORD $0x4e6786d8 // add v24.8h, v22.8h, v7.8h
	WORD $0x4e666f18 // smin v24.8h, v24.8h, v6.8h
	WORD $0x4e656718 // smax v24.8h, v24.8h, v5.8h
	WORD $0x4f1d0718 // sshr v24.8h, v24.8h, #3
	WORD $0x4f1f26f6 // srshr v22.8h, v23.8h, #1
	WORD $0x6e64863a // sub v26.8h, v17.8h, v4.8h
	WORD $0x4e76875a // add v26.8h, v26.8h, v22.8h
	WORD $0x4e666f5a // smin v26.8h, v26.8h, v6.8h
	WORD $0x4e65675a // smax v26.8h, v26.8h, v5.8h
	WORD $0x4e64875a // add v26.8h, v26.8h, v4.8h
	WORD $0x4eb91f3e // mov v30.16b, v25.16b
	WORD $0x6e7a1e3e // bsl v30.16b, v17.16b, v26.16b
	WORD $0x4e679e1f // mul v31.8h, v16.8h, v7.8h
	WORD $0x4f11563a // shl v26.8h, v17.8h, #1
	WORD $0x4e7a87ff // add v31.8h, v31.8h, v26.8h
	WORD $0x4f11565a // shl v26.8h, v18.8h, #1
	WORD $0x4e7a87ff // add v31.8h, v31.8h, v26.8h
	WORD $0x4e7387ff // add v31.8h, v31.8h, v19.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4ebd1fba // mov v26.16b, v29.16b
	WORD $0x6e7e1ffa // bsl v26.16b, v31.16b, v30.16b
	WORD $0x4ebc1f9b // mov v27.16b, v28.16b
	WORD $0x6e711f5b // bsl v27.16b, v26.16b, v17.16b
	WORD $0x0e212b7b // xtn v27.8b, v27.8h
	WORD $0x0c00715b // st1 {v27.8b}, [x10]
	WORD $0x6e64865a // sub v26.8h, v18.8h, v4.8h
	WORD $0x4e78875a // add v26.8h, v26.8h, v24.8h
	WORD $0x4e666f5a // smin v26.8h, v26.8h, v6.8h
	WORD $0x4e65675a // smax v26.8h, v26.8h, v5.8h
	WORD $0x4e64875a // add v26.8h, v26.8h, v4.8h
	WORD $0x4e74861f // add v31.8h, v16.8h, v20.8h
	WORD $0x4f11563e // shl v30.8h, v17.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f11565e // shl v30.8h, v18.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f11567e // shl v30.8h, v19.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4ebd1fbe // mov v30.16b, v29.16b
	WORD $0x6e7a1ffe // bsl v30.16b, v31.16b, v26.16b
	WORD $0x4ebc1f9b // mov v27.16b, v28.16b
	WORD $0x6e721fdb // bsl v27.16b, v30.16b, v18.16b
	WORD $0x0e212b7b // xtn v27.8b, v27.8h
	WORD $0x0c00717b // st1 {v27.8b}, [x11]
	WORD $0x6e64867a // sub v26.8h, v19.8h, v4.8h
	WORD $0x6e77875a // sub v26.8h, v26.8h, v23.8h
	WORD $0x4e666f5a // smin v26.8h, v26.8h, v6.8h
	WORD $0x4e65675a // smax v26.8h, v26.8h, v5.8h
	WORD $0x4e64875a // add v26.8h, v26.8h, v4.8h
	WORD $0x4e75863f // add v31.8h, v17.8h, v21.8h
	WORD $0x4f11565e // shl v30.8h, v18.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f11567e // shl v30.8h, v19.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f11569e // shl v30.8h, v20.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4ebd1fbe // mov v30.16b, v29.16b
	WORD $0x6e7a1ffe // bsl v30.16b, v31.16b, v26.16b
	WORD $0x4ebc1f9b // mov v27.16b, v28.16b
	WORD $0x6e731fdb // bsl v27.16b, v30.16b, v19.16b
	WORD $0x0e212b7b // xtn v27.8b, v27.8h
	WORD $0x0c00719b // st1 {v27.8b}, [x12]
	WORD $0x6e64869a // sub v26.8h, v20.8h, v4.8h
	WORD $0x6e76875a // sub v26.8h, v26.8h, v22.8h
	WORD $0x4e666f5a // smin v26.8h, v26.8h, v6.8h
	WORD $0x4e65675a // smax v26.8h, v26.8h, v5.8h
	WORD $0x4e64875a // add v26.8h, v26.8h, v4.8h
	WORD $0x4eb91f3e // mov v30.16b, v25.16b
	WORD $0x6e7a1e9e // bsl v30.16b, v20.16b, v26.16b
	WORD $0x4e679ebf // mul v31.8h, v21.8h, v7.8h
	WORD $0x4f11569a // shl v26.8h, v20.8h, #1
	WORD $0x4e7a87ff // add v31.8h, v31.8h, v26.8h
	WORD $0x4f11567a // shl v26.8h, v19.8h, #1
	WORD $0x4e7a87ff // add v31.8h, v31.8h, v26.8h
	WORD $0x4e7287ff // add v31.8h, v31.8h, v18.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4ebd1fba // mov v26.16b, v29.16b
	WORD $0x6e7e1ffa // bsl v26.16b, v31.16b, v30.16b
	WORD $0x4ebc1f9b // mov v27.16b, v28.16b
	WORD $0x6e741f5b // bsl v27.16b, v26.16b, v20.16b
	WORD $0x0e212b7b // xtn v27.8b, v27.8h
	WORD $0x0c0071bb // st1 {v27.8b}, [x13]
	ADD $8, R9, R9
	ADD $8, R10, R10
	ADD $8, R11, R11
	ADD $8, R12, R12
	ADD $8, R13, R13
	ADD $8, R14, R14
	SUB $1, R15, R15
	B   loop6

done6:
	RET

// ---- filter8 context offsets ----
#define F8_P3 0
#define F8_P2 8
#define F8_P1 16
#define F8_P0 24
#define F8_Q0 32
#define F8_Q1 40
#define F8_Q2 48
#define F8_Q3 56
#define F8_COUNT 64
#define F8_LIMIT 72
#define F8_BLIMIT 80
#define F8_HEV 88
#define F8_THR 96

// func filter8EdgeNEONAsm(ctx *filter8NEONCtx)
TEXT ·filter8EdgeNEONAsm(SB), NOSPLIT, $0-8
	MOVD ctx+0(FP), R0
	MOVD F8_P3(R0), R9
	MOVD F8_P2(R0), R10
	MOVD F8_P1(R0), R11
	MOVD F8_P0(R0), R12
	MOVD F8_Q0(R0), R13
	MOVD F8_Q1(R0), R14
	MOVD F8_Q2(R0), R15
	MOVD F8_Q3(R0), R16
	MOVD F8_COUNT(R0), R17

	MOVD F8_LIMIT(R0), R6
	WORD $0x4e020cc0 // dup v0.8h, w6
	MOVD F8_BLIMIT(R0), R7
	WORD $0x4e020ce1 // dup v1.8h, w7
	MOVD F8_HEV(R0), R8
	WORD $0x4e020d02 // dup v2.8h, w8
	MOVD F8_THR(R0), R5
	WORD $0x4e020ca3 // dup v3.8h, w5
	WORD $0x4f048404 // movi v4.8h, #128
	WORD $0x6f0387e5 // mvni v5.8h, #127  (-128)
	WORD $0x4f0387e6 // movi v6.8h, #127
	WORD $0x4f008467 // movi v7.8h, #3

loop8:
	CBZ R17, done8
	WORD $0x0c407130 // ld1 {v16.8b}, [x9]
	WORD $0x0c407151 // ld1 {v17.8b}, [x10]
	WORD $0x0c407172 // ld1 {v18.8b}, [x11]
	WORD $0x0c407193 // ld1 {v19.8b}, [x12]
	WORD $0x0c4071b4 // ld1 {v20.8b}, [x13]
	WORD $0x0c4071d5 // ld1 {v21.8b}, [x14]
	WORD $0x0c4071f6 // ld1 {v22.8b}, [x15]
	WORD $0x0c407217 // ld1 {v23.8b}, [x16]
	WORD $0x2f08a610 // uxtl v16.8h, v16.8b
	WORD $0x2f08a631 // uxtl v17.8h, v17.8b
	WORD $0x2f08a652 // uxtl v18.8h, v18.8b
	WORD $0x2f08a673 // uxtl v19.8h, v19.8b
	WORD $0x2f08a694 // uxtl v20.8h, v20.8b
	WORD $0x2f08a6b5 // uxtl v21.8h, v21.8b
	WORD $0x2f08a6d6 // uxtl v22.8h, v22.8b
	WORD $0x2f08a6f7 // uxtl v23.8h, v23.8b
	WORD $0x6e71861d // sub v29.8h, v16.8h, v17.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c18 // cmge v24.8h, v0.8h, v29.8h
	WORD $0x6e72863d // sub v29.8h, v17.8h, v18.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c1e // cmge v30.8h, v0.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e73865d // sub v29.8h, v18.8h, v19.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c1e // cmge v30.8h, v0.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e7486bd // sub v29.8h, v21.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c1e // cmge v30.8h, v0.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e7586dd // sub v29.8h, v22.8h, v21.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c1e // cmge v30.8h, v0.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e7686fd // sub v29.8h, v23.8h, v22.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c1e // cmge v30.8h, v0.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e74867d // sub v29.8h, v19.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4f1157bd // shl v29.8h, v29.8h, #1
	WORD $0x6e75865e // sub v30.8h, v18.8h, v21.8h
	WORD $0x4e60bbde // abs v30.8h, v30.8h
	WORD $0x4f1f07de // sshr v30.8h, v30.8h, #1
	WORD $0x4e7e87bd // add v29.8h, v29.8h, v30.8h
	WORD $0x4e7d3c3e // cmge v30.8h, v1.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e73865d // sub v29.8h, v18.8h, v19.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c79 // cmge v25.8h, v3.8h, v29.8h
	WORD $0x6e7486bd // sub v29.8h, v21.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c7e // cmge v30.8h, v3.8h, v29.8h
	WORD $0x4e3e1f39 // and v25.16b, v25.16b, v30.16b
	WORD $0x6e73863d // sub v29.8h, v17.8h, v19.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c7e // cmge v30.8h, v3.8h, v29.8h
	WORD $0x4e3e1f39 // and v25.16b, v25.16b, v30.16b
	WORD $0x6e7486dd // sub v29.8h, v22.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c7e // cmge v30.8h, v3.8h, v29.8h
	WORD $0x4e3e1f39 // and v25.16b, v25.16b, v30.16b
	WORD $0x6e73861d // sub v29.8h, v16.8h, v19.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c7e // cmge v30.8h, v3.8h, v29.8h
	WORD $0x4e3e1f39 // and v25.16b, v25.16b, v30.16b
	WORD $0x6e7486fd // sub v29.8h, v23.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c7e // cmge v30.8h, v3.8h, v29.8h
	WORD $0x4e3e1f39 // and v25.16b, v25.16b, v30.16b
	WORD $0x6e73865d // sub v29.8h, v18.8h, v19.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e6237ba // cmgt v26.8h, v29.8h, v2.8h
	WORD $0x6e7486bd // sub v29.8h, v21.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e6237bd // cmgt v29.8h, v29.8h, v2.8h
	WORD $0x4ebd1f5a // orr v26.16b, v26.16b, v29.16b
	WORD $0x6e64865d // sub v29.8h, v18.8h, v4.8h
	WORD $0x6e6486be // sub v30.8h, v21.8h, v4.8h
	WORD $0x6e7e87bf // sub v31.8h, v29.8h, v30.8h
	WORD $0x4e666fff // smin v31.8h, v31.8h, v6.8h
	WORD $0x4e6567ff // smax v31.8h, v31.8h, v5.8h
	WORD $0x4e3a1fff // and v31.16b, v31.16b, v26.16b
	WORD $0x6e73869d // sub v29.8h, v20.8h, v19.8h
	WORD $0x4e679fbd // mul v29.8h, v29.8h, v7.8h
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e666fff // smin v31.8h, v31.8h, v6.8h
	WORD $0x4e6567ff // smax v31.8h, v31.8h, v5.8h
	WORD $0x4f00849d // movi v29.8h, #4
	WORD $0x4e7d87fb // add v27.8h, v31.8h, v29.8h
	WORD $0x4e666f7b // smin v27.8h, v27.8h, v6.8h
	WORD $0x4e65677b // smax v27.8h, v27.8h, v5.8h
	WORD $0x4f1d077b // sshr v27.8h, v27.8h, #3
	WORD $0x4e6787fc // add v28.8h, v31.8h, v7.8h
	WORD $0x4e666f9c // smin v28.8h, v28.8h, v6.8h
	WORD $0x4e65679c // smax v28.8h, v28.8h, v5.8h
	WORD $0x4f1d079c // sshr v28.8h, v28.8h, #3
	WORD $0x4e73865f // add v31.8h, v18.8h, v19.8h
	WORD $0x4e7487ff // add v31.8h, v31.8h, v20.8h
	WORD $0x4f11563e // shl v30.8h, v17.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4e679e1e // mul v30.8h, v16.8h, v7.8h
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3e // mov v30.16b, v25.16b
	WORD $0x6e711ffe // bsl v30.16b, v31.16b, v17.16b
	WORD $0x4eb81f1d // mov v29.16b, v24.16b
	WORD $0x6e711fdd // bsl v29.16b, v30.16b, v17.16b
	WORD $0x0e212bbd // xtn v29.8b, v29.8h
	WORD $0x0c00715d // st1 {v29.8b}, [x10]
	WORD $0x4f1f277e // srshr v30.8h, v27.8h, #1
	WORD $0x6e64865d // sub v29.8h, v18.8h, v4.8h
	WORD $0x4e7e87bd // add v29.8h, v29.8h, v30.8h
	WORD $0x4e666fbd // smin v29.8h, v29.8h, v6.8h
	WORD $0x4e6567bd // smax v29.8h, v29.8h, v5.8h
	WORD $0x4e6487bd // add v29.8h, v29.8h, v4.8h
	WORD $0x4eba1f5e // mov v30.16b, v26.16b
	WORD $0x6e7d1e5e // bsl v30.16b, v18.16b, v29.16b
	WORD $0x4f11561f // shl v31.8h, v16.8h, #1
	WORD $0x4e7187ff // add v31.8h, v31.8h, v17.8h
	WORD $0x4f11565d // shl v29.8h, v18.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e7387ff // add v31.8h, v31.8h, v19.8h
	WORD $0x4e7487ff // add v31.8h, v31.8h, v20.8h
	WORD $0x4e7587ff // add v31.8h, v31.8h, v21.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3d // mov v29.16b, v25.16b
	WORD $0x6e7e1ffd // bsl v29.16b, v31.16b, v30.16b
	WORD $0x4eb81f1e // mov v30.16b, v24.16b
	WORD $0x6e721fbe // bsl v30.16b, v29.16b, v18.16b
	WORD $0x0e212bde // xtn v30.8b, v30.8h
	WORD $0x0c00717e // st1 {v30.8b}, [x11]
	WORD $0x6e64867d // sub v29.8h, v19.8h, v4.8h
	WORD $0x4e7c87bd // add v29.8h, v29.8h, v28.8h
	WORD $0x4e666fbd // smin v29.8h, v29.8h, v6.8h
	WORD $0x4e6567bd // smax v29.8h, v29.8h, v5.8h
	WORD $0x4e6487bd // add v29.8h, v29.8h, v4.8h
	WORD $0x4ebd1fbe // mov v30.16b, v29.16b
	WORD $0x4e71861f // add v31.8h, v16.8h, v17.8h
	WORD $0x4e7287ff // add v31.8h, v31.8h, v18.8h
	WORD $0x4f11567d // shl v29.8h, v19.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e7487ff // add v31.8h, v31.8h, v20.8h
	WORD $0x4e7587ff // add v31.8h, v31.8h, v21.8h
	WORD $0x4e7687ff // add v31.8h, v31.8h, v22.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3d // mov v29.16b, v25.16b
	WORD $0x6e7e1ffd // bsl v29.16b, v31.16b, v30.16b
	WORD $0x4eb81f1e // mov v30.16b, v24.16b
	WORD $0x6e731fbe // bsl v30.16b, v29.16b, v19.16b
	WORD $0x0e212bde // xtn v30.8b, v30.8h
	WORD $0x0c00719e // st1 {v30.8b}, [x12]
	WORD $0x6e64869d // sub v29.8h, v20.8h, v4.8h
	WORD $0x6e7b87bd // sub v29.8h, v29.8h, v27.8h
	WORD $0x4e666fbd // smin v29.8h, v29.8h, v6.8h
	WORD $0x4e6567bd // smax v29.8h, v29.8h, v5.8h
	WORD $0x4e6487bd // add v29.8h, v29.8h, v4.8h
	WORD $0x4ebd1fbe // mov v30.16b, v29.16b
	WORD $0x4e72863f // add v31.8h, v17.8h, v18.8h
	WORD $0x4e7387ff // add v31.8h, v31.8h, v19.8h
	WORD $0x4f11569d // shl v29.8h, v20.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e7587ff // add v31.8h, v31.8h, v21.8h
	WORD $0x4e7687ff // add v31.8h, v31.8h, v22.8h
	WORD $0x4e7787ff // add v31.8h, v31.8h, v23.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3d // mov v29.16b, v25.16b
	WORD $0x6e7e1ffd // bsl v29.16b, v31.16b, v30.16b
	WORD $0x4eb81f1e // mov v30.16b, v24.16b
	WORD $0x6e741fbe // bsl v30.16b, v29.16b, v20.16b
	WORD $0x0e212bde // xtn v30.8b, v30.8h
	WORD $0x0c0071be // st1 {v30.8b}, [x13]
	WORD $0x4f1f277e // srshr v30.8h, v27.8h, #1
	WORD $0x6e6486bd // sub v29.8h, v21.8h, v4.8h
	WORD $0x6e7e87bd // sub v29.8h, v29.8h, v30.8h
	WORD $0x4e666fbd // smin v29.8h, v29.8h, v6.8h
	WORD $0x4e6567bd // smax v29.8h, v29.8h, v5.8h
	WORD $0x4e6487bd // add v29.8h, v29.8h, v4.8h
	WORD $0x4eba1f5e // mov v30.16b, v26.16b
	WORD $0x6e7d1ebe // bsl v30.16b, v21.16b, v29.16b
	WORD $0x4e73865f // add v31.8h, v18.8h, v19.8h
	WORD $0x4e7487ff // add v31.8h, v31.8h, v20.8h
	WORD $0x4f1156bd // shl v29.8h, v21.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e7687ff // add v31.8h, v31.8h, v22.8h
	WORD $0x4f1156fd // shl v29.8h, v23.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3d // mov v29.16b, v25.16b
	WORD $0x6e7e1ffd // bsl v29.16b, v31.16b, v30.16b
	WORD $0x4eb81f1e // mov v30.16b, v24.16b
	WORD $0x6e751fbe // bsl v30.16b, v29.16b, v21.16b
	WORD $0x0e212bde // xtn v30.8b, v30.8h
	WORD $0x0c0071de // st1 {v30.8b}, [x14]
	WORD $0x4e74867f // add v31.8h, v19.8h, v20.8h
	WORD $0x4e7587ff // add v31.8h, v31.8h, v21.8h
	WORD $0x4f1156dd // shl v29.8h, v22.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e679efd // mul v29.8h, v23.8h, v7.8h
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3e // mov v30.16b, v25.16b
	WORD $0x6e761ffe // bsl v30.16b, v31.16b, v22.16b
	WORD $0x4eb81f1d // mov v29.16b, v24.16b
	WORD $0x6e761fdd // bsl v29.16b, v30.16b, v22.16b
	WORD $0x0e212bbd // xtn v29.8b, v29.8h
	WORD $0x0c0071fd // st1 {v29.8b}, [x15]
	ADD $8, R9, R9
	ADD $8, R10, R10
	ADD $8, R11, R11
	ADD $8, R12, R12
	ADD $8, R13, R13
	ADD $8, R14, R14
	ADD $8, R15, R15
	ADD $8, R16, R16
	SUB $1, R17, R17
	B   loop8

done8:
	RET


// ---- filter14 context offsets ----
#define F14_P6 0
#define F14_P5 8
#define F14_P4 16
#define F14_P3 24
#define F14_P2 32
#define F14_P1 40
#define F14_P0 48
#define F14_Q0 56
#define F14_Q1 64
#define F14_Q2 72
#define F14_Q3 80
#define F14_Q4 88
#define F14_Q5 96
#define F14_Q6 104
#define F14_COUNT 112
#define F14_LIMIT 120
#define F14_BLIMIT 128
#define F14_HEV 136
#define F14_THR 144

// func filter14EdgeNEONAsm(ctx *filter14NEONCtx)
// Bit-exact with filter14EdgePureGo. Per 8-position group, the filter8
// narrow/flat result stays in v8..v13 while the original inner taps remain in
// registers. Groups with no need&&flat lane store only p1..q1 and stop there.
// Otherwise the six fallbacks are written to their final destinations before
// the six outer taps reuse those registers and flat8out is evaluated once.
// Groups without a wide lane are already complete. Wide groups use one biased
// running sum for all twelve averages, loading mixed-lane fallbacks from the
// destination bytes they are about to overwrite.
// Keeping every flat decision on pristine samples is essential for exactness.
TEXT ·filter14EdgeNEONAsm(SB), NOSPLIT, $0-8
	MOVD ctx+0(FP), R0
	MOVD F14_P6(R0), R1
	MOVD F14_P5(R0), R2
	MOVD F14_P4(R0), R3
	MOVD F14_P3(R0), R4
	MOVD F14_P2(R0), R5
	MOVD F14_P1(R0), R6
	MOVD F14_P0(R0), R7
	MOVD F14_Q0(R0), R8
	MOVD F14_Q1(R0), R9
	MOVD F14_Q2(R0), R10
	MOVD F14_Q3(R0), R11
	MOVD F14_Q4(R0), R12
	MOVD F14_Q5(R0), R13
	MOVD F14_Q6(R0), R14
	MOVD F14_COUNT(R0), R15

	MOVD F14_LIMIT(R0), R16
	WORD $0x4e020e00 // dup v0.8h, w16
	MOVD F14_BLIMIT(R0), R17
	WORD $0x4e020e21 // dup v1.8h, w17
	MOVD F14_HEV(R0), R19
	WORD $0x4e020e62 // dup v2.8h, w19
	MOVD F14_THR(R0), R20
	WORD $0x4e020e83 // dup v3.8h, w20
	WORD $0x4f048404 // movi v4.8h, #128
	WORD $0x6f0387e5 // mvni v5.8h, #127  (-128)
	WORD $0x4f0387e6 // movi v6.8h, #127
	WORD $0x4f008467 // movi v7.8h, #3

loop14:
	CBZ R15, done14
	// The arithmetic reuses v1 (blimit) and v2 (hev) as scratch, so broadcast
	// both again at the top of each group.
	WORD $0x4e020e21 // dup v1.8h, w17  (blimit)
	WORD $0x4e020e62 // dup v2.8h, w19  (hev)
	WORD $0x0c407090 // ld1 {v16.8b}, [x4]
	WORD $0x0c4070b1 // ld1 {v17.8b}, [x5]
	WORD $0x0c4070d2 // ld1 {v18.8b}, [x6]
	WORD $0x0c4070f3 // ld1 {v19.8b}, [x7]
	WORD $0x0c407114 // ld1 {v20.8b}, [x8]
	WORD $0x0c407135 // ld1 {v21.8b}, [x9]
	WORD $0x0c407156 // ld1 {v22.8b}, [x10]
	WORD $0x0c407177 // ld1 {v23.8b}, [x11]
	WORD $0x2f08a610 // uxtl v16.8h, v16.8b
	WORD $0x2f08a631 // uxtl v17.8h, v17.8b
	WORD $0x2f08a652 // uxtl v18.8h, v18.8b
	WORD $0x2f08a673 // uxtl v19.8h, v19.8b
	WORD $0x2f08a694 // uxtl v20.8h, v20.8b
	WORD $0x2f08a6b5 // uxtl v21.8h, v21.8b
	WORD $0x2f08a6d6 // uxtl v22.8h, v22.8b
	WORD $0x2f08a6f7 // uxtl v23.8h, v23.8b
	WORD $0x6e71861d // sub v29.8h, v16.8h, v17.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c18 // cmge v24.8h, v0.8h, v29.8h
	WORD $0x6e72863d // sub v29.8h, v17.8h, v18.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c1e // cmge v30.8h, v0.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e73865d // sub v29.8h, v18.8h, v19.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c1e // cmge v30.8h, v0.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e7486bd // sub v29.8h, v21.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c1e // cmge v30.8h, v0.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e7586dd // sub v29.8h, v22.8h, v21.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c1e // cmge v30.8h, v0.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e7686fd // sub v29.8h, v23.8h, v22.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c1e // cmge v30.8h, v0.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e74867d // sub v29.8h, v19.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4f1157bd // shl v29.8h, v29.8h, #1
	WORD $0x6e75865e // sub v30.8h, v18.8h, v21.8h
	WORD $0x4e60bbde // abs v30.8h, v30.8h
	WORD $0x4f1f07de // sshr v30.8h, v30.8h, #1
	WORD $0x4e7e87bd // add v29.8h, v29.8h, v30.8h
	WORD $0x4e7d3c3e // cmge v30.8h, v1.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e73865d // sub v29.8h, v18.8h, v19.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c79 // cmge v25.8h, v3.8h, v29.8h
	WORD $0x6e7486bd // sub v29.8h, v21.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c7e // cmge v30.8h, v3.8h, v29.8h
	WORD $0x4e3e1f39 // and v25.16b, v25.16b, v30.16b
	WORD $0x6e73863d // sub v29.8h, v17.8h, v19.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c7e // cmge v30.8h, v3.8h, v29.8h
	WORD $0x4e3e1f39 // and v25.16b, v25.16b, v30.16b
	WORD $0x6e7486dd // sub v29.8h, v22.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c7e // cmge v30.8h, v3.8h, v29.8h
	WORD $0x4e3e1f39 // and v25.16b, v25.16b, v30.16b
	WORD $0x6e73861d // sub v29.8h, v16.8h, v19.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c7e // cmge v30.8h, v3.8h, v29.8h
	WORD $0x4e3e1f39 // and v25.16b, v25.16b, v30.16b
	WORD $0x6e7486fd // sub v29.8h, v23.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c7e // cmge v30.8h, v3.8h, v29.8h
	WORD $0x4e3e1f39 // and v25.16b, v25.16b, v30.16b
	WORD $0x6e73865d // sub v29.8h, v18.8h, v19.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e6237ba // cmgt v26.8h, v29.8h, v2.8h
	WORD $0x6e7486bd // sub v29.8h, v21.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e6237bd // cmgt v29.8h, v29.8h, v2.8h
	WORD $0x4ebd1f5a // orr v26.16b, v26.16b, v29.16b
	WORD $0x6e64865d // sub v29.8h, v18.8h, v4.8h
	WORD $0x6e6486be // sub v30.8h, v21.8h, v4.8h
	WORD $0x6e7e87bf // sub v31.8h, v29.8h, v30.8h
	WORD $0x4e666fff // smin v31.8h, v31.8h, v6.8h
	WORD $0x4e6567ff // smax v31.8h, v31.8h, v5.8h
	WORD $0x4e3a1fff // and v31.16b, v31.16b, v26.16b
	WORD $0x6e73869d // sub v29.8h, v20.8h, v19.8h
	WORD $0x4e679fbd // mul v29.8h, v29.8h, v7.8h
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e666fff // smin v31.8h, v31.8h, v6.8h
	WORD $0x4e6567ff // smax v31.8h, v31.8h, v5.8h
	WORD $0x4f00849d // movi v29.8h, #4
	WORD $0x4e7d87fb // add v27.8h, v31.8h, v29.8h
	WORD $0x4e666f7b // smin v27.8h, v27.8h, v6.8h
	WORD $0x4e65677b // smax v27.8h, v27.8h, v5.8h
	WORD $0x4f1d077b // sshr v27.8h, v27.8h, #3
	WORD $0x4e6787fc // add v28.8h, v31.8h, v7.8h
	WORD $0x4e666f9c // smin v28.8h, v28.8h, v6.8h
	WORD $0x4e65679c // smax v28.8h, v28.8h, v5.8h
	WORD $0x4f1d079c // sshr v28.8h, v28.8h, #3
	WORD $0x4e73865f // add v31.8h, v18.8h, v19.8h
	WORD $0x4e7487ff // add v31.8h, v31.8h, v20.8h
	WORD $0x4f11563e // shl v30.8h, v17.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4e679e1e // mul v30.8h, v16.8h, v7.8h
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3e // mov v30.16b, v25.16b
	WORD $0x6e711ffe // bsl v30.16b, v31.16b, v17.16b
	WORD $0x4eb81f1d // mov v29.16b, v24.16b
	WORD $0x6e711fdd // bsl v29.16b, v30.16b, v17.16b
	WORD $0x0e212ba8 // xtn v8.8b, v29.8h  (pass-1 x5 fallback)
	WORD $0x4f1f277e // srshr v30.8h, v27.8h, #1
	WORD $0x6e64865d // sub v29.8h, v18.8h, v4.8h
	WORD $0x4e7e87bd // add v29.8h, v29.8h, v30.8h
	WORD $0x4e666fbd // smin v29.8h, v29.8h, v6.8h
	WORD $0x4e6567bd // smax v29.8h, v29.8h, v5.8h
	WORD $0x4e6487bd // add v29.8h, v29.8h, v4.8h
	WORD $0x4eba1f5e // mov v30.16b, v26.16b
	WORD $0x6e7d1e5e // bsl v30.16b, v18.16b, v29.16b
	WORD $0x4f11561f // shl v31.8h, v16.8h, #1
	WORD $0x4e7187ff // add v31.8h, v31.8h, v17.8h
	WORD $0x4f11565d // shl v29.8h, v18.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e7387ff // add v31.8h, v31.8h, v19.8h
	WORD $0x4e7487ff // add v31.8h, v31.8h, v20.8h
	WORD $0x4e7587ff // add v31.8h, v31.8h, v21.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3d // mov v29.16b, v25.16b
	WORD $0x6e7e1ffd // bsl v29.16b, v31.16b, v30.16b
	WORD $0x4eb81f1e // mov v30.16b, v24.16b
	WORD $0x6e721fbe // bsl v30.16b, v29.16b, v18.16b
	WORD $0x0e212bc9 // xtn v9.8b, v30.8h  (pass-1 x6 fallback)
	WORD $0x6e64867d // sub v29.8h, v19.8h, v4.8h
	WORD $0x4e7c87bd // add v29.8h, v29.8h, v28.8h
	WORD $0x4e666fbd // smin v29.8h, v29.8h, v6.8h
	WORD $0x4e6567bd // smax v29.8h, v29.8h, v5.8h
	WORD $0x4e6487bd // add v29.8h, v29.8h, v4.8h
	WORD $0x4ebd1fbe // mov v30.16b, v29.16b
	WORD $0x4e71861f // add v31.8h, v16.8h, v17.8h
	WORD $0x4e7287ff // add v31.8h, v31.8h, v18.8h
	WORD $0x4f11567d // shl v29.8h, v19.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e7487ff // add v31.8h, v31.8h, v20.8h
	WORD $0x4e7587ff // add v31.8h, v31.8h, v21.8h
	WORD $0x4e7687ff // add v31.8h, v31.8h, v22.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3d // mov v29.16b, v25.16b
	WORD $0x6e7e1ffd // bsl v29.16b, v31.16b, v30.16b
	WORD $0x4eb81f1e // mov v30.16b, v24.16b
	WORD $0x6e731fbe // bsl v30.16b, v29.16b, v19.16b
	WORD $0x0e212bca // xtn v10.8b, v30.8h  (pass-1 x7 fallback)
	WORD $0x6e64869d // sub v29.8h, v20.8h, v4.8h
	WORD $0x6e7b87bd // sub v29.8h, v29.8h, v27.8h
	WORD $0x4e666fbd // smin v29.8h, v29.8h, v6.8h
	WORD $0x4e6567bd // smax v29.8h, v29.8h, v5.8h
	WORD $0x4e6487bd // add v29.8h, v29.8h, v4.8h
	WORD $0x4ebd1fbe // mov v30.16b, v29.16b
	WORD $0x4e72863f // add v31.8h, v17.8h, v18.8h
	WORD $0x4e7387ff // add v31.8h, v31.8h, v19.8h
	WORD $0x4f11569d // shl v29.8h, v20.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e7587ff // add v31.8h, v31.8h, v21.8h
	WORD $0x4e7687ff // add v31.8h, v31.8h, v22.8h
	WORD $0x4e7787ff // add v31.8h, v31.8h, v23.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3d // mov v29.16b, v25.16b
	WORD $0x6e7e1ffd // bsl v29.16b, v31.16b, v30.16b
	WORD $0x4eb81f1e // mov v30.16b, v24.16b
	WORD $0x6e741fbe // bsl v30.16b, v29.16b, v20.16b
	WORD $0x0e212bcb // xtn v11.8b, v30.8h  (pass-1 x8 fallback)
	WORD $0x4f1f277e // srshr v30.8h, v27.8h, #1
	WORD $0x6e6486bd // sub v29.8h, v21.8h, v4.8h
	WORD $0x6e7e87bd // sub v29.8h, v29.8h, v30.8h
	WORD $0x4e666fbd // smin v29.8h, v29.8h, v6.8h
	WORD $0x4e6567bd // smax v29.8h, v29.8h, v5.8h
	WORD $0x4e6487bd // add v29.8h, v29.8h, v4.8h
	WORD $0x4eba1f5e // mov v30.16b, v26.16b
	WORD $0x6e7d1ebe // bsl v30.16b, v21.16b, v29.16b
	WORD $0x4e73865f // add v31.8h, v18.8h, v19.8h
	WORD $0x4e7487ff // add v31.8h, v31.8h, v20.8h
	WORD $0x4f1156bd // shl v29.8h, v21.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e7687ff // add v31.8h, v31.8h, v22.8h
	WORD $0x4f1156fd // shl v29.8h, v23.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3d // mov v29.16b, v25.16b
	WORD $0x6e7e1ffd // bsl v29.16b, v31.16b, v30.16b
	WORD $0x4eb81f1e // mov v30.16b, v24.16b
	WORD $0x6e751fbe // bsl v30.16b, v29.16b, v21.16b
	WORD $0x0e212bcc // xtn v12.8b, v30.8h  (pass-1 x9 fallback)
	WORD $0x4e74867f // add v31.8h, v19.8h, v20.8h
	WORD $0x4e7587ff // add v31.8h, v31.8h, v21.8h
	WORD $0x4f1156dd // shl v29.8h, v22.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e679efd // mul v29.8h, v23.8h, v7.8h
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3e // mov v30.16b, v25.16b
	WORD $0x6e761ffe // bsl v30.16b, v31.16b, v22.16b
	WORD $0x4eb81f1d // mov v29.16b, v24.16b
	WORD $0x6e761fdd // bsl v29.16b, v30.16b, v22.16b
	WORD $0x0e212bad // xtn v13.8b, v29.8h  (pass-1 x10 fallback)
	// Most real edges are not flat enough to enter either wide branch.  The
	// pass-1 result is already complete for those groups, so reduce need&flat
	// once and avoid reloading fourteen taps, recomputing both masks, and
	// executing all twelve fourteen-tap averages when every lane is narrow.
	WORD $0x4e391f1d // and v29.16b, v24.16b, v25.16b
	WORD $0x6e70abbd // umaxv h29, v29.8h
	WORD $0x0e023fb6 // umov w22, v29.h[0]
	CBNZ R22, flat14Fast
	WORD $0x0c0070c9 // st1 {v9.8b}, [x6]   pass-1 p1
	WORD $0x0c0070ea // st1 {v10.8b}, [x7]  pass-1 p0
	WORD $0x0c00710b // st1 {v11.8b}, [x8]  pass-1 q0
	WORD $0x0c00712c // st1 {v12.8b}, [x9]  pass-1 q1
	B advance14

flat14Fast:
	// Pass 1 preserved the original inner taps and materialized the exact
	// filter8/filter4 fallback in v8..v13. Commit those six results directly;
	// the wide path below can load a mixed lane back from its destination before
	// overwriting it, and the no-wide path needs no copy-back at all.
	WORD $0x0c0070a8 // st1 {v8.8b}, [x5]   pass-1 p2
	WORD $0x0c0070c9 // st1 {v9.8b}, [x6]   pass-1 p1
	WORD $0x0c0070ea // st1 {v10.8b}, [x7]  pass-1 p0
	WORD $0x0c00710b // st1 {v11.8b}, [x8]  pass-1 q0
	WORD $0x0c00712c // st1 {v12.8b}, [x9]  pass-1 q1
	WORD $0x0c00714d // st1 {v13.8b}, [x10] pass-1 q2
	WORD $0x0c407028 // ld1.8b { v8 }, [x1]
	WORD $0x0c407049 // ld1.8b { v9 }, [x2]
	WORD $0x0c40706a // ld1.8b { v10 }, [x3]
	WORD $0x0c40718b // ld1.8b { v11 }, [x12]
	WORD $0x0c4071ac // ld1.8b { v12 }, [x13]
	WORD $0x0c4071cd // ld1.8b { v13 }, [x14]
	WORD $0x2f08a508 // ushll.8h v8, v8, #0x0
	WORD $0x2f08a529 // ushll.8h v9, v9, #0x0
	WORD $0x2f08a54a // ushll.8h v10, v10, #0x0
	WORD $0x2f08a56b // ushll.8h v11, v11, #0x0
	WORD $0x2f08a58c // ushll.8h v12, v12, #0x0
	WORD $0x2f08a5ad // ushll.8h v13, v13, #0x0
	WORD $0x6e73855a // sub.8h v26, v10, v19
	WORD $0x4e60bb5a // abs.8h v26, v26
	WORD $0x4e7a3c6e // cmge.8h v14, v3, v26
	WORD $0x6e74857a // sub.8h v26, v11, v20
	WORD $0x4e60bb5a // abs.8h v26, v26
	WORD $0x4e7a3c6f // cmge.8h v15, v3, v26
	WORD $0x4e2f1dce // and.16b v14, v14, v15
	WORD $0x6e73853a // sub.8h v26, v9, v19
	WORD $0x4e60bb5a // abs.8h v26, v26
	WORD $0x4e7a3c6f // cmge.8h v15, v3, v26
	WORD $0x4e2f1dce // and.16b v14, v14, v15
	WORD $0x6e74859a // sub.8h v26, v12, v20
	WORD $0x4e60bb5a // abs.8h v26, v26
	WORD $0x4e7a3c6f // cmge.8h v15, v3, v26
	WORD $0x4e2f1dce // and.16b v14, v14, v15
	WORD $0x6e73851a // sub.8h v26, v8, v19
	WORD $0x4e60bb5a // abs.8h v26, v26
	WORD $0x4e7a3c6f // cmge.8h v15, v3, v26
	WORD $0x4e2f1dce // and.16b v14, v14, v15
	WORD $0x6e7485ba // sub.8h v26, v13, v20
	WORD $0x4e60bb5a // abs.8h v26, v26
	WORD $0x4e7a3c6f // cmge.8h v15, v3, v26
	WORD $0x4e2f1dce // and.16b v14, v14, v15
	WORD $0x4e381dce // and.16b v14, v14, v24
	WORD $0x4e391dce // and.16b v14, v14, v25
	WORD $0x6e70a9cf // umaxv.8h h15, v14
	WORD $0x0e023df6 // umov.h w22, v15[0]
	CBZ R22, filter8Only14
	WORD $0x4f13551a // shl.8h v26, v8, #0x3
	WORD $0x6e68875a // sub.8h v26, v26, v8
	WORD $0x4e6a853b // add.8h v27, v9, v10
	WORD $0x4f11577b // shl.8h v27, v27, #0x1
	WORD $0x4e7b875a // add.8h v26, v26, v27
	WORD $0x4e71861b // add.8h v27, v16, v17
	WORD $0x4e7b875a // add.8h v26, v26, v27
	WORD $0x4e73865b // add.8h v27, v18, v19
	WORD $0x4e7b875a // add.8h v26, v26, v27
	WORD $0x4e74875a // add.8h v26, v26, v20
	WORD $0x4f00851b // movi.8h v27, #0x8
	WORD $0x4e7b875a // add.8h v26, v26, v27
	WORD $0x4f1c075d // sshr.8h v29, v26, #0x4
	WORD $0x4eae1dde // mov.16b v30, v14
	WORD $0x6e691fbe // bsl.16b v30, v29, v9
	WORD $0x0e212bde // xtn.8b v30, v30
	WORD $0x0c00705e // st1.8b { v30 }, [x2]
	WORD $0x4e75861b // add.8h v27, v16, v21
	WORD $0x4e7b875a // add.8h v26, v26, v27
	WORD $0x4f11551b // shl.8h v27, v8, #0x1
	WORD $0x6e7b875a // sub.8h v26, v26, v27
	WORD $0x4f1c075d // sshr.8h v29, v26, #0x4
	WORD $0x4eae1dde // mov.16b v30, v14
	WORD $0x6e6a1fbe // bsl.16b v30, v29, v10
	WORD $0x0e212bde // xtn.8b v30, v30
	WORD $0x0c00707e // st1.8b { v30 }, [x3]
	WORD $0x4e76863b // add.8h v27, v17, v22
	WORD $0x4e7b875a // add.8h v26, v26, v27
	WORD $0x4e69851b // add.8h v27, v8, v9
	WORD $0x6e7b875a // sub.8h v26, v26, v27
	WORD $0x4f1c075d // sshr.8h v29, v26, #0x4
	WORD $0x4eae1dde // mov.16b v30, v14
	WORD $0x6e701fbe // bsl.16b v30, v29, v16
	WORD $0x0e212bde // xtn.8b v30, v30
	WORD $0x0c00709e // st1.8b { v30 }, [x4]
	WORD $0x4e77865b // add.8h v27, v18, v23
	WORD $0x4e7b875a // add.8h v26, v26, v27
	WORD $0x4e6a851b // add.8h v27, v8, v10
	WORD $0x6e7b875a // sub.8h v26, v26, v27
	WORD $0x4f1c075d // sshr.8h v29, v26, #0x4
	WORD $0x0c4070be // ld1.8b { v30 }, [x5]  pass-1 fallback
	WORD $0x2f08a7de // ushll.8h v30, v30, #0x0
	WORD $0x4eae1ddc // mov.16b v28, v14
	WORD $0x6e7e1fbc // bsl.16b v28, v29, v30
	WORD $0x0e212b9c // xtn.8b v28, v28
	WORD $0x0c0070bc // st1.8b { v28 }, [x5]
	WORD $0x4e6b867b // add.8h v27, v19, v11
	WORD $0x4e7b875a // add.8h v26, v26, v27
	WORD $0x4e70851b // add.8h v27, v8, v16
	WORD $0x6e7b875a // sub.8h v26, v26, v27
	WORD $0x4f1c075d // sshr.8h v29, v26, #0x4
	WORD $0x0c4070de // ld1.8b { v30 }, [x6]  pass-1 fallback
	WORD $0x2f08a7de // ushll.8h v30, v30, #0x0
	WORD $0x4eae1ddc // mov.16b v28, v14
	WORD $0x6e7e1fbc // bsl.16b v28, v29, v30
	WORD $0x0e212b9c // xtn.8b v28, v28
	WORD $0x0c0070dc // st1.8b { v28 }, [x6]
	WORD $0x4e6c869b // add.8h v27, v20, v12
	WORD $0x4e7b875a // add.8h v26, v26, v27
	WORD $0x4e71851b // add.8h v27, v8, v17
	WORD $0x6e7b875a // sub.8h v26, v26, v27
	WORD $0x4f1c075d // sshr.8h v29, v26, #0x4
	WORD $0x0c4070fe // ld1.8b { v30 }, [x7]  pass-1 fallback
	WORD $0x2f08a7de // ushll.8h v30, v30, #0x0
	WORD $0x4eae1ddc // mov.16b v28, v14
	WORD $0x6e7e1fbc // bsl.16b v28, v29, v30
	WORD $0x0e212b9c // xtn.8b v28, v28
	WORD $0x0c0070fc // st1.8b { v28 }, [x7]
	WORD $0x4e6d86bb // add.8h v27, v21, v13
	WORD $0x4e7b875a // add.8h v26, v26, v27
	WORD $0x4e72851b // add.8h v27, v8, v18
	WORD $0x6e7b875a // sub.8h v26, v26, v27
	WORD $0x4f1c075d // sshr.8h v29, v26, #0x4
	WORD $0x0c40711e // ld1.8b { v30 }, [x8]  pass-1 fallback
	WORD $0x2f08a7de // ushll.8h v30, v30, #0x0
	WORD $0x4eae1ddc // mov.16b v28, v14
	WORD $0x6e7e1fbc // bsl.16b v28, v29, v30
	WORD $0x0e212b9c // xtn.8b v28, v28
	WORD $0x0c00711c // st1.8b { v28 }, [x8]
	WORD $0x4e6d86db // add.8h v27, v22, v13
	WORD $0x4e7b875a // add.8h v26, v26, v27
	WORD $0x4e73853b // add.8h v27, v9, v19
	WORD $0x6e7b875a // sub.8h v26, v26, v27
	WORD $0x4f1c075d // sshr.8h v29, v26, #0x4
	WORD $0x0c40713e // ld1.8b { v30 }, [x9]  pass-1 fallback
	WORD $0x2f08a7de // ushll.8h v30, v30, #0x0
	WORD $0x4eae1ddc // mov.16b v28, v14
	WORD $0x6e7e1fbc // bsl.16b v28, v29, v30
	WORD $0x0e212b9c // xtn.8b v28, v28
	WORD $0x0c00713c // st1.8b { v28 }, [x9]
	WORD $0x4e6d86fb // add.8h v27, v23, v13
	WORD $0x4e7b875a // add.8h v26, v26, v27
	WORD $0x4e74855b // add.8h v27, v10, v20
	WORD $0x6e7b875a // sub.8h v26, v26, v27
	WORD $0x4f1c075d // sshr.8h v29, v26, #0x4
	WORD $0x0c40715e // ld1.8b { v30 }, [x10] pass-1 fallback
	WORD $0x2f08a7de // ushll.8h v30, v30, #0x0
	WORD $0x4eae1ddc // mov.16b v28, v14
	WORD $0x6e7e1fbc // bsl.16b v28, v29, v30
	WORD $0x0e212b9c // xtn.8b v28, v28
	WORD $0x0c00715c // st1.8b { v28 }, [x10]
	WORD $0x4e6d857b // add.8h v27, v11, v13
	WORD $0x4e7b875a // add.8h v26, v26, v27
	WORD $0x4e75861b // add.8h v27, v16, v21
	WORD $0x6e7b875a // sub.8h v26, v26, v27
	WORD $0x4f1c075d // sshr.8h v29, v26, #0x4
	WORD $0x4eae1dde // mov.16b v30, v14
	WORD $0x6e771fbe // bsl.16b v30, v29, v23
	WORD $0x0e212bde // xtn.8b v30, v30
	WORD $0x0c00717e // st1.8b { v30 }, [x11]
	WORD $0x4e6d859b // add.8h v27, v12, v13
	WORD $0x4e7b875a // add.8h v26, v26, v27
	WORD $0x4e76863b // add.8h v27, v17, v22
	WORD $0x6e7b875a // sub.8h v26, v26, v27
	WORD $0x4f1c075d // sshr.8h v29, v26, #0x4
	WORD $0x4eae1dde // mov.16b v30, v14
	WORD $0x6e6b1fbe // bsl.16b v30, v29, v11
	WORD $0x0e212bde // xtn.8b v30, v30
	WORD $0x0c00719e // st1.8b { v30 }, [x12]
	WORD $0x4f1155bb // shl.8h v27, v13, #0x1
	WORD $0x4e7b875a // add.8h v26, v26, v27
	WORD $0x4e77865b // add.8h v27, v18, v23
	WORD $0x6e7b875a // sub.8h v26, v26, v27
	WORD $0x4f1c075d // sshr.8h v29, v26, #0x4
	WORD $0x4eae1dde // mov.16b v30, v14
	WORD $0x6e6c1fbe // bsl.16b v30, v29, v12
	WORD $0x0e212bde // xtn.8b v30, v30
	WORD $0x0c0071be // st1.8b { v30 }, [x13]
	B advance14

filter8Only14:
	B advance14


advance14:
	ADD $8, R1, R1
	ADD $8, R2, R2
	ADD $8, R3, R3
	ADD $8, R4, R4
	ADD $8, R5, R5
	ADD $8, R6, R6
	ADD $8, R7, R7
	ADD $8, R8, R8
	ADD $8, R9, R9
	ADD $8, R10, R10
	ADD $8, R11, R11
	ADD $8, R12, R12
	ADD $8, R13, R13
	ADD $8, R14, R14
	SUB $1, R15, R15
	B   loop14

done14:
	RET

// ---- shared vertical wide context offsets ----
#define WV_BASE 0
#define WV_STRIDE 8
#define WV_COUNT 16
#define WV_LIMIT 24
#define WV_BLIMIT 32
#define WV_HEV 40
#define WV_THR 48

// func filter8VertNEONAsm(ctx *wideVertNEONCtx)
// Vertical-edge eight-sample filter. base points at p3 of the first position;
// the eight taps p3..q3 are contiguous bytes within a row and positions step by
// stride. Per group the kernel transposes through ld4 (gathering p3..q3 into
// lane vectors v16..v23), runs the exact filter8 lane arithmetic shared with
// filter8EdgeNEONAsm, transposes the six modified samples (p2..q2), and writes
// one 32-bit plus one 16-bit word per row. Bit-exact with filter8EdgePureGo.
TEXT ·filter8VertNEONAsm(SB), NOSPLIT, $0-8
	MOVD ctx+0(FP), R0
	MOVD WV_BASE(R0), R1
	MOVD WV_STRIDE(R0), R2
	MOVD WV_COUNT(R0), R3

	MOVD WV_LIMIT(R0), R6
	WORD $0x4e020cc0 // dup v0.8h, w6
	MOVD WV_BLIMIT(R0), R7
	WORD $0x4e020ce1 // dup v1.8h, w7
	MOVD WV_HEV(R0), R8
	WORD $0x4e020d02 // dup v2.8h, w8
	MOVD WV_THR(R0), R5
	WORD $0x4e020ca3 // dup v3.8h, w5
	WORD $0x4f048404 // movi v4.8h, #128
	WORD $0x6f0387e5 // mvni v5.8h, #127  (-128)
	WORD $0x4f0387e6 // movi v6.8h, #127
	WORD $0x4f008467 // movi v7.8h, #3

loop8v:
	CBZ R3, done8v
	MOVD R1, R9        // ld4 cursor A = p3 base
	ADD $4, R1, R10    // ld4 cursor B = q0 base
	WORD $0x0d602130 // ld4 {v16.b, v17.b, v18.b, v19.b}[0], [x9]
	WORD $0x0d602154 // ld4 {v20.b, v21.b, v22.b, v23.b}[0], [x10]
	ADD R2, R9, R9
	ADD R2, R10, R10
	WORD $0x0d602530 // ld4 {v16.b, v17.b, v18.b, v19.b}[1], [x9]
	WORD $0x0d602554 // ld4 {v20.b, v21.b, v22.b, v23.b}[1], [x10]
	ADD R2, R9, R9
	ADD R2, R10, R10
	WORD $0x0d602930 // ld4 {v16.b, v17.b, v18.b, v19.b}[2], [x9]
	WORD $0x0d602954 // ld4 {v20.b, v21.b, v22.b, v23.b}[2], [x10]
	ADD R2, R9, R9
	ADD R2, R10, R10
	WORD $0x0d602d30 // ld4 {v16.b, v17.b, v18.b, v19.b}[3], [x9]
	WORD $0x0d602d54 // ld4 {v20.b, v21.b, v22.b, v23.b}[3], [x10]
	ADD R2, R9, R9
	ADD R2, R10, R10
	WORD $0x0d603130 // ld4 {v16.b, v17.b, v18.b, v19.b}[4], [x9]
	WORD $0x0d603154 // ld4 {v20.b, v21.b, v22.b, v23.b}[4], [x10]
	ADD R2, R9, R9
	ADD R2, R10, R10
	WORD $0x0d603530 // ld4 {v16.b, v17.b, v18.b, v19.b}[5], [x9]
	WORD $0x0d603554 // ld4 {v20.b, v21.b, v22.b, v23.b}[5], [x10]
	ADD R2, R9, R9
	ADD R2, R10, R10
	WORD $0x0d603930 // ld4 {v16.b, v17.b, v18.b, v19.b}[6], [x9]
	WORD $0x0d603954 // ld4 {v20.b, v21.b, v22.b, v23.b}[6], [x10]
	ADD R2, R9, R9
	ADD R2, R10, R10
	WORD $0x0d603d30 // ld4 {v16.b, v17.b, v18.b, v19.b}[7], [x9]
	WORD $0x0d603d54 // ld4 {v20.b, v21.b, v22.b, v23.b}[7], [x10]
	ADD R2, R9, R9
	ADD R2, R10, R10
	WORD $0x2f08a610 // uxtl v16.8h, v16.8b
	WORD $0x2f08a631 // uxtl v17.8h, v17.8b
	WORD $0x2f08a652 // uxtl v18.8h, v18.8b
	WORD $0x2f08a673 // uxtl v19.8h, v19.8b
	WORD $0x2f08a694 // uxtl v20.8h, v20.8b
	WORD $0x2f08a6b5 // uxtl v21.8h, v21.8b
	WORD $0x2f08a6d6 // uxtl v22.8h, v22.8b
	WORD $0x2f08a6f7 // uxtl v23.8h, v23.8b
	WORD $0x6e71861d // sub v29.8h, v16.8h, v17.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c18 // cmge v24.8h, v0.8h, v29.8h
	WORD $0x6e72863d // sub v29.8h, v17.8h, v18.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c1e // cmge v30.8h, v0.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e73865d // sub v29.8h, v18.8h, v19.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c1e // cmge v30.8h, v0.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e7486bd // sub v29.8h, v21.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c1e // cmge v30.8h, v0.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e7586dd // sub v29.8h, v22.8h, v21.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c1e // cmge v30.8h, v0.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e7686fd // sub v29.8h, v23.8h, v22.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c1e // cmge v30.8h, v0.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e74867d // sub v29.8h, v19.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4f1157bd // shl v29.8h, v29.8h, #1
	WORD $0x6e75865e // sub v30.8h, v18.8h, v21.8h
	WORD $0x4e60bbde // abs v30.8h, v30.8h
	WORD $0x4f1f07de // sshr v30.8h, v30.8h, #1
	WORD $0x4e7e87bd // add v29.8h, v29.8h, v30.8h
	WORD $0x4e7d3c3e // cmge v30.8h, v1.8h, v29.8h
	WORD $0x4e3e1f18 // and v24.16b, v24.16b, v30.16b
	WORD $0x6e73865d // sub v29.8h, v18.8h, v19.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c79 // cmge v25.8h, v3.8h, v29.8h
	WORD $0x6e7486bd // sub v29.8h, v21.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c7e // cmge v30.8h, v3.8h, v29.8h
	WORD $0x4e3e1f39 // and v25.16b, v25.16b, v30.16b
	WORD $0x6e73863d // sub v29.8h, v17.8h, v19.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c7e // cmge v30.8h, v3.8h, v29.8h
	WORD $0x4e3e1f39 // and v25.16b, v25.16b, v30.16b
	WORD $0x6e7486dd // sub v29.8h, v22.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c7e // cmge v30.8h, v3.8h, v29.8h
	WORD $0x4e3e1f39 // and v25.16b, v25.16b, v30.16b
	WORD $0x6e73861d // sub v29.8h, v16.8h, v19.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c7e // cmge v30.8h, v3.8h, v29.8h
	WORD $0x4e3e1f39 // and v25.16b, v25.16b, v30.16b
	WORD $0x6e7486fd // sub v29.8h, v23.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e7d3c7e // cmge v30.8h, v3.8h, v29.8h
	WORD $0x4e3e1f39 // and v25.16b, v25.16b, v30.16b
	WORD $0x6e73865d // sub v29.8h, v18.8h, v19.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e6237ba // cmgt v26.8h, v29.8h, v2.8h
	WORD $0x6e7486bd // sub v29.8h, v21.8h, v20.8h
	WORD $0x4e60bbbd // abs v29.8h, v29.8h
	WORD $0x4e6237bd // cmgt v29.8h, v29.8h, v2.8h
	WORD $0x4ebd1f5a // orr v26.16b, v26.16b, v29.16b
	WORD $0x6e64865d // sub v29.8h, v18.8h, v4.8h
	WORD $0x6e6486be // sub v30.8h, v21.8h, v4.8h
	WORD $0x6e7e87bf // sub v31.8h, v29.8h, v30.8h
	WORD $0x4e666fff // smin v31.8h, v31.8h, v6.8h
	WORD $0x4e6567ff // smax v31.8h, v31.8h, v5.8h
	WORD $0x4e3a1fff // and v31.16b, v31.16b, v26.16b
	WORD $0x6e73869d // sub v29.8h, v20.8h, v19.8h
	WORD $0x4e679fbd // mul v29.8h, v29.8h, v7.8h
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e666fff // smin v31.8h, v31.8h, v6.8h
	WORD $0x4e6567ff // smax v31.8h, v31.8h, v5.8h
	WORD $0x4f00849d // movi v29.8h, #4
	WORD $0x4e7d87fb // add v27.8h, v31.8h, v29.8h
	WORD $0x4e666f7b // smin v27.8h, v27.8h, v6.8h
	WORD $0x4e65677b // smax v27.8h, v27.8h, v5.8h
	WORD $0x4f1d077b // sshr v27.8h, v27.8h, #3
	WORD $0x4e6787fc // add v28.8h, v31.8h, v7.8h
	WORD $0x4e666f9c // smin v28.8h, v28.8h, v6.8h
	WORD $0x4e65679c // smax v28.8h, v28.8h, v5.8h
	WORD $0x4f1d079c // sshr v28.8h, v28.8h, #3
	WORD $0x4e73865f // add v31.8h, v18.8h, v19.8h
	WORD $0x4e7487ff // add v31.8h, v31.8h, v20.8h
	WORD $0x4f11563e // shl v30.8h, v17.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4e679e1e // mul v30.8h, v16.8h, v7.8h
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3e // mov v30.16b, v25.16b
	WORD $0x6e711ffe // bsl v30.16b, v31.16b, v17.16b
	WORD $0x4eb81f1d // mov v29.16b, v24.16b
	WORD $0x6e711fdd // bsl v29.16b, v30.16b, v17.16b
	WORD $0x0e212ba8 // xtn v8.8b, v29.8h (p2 rows 0..7)
	WORD $0x4f1f277e // srshr v30.8h, v27.8h, #1
	WORD $0x6e64865d // sub v29.8h, v18.8h, v4.8h
	WORD $0x4e7e87bd // add v29.8h, v29.8h, v30.8h
	WORD $0x4e666fbd // smin v29.8h, v29.8h, v6.8h
	WORD $0x4e6567bd // smax v29.8h, v29.8h, v5.8h
	WORD $0x4e6487bd // add v29.8h, v29.8h, v4.8h
	WORD $0x4eba1f5e // mov v30.16b, v26.16b
	WORD $0x6e7d1e5e // bsl v30.16b, v18.16b, v29.16b
	WORD $0x4f11561f // shl v31.8h, v16.8h, #1
	WORD $0x4e7187ff // add v31.8h, v31.8h, v17.8h
	WORD $0x4f11565d // shl v29.8h, v18.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e7387ff // add v31.8h, v31.8h, v19.8h
	WORD $0x4e7487ff // add v31.8h, v31.8h, v20.8h
	WORD $0x4e7587ff // add v31.8h, v31.8h, v21.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3d // mov v29.16b, v25.16b
	WORD $0x6e7e1ffd // bsl v29.16b, v31.16b, v30.16b
	WORD $0x4eb81f1e // mov v30.16b, v24.16b
	WORD $0x6e721fbe // bsl v30.16b, v29.16b, v18.16b
	WORD $0x0e212bc9 // xtn v9.8b, v30.8h (p1 rows 0..7)
	WORD $0x6e64867d // sub v29.8h, v19.8h, v4.8h
	WORD $0x4e7c87bd // add v29.8h, v29.8h, v28.8h
	WORD $0x4e666fbd // smin v29.8h, v29.8h, v6.8h
	WORD $0x4e6567bd // smax v29.8h, v29.8h, v5.8h
	WORD $0x4e6487bd // add v29.8h, v29.8h, v4.8h
	WORD $0x4ebd1fbe // mov v30.16b, v29.16b
	WORD $0x4e71861f // add v31.8h, v16.8h, v17.8h
	WORD $0x4e7287ff // add v31.8h, v31.8h, v18.8h
	WORD $0x4f11567d // shl v29.8h, v19.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e7487ff // add v31.8h, v31.8h, v20.8h
	WORD $0x4e7587ff // add v31.8h, v31.8h, v21.8h
	WORD $0x4e7687ff // add v31.8h, v31.8h, v22.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3d // mov v29.16b, v25.16b
	WORD $0x6e7e1ffd // bsl v29.16b, v31.16b, v30.16b
	WORD $0x4eb81f1e // mov v30.16b, v24.16b
	WORD $0x6e731fbe // bsl v30.16b, v29.16b, v19.16b
	WORD $0x0e212bca // xtn v10.8b, v30.8h (p0 rows 0..7)
	WORD $0x6e64869d // sub v29.8h, v20.8h, v4.8h
	WORD $0x6e7b87bd // sub v29.8h, v29.8h, v27.8h
	WORD $0x4e666fbd // smin v29.8h, v29.8h, v6.8h
	WORD $0x4e6567bd // smax v29.8h, v29.8h, v5.8h
	WORD $0x4e6487bd // add v29.8h, v29.8h, v4.8h
	WORD $0x4ebd1fbe // mov v30.16b, v29.16b
	WORD $0x4e72863f // add v31.8h, v17.8h, v18.8h
	WORD $0x4e7387ff // add v31.8h, v31.8h, v19.8h
	WORD $0x4f11569d // shl v29.8h, v20.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e7587ff // add v31.8h, v31.8h, v21.8h
	WORD $0x4e7687ff // add v31.8h, v31.8h, v22.8h
	WORD $0x4e7787ff // add v31.8h, v31.8h, v23.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3d // mov v29.16b, v25.16b
	WORD $0x6e7e1ffd // bsl v29.16b, v31.16b, v30.16b
	WORD $0x4eb81f1e // mov v30.16b, v24.16b
	WORD $0x6e741fbe // bsl v30.16b, v29.16b, v20.16b
	WORD $0x0e212bcb // xtn v11.8b, v30.8h (q0 rows 0..7)
	WORD $0x4f1f277e // srshr v30.8h, v27.8h, #1
	WORD $0x6e6486bd // sub v29.8h, v21.8h, v4.8h
	WORD $0x6e7e87bd // sub v29.8h, v29.8h, v30.8h
	WORD $0x4e666fbd // smin v29.8h, v29.8h, v6.8h
	WORD $0x4e6567bd // smax v29.8h, v29.8h, v5.8h
	WORD $0x4e6487bd // add v29.8h, v29.8h, v4.8h
	WORD $0x4eba1f5e // mov v30.16b, v26.16b
	WORD $0x6e7d1ebe // bsl v30.16b, v21.16b, v29.16b
	WORD $0x4e73865f // add v31.8h, v18.8h, v19.8h
	WORD $0x4e7487ff // add v31.8h, v31.8h, v20.8h
	WORD $0x4f1156bd // shl v29.8h, v21.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e7687ff // add v31.8h, v31.8h, v22.8h
	WORD $0x4f1156fd // shl v29.8h, v23.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3d // mov v29.16b, v25.16b
	WORD $0x6e7e1ffd // bsl v29.16b, v31.16b, v30.16b
	WORD $0x4eb81f1e // mov v30.16b, v24.16b
	WORD $0x6e751fbe // bsl v30.16b, v29.16b, v21.16b
	WORD $0x0e212bcc // xtn v12.8b, v30.8h (q1 rows 0..7)
	WORD $0x4e74867f // add v31.8h, v19.8h, v20.8h
	WORD $0x4e7587ff // add v31.8h, v31.8h, v21.8h
	WORD $0x4f1156dd // shl v29.8h, v22.8h, #1
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4e679efd // mul v29.8h, v23.8h, v7.8h
	WORD $0x4e7d87ff // add v31.8h, v31.8h, v29.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4eb91f3e // mov v30.16b, v25.16b
	WORD $0x6e761ffe // bsl v30.16b, v31.16b, v22.16b
	WORD $0x4eb81f1d // mov v29.16b, v24.16b
	WORD $0x6e761fdd // bsl v29.16b, v30.16b, v22.16b
	WORD $0x0e212bad // xtn v13.8b, v29.8h (q2 rows 0..7)

	// Interleaved lane stores write p2..q0 and q1..q2 contiguously per row.
	ADD $1, R1, R11
	ADD $5, R1, R12
	WORD $0x0da22168 // st4 {v8.b-v11.b}[0], [x11], x2
	WORD $0x0da2018c // st2 {v12.b-v13.b}[0], [x12], x2
	WORD $0x0da22568 // st4 {v8.b-v11.b}[1], [x11], x2
	WORD $0x0da2058c // st2 {v12.b-v13.b}[1], [x12], x2
	WORD $0x0da22968 // st4 {v8.b-v11.b}[2], [x11], x2
	WORD $0x0da2098c // st2 {v12.b-v13.b}[2], [x12], x2
	WORD $0x0da22d68 // st4 {v8.b-v11.b}[3], [x11], x2
	WORD $0x0da20d8c // st2 {v12.b-v13.b}[3], [x12], x2
	WORD $0x0da23168 // st4 {v8.b-v11.b}[4], [x11], x2
	WORD $0x0da2118c // st2 {v12.b-v13.b}[4], [x12], x2
	WORD $0x0da23568 // st4 {v8.b-v11.b}[5], [x11], x2
	WORD $0x0da2158c // st2 {v12.b-v13.b}[5], [x12], x2
	WORD $0x0da23968 // st4 {v8.b-v11.b}[6], [x11], x2
	WORD $0x0da2198c // st2 {v12.b-v13.b}[6], [x12], x2
	WORD $0x0da23d68 // st4 {v8.b-v11.b}[7], [x11], x2
	WORD $0x0da21d8c // st2 {v12.b-v13.b}[7], [x12], x2
	LSL $3, R2, R12   // 8*stride
	ADD R12, R1, R1
	SUB $1, R3, R3
	B loop8v

done8v:
	RET


// func filter6VertNEONAsm(ctx *wideVertNEONCtx)
// Vertical-edge six-sample filter. base points at p2 of the first position; the
// six taps p2..q2 are contiguous bytes within a row and positions step by
// stride. Per group the kernel transposes through ld4+ld2 (gathering p2..q2 into
// lane vectors v16..v21), runs the exact filter6 lane arithmetic shared with
// filter6EdgeNEONAsm, transposes the four modified samples (p1..q1), and writes
// one contiguous 32-bit word per row. Bit-exact with filter6EdgePureGo.
TEXT ·filter6VertNEONAsm(SB), NOSPLIT, $0-8
	MOVD ctx+0(FP), R0
	MOVD WV_BASE(R0), R1
	MOVD WV_STRIDE(R0), R2
	MOVD WV_COUNT(R0), R3

	MOVD WV_LIMIT(R0), R6
	WORD $0x4e020cc0 // dup v0.8h, w6
	MOVD WV_BLIMIT(R0), R7
	WORD $0x4e020ce1 // dup v1.8h, w7
	MOVD WV_HEV(R0), R8
	WORD $0x4e020d02 // dup v2.8h, w8
	MOVD WV_THR(R0), R5
	WORD $0x4e020ca3 // dup v3.8h, w5
	WORD $0x4f048404 // movi v4.8h, #128
	WORD $0x6f0387e5 // mvni v5.8h, #127  (-128)
	WORD $0x4f0387e6 // movi v6.8h, #127
	WORD $0x4f008467 // movi v7.8h, #3

loop6v:
	CBZ R3, done6v
	MOVD R1, R9        // ld4 cursor A = p2 base
	ADD $4, R1, R10    // ld2 cursor B = q1 base
	WORD $0x0d602130 // ld4 {v16.b, v17.b, v18.b, v19.b}[0], [x9]
	WORD $0x0d600154 // ld2 {v20.b, v21.b}[0], [x10]
	ADD R2, R9, R9
	ADD R2, R10, R10
	WORD $0x0d602530 // ld4 {v16.b, v17.b, v18.b, v19.b}[1], [x9]
	WORD $0x0d600554 // ld2 {v20.b, v21.b}[1], [x10]
	ADD R2, R9, R9
	ADD R2, R10, R10
	WORD $0x0d602930 // ld4 {v16.b, v17.b, v18.b, v19.b}[2], [x9]
	WORD $0x0d600954 // ld2 {v20.b, v21.b}[2], [x10]
	ADD R2, R9, R9
	ADD R2, R10, R10
	WORD $0x0d602d30 // ld4 {v16.b, v17.b, v18.b, v19.b}[3], [x9]
	WORD $0x0d600d54 // ld2 {v20.b, v21.b}[3], [x10]
	ADD R2, R9, R9
	ADD R2, R10, R10
	WORD $0x0d603130 // ld4 {v16.b, v17.b, v18.b, v19.b}[4], [x9]
	WORD $0x0d601154 // ld2 {v20.b, v21.b}[4], [x10]
	ADD R2, R9, R9
	ADD R2, R10, R10
	WORD $0x0d603530 // ld4 {v16.b, v17.b, v18.b, v19.b}[5], [x9]
	WORD $0x0d601554 // ld2 {v20.b, v21.b}[5], [x10]
	ADD R2, R9, R9
	ADD R2, R10, R10
	WORD $0x0d603930 // ld4 {v16.b, v17.b, v18.b, v19.b}[6], [x9]
	WORD $0x0d601954 // ld2 {v20.b, v21.b}[6], [x10]
	ADD R2, R9, R9
	ADD R2, R10, R10
	WORD $0x0d603d30 // ld4 {v16.b, v17.b, v18.b, v19.b}[7], [x9]
	WORD $0x0d601d54 // ld2 {v20.b, v21.b}[7], [x10]
	ADD R2, R9, R9
	ADD R2, R10, R10
	WORD $0x2f08a610 // uxtl v16.8h, v16.8b
	WORD $0x2f08a631 // uxtl v17.8h, v17.8b
	WORD $0x2f08a652 // uxtl v18.8h, v18.8b
	WORD $0x2f08a673 // uxtl v19.8h, v19.8b
	WORD $0x2f08a694 // uxtl v20.8h, v20.8b
	WORD $0x2f08a6b5 // uxtl v21.8h, v21.8b
	WORD $0x6e718616 // sub v22.8h, v16.8h, v17.8h
	WORD $0x4e60bad6 // abs v22.8h, v22.8h
	WORD $0x6e728637 // sub v23.8h, v17.8h, v18.8h
	WORD $0x4e60baf7 // abs v23.8h, v23.8h
	WORD $0x6e738698 // sub v24.8h, v20.8h, v19.8h
	WORD $0x4e60bb18 // abs v24.8h, v24.8h
	WORD $0x6e7486b9 // sub v25.8h, v21.8h, v20.8h
	WORD $0x4e60bb39 // abs v25.8h, v25.8h
	WORD $0x6e73865a // sub v26.8h, v18.8h, v19.8h
	WORD $0x4e60bb5a // abs v26.8h, v26.8h
	WORD $0x6e74863b // sub v27.8h, v17.8h, v20.8h
	WORD $0x4e60bb7b // abs v27.8h, v27.8h
	WORD $0x4e763c1c // cmge v28.8h, v0.8h, v22.8h
	WORD $0x4e773c1e // cmge v30.8h, v0.8h, v23.8h
	WORD $0x4e3e1f9c // and v28.16b, v28.16b, v30.16b
	WORD $0x4e783c1e // cmge v30.8h, v0.8h, v24.8h
	WORD $0x4e3e1f9c // and v28.16b, v28.16b, v30.16b
	WORD $0x4e793c1e // cmge v30.8h, v0.8h, v25.8h
	WORD $0x4e3e1f9c // and v28.16b, v28.16b, v30.16b
	WORD $0x4f11575e // shl v30.8h, v26.8h, #1
	WORD $0x4f1f077f // sshr v31.8h, v27.8h, #1
	WORD $0x4e7f87de // add v30.8h, v30.8h, v31.8h
	WORD $0x4e7e3c3e // cmge v30.8h, v1.8h, v30.8h
	WORD $0x4e3e1f9c // and v28.16b, v28.16b, v30.16b
	WORD $0x4e773c7d // cmge v29.8h, v3.8h, v23.8h
	WORD $0x4e783c7e // cmge v30.8h, v3.8h, v24.8h
	WORD $0x4e3e1fbd // and v29.16b, v29.16b, v30.16b
	WORD $0x6e72861e // sub v30.8h, v16.8h, v18.8h
	WORD $0x4e60bbde // abs v30.8h, v30.8h
	WORD $0x4e7e3c7e // cmge v30.8h, v3.8h, v30.8h
	WORD $0x4e3e1fbd // and v29.16b, v29.16b, v30.16b
	WORD $0x6e7386be // sub v30.8h, v21.8h, v19.8h
	WORD $0x4e60bbde // abs v30.8h, v30.8h
	WORD $0x4e7e3c7e // cmge v30.8h, v3.8h, v30.8h
	WORD $0x4e3e1fbd // and v29.16b, v29.16b, v30.16b
	WORD $0x6e64863a // sub v26.8h, v17.8h, v4.8h
	WORD $0x6e64869b // sub v27.8h, v20.8h, v4.8h
	WORD $0x6e64867e // sub v30.8h, v19.8h, v4.8h
	WORD $0x6e64865f // sub v31.8h, v18.8h, v4.8h
	WORD $0x6e728636 // sub v22.8h, v17.8h, v18.8h
	WORD $0x4e60bad6 // abs v22.8h, v22.8h
	WORD $0x4e6236d9 // cmgt v25.8h, v22.8h, v2.8h
	WORD $0x6e738696 // sub v22.8h, v20.8h, v19.8h
	WORD $0x4e60bad6 // abs v22.8h, v22.8h
	WORD $0x4e6236d6 // cmgt v22.8h, v22.8h, v2.8h
	WORD $0x4eb61f39 // orr v25.16b, v25.16b, v22.16b
	WORD $0x6e7b8756 // sub v22.8h, v26.8h, v27.8h
	WORD $0x4e666ed6 // smin v22.8h, v22.8h, v6.8h
	WORD $0x4e6566d6 // smax v22.8h, v22.8h, v5.8h
	WORD $0x4e391ed6 // and v22.16b, v22.16b, v25.16b
	WORD $0x6e7f87d7 // sub v23.8h, v30.8h, v31.8h
	WORD $0x4e679ef7 // mul v23.8h, v23.8h, v7.8h
	WORD $0x4e7786d6 // add v22.8h, v22.8h, v23.8h
	WORD $0x4e666ed6 // smin v22.8h, v22.8h, v6.8h
	WORD $0x4e6566d6 // smax v22.8h, v22.8h, v5.8h
	WORD $0x4f008498 // movi v24.8h, #4
	WORD $0x4e7886d7 // add v23.8h, v22.8h, v24.8h
	WORD $0x4e666ef7 // smin v23.8h, v23.8h, v6.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4f1d06f7 // sshr v23.8h, v23.8h, #3
	WORD $0x4e6786d8 // add v24.8h, v22.8h, v7.8h
	WORD $0x4e666f18 // smin v24.8h, v24.8h, v6.8h
	WORD $0x4e656718 // smax v24.8h, v24.8h, v5.8h
	WORD $0x4f1d0718 // sshr v24.8h, v24.8h, #3
	WORD $0x4f1f26f6 // srshr v22.8h, v23.8h, #1
	WORD $0x6e64863a // sub v26.8h, v17.8h, v4.8h
	WORD $0x4e76875a // add v26.8h, v26.8h, v22.8h
	WORD $0x4e666f5a // smin v26.8h, v26.8h, v6.8h
	WORD $0x4e65675a // smax v26.8h, v26.8h, v5.8h
	WORD $0x4e64875a // add v26.8h, v26.8h, v4.8h
	WORD $0x4eb91f3e // mov v30.16b, v25.16b
	WORD $0x6e7a1e3e // bsl v30.16b, v17.16b, v26.16b
	WORD $0x4e679e1f // mul v31.8h, v16.8h, v7.8h
	WORD $0x4f11563a // shl v26.8h, v17.8h, #1
	WORD $0x4e7a87ff // add v31.8h, v31.8h, v26.8h
	WORD $0x4f11565a // shl v26.8h, v18.8h, #1
	WORD $0x4e7a87ff // add v31.8h, v31.8h, v26.8h
	WORD $0x4e7387ff // add v31.8h, v31.8h, v19.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4ebd1fba // mov v26.16b, v29.16b
	WORD $0x6e7e1ffa // bsl v26.16b, v31.16b, v30.16b
	WORD $0x4ebc1f9b // mov v27.16b, v28.16b
	WORD $0x6e711f5b // bsl v27.16b, v26.16b, v17.16b
	WORD $0x0e212b68 // xtn v8.8b, v27.8h (p1 rows 0..7)
	WORD $0x6e64865a // sub v26.8h, v18.8h, v4.8h
	WORD $0x4e78875a // add v26.8h, v26.8h, v24.8h
	WORD $0x4e666f5a // smin v26.8h, v26.8h, v6.8h
	WORD $0x4e65675a // smax v26.8h, v26.8h, v5.8h
	WORD $0x4e64875a // add v26.8h, v26.8h, v4.8h
	WORD $0x4e74861f // add v31.8h, v16.8h, v20.8h
	WORD $0x4f11563e // shl v30.8h, v17.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f11565e // shl v30.8h, v18.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f11567e // shl v30.8h, v19.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4ebd1fbe // mov v30.16b, v29.16b
	WORD $0x6e7a1ffe // bsl v30.16b, v31.16b, v26.16b
	WORD $0x4ebc1f9b // mov v27.16b, v28.16b
	WORD $0x6e721fdb // bsl v27.16b, v30.16b, v18.16b
	WORD $0x0e212b69 // xtn v9.8b, v27.8h (p0 rows 0..7)
	WORD $0x6e64867a // sub v26.8h, v19.8h, v4.8h
	WORD $0x6e77875a // sub v26.8h, v26.8h, v23.8h
	WORD $0x4e666f5a // smin v26.8h, v26.8h, v6.8h
	WORD $0x4e65675a // smax v26.8h, v26.8h, v5.8h
	WORD $0x4e64875a // add v26.8h, v26.8h, v4.8h
	WORD $0x4e75863f // add v31.8h, v17.8h, v21.8h
	WORD $0x4f11565e // shl v30.8h, v18.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f11567e // shl v30.8h, v19.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f11569e // shl v30.8h, v20.8h, #1
	WORD $0x4e7e87ff // add v31.8h, v31.8h, v30.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4ebd1fbe // mov v30.16b, v29.16b
	WORD $0x6e7a1ffe // bsl v30.16b, v31.16b, v26.16b
	WORD $0x4ebc1f9b // mov v27.16b, v28.16b
	WORD $0x6e731fdb // bsl v27.16b, v30.16b, v19.16b
	WORD $0x0e212b6a // xtn v10.8b, v27.8h (q0 rows 0..7)
	WORD $0x6e64869a // sub v26.8h, v20.8h, v4.8h
	WORD $0x6e76875a // sub v26.8h, v26.8h, v22.8h
	WORD $0x4e666f5a // smin v26.8h, v26.8h, v6.8h
	WORD $0x4e65675a // smax v26.8h, v26.8h, v5.8h
	WORD $0x4e64875a // add v26.8h, v26.8h, v4.8h
	WORD $0x4eb91f3e // mov v30.16b, v25.16b
	WORD $0x6e7a1e9e // bsl v30.16b, v20.16b, v26.16b
	WORD $0x4e679ebf // mul v31.8h, v21.8h, v7.8h
	WORD $0x4f11569a // shl v26.8h, v20.8h, #1
	WORD $0x4e7a87ff // add v31.8h, v31.8h, v26.8h
	WORD $0x4f11567a // shl v26.8h, v19.8h, #1
	WORD $0x4e7a87ff // add v31.8h, v31.8h, v26.8h
	WORD $0x4e7287ff // add v31.8h, v31.8h, v18.8h
	WORD $0x4f1d27ff // srshr v31.8h, v31.8h, #3
	WORD $0x4ebd1fba // mov v26.16b, v29.16b
	WORD $0x6e7e1ffa // bsl v26.16b, v31.16b, v30.16b
	WORD $0x4ebc1f9b // mov v27.16b, v28.16b
	WORD $0x6e741f5b // bsl v27.16b, v26.16b, v20.16b
	WORD $0x0e212b6b // xtn v11.8b, v27.8h (q1 rows 0..7)

	// Transpose four 8-byte row columns into eight 32-bit row words.
	VZIP1 V9.B8, V8.B8, V12.B8
	VZIP2 V9.B8, V8.B8, V13.B8
	VZIP1 V11.B8, V10.B8, V14.B8
	VZIP2 V11.B8, V10.B8, V15.B8
	VZIP1 V14.H4, V12.H4, V8.H4
	VZIP2 V14.H4, V12.H4, V9.H4
	VZIP1 V15.H4, V13.H4, V10.H4
	VZIP2 V15.H4, V13.H4, V11.H4
	ADD $1, R1, R11
	VST1.P V8.S[0], (R11)(R2)
	VST1.P V8.S[1], (R11)(R2)
	VST1.P V9.S[0], (R11)(R2)
	VST1.P V9.S[1], (R11)(R2)
	VST1.P V10.S[0], (R11)(R2)
	VST1.P V10.S[1], (R11)(R2)
	VST1.P V11.S[0], (R11)(R2)
	VST1.P V11.S[1], (R11)(R2)
	LSL $3, R2, R12   // 8*stride
	ADD R12, R1, R1
	SUB $1, R3, R3
	B loop6v

done6v:
	RET
