// NEON-accelerated inverse ADST16 four-column kernel.
//
// Four adjacent columns of the row-major scratch buffer ride the four int32
// lanes of each .4s register, following dav1d's high-bitdepth inverse
// transform shape (src/arm/64/itx16.S: inv_adst_4s_x16_neon and the
// mul_mla/mul_mls + srshr + smax/smin idiom): every butterfly multiply is a
// plain mul/mla/mls .4s, every rounding shift is srshr .4s and every stage
// clamp is smax+smin against the stage bounds. Working in int32 lanes without
// widening is exact here because the column-pass inputs are pre-clamped to the
// stage range (|v| <= 2^19 across all supported bit depths) and every
// coefficient with |w| > 2048 (2751, 2276) is rewritten as w-4096 plus a
// compensating post-shift add of the (clamped) input, an exact integer
// identity that keeps every multiply accumulator below 2^31 (the adapter
// enforces the clamp-bound precondition and falls back otherwise). The
// fixed-point products, rounding shifts and clamps are bit-for-bit identical
// to running the pure-Go inverseADST16 on each column, asserted exhaustively
// by the column dispatch differential tests.
//
// The body is generated by transliterating the pure-Go butterfly to NEON
// intrinsics (tools/itxgen: inverseADST16Core), compiling with the system C
// compiler at -O2 and transcribing the disassembly verbatim as WORD-encoded
// opcodes, because Go's arm64 assembler does not expose the
// signed-rounding-shift mnemonics. The kernel is pure straight-line leaf code
// (no branches, no calls) and manages its own small spill frame below the
// (empty) Go frame, within the nosplit stack budget.
//
// SPDX-License-Identifier: BSD-2-Clause
//
// See LICENSE for the BSD-2-Clause grant and NOTICE for the AOM attribution.

//go:build arm64 && !purego

#include "textflag.h"

// func inverseADST16Col4NEON(base *int32, rowStrideBytes, min, max int64)
// Transforms four adjacent columns (col..col+3) of the row-major scratch
// buffer in place. base points at scratch[col]; rows are rowStrideBytes
// apart. The four columns occupy int32 lanes 0-3. Bit-for-bit identical to
// inverseADST16 run on each column.
TEXT ·inverseADST16Col4NEON(SB), NOSPLIT, $0-32
	MOVD base+0(FP), R0
	MOVD rowStrideBytes+8(FP), R1
	MOVD min+16(FP), R2
	MOVD max+24(FP), R3
	WORD $0x6dbf23e9 // stp	d9, d8, [sp, #-0x10]!
	WORD $0x4e040c41 // dup.4s	v1, w2
	WORD $0x4e040c60 // dup.4s	v0, w3
	WORD $0x6f000483 // mvni.4s	v3, #0x4
	WORD $0x4f060524 // movi.4s	v4, #0xc9
	WORD $0x3dc00005 // ldr	q5, [x0]
	WORD $0x4ea49ca6 // mul.4s	v6, v5, v4
	WORD $0xd37cec28 // lsl	x8, x1, #4
	WORD $0xcb010009 // sub	x9, x0, x1
	WORD $0x3ce86922 // ldr	q2, [x9, x8]
	WORD $0x4ea39446 // mla.4s	v6, v2, v3
	WORD $0x4f0004a3 // movi.4s	v3, #0x5
	WORD $0x4ea39ca3 // mul.4s	v3, v5, v3
	WORD $0x4ea49443 // mla.4s	v3, v2, v4
	WORD $0x4f3434c2 // srsra.4s	v2, v6, #0xc
	WORD $0x4f342463 // srshr.4s	v3, v3, #0xc
	WORD $0x6ea58463 // sub.4s	v3, v3, v5
	WORD $0x52807c6a // mov	w10, #0x3e3             ; =995
	WORD $0x4e040d45 // dup.4s	v5, w10
	WORD $0xd37ff82b // lsl	x11, x1, #1
	WORD $0x3ceb6806 // ldr	q6, [x0, x11]
	WORD $0x6f030747 // mvni.4s	v7, #0x7a
	WORD $0x4ea59cd0 // mul.4s	v16, v6, v5
	WORD $0x528001aa // mov	w10, #0xd               ; =13
	WORD $0x9b0a7c2a // mul	x10, x1, x10
	WORD $0x3cea6804 // ldr	q4, [x0, x10]
	WORD $0x4ea79490 // mla.4s	v16, v4, v7
	WORD $0x4f030767 // movi.4s	v7, #0x7b
	WORD $0x4ea79cc7 // mul.4s	v7, v6, v7
	WORD $0x4ea59487 // mla.4s	v7, v4, v5
	WORD $0x4f343604 // srsra.4s	v4, v16, #0xc
	WORD $0x4f3424e5 // srshr.4s	v5, v7, #0xc
	WORD $0x1280310c // mov	w12, #-0x189            ; =-393
	WORD $0x4e040d87 // dup.4s	v7, w12
	WORD $0x5280daec // mov	w12, #0x6d7             ; =1751
	WORD $0x4e040d90 // dup.4s	v16, w12
	WORD $0x6ea684a5 // sub.4s	v5, v5, v6
	WORD $0xd37ef42d // lsl	x13, x1, #2
	WORD $0x3ced6811 // ldr	q17, [x0, x13]
	WORD $0x4eb09e32 // mul.4s	v18, v17, v16
	WORD $0x5280312c // mov	w12, #0x189             ; =393
	WORD $0x4e040d93 // dup.4s	v19, w12
	WORD $0x5280016c // mov	w12, #0xb               ; =11
	WORD $0x9b0c7c2c // mul	x12, x1, x12
	WORD $0x3cec6806 // ldr	q6, [x0, x12]
	WORD $0x4ea794d2 // mla.4s	v18, v6, v7
	WORD $0x4eb39e27 // mul.4s	v7, v17, v19
	WORD $0x4eb094c7 // mla.4s	v7, v6, v16
	WORD $0x4f343646 // srsra.4s	v6, v18, #0xc
	WORD $0x4f3424e7 // srshr.4s	v7, v7, #0xc
	WORD $0x6eb184e7 // sub.4s	v7, v7, v17
	WORD $0x5280cdae // mov	w14, #0x66d             ; =1645
	WORD $0x4e040dd0 // dup.4s	v16, w14
	WORD $0x5280988e // mov	w14, #0x4c4             ; =1220
	WORD $0x4e040dd1 // dup.4s	v17, w14
	WORD $0x528000ce // mov	w14, #0x6               ; =6
	WORD $0x9b0e7c30 // mul	x16, x1, x14
	WORD $0x3cf06812 // ldr	q18, [x0, x16]
	WORD $0x4eb19e54 // mul.4s	v20, v18, v17
	WORD $0xd37df02f // lsl	x15, x1, #3
	WORD $0x8b0101ee // add	x14, x15, x1
	WORD $0x3cee6813 // ldr	q19, [x0, x14]
	WORD $0x4eb09674 // mla.4s	v20, v19, v16
	WORD $0x4f352697 // srshr.4s	v23, v20, #0xb
	WORD $0x1280cd91 // mov	w17, #-0x66d            ; =-1645
	WORD $0x4e040e30 // dup.4s	v16, w17
	WORD $0x4eb09e55 // mul.4s	v21, v18, v16
	WORD $0x4eb19675 // mla.4s	v21, v19, v17
	WORD $0x4f3526b6 // srshr.4s	v22, v21, #0xb
	WORD $0x1280a811 // mov	w17, #-0x541            ; =-1345
	WORD $0x4e040e30 // dup.4s	v16, w17
	WORD $0xcb0101f1 // sub	x17, x15, x1
	WORD $0x3cf16811 // ldr	q17, [x0, x17]
	WORD $0x4eb09e30 // mul.4s	v16, v17, v16
	WORD $0x12808482 // mov	w2, #-0x425             ; =-1061
	WORD $0x4e040c52 // dup.4s	v18, w2
	WORD $0x3cef6813 // ldr	q19, [x0, x15]
	WORD $0x4eb29670 // mla.4s	v16, v19, v18
	WORD $0x4eb1867a // add.4s	v26, v19, v17
	WORD $0x4f34361a // srsra.4s	v26, v16, #0xc
	WORD $0x4eb29e30 // mul.4s	v16, v17, v18
	WORD $0x5280a822 // mov	w2, #0x541              ; =1345
	WORD $0x4e040c52 // dup.4s	v18, w2
	WORD $0x4eb29670 // mla.4s	v16, v19, v18
	WORD $0x4f342610 // srshr.4s	v16, v16, #0xc
	WORD $0x6eb38610 // sub.4s	v16, v16, v19
	WORD $0x1280f8a2 // mov	w2, #-0x7c6             ; =-1990
	WORD $0x4e040c52 // dup.4s	v18, w2
	WORD $0x4eb1861b // add.4s	v27, v16, v17
	WORD $0x8b0101a3 // add	x3, x13, x1
	WORD $0x3ce36810 // ldr	q16, [x0, x3]
	WORD $0x4eb29e11 // mul.4s	v17, v16, v18
	WORD $0x128048c2 // mov	w2, #-0x247             ; =-583
	WORD $0x4e040c52 // dup.4s	v18, w2
	WORD $0x52800142 // mov	w2, #0xa                ; =10
	WORD $0x9b027c22 // mul	x2, x1, x2
	WORD $0x3ce26813 // ldr	q19, [x0, x2]
	WORD $0x4eb29671 // mla.4s	v17, v19, v18
	WORD $0x4eb0867c // add.4s	v28, v19, v16
	WORD $0x4f34363c // srsra.4s	v28, v17, #0xc
	WORD $0x5280f8c4 // mov	w4, #0x7c6              ; =1990
	WORD $0x4e040c91 // dup.4s	v17, w4
	WORD $0x4eb29e12 // mul.4s	v18, v16, v18
	WORD $0x4eb19672 // mla.4s	v18, v19, v17
	WORD $0x4f342651 // srshr.4s	v17, v18, #0xc
	WORD $0x6eb38631 // sub.4s	v17, v17, v19
	WORD $0x4eb0863e // add.4s	v30, v17, v16
	WORD $0x5280ac84 // mov	w4, #0x564              ; =1380
	WORD $0x4e040c90 // dup.4s	v16, w4
	WORD $0x8b010166 // add	x6, x11, x1
	WORD $0x3ce6681d // ldr	q29, [x0, x6]
	WORD $0x4eb09fb0 // mul.4s	v16, v29, v16
	WORD $0x6f0705d1 // mvni.4s	v17, #0xee
	WORD $0x52800184 // mov	w4, #0xc                ; =12
	WORD $0x9b047c24 // mul	x4, x1, x4
	WORD $0x3ce4681f // ldr	q31, [x0, x4]
	WORD $0x4eb197f0 // mla.4s	v16, v31, v17
	WORD $0x4eb19fb1 // mul.4s	v17, v29, v17
	WORD $0x1280ac65 // mov	w5, #-0x564             ; =-1380
	WORD $0x4e040cb2 // dup.4s	v18, w5
	WORD $0x4eb297f1 // mla.4s	v17, v31, v18
	WORD $0x4f34361f // srsra.4s	v31, v16, #0xc
	WORD $0x4f34363d // srsra.4s	v29, v17, #0xc
	WORD $0x52804b25 // mov	w5, #0x259              ; =601
	WORD $0x4e040cb0 // dup.4s	v16, w5
	WORD $0x3ce16808 // ldr	q8, [x0, x1]
	WORD $0x4eb09d10 // mul.4s	v16, v8, v16
	WORD $0x6f010571 // mvni.4s	v17, #0x2b
	WORD $0x528001c5 // mov	w5, #0xe                ; =14
	WORD $0x9b057c25 // mul	x5, x1, x5
	WORD $0x3ce56809 // ldr	q9, [x0, x5]
	WORD $0x4eb19530 // mla.4s	v16, v9, v17
	WORD $0x4eb19d11 // mul.4s	v17, v8, v17
	WORD $0x12804b07 // mov	w7, #-0x259             ; =-601
	WORD $0x4e040cf2 // dup.4s	v18, w7
	WORD $0x4eb29531 // mla.4s	v17, v9, v18
	WORD $0x4f343609 // srsra.4s	v9, v16, #0xc
	WORD $0x4f343628 // srsra.4s	v8, v17, #0xc
	WORD $0x4ea28750 // add.4s	v16, v26, v2
	WORD $0x4ea16610 // smax.4s	v16, v16, v1
	WORD $0x4ea06e10 // smin.4s	v16, v16, v0
	WORD $0x4ea38771 // add.4s	v17, v27, v3
	WORD $0x4ea16631 // smax.4s	v17, v17, v1
	WORD $0x4ea06e31 // smin.4s	v17, v17, v0
	WORD $0x4ea48792 // add.4s	v18, v28, v4
	WORD $0x4ea16652 // smax.4s	v18, v18, v1
	WORD $0x4ea06e52 // smin.4s	v18, v18, v0
	WORD $0x4ea587d3 // add.4s	v19, v30, v5
	WORD $0x4ea16673 // smax.4s	v19, v19, v1
	WORD $0x4ea06e73 // smin.4s	v19, v19, v0
	WORD $0x4ea687f8 // add.4s	v24, v31, v6
	WORD $0x4ea16718 // smax.4s	v24, v24, v1
	WORD $0x4ea06f18 // smin.4s	v24, v24, v0
	WORD $0x4ea787b9 // add.4s	v25, v29, v7
	WORD $0x4ea16739 // smax.4s	v25, v25, v1
	WORD $0x4ea06f39 // smin.4s	v25, v25, v0
	WORD $0x6ea986f7 // sub.4s	v23, v23, v9
	WORD $0x4f353689 // srsra.4s	v9, v20, #0xb
	WORD $0x4ea16534 // smax.4s	v20, v9, v1
	WORD $0x4ea06e94 // smin.4s	v20, v20, v0
	WORD $0x6ea886d6 // sub.4s	v22, v22, v8
	WORD $0x4f3536a8 // srsra.4s	v8, v21, #0xb
	WORD $0x4ea16515 // smax.4s	v21, v8, v1
	WORD $0x4ea06eb5 // smin.4s	v21, v21, v0
	WORD $0x6eba8442 // sub.4s	v2, v2, v26
	WORD $0x4ea16442 // smax.4s	v2, v2, v1
	WORD $0x4ea06c42 // smin.4s	v2, v2, v0
	WORD $0x6ebb8463 // sub.4s	v3, v3, v27
	WORD $0x4ea16463 // smax.4s	v3, v3, v1
	WORD $0x4ea06c7a // smin.4s	v26, v3, v0
	WORD $0x6ebc8483 // sub.4s	v3, v4, v28
	WORD $0x4ea16463 // smax.4s	v3, v3, v1
	WORD $0x4ea06c7b // smin.4s	v27, v3, v0
	WORD $0x6ebe84a3 // sub.4s	v3, v5, v30
	WORD $0x4ea16463 // smax.4s	v3, v3, v1
	WORD $0x4ea06c65 // smin.4s	v5, v3, v0
	WORD $0x6ebf84c3 // sub.4s	v3, v6, v31
	WORD $0x4ea16463 // smax.4s	v3, v3, v1
	WORD $0x4ea06c63 // smin.4s	v3, v3, v0
	WORD $0x6ebd84e4 // sub.4s	v4, v7, v29
	WORD $0x4ea16484 // smax.4s	v4, v4, v1
	WORD $0x4ea06c84 // smin.4s	v4, v4, v0
	WORD $0x4ea166e6 // smax.4s	v6, v23, v1
	WORD $0x4ea06cc6 // smin.4s	v6, v6, v0
	WORD $0x4ea166c7 // smax.4s	v7, v22, v1
	WORD $0x4ea06ce7 // smin.4s	v7, v7, v0
	WORD $0x6f0205d6 // mvni.4s	v22, #0x4e
	WORD $0x4eb69c57 // mul.4s	v23, v2, v22
	WORD $0x528063e7 // mov	w7, #0x31f              ; =799
	WORD $0x4e040cff // dup.4s	v31, w7
	WORD $0x4ebf9757 // mla.4s	v23, v26, v31
	WORD $0x4ebf9c5c // mul.4s	v28, v2, v31
	WORD $0x4f3436e2 // srsra.4s	v2, v23, #0xc
	WORD $0x4f0205f7 // movi.4s	v23, #0x4f
	WORD $0x4eb7975c // mla.4s	v28, v26, v23
	WORD $0x4f342797 // srshr.4s	v23, v28, #0xc
	WORD $0x1280e367 // mov	w7, #-0x71c             ; =-1820
	WORD $0x4e040ce8 // dup.4s	v8, w7
	WORD $0x6eba86fc // sub.4s	v28, v23, v26
	WORD $0x4ea89f77 // mul.4s	v23, v27, v8
	WORD $0x12805627 // mov	w7, #-0x2b2             ; =-690
	WORD $0x4e040cfa // dup.4s	v26, w7
	WORD $0x4eba94b7 // mla.4s	v23, v5, v26
	WORD $0x4ebb84bd // add.4s	v29, v5, v27
	WORD $0x4f3436fd // srsra.4s	v29, v23, #0xc
	WORD $0x4eba9f77 // mul.4s	v23, v27, v26
	WORD $0x5280e387 // mov	w7, #0x71c              ; =1820
	WORD $0x4e040cfe // dup.4s	v30, w7
	WORD $0x4ebe94b7 // mla.4s	v23, v5, v30
	WORD $0x4f3426f7 // srshr.4s	v23, v23, #0xc
	WORD $0x6ea586e5 // sub.4s	v5, v23, v5
	WORD $0x128063c7 // mov	w7, #-0x31f             ; =-799
	WORD $0x4e040cf7 // dup.4s	v23, w7
	WORD $0x4ebb84be // add.4s	v30, v5, v27
	WORD $0x4eb79c65 // mul.4s	v5, v3, v23
	WORD $0x4eb69485 // mla.4s	v5, v4, v22
	WORD $0x4eb69c76 // mul.4s	v22, v3, v22
	WORD $0x4ebf9496 // mla.4s	v22, v4, v31
	WORD $0x4f3434a4 // srsra.4s	v4, v5, #0xc
	WORD $0x4f3436c3 // srsra.4s	v3, v22, #0xc
	WORD $0x52805647 // mov	w7, #0x2b2              ; =690
	WORD $0x4e040ce5 // dup.4s	v5, w7
	WORD $0x4ea59cc5 // mul.4s	v5, v6, v5
	WORD $0x4ea894e5 // mla.4s	v5, v7, v8
	WORD $0x6ea684ff // sub.4s	v31, v7, v6
	WORD $0x4f3434bf // srsra.4s	v31, v5, #0xc
	WORD $0x4ea89cc5 // mul.4s	v5, v6, v8
	WORD $0x4eba94e5 // mla.4s	v5, v7, v26
	WORD $0x4ea684e8 // add.4s	v8, v7, v6
	WORD $0x4f3434a8 // srsra.4s	v8, v5, #0xc
	WORD $0x4eb08705 // add.4s	v5, v24, v16
	WORD $0x4ea164a5 // smax.4s	v5, v5, v1
	WORD $0x4ea06cb6 // smin.4s	v22, v5, v0
	WORD $0x4eb18725 // add.4s	v5, v25, v17
	WORD $0x4ea164a5 // smax.4s	v5, v5, v1
	WORD $0x4ea06cb7 // smin.4s	v23, v5, v0
	WORD $0x4eb28685 // add.4s	v5, v20, v18
	WORD $0x4ea164a5 // smax.4s	v5, v5, v1
	WORD $0x4ea06cba // smin.4s	v26, v5, v0
	WORD $0x4eb386a5 // add.4s	v5, v21, v19
	WORD $0x4ea164a5 // smax.4s	v5, v5, v1
	WORD $0x4ea06cbb // smin.4s	v27, v5, v0
	WORD $0x6eb88605 // sub.4s	v5, v16, v24
	WORD $0x4ea164a5 // smax.4s	v5, v5, v1
	WORD $0x4ea06ca7 // smin.4s	v7, v5, v0
	WORD $0x6eb98625 // sub.4s	v5, v17, v25
	WORD $0x4ea164a5 // smax.4s	v5, v5, v1
	WORD $0x4ea06cb8 // smin.4s	v24, v5, v0
	WORD $0x6eb48645 // sub.4s	v5, v18, v20
	WORD $0x4ea164a5 // smax.4s	v5, v5, v1
	WORD $0x4ea06cb0 // smin.4s	v16, v5, v0
	WORD $0x6eb58665 // sub.4s	v5, v19, v21
	WORD $0x4ea164a5 // smax.4s	v5, v5, v1
	WORD $0x4ea06cb5 // smin.4s	v21, v5, v0
	WORD $0x4ea28485 // add.4s	v5, v4, v2
	WORD $0x4ea164a5 // smax.4s	v5, v5, v1
	WORD $0x4ea06ca5 // smin.4s	v5, v5, v0
	WORD $0x4ebc8466 // add.4s	v6, v3, v28
	WORD $0x4ea164c6 // smax.4s	v6, v6, v1
	WORD $0x4ea06cc6 // smin.4s	v6, v6, v0
	WORD $0x4ebd87f1 // add.4s	v17, v31, v29
	WORD $0x4ea16631 // smax.4s	v17, v17, v1
	WORD $0x4ea06e31 // smin.4s	v17, v17, v0
	WORD $0x4ebe8512 // add.4s	v18, v8, v30
	WORD $0x4ea16652 // smax.4s	v18, v18, v1
	WORD $0x4ea06e52 // smin.4s	v18, v18, v0
	WORD $0x6ea48442 // sub.4s	v2, v2, v4
	WORD $0x4ea16442 // smax.4s	v2, v2, v1
	WORD $0x4ea06c44 // smin.4s	v4, v2, v0
	WORD $0x6ea38782 // sub.4s	v2, v28, v3
	WORD $0x4ea16442 // smax.4s	v2, v2, v1
	WORD $0x4ea06c42 // smin.4s	v2, v2, v0
	WORD $0x6ebf87a3 // sub.4s	v3, v29, v31
	WORD $0x4ea16463 // smax.4s	v3, v3, v1
	WORD $0x4ea06c63 // smin.4s	v3, v3, v0
	WORD $0x6ea887d3 // sub.4s	v19, v30, v8
	WORD $0x4ea16673 // smax.4s	v19, v19, v1
	WORD $0x4ea06e73 // smin.4s	v19, v19, v0
	WORD $0x128026e7 // mov	w7, #-0x138             ; =-312
	WORD $0x4e040cf4 // dup.4s	v20, w7
	WORD $0x5280c3e7 // mov	w7, #0x61f              ; =1567
	WORD $0x4e040cf9 // dup.4s	v25, w7
	WORD $0x4eb49cfc // mul.4s	v28, v7, v20
	WORD $0x4eb9971c // mla.4s	v28, v24, v25
	WORD $0x4eb99cfd // mul.4s	v29, v7, v25
	WORD $0x52802707 // mov	w7, #0x138              ; =312
	WORD $0x4e040cfe // dup.4s	v30, w7
	WORD $0x4f343787 // srsra.4s	v7, v28, #0xc
	WORD $0x4ebe971d // mla.4s	v29, v24, v30
	WORD $0x4f3427bc // srshr.4s	v28, v29, #0xc
	WORD $0x1280c3c7 // mov	w7, #-0x61f             ; =-1567
	WORD $0x4e040cfd // dup.4s	v29, w7
	WORD $0x6eb8879c // sub.4s	v28, v28, v24
	WORD $0x4ebd9e18 // mul.4s	v24, v16, v29
	WORD $0x4eb496b8 // mla.4s	v24, v21, v20
	WORD $0x4eb49e1f // mul.4s	v31, v16, v20
	WORD $0x4eb996bf // mla.4s	v31, v21, v25
	WORD $0x4f343715 // srsra.4s	v21, v24, #0xc
	WORD $0x4f3437f0 // srsra.4s	v16, v31, #0xc
	WORD $0x4eb49c98 // mul.4s	v24, v4, v20
	WORD $0x4eb99458 // mla.4s	v24, v2, v25
	WORD $0x4eb99c9f // mul.4s	v31, v4, v25
	WORD $0x4f343704 // srsra.4s	v4, v24, #0xc
	WORD $0x4ebe945f // mla.4s	v31, v2, v30
	WORD $0x4f3427f8 // srshr.4s	v24, v31, #0xc
	WORD $0x6ea2871e // sub.4s	v30, v24, v2
	WORD $0x4ebd9c62 // mul.4s	v2, v3, v29
	WORD $0x4eb49662 // mla.4s	v2, v19, v20
	WORD $0x4eb49c74 // mul.4s	v20, v3, v20
	WORD $0x4eb99674 // mla.4s	v20, v19, v25
	WORD $0x4f343453 // srsra.4s	v19, v2, #0xc
	WORD $0x4f343683 // srsra.4s	v3, v20, #0xc
	WORD $0x4eb68742 // add.4s	v2, v26, v22
	WORD $0x4ea16442 // smax.4s	v2, v2, v1
	WORD $0x4ea06c58 // smin.4s	v24, v2, v0
	WORD $0x4eb78762 // add.4s	v2, v27, v23
	WORD $0x4ea16442 // smax.4s	v2, v2, v1
	WORD $0x6eba86d4 // sub.4s	v20, v22, v26
	WORD $0x4ea16694 // smax.4s	v20, v20, v1
	WORD $0x4ea06e99 // smin.4s	v25, v20, v0
	WORD $0x6ebb86f4 // sub.4s	v20, v23, v27
	WORD $0x4ea16694 // smax.4s	v20, v20, v1
	WORD $0x4ea06e97 // smin.4s	v23, v20, v0
	WORD $0x4ea786b4 // add.4s	v20, v21, v7
	WORD $0x4ea16694 // smax.4s	v20, v20, v1
	WORD $0x4ea06e94 // smin.4s	v20, v20, v0
	WORD $0x6ea0ba96 // neg.4s	v22, v20
	WORD $0x4ebc8614 // add.4s	v20, v16, v28
	WORD $0x4ea16694 // smax.4s	v20, v20, v1
	WORD $0x4ea06e94 // smin.4s	v20, v20, v0
	WORD $0x6eb584e7 // sub.4s	v7, v7, v21
	WORD $0x4ea164e7 // smax.4s	v7, v7, v1
	WORD $0x4ea06cf5 // smin.4s	v21, v7, v0
	WORD $0x6eb08787 // sub.4s	v7, v28, v16
	WORD $0x4ea164e7 // smax.4s	v7, v7, v1
	WORD $0x4ea06cf0 // smin.4s	v16, v7, v0
	WORD $0x4ea58627 // add.4s	v7, v17, v5
	WORD $0x4ea164e7 // smax.4s	v7, v7, v1
	WORD $0x4ea06ce7 // smin.4s	v7, v7, v0
	WORD $0x6ea0b8fa // neg.4s	v26, v7
	WORD $0x4ea68647 // add.4s	v7, v18, v6
	WORD $0x6eb184a5 // sub.4s	v5, v5, v17
	WORD $0x4ea164a5 // smax.4s	v5, v5, v1
	WORD $0x4ea06cb1 // smin.4s	v17, v5, v0
	WORD $0x6eb284c5 // sub.4s	v5, v6, v18
	WORD $0x4ea164a5 // smax.4s	v5, v5, v1
	WORD $0x4ea06ca6 // smin.4s	v6, v5, v0
	WORD $0x4ea48665 // add.4s	v5, v19, v4
	WORD $0x4ea164a5 // smax.4s	v5, v5, v1
	WORD $0x4ea06cb2 // smin.4s	v18, v5, v0
	WORD $0x4ebe8465 // add.4s	v5, v3, v30
	WORD $0x4ea164a5 // smax.4s	v5, v5, v1
	WORD $0x6eb38484 // sub.4s	v4, v4, v19
	WORD $0x4ea16484 // smax.4s	v4, v4, v1
	WORD $0x4ea06c84 // smin.4s	v4, v4, v0
	WORD $0x6ea387c3 // sub.4s	v3, v30, v3
	WORD $0x4ea16463 // smax.4s	v3, v3, v1
	WORD $0x4ea06c63 // smin.4s	v3, v3, v0
	WORD $0x4eb986f3 // add.4s	v19, v23, v25
	WORD $0x4f0506bb // movi.4s	v27, #0xb5
	WORD $0x4ebb9e73 // mul.4s	v19, v19, v27
	WORD $0x4f382673 // srshr.4s	v19, v19, #0x8
	WORD $0x6ea0ba73 // neg.4s	v19, v19
	WORD $0x6eb78737 // sub.4s	v23, v25, v23
	WORD $0x3d800018 // str	q24, [x0]
	WORD $0x3ca1681a // str	q26, [x0, x1]
	WORD $0x4eb58618 // add.4s	v24, v16, v21
	WORD $0x4ebb9f18 // mul.4s	v24, v24, v27
	WORD $0x4f382718 // srshr.4s	v24, v24, #0x8
	WORD $0x4ea48479 // add.4s	v25, v3, v4
	WORD $0x4ebb9f39 // mul.4s	v25, v25, v27
	WORD $0x4f382739 // srshr.4s	v25, v25, #0x8
	WORD $0x6ea0bb39 // neg.4s	v25, v25
	WORD $0x3cab6812 // str	q18, [x0, x11]
	WORD $0x3ca66816 // str	q22, [x0, x6]
	WORD $0x3cad6818 // str	q24, [x0, x13]
	WORD $0x3ca36819 // str	q25, [x0, x3]
	WORD $0x4ebb9ef2 // mul.4s	v18, v23, v27
	WORD $0x4f382652 // srshr.4s	v18, v18, #0x8
	WORD $0x6eb086b0 // sub.4s	v16, v21, v16
	WORD $0x4ebb9e10 // mul.4s	v16, v16, v27
	WORD $0x4eb184d5 // add.4s	v21, v6, v17
	WORD $0x4ebb9eb5 // mul.4s	v21, v21, v27
	WORD $0x4f3826b5 // srshr.4s	v21, v21, #0x8
	WORD $0x6ea68626 // sub.4s	v6, v17, v6
	WORD $0x3cb06815 // str	q21, [x0, x16]
	WORD $0x3cb16813 // str	q19, [x0, x17]
	WORD $0x4ebb9cc6 // mul.4s	v6, v6, v27
	WORD $0x4f3824c6 // srshr.4s	v6, v6, #0x8
	WORD $0x6ea0b8c6 // neg.4s	v6, v6
	WORD $0x3caf6812 // str	q18, [x0, x15]
	WORD $0x6ea38483 // sub.4s	v3, v4, v3
	WORD $0x3cae6806 // str	q6, [x0, x14]
	WORD $0x4ebb9c63 // mul.4s	v3, v3, v27
	WORD $0x4f382463 // srshr.4s	v3, v3, #0x8
	WORD $0x3ca26803 // str	q3, [x0, x2]
	WORD $0x4f382603 // srshr.4s	v3, v16, #0x8
	WORD $0x6ea0b863 // neg.4s	v3, v3
	WORD $0x3cac6803 // str	q3, [x0, x12]
	WORD $0x3ca46814 // str	q20, [x0, x4]
	WORD $0x4ea06ca3 // smin.4s	v3, v5, v0
	WORD $0x6ea0b863 // neg.4s	v3, v3
	WORD $0x3caa6803 // str	q3, [x0, x10]
	WORD $0x4ea164e1 // smax.4s	v1, v7, v1
	WORD $0x4ea06c21 // smin.4s	v1, v1, v0
	WORD $0x3ca56801 // str	q1, [x0, x5]
	WORD $0x4ea06c40 // smin.4s	v0, v2, v0
	WORD $0x6ea0b800 // neg.4s	v0, v0
	WORD $0x3ca86920 // str	q0, [x9, x8]
	WORD $0x6cc123e9 // ldp	d9, d8, [sp], #0x10
	WORD $0xd65f03c0 // ret
