// NEON-accelerated inverse DCT32 four-column kernel.
//
// Four adjacent columns of the row-major scratch buffer ride the four int32
// lanes of each .4s register, following dav1d's high-bitdepth inverse
// transform shape (dav1d src/arm/64/itx16.S: inv_dct_4s_x16_neon and the
// mul_mla/mul_mls + srshr + smax/smin idiom): every butterfly multiply is a
// plain mul/mla/mls .4s, every rounding shift is srshr .4s and every stage
// clamp is smax+smin against the stage bounds. Working in int32 lanes without
// widening is exact here because the column-pass inputs are pre-clamped to the
// stage range (|v| <= 2^19 across all supported bit depths) and every cosine
// pair in the (cospi-4096)-rewritten butterflies keeps the multiply
// accumulator below 2^31 (the adapter enforces the clamp-bound precondition
// and falls back otherwise). The fixed-point products, rounding shifts and
// clamps are bit-for-bit identical to running the pure-Go inverseDCT32 on
// each column, asserted exhaustively by the column dispatch differential
// tests.
//
// The body is generated by transliterating the pure-Go butterfly to NEON
// intrinsics, compiling with the system C compiler at -O2 and transcribing
// the disassembly verbatim as WORD-encoded opcodes, because Go's arm64
// assembler does not expose the signed-rounding-shift mnemonics. The kernel
// is pure straight-line leaf code (no branches, no calls); it manages its own
// 512-byte caller/callee-saved spill frame below the (empty) Go frame, within
// the nosplit stack budget, and restores every callee-saved register before
// returning.
//
// SPDX-License-Identifier: BSD-2-Clause
//
// See LICENSE for the BSD-2-Clause grant and NOTICE for the AOM attribution.

//go:build arm64 && !purego

#include "textflag.h"

// func inverseDCT32Col4NEON(base *int32, rowStrideBytes, min, max int64)
// Transforms four adjacent columns (col..col+3) of the row-major scratch
// buffer in place. base points at scratch[col]; rows are rowStrideBytes
// apart. The four columns occupy int32 lanes 0-3. Bit-for-bit identical to
// inverseDCT32 run on each column.
TEXT ·inverseDCT32Col4NEON(SB), NOSPLIT, $0-32
	MOVD base+0(FP), R0
	MOVD rowStrideBytes+8(FP), R1
	MOVD min+16(FP), R2
	MOVD max+24(FP), R3
	WORD $0x6db63bef // stp	d15, d14, [sp, #-0xa0]!
	WORD $0x6d0133ed // stp	d13, d12, [sp, #0x10]
	WORD $0x6d022beb // stp	d11, d10, [sp, #0x20]
	WORD $0x6d0323e9 // stp	d9, d8, [sp, #0x30]
	WORD $0xa9046ffc // stp	x28, x27, [sp, #0x40]
	WORD $0xa90567fa // stp	x26, x25, [sp, #0x50]
	WORD $0xa9065ff8 // stp	x24, x23, [sp, #0x60]
	WORD $0xa90757f6 // stp	x22, x21, [sp, #0x70]
	WORD $0xa9084ff4 // stp	x20, x19, [sp, #0x80]
	WORD $0xa9097bfd // stp	x29, x30, [sp, #0x90]
	WORD $0xd10583ff // sub	sp, sp, #0x160
	WORD $0x4e040c54 // dup.4s	v20, w2
	WORD $0x4e040c66 // dup.4s	v6, w3
	WORD $0x3dc00002 // ldr	q2, [x0]
	WORD $0xd37cec2f // lsl	x15, x1, #4
	WORD $0x3cef6803 // ldr	q3, [x0, x15]
	WORD $0x4ea28464 // add.4s	v4, v3, v2
	WORD $0x4f0506a0 // movi.4s	v0, #0xb5
	WORD $0x4ea09c84 // mul.4s	v4, v4, v0
	WORD $0x4f382485 // srshr.4s	v5, v4, #0x8
	WORD $0x6ea38442 // sub.4s	v2, v2, v3
	WORD $0x4ea09c43 // mul.4s	v3, v2, v0
	WORD $0x4f382460 // srshr.4s	v0, v3, #0x8
	WORD $0x5280c3e8 // mov	w8, #0x61f              ; =1567
	WORD $0x4e040d0e // dup.4s	v14, w8
	WORD $0x52802708 // mov	w8, #0x138              ; =312
	WORD $0x4e040d01 // dup.4s	v1, w8
	WORD $0x3d8047e1 // str	q1, [sp, #0x110]
	WORD $0xd37df02e // lsl	x14, x1, #3
	WORD $0x3cee6807 // ldr	q7, [x0, x14]
	WORD $0x52800308 // mov	w8, #0x18               ; =24
	WORD $0x9b087c28 // mul	x8, x1, x8
	WORD $0xf900a7e8 // str	x8, [sp, #0x148]
	WORD $0x3ce86810 // ldr	q16, [x0, x8]
	WORD $0x4eae9ce2 // mul.4s	v2, v7, v14
	WORD $0x4ea19602 // mla.4s	v2, v16, v1
	WORD $0x4f342442 // srshr.4s	v2, v2, #0xc
	WORD $0x128026e8 // mov	w8, #-0x138             ; =-312
	WORD $0x4e040d01 // dup.4s	v1, w8
	WORD $0x3d8057e1 // str	q1, [sp, #0x150]
	WORD $0x6eb0845e // sub.4s	v30, v2, v16
	WORD $0x4ea19cf1 // mul.4s	v17, v7, v1
	WORD $0x4eae9611 // mla.4s	v17, v16, v14
	WORD $0x4f343627 // srsra.4s	v7, v17, #0xc
	WORD $0x6ea784a1 // sub.4s	v1, v5, v7
	WORD $0x4f383487 // srsra.4s	v7, v4, #0x8
	WORD $0x6ebe8408 // sub.4s	v8, v0, v30
	WORD $0x4f38347e // srsra.4s	v30, v3, #0x8
	WORD $0x528063e8 // mov	w8, #0x31f              ; =799
	WORD $0x4e040d00 // dup.4s	v0, w8
	WORD $0x5280d4e8 // mov	w8, #0x6a7              ; =1703
	WORD $0x4e040d17 // dup.4s	v23, w8
	WORD $0x12808e28 // mov	w8, #-0x472             ; =-1138
	WORD $0x4e040d18 // dup.4s	v24, w8
	WORD $0x52800188 // mov	w8, #0xc                ; =12
	WORD $0x9b087c28 // mul	x8, x1, x8
	WORD $0xf9009fe8 // str	x8, [sp, #0x138]
	WORD $0x3ce86804 // ldr	q4, [x0, x8]
	WORD $0x4eb89c93 // mul.4s	v19, v4, v24
	WORD $0x52800288 // mov	w8, #0x14               ; =20
	WORD $0x9b087c28 // mul	x8, x1, x8
	WORD $0xf900a3e8 // str	x8, [sp, #0x140]
	WORD $0x3ce86805 // ldr	q5, [x0, x8]
	WORD $0x4eb794b3 // mla.4s	v19, v5, v23
	WORD $0x52808e48 // mov	w8, #0x472              ; =1138
	WORD $0x4e040d03 // dup.4s	v3, w8
	WORD $0x4eb79c96 // mul.4s	v22, v4, v23
	WORD $0x4ea394b6 // mla.4s	v22, v5, v3
	WORD $0x5280c5e8 // mov	w8, #0x62f              ; =1583
	WORD $0x4e040d04 // dup.4s	v4, w8
	WORD $0x1280a248 // mov	w8, #-0x513             ; =-1299
	WORD $0x4e040d05 // dup.4s	v5, w8
	WORD $0x528001c8 // mov	w8, #0xe                ; =14
	WORD $0x9b087c28 // mul	x8, x1, x8
	WORD $0xf90097e8 // str	x8, [sp, #0x128]
	WORD $0x3ce86810 // ldr	q16, [x0, x8]
	WORD $0x4ea59e02 // mul.4s	v2, v16, v5
	WORD $0x52800248 // mov	w8, #0x12               ; =18
	WORD $0x9b087c28 // mul	x8, x1, x8
	WORD $0xf9009be8 // str	x8, [sp, #0x130]
	WORD $0x3ce86805 // ldr	q5, [x0, x8]
	WORD $0x4ea494a2 // mla.4s	v2, v5, v4
	WORD $0x3d8043e2 // str	q2, [sp, #0x100]
	WORD $0x5280a268 // mov	w8, #0x513              ; =1299
	WORD $0x4e040d11 // dup.4s	v17, w8
	WORD $0x4ea49e02 // mul.4s	v2, v16, v4
	WORD $0x4eb194a2 // mla.4s	v2, v5, v17
	WORD $0x3d803fe2 // str	q2, [sp, #0xf0]
	WORD $0x52807c68 // mov	w8, #0x3e3              ; =995
	WORD $0x4e040d05 // dup.4s	v5, w8
	WORD $0xd37ef423 // lsl	x3, x1, #2
	WORD $0x8b010062 // add	x2, x3, x1
	WORD $0x3ce2681b // ldr	q27, [x0, x2]
	WORD $0x4ea59f64 // mul.4s	v4, v27, v5
	WORD $0x4f030775 // movi.4s	v21, #0x7b
	WORD $0x128048c8 // mov	w8, #-0x247             ; =-583
	WORD $0x4e040d11 // dup.4s	v17, w8
	WORD $0x52809888 // mov	w8, #0x4c4              ; =1220
	WORD $0x4e040d1a // dup.4s	v26, w8
	WORD $0x52800368 // mov	w8, #0x1b               ; =27
	WORD $0x9b087c28 // mul	x8, x1, x8
	WORD $0xf90093e8 // str	x8, [sp, #0x120]
	WORD $0x3ce86810 // ldr	q16, [x0, x8]
	WORD $0x4eb59604 // mla.4s	v4, v16, v21
	WORD $0x1280cd88 // mov	w8, #-0x66d             ; =-1645
	WORD $0x4e040d15 // dup.4s	v21, w8
	WORD $0x528001a8 // mov	w8, #0xd                ; =13
	WORD $0x9b087c24 // mul	x4, x1, x8
	WORD $0x3ce4681c // ldr	q28, [x0, x4]
	WORD $0x52800268 // mov	w8, #0x13               ; =19
	WORD $0x9b087c31 // mul	x17, x1, x8
	WORD $0x3cf1681d // ldr	q29, [x0, x17]
	WORD $0x4eba9f82 // mul.4s	v2, v28, v26
	WORD $0x4eb597a2 // mla.4s	v2, v29, v21
	WORD $0x3d8017e2 // str	q2, [sp, #0x50]
	WORD $0x6f010569 // mvni.4s	v9, #0x2b
	WORD $0x12804b08 // mov	w8, #-0x259             ; =-601
	WORD $0x4e040d19 // dup.4s	v25, w8
	WORD $0xd37ff833 // lsl	x19, x1, #1
	WORD $0x8b010267 // add	x7, x19, x1
	WORD $0x3ce76815 // ldr	q21, [x0, x7]
	WORD $0x4eb99eaa // mul.4s	v10, v21, v25
	WORD $0x52804b28 // mov	w8, #0x259              ; =601
	WORD $0x4e040d0c // dup.4s	v12, w8
	WORD $0x528003a8 // mov	w8, #0x1d               ; =29
	WORD $0x9b087c30 // mul	x16, x1, x8
	WORD $0x3cf06819 // ldr	q25, [x0, x16]
	WORD $0x4ea9972a // mla.4s	v10, v25, v9
	WORD $0x4ea99ea9 // mul.4s	v9, v21, v9
	WORD $0x4eac9729 // mla.4s	v9, v25, v12
	WORD $0x5280f8c8 // mov	w8, #0x7c6              ; =1990
	WORD $0x4e040d0c // dup.4s	v12, w8
	WORD $0x4f343559 // srsra.4s	v25, v10, #0xc
	WORD $0x52800168 // mov	w8, #0xb                ; =11
	WORD $0x9b087c26 // mul	x6, x1, x8
	WORD $0x3ce6680f // ldr	q15, [x0, x6]
	WORD $0x4eac9dec // mul.4s	v12, v15, v12
	WORD $0x4f343535 // srsra.4s	v21, v9, #0xc
	WORD $0x5280cda8 // mov	w8, #0x66d              ; =1645
	WORD $0x4e040d09 // dup.4s	v9, w8
	WORD $0x4ea99f8d // mul.4s	v13, v28, v9
	WORD $0x528002a8 // mov	w8, #0x15               ; =21
	WORD $0x9b087c25 // mul	x5, x1, x8
	WORD $0x3ce5681c // ldr	q28, [x0, x5]
	WORD $0x4eb1978c // mla.4s	v12, v28, v17
	WORD $0x4eba97ad // mla.4s	v13, v29, v26
	WORD $0x1280f8a8 // mov	w8, #-0x7c6             ; =-1990
	WORD $0x4e040d1a // dup.4s	v26, w8
	WORD $0x4eb19df1 // mul.4s	v17, v15, v17
	WORD $0x4eba9791 // mla.4s	v17, v28, v26
	WORD $0x3ce36809 // ldr	q9, [x0, x3]
	WORD $0x3d8007e0 // str	q0, [sp, #0x10]
	WORD $0x4ea09d3a // mul.4s	v26, v9, v0
	WORD $0x4f342484 // srshr.4s	v4, v4, #0xc
	WORD $0x6eb08492 // sub.4s	v18, v4, v16
	WORD $0x4f342584 // srshr.4s	v4, v12, #0xc
	WORD $0x6eaf8484 // sub.4s	v4, v4, v15
	WORD $0x4ebc849d // add.4s	v29, v4, v28
	WORD $0xad01f7f2 // stp	q18, q29, [sp, #0x30]
	WORD $0x4eaf878c // add.4s	v12, v28, v15
	WORD $0x4f352444 // srshr.4s	v4, v2, #0xb
	WORD $0x4f34362c // srsra.4s	v12, v17, #0xc
	WORD $0x6f030751 // mvni.4s	v17, #0x7a
	WORD $0x4eb19f71 // mul.4s	v17, v27, v17
	WORD $0x4ea59611 // mla.4s	v17, v16, v5
	WORD $0x4f34363b // srsra.4s	v27, v17, #0xc
	WORD $0x6ebd8645 // sub.4s	v5, v18, v29
	WORD $0x4eb464a5 // smax.4s	v5, v5, v20
	WORD $0x4ea66ca5 // smin.4s	v5, v5, v6
	WORD $0x6eac8770 // sub.4s	v16, v27, v12
	WORD $0x4eb46610 // smax.4s	v16, v16, v20
	WORD $0x4ea66e10 // smin.4s	v16, v16, v6
	WORD $0x4eb79caf // mul.4s	v15, v5, v23
	WORD $0x4ea3960f // mla.4s	v15, v16, v3
	WORD $0x4f3525a3 // srshr.4s	v3, v13, #0xb
	WORD $0x6ea48724 // sub.4s	v4, v25, v4
	WORD $0x4eb46484 // smax.4s	v4, v4, v20
	WORD $0x4ea66c91 // smin.4s	v17, v4, v6
	WORD $0x6ea386a3 // sub.4s	v3, v21, v3
	WORD $0x4eb46463 // smax.4s	v3, v3, v20
	WORD $0x4ea66c63 // smin.4s	v3, v3, v6
	WORD $0x4eb89cab // mul.4s	v11, v5, v24
	WORD $0x4eb7960b // mla.4s	v11, v16, v23
	WORD $0x1280d4c8 // mov	w8, #-0x6a7             ; =-1703
	WORD $0x4e040d05 // dup.4s	v5, w8
	WORD $0x4ea59e2a // mul.4s	v10, v17, v5
	WORD $0x4eb8946a // mla.4s	v10, v3, v24
	WORD $0x4eb89e22 // mul.4s	v2, v17, v24
	WORD $0x4f0205e4 // movi.4s	v4, #0x4f
	WORD $0x4eb79462 // mla.4s	v2, v3, v23
	WORD $0x3d800be2 // str	q2, [sp, #0x20]
	WORD $0x52800388 // mov	w8, #0x1c               ; =28
	WORD $0x9b087c34 // mul	x20, x1, x8
	WORD $0x3cf46803 // ldr	q3, [x0, x20]
	WORD $0x4ea4947a // mla.4s	v26, v3, v4
	WORD $0x4f342751 // srshr.4s	v17, v26, #0xc
	WORD $0x6ea38631 // sub.4s	v17, v17, v3
	WORD $0x6f0205c2 // mvni.4s	v2, #0x4e
	WORD $0x4ea29d38 // mul.4s	v24, v9, v2
	WORD $0x4ea09478 // mla.4s	v24, v3, v0
	WORD $0x4eb464e3 // smax.4s	v3, v7, v20
	WORD $0x4ea66c62 // smin.4s	v2, v3, v6
	WORD $0x4eb467c3 // smax.4s	v3, v30, v20
	WORD $0x4ea66c63 // smin.4s	v3, v3, v6
	WORD $0x4eb46507 // smax.4s	v7, v8, v20
	WORD $0x4ea66ce7 // smin.4s	v7, v7, v6
	WORD $0x4eb4643a // smax.4s	v26, v1, v20
	WORD $0x4ea66f5a // smin.4s	v26, v26, v6
	WORD $0x4f343709 // srsra.4s	v9, v24, #0xc
	WORD $0x4f352678 // srshr.4s	v24, v19, #0xb
	WORD $0x6eb88638 // sub.4s	v24, v17, v24
	WORD $0x4f353671 // srsra.4s	v17, v19, #0xb
	WORD $0x4f3526d3 // srshr.4s	v19, v22, #0xb
	WORD $0x4eb46631 // smax.4s	v17, v17, v20
	WORD $0x4ea66e31 // smin.4s	v17, v17, v6
	WORD $0x4eb46718 // smax.4s	v24, v24, v20
	WORD $0x4ea66f18 // smin.4s	v24, v24, v6
	WORD $0x6eb38533 // sub.4s	v19, v9, v19
	WORD $0x4f3536c9 // srsra.4s	v9, v22, #0xb
	WORD $0x4eb46536 // smax.4s	v22, v9, v20
	WORD $0x4ea66ede // smin.4s	v30, v22, v6
	WORD $0x4eb46673 // smax.4s	v19, v19, v20
	WORD $0x4ea66e73 // smin.4s	v19, v19, v6
	WORD $0x6eb88676 // sub.4s	v22, v19, v24
	WORD $0x4f0506a0 // movi.4s	v0, #0xb5
	WORD $0x4ea09ec9 // mul.4s	v9, v22, v0
	WORD $0x4eb88673 // add.4s	v19, v19, v24
	WORD $0x4ea09e73 // mul.4s	v19, v19, v0
	WORD $0x4f0506b0 // movi.4s	v16, #0xb5
	WORD $0x4f382676 // srshr.4s	v22, v19, #0x8
	WORD $0x6eb6847f // sub.4s	v31, v3, v22
	WORD $0x4ea31c78 // mov.16b	v24, v3
	WORD $0x4f383678 // srsra.4s	v24, v19, #0x8
	WORD $0x4f382523 // srshr.4s	v3, v9, #0x8
	WORD $0x6ea384e8 // sub.4s	v8, v7, v3
	WORD $0x4f383527 // srsra.4s	v7, v9, #0x8
	WORD $0x4eba8632 // add.4s	v18, v17, v26
	WORD $0x6eb18749 // sub.4s	v9, v26, v17
	WORD $0x4ea287da // add.4s	v26, v30, v2
	WORD $0x6ebe845e // sub.4s	v30, v2, v30
	WORD $0x3cf36813 // ldr	q19, [x0, x19]
	WORD $0x528003c8 // mov	w8, #0x1e               ; =30
	WORD $0x9b087c35 // mul	x21, x1, x8
	WORD $0x52803228 // mov	w8, #0x191              ; =401
	WORD $0x3cf56802 // ldr	q2, [x0, x21]
	WORD $0x4e040d11 // dup.4s	v17, w8
	WORD $0x4eb19e60 // mul.4s	v0, v19, v17
	WORD $0x4f000697 // movi.4s	v23, #0x14
	WORD $0x4eb79440 // mla.4s	v0, v2, v23
	WORD $0x6f000677 // mvni.4s	v23, #0x13
	WORD $0x4eb79e77 // mul.4s	v23, v19, v23
	WORD $0x4eb19457 // mla.4s	v23, v2, v17
	WORD $0x4f342400 // srshr.4s	v0, v0, #0xc
	WORD $0x6ea28405 // sub.4s	v5, v0, v2
	WORD $0x52800148 // mov	w8, #0xa                ; =10
	WORD $0x9b087c38 // mul	x24, x1, x8
	WORD $0x528002c8 // mov	w8, #0x16               ; =22
	WORD $0x9b087c36 // mul	x22, x1, x8
	WORD $0x5280f168 // mov	w8, #0x78b              ; =1931
	WORD $0x3cf86801 // ldr	q1, [x0, x24]
	WORD $0x3cf66811 // ldr	q17, [x0, x22]
	WORD $0x4e040d02 // dup.4s	v2, w8
	WORD $0x52803c88 // mov	w8, #0x1e4              ; =484
	WORD $0x4ea29c20 // mul.4s	v0, v1, v2
	WORD $0x4e040d1d // dup.4s	v29, w8
	WORD $0x4ebd9620 // mla.4s	v0, v17, v29
	WORD $0x12803c68 // mov	w8, #-0x1e4             ; =-484
	WORD $0x4e040d1d // dup.4s	v29, w8
	WORD $0x4ebd9c3d // mul.4s	v29, v1, v29
	WORD $0x4ea2963d // mla.4s	v29, v17, v2
	WORD $0x4f342400 // srshr.4s	v0, v0, #0xc
	WORD $0x6eb18403 // sub.4s	v3, v0, v17
	WORD $0x528000c8 // mov	w8, #0x6                ; =6
	WORD $0x9b087c39 // mul	x25, x1, x8
	WORD $0x52800348 // mov	w8, #0x1a               ; =26
	WORD $0x9b087c37 // mul	x23, x1, x8
	WORD $0x3cf96802 // ldr	q2, [x0, x25]
	WORD $0x12809488 // mov	w8, #-0x4a5             ; =-1189
	WORD $0x4e040d11 // dup.4s	v17, w8
	WORD $0x4eb19c51 // mul.4s	v17, v2, v17
	WORD $0x3cf76800 // ldr	q0, [x0, x23]
	WORD $0x6f0505e4 // mvni.4s	v4, #0xaf
	WORD $0x4ea49411 // mla.4s	v17, v0, v4
	WORD $0x528094a8 // mov	w8, #0x4a5              ; =1189
	WORD $0x4ea49c44 // mul.4s	v4, v2, v4
	WORD $0x4e040d1c // dup.4s	v28, w8
	WORD $0x4ebc9404 // mla.4s	v4, v0, v28
	WORD $0x4f343620 // srsra.4s	v0, v17, #0xc
	WORD $0x4f343482 // srsra.4s	v2, v4, #0xc
	WORD $0x4f3437a1 // srsra.4s	v1, v29, #0xc
	WORD $0x4f3436f3 // srsra.4s	v19, v23, #0xc
	WORD $0xad47c7f6 // ldp	q22, q17, [sp, #0xf0]
	WORD $0x4f352624 // srshr.4s	v4, v17, #0xb
	WORD $0x6ea484a4 // sub.4s	v4, v5, v4
	WORD $0x4f353625 // srsra.4s	v5, v17, #0xb
	WORD $0x6ea38411 // sub.4s	v17, v0, v3
	WORD $0x4ea38400 // add.4s	v0, v0, v3
	WORD $0x4ea28423 // add.4s	v3, v1, v2
	WORD $0x6ea18441 // sub.4s	v1, v2, v1
	WORD $0x4f3526c2 // srshr.4s	v2, v22, #0xb
	WORD $0x6ea28662 // sub.4s	v2, v19, v2
	WORD $0x4f3536d3 // srsra.4s	v19, v22, #0xb
	WORD $0x4eb46484 // smax.4s	v4, v4, v20
	WORD $0x4ea66c84 // smin.4s	v4, v4, v6
	WORD $0x4eb46442 // smax.4s	v2, v2, v20
	WORD $0x4ea66c42 // smin.4s	v2, v2, v6
	WORD $0x3dc047f6 // ldr	q22, [sp, #0x110]
	WORD $0x4eb69c97 // mul.4s	v23, v4, v22
	WORD $0x4eae9457 // mla.4s	v23, v2, v14
	WORD $0x4f3426f7 // srshr.4s	v23, v23, #0xc
	WORD $0x6ea486f7 // sub.4s	v23, v23, v4
	WORD $0x4eae9c84 // mul.4s	v4, v4, v14
	WORD $0x3dc057fc // ldr	q28, [sp, #0x150]
	WORD $0x4ebc9444 // mla.4s	v4, v2, v28
	WORD $0x4f343482 // srsra.4s	v2, v4, #0xc
	WORD $0x4eb46624 // smax.4s	v4, v17, v20
	WORD $0x4ea66c84 // smin.4s	v4, v4, v6
	WORD $0x4eb46421 // smax.4s	v1, v1, v20
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x1280c3c8 // mov	w8, #-0x61f             ; =-1567
	WORD $0x4e040d11 // dup.4s	v17, w8
	WORD $0x4eb19c9c // mul.4s	v28, v4, v17
	WORD $0x4eb6943c // mla.4s	v28, v1, v22
	WORD $0x4f34279c // srshr.4s	v28, v28, #0xc
	WORD $0x6ea1879c // sub.4s	v28, v28, v1
	WORD $0x4eb69c9d // mul.4s	v29, v4, v22
	WORD $0x4eae943d // mla.4s	v29, v1, v14
	WORD $0x4f3427a1 // srshr.4s	v1, v29, #0xc
	WORD $0x6ea48421 // sub.4s	v1, v1, v4
	WORD $0x4eb78784 // add.4s	v4, v28, v23
	WORD $0x6ebc86f7 // sub.4s	v23, v23, v28
	WORD $0x4eb464a5 // smax.4s	v5, v5, v20
	WORD $0x4ea66ca5 // smin.4s	v5, v5, v6
	WORD $0x4eb46400 // smax.4s	v0, v0, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x4ea5841c // add.4s	v28, v0, v5
	WORD $0x6ea084a0 // sub.4s	v0, v5, v0
	WORD $0x6ea18445 // sub.4s	v5, v2, v1
	WORD $0x4ea28422 // add.4s	v2, v1, v2
	WORD $0x4eb46461 // smax.4s	v1, v3, v20
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x4eb46663 // smax.4s	v3, v19, v20
	WORD $0x4ea66c63 // smin.4s	v3, v3, v6
	WORD $0x6ea18473 // sub.4s	v19, v3, v1
	WORD $0x4ea18463 // add.4s	v3, v3, v1
	WORD $0x4eb466e1 // smax.4s	v1, v23, v20
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x4eb464a5 // smax.4s	v5, v5, v20
	WORD $0x4ea66ca5 // smin.4s	v5, v5, v6
	WORD $0x6ea184b7 // sub.4s	v23, v5, v1
	WORD $0x4ea184a1 // add.4s	v1, v5, v1
	WORD $0x4eb46400 // smax.4s	v0, v0, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x4eb46665 // smax.4s	v5, v19, v20
	WORD $0x4ea66ca5 // smin.4s	v5, v5, v6
	WORD $0x6ea084bd // sub.4s	v29, v5, v0
	WORD $0x4ea084a0 // add.4s	v0, v5, v0
	WORD $0x4eb464e5 // smax.4s	v5, v7, v20
	WORD $0x4ea66ca5 // smin.4s	v5, v5, v6
	WORD $0x4eb09c21 // mul.4s	v1, v1, v16
	WORD $0x4f382427 // srshr.4s	v7, v1, #0x8
	WORD $0x6ea784a7 // sub.4s	v7, v5, v7
	WORD $0x4f383425 // srsra.4s	v5, v1, #0x8
	WORD $0x4eb46641 // smax.4s	v1, v18, v20
	WORD $0x4ea66c33 // smin.4s	v19, v1, v6
	WORD $0x4eb09c00 // mul.4s	v0, v0, v16
	WORD $0x4f382401 // srshr.4s	v1, v0, #0x8
	WORD $0x6ea18661 // sub.4s	v1, v19, v1
	WORD $0xad069fe1 // stp	q1, q7, [sp, #0xd0]
	WORD $0x4f383413 // srsra.4s	v19, v0, #0x8
	WORD $0xad0797f3 // stp	q19, q5, [sp, #0xf0]
	WORD $0x4eb46520 // smax.4s	v0, v9, v20
	WORD $0x4ea66c13 // smin.4s	v19, v0, v6
	WORD $0x4eb09fa0 // mul.4s	v0, v29, v16
	WORD $0x4f382405 // srshr.4s	v5, v0, #0x8
	WORD $0x6ea58667 // sub.4s	v7, v19, v5
	WORD $0x4f383413 // srsra.4s	v19, v0, #0x8
	WORD $0x4eb46500 // smax.4s	v0, v8, v20
	WORD $0x4ea66c08 // smin.4s	v8, v0, v6
	WORD $0x4eb09ee0 // mul.4s	v0, v23, v16
	WORD $0x4f382405 // srshr.4s	v5, v0, #0x8
	WORD $0x6ea58501 // sub.4s	v1, v8, v5
	WORD $0xad049fe1 // stp	q1, q7, [sp, #0x90]
	WORD $0x4f383408 // srsra.4s	v8, v0, #0x8
	WORD $0x4eb467c0 // smax.4s	v0, v30, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x4eb46785 // smax.4s	v5, v28, v20
	WORD $0x4ea66ca5 // smin.4s	v5, v5, v6
	WORD $0x4ea084be // add.4s	v30, v5, v0
	WORD $0x6ea58401 // sub.4s	v1, v0, v5
	WORD $0x4eb467e0 // smax.4s	v0, v31, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x4eb46484 // smax.4s	v4, v4, v20
	WORD $0x4ea66c84 // smin.4s	v4, v4, v6
	WORD $0x4ea08489 // add.4s	v9, v4, v0
	WORD $0x6ea48400 // sub.4s	v0, v0, v4
	WORD $0xad0307e0 // stp	q0, q1, [sp, #0x60]
	WORD $0x4eb46700 // smax.4s	v0, v24, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x4eb46442 // smax.4s	v2, v2, v20
	WORD $0x4ea66c42 // smin.4s	v2, v2, v6
	WORD $0x4ea08445 // add.4s	v5, v2, v0
	WORD $0x6ea28400 // sub.4s	v0, v0, v2
	WORD $0x3d8023e0 // str	q0, [sp, #0x80]
	WORD $0xd37be83a // lsl	x26, x1, #5
	WORD $0xcb01001b // sub	x27, x0, x1
	WORD $0x4eb46740 // smax.4s	v0, v26, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x4eb46462 // smax.4s	v2, v3, v20
	WORD $0x4ea66c43 // smin.4s	v3, v2, v6
	WORD $0x3ce16802 // ldr	q2, [x0, x1]
	WORD $0x3cfa6b64 // ldr	q4, [x27, x26]
	WORD $0x4ea08461 // add.4s	v1, v3, v0
	WORD $0xad0597e1 // stp	q1, q5, [sp, #0xb0]
	WORD $0x6ea3841a // sub.4s	v26, v0, v3
	WORD $0x4f060520 // movi.4s	v0, #0xc9
	WORD $0x4ea09c43 // mul.4s	v3, v2, v0
	WORD $0x4f0004a5 // movi.4s	v5, #0x5
	WORD $0x4ea59483 // mla.4s	v3, v4, v5
	WORD $0x6f000485 // mvni.4s	v5, #0x4
	WORD $0x4ea59c45 // mul.4s	v5, v2, v5
	WORD $0x4ea09485 // mla.4s	v5, v4, v0
	WORD $0x4f342460 // srshr.4s	v0, v3, #0xc
	WORD $0x6ea48401 // sub.4s	v1, v0, v4
	WORD $0x8b0101cd // add	x13, x14, x1
	WORD $0x528002e8 // mov	w8, #0x17               ; =23
	WORD $0x9b087c3c // mul	x28, x1, x8
	WORD $0x5280dae8 // mov	w8, #0x6d7              ; =1751
	WORD $0x3ced6803 // ldr	q3, [x0, x13]
	WORD $0x3cfc6804 // ldr	q4, [x0, x28]
	WORD $0x52803129 // mov	w9, #0x189              ; =393
	WORD $0x4e040d07 // dup.4s	v7, w8
	WORD $0x4ea79c70 // mul.4s	v16, v3, v7
	WORD $0x4e040d37 // dup.4s	v23, w9
	WORD $0x4eb79490 // mla.4s	v16, v4, v23
	WORD $0x12803108 // mov	w8, #-0x189             ; =-393
	WORD $0x4e040d17 // dup.4s	v23, w8
	WORD $0x4eb79c77 // mul.4s	v23, v3, v23
	WORD $0x4ea79497 // mla.4s	v23, v4, v7
	WORD $0x4f342607 // srshr.4s	v7, v16, #0xc
	WORD $0x6ea484e4 // sub.4s	v4, v7, v4
	WORD $0xcb0101ca // sub	x10, x14, x1
	WORD $0x52800329 // mov	w9, #0x19               ; =25
	WORD $0x9b097c3e // mul	x30, x1, x9
	WORD $0x1280ac69 // mov	w9, #-0x564             ; =-1380
	WORD $0x3cea6807 // ldr	q7, [x0, x10]
	WORD $0x3cfe6810 // ldr	q16, [x0, x30]
	WORD $0x4e040d3c // dup.4s	v28, w9
	WORD $0x4ebc9cfc // mul.4s	v28, v7, v28
	WORD $0x6f0705dd // mvni.4s	v29, #0xee
	WORD $0x4ebd961c // mla.4s	v28, v16, v29
	WORD $0x5280ac89 // mov	w9, #0x564              ; =1380
	WORD $0x4e040d20 // dup.4s	v0, w9
	WORD $0x4ebd9cfd // mul.4s	v29, v7, v29
	WORD $0x4ea0961d // mla.4s	v29, v16, v0
	WORD $0x4f343790 // srsra.4s	v16, v28, #0xc
	WORD $0x4f3437a7 // srsra.4s	v7, v29, #0xc
	WORD $0x4f3436e3 // srsra.4s	v3, v23, #0xc
	WORD $0xcb0101eb // sub	x11, x15, x1
	WORD $0x8b0101ec // add	x12, x15, x1
	WORD $0x12808488 // mov	w8, #-0x425             ; =-1061
	WORD $0x5280a829 // mov	w9, #0x541              ; =1345
	WORD $0x4e040d00 // dup.4s	v0, w8
	WORD $0x3ceb6817 // ldr	q23, [x0, x11]
	WORD $0x3cec681c // ldr	q28, [x0, x12]
	WORD $0x4e040d3d // dup.4s	v29, w9
	WORD $0x4ebd9efd // mul.4s	v29, v23, v29
	WORD $0x4ea0979d // mla.4s	v29, v28, v0
	WORD $0x4ea09ee0 // mul.4s	v0, v23, v0
	WORD $0x1280a808 // mov	w8, #-0x541             ; =-1345
	WORD $0x4e040d18 // dup.4s	v24, w8
	WORD $0x4eb89780 // mla.4s	v0, v28, v24
	WORD $0x4f3427b8 // srshr.4s	v24, v29, #0xc
	WORD $0x6eb78718 // sub.4s	v24, v24, v23
	WORD $0x4ebc8718 // add.4s	v24, v24, v28
	WORD $0x4eb78797 // add.4s	v23, v28, v23
	WORD $0x4f343417 // srsra.4s	v23, v0, #0xc
	WORD $0x4f3434a2 // srsra.4s	v2, v5, #0xc
	WORD $0x4ea18700 // add.4s	v0, v24, v1
	WORD $0x6eb88421 // sub.4s	v1, v1, v24
	WORD $0x6ea48605 // sub.4s	v5, v16, v4
	WORD $0x4ea48604 // add.4s	v4, v16, v4
	WORD $0xad41c3f2 // ldp	q18, q16, [sp, #0x30]
	WORD $0x4eb28610 // add.4s	v16, v16, v18
	WORD $0x3dc017f2 // ldr	q18, [sp, #0x50]
	WORD $0x4f353659 // srsra.4s	v25, v18, #0xb
	WORD $0x4f3535b5 // srsra.4s	v21, v13, #0xb
	WORD $0x4eac876d // add.4s	v13, v27, v12
	WORD $0x4ea7846c // add.4s	v12, v3, v7
	WORD $0x6ea384e3 // sub.4s	v3, v7, v3
	WORD $0x6eb78447 // sub.4s	v7, v2, v23
	WORD $0x4eb7845d // add.4s	v29, v2, v23
	WORD $0x4eb46421 // smax.4s	v1, v1, v20
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x4eb464e2 // smax.4s	v2, v7, v20
	WORD $0x4ea66c5f // smin.4s	v31, v2, v6
	WORD $0x4f0205f2 // movi.4s	v18, #0x4f
	WORD $0x4eb29c22 // mul.4s	v2, v1, v18
	WORD $0x3dc007f7 // ldr	q23, [sp, #0x10]
	WORD $0x4eb797e2 // mla.4s	v2, v31, v23
	WORD $0x4f342442 // srshr.4s	v2, v2, #0xc
	WORD $0x6ea18447 // sub.4s	v7, v2, v1
	WORD $0x4eb79c21 // mul.4s	v1, v1, v23
	WORD $0x6f0205c2 // mvni.4s	v2, #0x4e
	WORD $0x4ea297e1 // mla.4s	v1, v31, v2
	WORD $0x4f34343f // srsra.4s	v31, v1, #0xc
	WORD $0x4eb464a1 // smax.4s	v1, v5, v20
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x4eb46462 // smax.4s	v2, v3, v20
	WORD $0x128063c8 // mov	w8, #-0x31f             ; =-799
	WORD $0x4e040d03 // dup.4s	v3, w8
	WORD $0x4ea66c42 // smin.4s	v2, v2, v6
	WORD $0x4ea39c23 // mul.4s	v3, v1, v3
	WORD $0x4eb29443 // mla.4s	v3, v2, v18
	WORD $0x4eb29c25 // mul.4s	v5, v1, v18
	WORD $0x4eb79445 // mla.4s	v5, v2, v23
	WORD $0x4f342463 // srshr.4s	v3, v3, #0xc
	WORD $0x6ea28463 // sub.4s	v3, v3, v2
	WORD $0x4f3424a2 // srshr.4s	v2, v5, #0xc
	WORD $0x6ea18442 // sub.4s	v2, v2, v1
	WORD $0x4ea78477 // add.4s	v23, v3, v7
	WORD $0x6ea384fc // sub.4s	v28, v7, v3
	WORD $0x4eb46400 // smax.4s	v0, v0, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x4eb46481 // smax.4s	v1, v4, v20
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x4ea08427 // add.4s	v7, v1, v0
	WORD $0x6ea18403 // sub.4s	v3, v0, v1
	WORD $0x4f352545 // srshr.4s	v5, v10, #0xb
	WORD $0x4f352560 // srshr.4s	v0, v11, #0xb
	WORD $0x6ea084aa // sub.4s	v10, v5, v0
	WORD $0x4f353565 // srsra.4s	v5, v11, #0xb
	WORD $0x4eb46600 // smax.4s	v0, v16, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x4eb46721 // smax.4s	v1, v25, v20
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x6ea08424 // sub.4s	v4, v1, v0
	WORD $0x4ea0843b // add.4s	v27, v1, v0
	WORD $0x3dc00be0 // ldr	q0, [sp, #0x20]
	WORD $0x4f352410 // srshr.4s	v16, v0, #0xb
	WORD $0x4f3525e0 // srshr.4s	v0, v15, #0xb
	WORD $0x6ea08600 // sub.4s	v0, v16, v0
	WORD $0x4f3535f0 // srsra.4s	v16, v15, #0xb
	WORD $0x4eb466a1 // smax.4s	v1, v21, v20
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x4eb465b2 // smax.4s	v18, v13, v20
	WORD $0x4ea66e52 // smin.4s	v18, v18, v6
	WORD $0x4ea18659 // add.4s	v25, v18, v1
	WORD $0x6eb28421 // sub.4s	v1, v1, v18
	WORD $0x6ea287f2 // sub.4s	v18, v31, v2
	WORD $0x4ebf844d // add.4s	v13, v2, v31
	WORD $0x4eb46582 // smax.4s	v2, v12, v20
	WORD $0x4ea66c42 // smin.4s	v2, v2, v6
	WORD $0x4eb467b5 // smax.4s	v21, v29, v20
	WORD $0x4ea66eb5 // smin.4s	v21, v21, v6
	WORD $0x6ea286b8 // sub.4s	v24, v21, v2
	WORD $0x4ea286bd // add.4s	v29, v21, v2
	WORD $0x4eb46782 // smax.4s	v2, v28, v20
	WORD $0x4ea66c42 // smin.4s	v2, v2, v6
	WORD $0x4eb46652 // smax.4s	v18, v18, v20
	WORD $0x4ea66e5f // smin.4s	v31, v18, v6
	WORD $0x4eb69c52 // mul.4s	v18, v2, v22
	WORD $0x4eae97f2 // mla.4s	v18, v31, v14
	WORD $0x4f342652 // srshr.4s	v18, v18, #0xc
	WORD $0x6ea28655 // sub.4s	v21, v18, v2
	WORD $0x4eae9c42 // mul.4s	v2, v2, v14
	WORD $0x3dc057fc // ldr	q28, [sp, #0x150]
	WORD $0x4ebc97e2 // mla.4s	v2, v31, v28
	WORD $0x4f34345f // srsra.4s	v31, v2, #0xc
	WORD $0x4eb46462 // smax.4s	v2, v3, v20
	WORD $0x4ea66c43 // smin.4s	v3, v2, v6
	WORD $0x4eb46702 // smax.4s	v2, v24, v20
	WORD $0x4ea66c42 // smin.4s	v2, v2, v6
	WORD $0x4eb69c72 // mul.4s	v18, v3, v22
	WORD $0x4eae9452 // mla.4s	v18, v2, v14
	WORD $0x4f342652 // srshr.4s	v18, v18, #0xc
	WORD $0x6ea38652 // sub.4s	v18, v18, v3
	WORD $0x4eae9c63 // mul.4s	v3, v3, v14
	WORD $0x4ebc9443 // mla.4s	v3, v2, v28
	WORD $0x4f343462 // srsra.4s	v2, v3, #0xc
	WORD $0x4eb46483 // smax.4s	v3, v4, v20
	WORD $0x4ea66c63 // smin.4s	v3, v3, v6
	WORD $0x4eb46421 // smax.4s	v1, v1, v20
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x4eb19c64 // mul.4s	v4, v3, v17
	WORD $0x4eb69424 // mla.4s	v4, v1, v22
	WORD $0x4f342484 // srshr.4s	v4, v4, #0xc
	WORD $0x6ea18484 // sub.4s	v4, v4, v1
	WORD $0x4eb69c78 // mul.4s	v24, v3, v22
	WORD $0x4eae9438 // mla.4s	v24, v1, v14
	WORD $0x4f342701 // srshr.4s	v1, v24, #0xc
	WORD $0x6ea38421 // sub.4s	v1, v1, v3
	WORD $0x4eb46543 // smax.4s	v3, v10, v20
	WORD $0x4ea66c63 // smin.4s	v3, v3, v6
	WORD $0x4eb46400 // smax.4s	v0, v0, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x4eb19c71 // mul.4s	v17, v3, v17
	WORD $0x4eb69411 // mla.4s	v17, v0, v22
	WORD $0x4eb69c78 // mul.4s	v24, v3, v22
	WORD $0x4eae9418 // mla.4s	v24, v0, v14
	WORD $0x4f342631 // srshr.4s	v17, v17, #0xc
	WORD $0x6ea08620 // sub.4s	v0, v17, v0
	WORD $0x4f342711 // srshr.4s	v17, v24, #0xc
	WORD $0x6ea38638 // sub.4s	v24, v17, v3
	WORD $0x4eb2848f // add.4s	v15, v4, v18
	WORD $0x6ea4865c // sub.4s	v28, v18, v4
	WORD $0x4eb58403 // add.4s	v3, v0, v21
	WORD $0x6ea086aa // sub.4s	v10, v21, v0
	WORD $0x4eb466e0 // smax.4s	v0, v23, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x4eb464a4 // smax.4s	v4, v5, v20
	WORD $0x4ea66c85 // smin.4s	v5, v4, v6
	WORD $0x4ea084a4 // add.4s	v4, v5, v0
	WORD $0x6ea58417 // sub.4s	v23, v0, v5
	WORD $0x4eb464e0 // smax.4s	v0, v7, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x4eb46765 // smax.4s	v5, v27, v20
	WORD $0x4ea66ca5 // smin.4s	v5, v5, v6
	WORD $0x4ea084b5 // add.4s	v21, v5, v0
	WORD $0x6ea58412 // sub.4s	v18, v0, v5
	WORD $0x6ea18447 // sub.4s	v7, v2, v1
	WORD $0x4ea28431 // add.4s	v17, v1, v2
	WORD $0x6eb887e1 // sub.4s	v1, v31, v24
	WORD $0x4ebf8705 // add.4s	v5, v24, v31
	WORD $0x4eb46600 // smax.4s	v0, v16, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x4eb465a2 // smax.4s	v2, v13, v20
	WORD $0x4ea66c42 // smin.4s	v2, v2, v6
	WORD $0x6ea08458 // sub.4s	v24, v2, v0
	WORD $0x4ea08440 // add.4s	v0, v2, v0
	WORD $0x3d8057e0 // str	q0, [sp, #0x150]
	WORD $0x4eb46722 // smax.4s	v2, v25, v20
	WORD $0x4ea66c42 // smin.4s	v2, v2, v6
	WORD $0x4eb467b0 // smax.4s	v16, v29, v20
	WORD $0x4ea66e10 // smin.4s	v16, v16, v6
	WORD $0x6ea28619 // sub.4s	v25, v16, v2
	WORD $0x4ea28600 // add.4s	v0, v16, v2
	WORD $0x3d8047e0 // str	q0, [sp, #0x110]
	WORD $0x4eb46782 // smax.4s	v2, v28, v20
	WORD $0x4ea66c42 // smin.4s	v2, v2, v6
	WORD $0x4eb464e7 // smax.4s	v7, v7, v20
	WORD $0x4ea66ce7 // smin.4s	v7, v7, v6
	WORD $0x6ea284fb // sub.4s	v27, v7, v2
	WORD $0x4ea284e2 // add.4s	v2, v7, v2
	WORD $0x4eb46547 // smax.4s	v7, v10, v20
	WORD $0x4ea66ce7 // smin.4s	v7, v7, v6
	WORD $0x4eb46421 // smax.4s	v1, v1, v20
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x6ea7843d // sub.4s	v29, v1, v7
	WORD $0x4ea78421 // add.4s	v1, v1, v7
	WORD $0x4eb466e7 // smax.4s	v7, v23, v20
	WORD $0x4ea66ce7 // smin.4s	v7, v7, v6
	WORD $0x4eb46717 // smax.4s	v23, v24, v20
	WORD $0x4ea66ef7 // smin.4s	v23, v23, v6
	WORD $0x6ea786f8 // sub.4s	v24, v23, v7
	WORD $0x4ea786e7 // add.4s	v7, v23, v7
	WORD $0x4eb46652 // smax.4s	v18, v18, v20
	WORD $0x4ea66e52 // smin.4s	v18, v18, v6
	WORD $0x4eb46737 // smax.4s	v23, v25, v20
	WORD $0x4ea66ef7 // smin.4s	v23, v23, v6
	WORD $0x6eb286ea // sub.4s	v10, v23, v18
	WORD $0x4eb286f2 // add.4s	v18, v23, v18
	WORD $0x4f0506a0 // movi.4s	v0, #0xb5
	WORD $0x4ea09f7c // mul.4s	v28, v27, v0
	WORD $0x4ea09c57 // mul.4s	v23, v2, v0
	WORD $0x4ea09fbd // mul.4s	v29, v29, v0
	WORD $0x4ea09c39 // mul.4s	v25, v1, v0
	WORD $0x4ea09f1f // mul.4s	v31, v24, v0
	WORD $0x4ea09cfb // mul.4s	v27, v7, v0
	WORD $0x4ea09d4a // mul.4s	v10, v10, v0
	WORD $0x4ea09e4c // mul.4s	v12, v18, v0
	WORD $0x4eb46661 // smax.4s	v1, v19, v20
	WORD $0x4ea66c2b // smin.4s	v11, v1, v6
	WORD $0x4f3826f2 // srshr.4s	v18, v23, #0x8
	WORD $0x6eb28562 // sub.4s	v2, v11, v18
	WORD $0x4f3836eb // srsra.4s	v11, v23, #0x8
	WORD $0x4eb46501 // smax.4s	v1, v8, v20
	WORD $0x4ea66c28 // smin.4s	v8, v1, v6
	WORD $0x4f382721 // srshr.4s	v1, v25, #0x8
	WORD $0x6ea18500 // sub.4s	v0, v8, v1
	WORD $0xad020be0 // stp	q0, q2, [sp, #0x40]
	WORD $0x4f383728 // srsra.4s	v8, v25, #0x8
	WORD $0x4eb46521 // smax.4s	v1, v9, v20
	WORD $0x4ea66c29 // smin.4s	v9, v1, v6
	WORD $0x4f382761 // srshr.4s	v1, v27, #0x8
	WORD $0x6ea18520 // sub.4s	v0, v9, v1
	WORD $0x3d800fe0 // str	q0, [sp, #0x30]
	WORD $0x4f383769 // srsra.4s	v9, v27, #0x8
	WORD $0x4eb467c1 // smax.4s	v1, v30, v20
	WORD $0x4ea66c2d // smin.4s	v13, v1, v6
	WORD $0x4f382581 // srshr.4s	v1, v12, #0x8
	WORD $0x6ea185bb // sub.4s	v27, v13, v1
	WORD $0x4f38358d // srsra.4s	v13, v12, #0x8
	WORD $0xad430be0 // ldp	q0, q2, [sp, #0x60]
	WORD $0x4eb46441 // smax.4s	v1, v2, v20
	WORD $0x4ea66c2c // smin.4s	v12, v1, v6
	WORD $0x4f382541 // srshr.4s	v1, v10, #0x8
	WORD $0x6ea18592 // sub.4s	v18, v12, v1
	WORD $0x4f38354c // srsra.4s	v12, v10, #0x8
	WORD $0x4eb46402 // smax.4s	v2, v0, v20
	WORD $0x4ea66c4a // smin.4s	v10, v2, v6
	WORD $0x4f3827e2 // srshr.4s	v2, v31, #0x8
	WORD $0x6ea28556 // sub.4s	v22, v10, v2
	WORD $0x4f3837ea // srsra.4s	v10, v31, #0x8
	WORD $0xad4483e1 // ldp	q1, q0, [sp, #0x90]
	WORD $0x4eb46422 // smax.4s	v2, v1, v20
	WORD $0x4ea66c5f // smin.4s	v31, v2, v6
	WORD $0x4f3827a2 // srshr.4s	v2, v29, #0x8
	WORD $0x6ea287fe // sub.4s	v30, v31, v2
	WORD $0x4f3837bf // srsra.4s	v31, v29, #0x8
	WORD $0x4eb46402 // smax.4s	v2, v0, v20
	WORD $0x4ea66c4e // smin.4s	v14, v2, v6
	WORD $0x4f382782 // srshr.4s	v2, v28, #0x8
	WORD $0x6ea285dd // sub.4s	v29, v14, v2
	WORD $0x4f38378e // srsra.4s	v14, v28, #0x8
	WORD $0x4eb46742 // smax.4s	v2, v26, v20
	WORD $0x4ea66c42 // smin.4s	v2, v2, v6
	WORD $0x4eb466a7 // smax.4s	v7, v21, v20
	WORD $0x4ea66ce7 // smin.4s	v7, v7, v6
	WORD $0x4ea284fa // add.4s	v26, v7, v2
	WORD $0x6ea78455 // sub.4s	v21, v2, v7
	WORD $0x3dc023e0 // ldr	q0, [sp, #0x80]
	WORD $0x4eb46402 // smax.4s	v2, v0, v20
	WORD $0x4ea66c47 // smin.4s	v7, v2, v6
	WORD $0x4eb46482 // smax.4s	v2, v4, v20
	WORD $0x4ea66c44 // smin.4s	v4, v2, v6
	WORD $0x4ea78490 // add.4s	v16, v4, v7
	WORD $0x6ea484f8 // sub.4s	v24, v7, v4
	WORD $0xad4687e0 // ldp	q0, q1, [sp, #0xd0]
	WORD $0x4eb46424 // smax.4s	v4, v1, v20
	WORD $0x4ea66c84 // smin.4s	v4, v4, v6
	WORD $0x4eb46463 // smax.4s	v3, v3, v20
	WORD $0x4ea66c67 // smin.4s	v7, v3, v6
	WORD $0x4ea484e3 // add.4s	v3, v7, v4
	WORD $0x6ea7849c // sub.4s	v28, v4, v7
	WORD $0x4eb46404 // smax.4s	v4, v0, v20
	WORD $0x4ea66c87 // smin.4s	v7, v4, v6
	WORD $0x4eb465e4 // smax.4s	v4, v15, v20
	WORD $0x4ea66c93 // smin.4s	v19, v4, v6
	WORD $0x4ea78664 // add.4s	v4, v19, v7
	WORD $0x6eb384ef // sub.4s	v15, v7, v19
	WORD $0xad4783e1 // ldp	q1, q0, [sp, #0xf0]
	WORD $0x4eb46427 // smax.4s	v7, v1, v20
	WORD $0x4ea66ce7 // smin.4s	v7, v7, v6
	WORD $0x4eb46631 // smax.4s	v17, v17, v20
	WORD $0x4ea66e31 // smin.4s	v17, v17, v6
	WORD $0x4ea78633 // add.4s	v19, v17, v7
	WORD $0x6eb184e7 // sub.4s	v7, v7, v17
	WORD $0x4eb46411 // smax.4s	v17, v0, v20
	WORD $0x4ea66e31 // smin.4s	v17, v17, v6
	WORD $0x4eb464a5 // smax.4s	v5, v5, v20
	WORD $0x4ea66ca5 // smin.4s	v5, v5, v6
	WORD $0x4eb184a2 // add.4s	v2, v5, v17
	WORD $0x6ea58631 // sub.4s	v17, v17, v5
	WORD $0x3dc033e0 // ldr	q0, [sp, #0xc0]
	WORD $0x4eb46401 // smax.4s	v1, v0, v20
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x3dc057e0 // ldr	q0, [sp, #0x150]
	WORD $0x4eb46405 // smax.4s	v5, v0, v20
	WORD $0x4ea66ca5 // smin.4s	v5, v5, v6
	WORD $0x4ea184a0 // add.4s	v0, v5, v1
	WORD $0x6ea58421 // sub.4s	v1, v1, v5
	WORD $0x3dc02fe5 // ldr	q5, [sp, #0xb0]
	WORD $0x4eb464a5 // smax.4s	v5, v5, v20
	WORD $0x4ea66ca5 // smin.4s	v5, v5, v6
	WORD $0x3dc047f7 // ldr	q23, [sp, #0x110]
	WORD $0x4eb466f7 // smax.4s	v23, v23, v20
	WORD $0x4ea66ef7 // smin.4s	v23, v23, v6
	WORD $0x4ea586f9 // add.4s	v25, v23, v5
	WORD $0x4eb46739 // smax.4s	v25, v25, v20
	WORD $0x4ea66f39 // smin.4s	v25, v25, v6
	WORD $0x3d800019 // str	q25, [x0]
	WORD $0x4eb46400 // smax.4s	v0, v0, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3ca16800 // str	q0, [x0, x1]
	WORD $0x4eb46440 // smax.4s	v0, v2, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cb36800 // str	q0, [x0, x19]
	WORD $0x6eb784a5 // sub.4s	v5, v5, v23
	WORD $0x4eb46660 // smax.4s	v0, v19, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3ca76800 // str	q0, [x0, x7]
	WORD $0x4eb46560 // smax.4s	v0, v11, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3ca36800 // str	q0, [x0, x3]
	WORD $0x4eb46500 // smax.4s	v0, v8, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3ca26800 // str	q0, [x0, x2]
	WORD $0x4eb46520 // smax.4s	v0, v9, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cb96800 // str	q0, [x0, x25]
	WORD $0x4eb465a0 // smax.4s	v0, v13, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3caa6800 // str	q0, [x0, x10]
	WORD $0x4eb46580 // smax.4s	v0, v12, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cae6800 // str	q0, [x0, x14]
	WORD $0x4eb46540 // smax.4s	v0, v10, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cad6800 // str	q0, [x0, x13]
	WORD $0x4eb467e0 // smax.4s	v0, v31, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cb86800 // str	q0, [x0, x24]
	WORD $0x4eb465c0 // smax.4s	v0, v14, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3ca66800 // str	q0, [x0, x6]
	WORD $0x4eb46480 // smax.4s	v0, v4, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0xf9409fe8 // ldr	x8, [sp, #0x138]
	WORD $0x3ca86800 // str	q0, [x0, x8]
	WORD $0x4eb46460 // smax.4s	v0, v3, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3ca46800 // str	q0, [x0, x4]
	WORD $0x4eb46600 // smax.4s	v0, v16, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0xa952a3e9 // ldp	x9, x8, [sp, #0x128]
	WORD $0x3ca96800 // str	q0, [x0, x9]
	WORD $0x4eb46740 // smax.4s	v0, v26, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cab6800 // str	q0, [x0, x11]
	WORD $0x4eb466a0 // smax.4s	v0, v21, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3caf6800 // str	q0, [x0, x15]
	WORD $0x4eb46700 // smax.4s	v0, v24, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cac6800 // str	q0, [x0, x12]
	WORD $0x4eb46780 // smax.4s	v0, v28, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3ca86800 // str	q0, [x0, x8]
	WORD $0x4eb465e0 // smax.4s	v0, v15, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cb16800 // str	q0, [x0, x17]
	WORD $0x4eb467a0 // smax.4s	v0, v29, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0xa95423e9 // ldp	x9, x8, [sp, #0x140]
	WORD $0x3ca96800 // str	q0, [x0, x9]
	WORD $0x4eb467c0 // smax.4s	v0, v30, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3ca56800 // str	q0, [x0, x5]
	WORD $0x4eb466c0 // smax.4s	v0, v22, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cb66800 // str	q0, [x0, x22]
	WORD $0x4eb46640 // smax.4s	v0, v18, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cbc6800 // str	q0, [x0, x28]
	WORD $0x4eb46760 // smax.4s	v0, v27, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3ca86800 // str	q0, [x0, x8]
	WORD $0x3dc00fe0 // ldr	q0, [sp, #0x30]
	WORD $0x4eb46400 // smax.4s	v0, v0, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cbe6800 // str	q0, [x0, x30]
	WORD $0x3dc013e0 // ldr	q0, [sp, #0x40]
	WORD $0x4eb46400 // smax.4s	v0, v0, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cb76800 // str	q0, [x0, x23]
	WORD $0x3dc017e0 // ldr	q0, [sp, #0x50]
	WORD $0x4eb46400 // smax.4s	v0, v0, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0xf94093e8 // ldr	x8, [sp, #0x120]
	WORD $0x3ca86800 // str	q0, [x0, x8]
	WORD $0x4eb464e0 // smax.4s	v0, v7, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cb46800 // str	q0, [x0, x20]
	WORD $0x4eb46620 // smax.4s	v0, v17, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cb06800 // str	q0, [x0, x16]
	WORD $0x4eb46420 // smax.4s	v0, v1, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cb56800 // str	q0, [x0, x21]
	WORD $0x4eb464a0 // smax.4s	v0, v5, v20
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cba6b60 // str	q0, [x27, x26]
	WORD $0x910583ff // add	sp, sp, #0x160
	WORD $0xa9497bfd // ldp	x29, x30, [sp, #0x90]
	WORD $0xa9484ff4 // ldp	x20, x19, [sp, #0x80]
	WORD $0xa94757f6 // ldp	x22, x21, [sp, #0x70]
	WORD $0xa9465ff8 // ldp	x24, x23, [sp, #0x60]
	WORD $0xa94567fa // ldp	x26, x25, [sp, #0x50]
	WORD $0xa9446ffc // ldp	x28, x27, [sp, #0x40]
	WORD $0x6d4323e9 // ldp	d9, d8, [sp, #0x30]
	WORD $0x6d422beb // ldp	d11, d10, [sp, #0x20]
	WORD $0x6d4133ed // ldp	d13, d12, [sp, #0x10]
	WORD $0x6cca3bef // ldp	d15, d14, [sp], #0xa0
	WORD $0xd65f03c0 // ret
