// NEON-accelerated inverse DCT32 four-column kernel.
//
// Four adjacent columns of the row-major scratch buffer ride the four int32
// lanes of each .4s register, following dav1d's high-bitdepth inverse
// transform shape (dav1d src/arm/64/itx16.S: inv_dct_4s_x16_neon and the
// mul_mla/mul_mls + srshr + smax/smin idiom): every butterfly multiply is a
// plain mul/mla/mls .4s, every rounding shift is srshr .4s and every stage
// clamp is smax+smin against the stage bounds. Working in int32 lanes without
// widening is exact here because the column-pass inputs are pre-clamped to the
// stage range (|v| <= 2^19 across all supported bit depths) and every cosine
// pair in the (cospi-4096)-rewritten butterflies keeps the multiply
// accumulator below 2^31 (the adapter enforces the clamp-bound precondition
// and falls back otherwise). The fixed-point products, rounding shifts and
// clamps are bit-for-bit identical to running the pure-Go inverseDCT32 on
// each column, asserted exhaustively by the column dispatch differential
// tests.
//
// The body is generated by transliterating the pure-Go butterfly to NEON
// intrinsics, compiling with the system C compiler at -O2 and transcribing
// the disassembly verbatim as WORD-encoded opcodes, because Go's arm64
// assembler does not expose the signed-rounding-shift mnemonics. The kernel
// is pure straight-line leaf code (no branches, no calls); it manages its own
// 512-byte caller/callee-saved spill frame below the (empty) Go frame, within
// the nosplit stack budget, and restores every callee-saved register before
// returning.
//
// SPDX-License-Identifier: BSD-2-Clause
//
// See LICENSE for the BSD-2-Clause grant and NOTICE for the AOM attribution.

//go:build arm64 && !purego

#include "textflag.h"

// func inverseDCT32Col4NEON(base *int32, rowStrideBytes, min, max int64)
// Transforms four adjacent columns (col..col+3) of the row-major scratch
// buffer in place. base points at scratch[col]; rows are rowStrideBytes
// apart. The four columns occupy int32 lanes 0-3. Bit-for-bit identical to
// inverseDCT32 run on each column.
TEXT ·inverseDCT32Col4NEON(SB), NOSPLIT, $0-32
	MOVD base+0(FP), R0
	MOVD rowStrideBytes+8(FP), R1
	MOVD min+16(FP), R2
	MOVD max+24(FP), R3
	WORD $0xd10783ff // sub	sp, sp, #0x1e0
	WORD $0x6d143bef // stp	d15, d14, [sp, #0x140]
	WORD $0x6d1533ed // stp	d13, d12, [sp, #0x150]
	WORD $0x6d162beb // stp	d11, d10, [sp, #0x160]
	WORD $0x6d1723e9 // stp	d9, d8, [sp, #0x170]
	WORD $0xf900c3fb // str	x27, [sp, #0x180]
	WORD $0xa91967fa // stp	x26, x25, [sp, #0x190]
	WORD $0xa91a5ff8 // stp	x24, x23, [sp, #0x1a0]
	WORD $0xa91b57f6 // stp	x22, x21, [sp, #0x1b0]
	WORD $0xa91c4ff4 // stp	x20, x19, [sp, #0x1c0]
	WORD $0xa91d7bfd // stp	x29, x30, [sp, #0x1d0]
	WORD $0x4e040c50 // dup.4s	v16, w2
	WORD $0x4e040c66 // dup.4s	v6, w3
	WORD $0x3dc00002 // ldr	q2, [x0]
	WORD $0xd37cec30 // lsl	x16, x1, #4
	WORD $0x3cf06803 // ldr	q3, [x0, x16]
	WORD $0x4ea28464 // add.4s	v4, v3, v2
	WORD $0x4f0506a0 // movi.4s	v0, #0xb5
	WORD $0x4ea09c84 // mul.4s	v4, v4, v0
	WORD $0x4f382485 // srshr.4s	v5, v4, #0x8
	WORD $0x6ea38442 // sub.4s	v2, v2, v3
	WORD $0x4ea09c43 // mul.4s	v3, v2, v0
	WORD $0x4f382460 // srshr.4s	v0, v3, #0x8
	WORD $0x5280c3e8 // mov	w8, #0x61f              ; =1567
	WORD $0x4e040d0b // dup.4s	v11, w8
	WORD $0x52802708 // mov	w8, #0x138              ; =312
	WORD $0x4e040d0e // dup.4s	v14, w8
	WORD $0xd37df02f // lsl	x15, x1, #3
	WORD $0x3cef6807 // ldr	q7, [x0, x15]
	WORD $0x52800308 // mov	w8, #0x18               ; =24
	WORD $0x9b087c28 // mul	x8, x1, x8
	WORD $0xf900c7e8 // str	x8, [sp, #0x188]
	WORD $0x3ce86811 // ldr	q17, [x0, x8]
	WORD $0x4eab9ce2 // mul.4s	v2, v7, v11
	WORD $0x4eae9622 // mla.4s	v2, v17, v14
	WORD $0x4f342442 // srshr.4s	v2, v2, #0xc
	WORD $0x128026e8 // mov	w8, #-0x138             ; =-312
	WORD $0x4e040d01 // dup.4s	v1, w8
	WORD $0x3d804fe1 // str	q1, [sp, #0x130]
	WORD $0x6eb1845c // sub.4s	v28, v2, v17
	WORD $0x4ea19cf2 // mul.4s	v18, v7, v1
	WORD $0x4eab9632 // mla.4s	v18, v17, v11
	WORD $0x4f343647 // srsra.4s	v7, v18, #0xc
	WORD $0x6ea784a8 // sub.4s	v8, v5, v7
	WORD $0x4f383487 // srsra.4s	v7, v4, #0x8
	WORD $0x6ebc841e // sub.4s	v30, v0, v28
	WORD $0x4f38347c // srsra.4s	v28, v3, #0x8
	WORD $0x528063e8 // mov	w8, #0x31f              ; =799
	WORD $0x4e040d00 // dup.4s	v0, w8
	WORD $0x5280d4e8 // mov	w8, #0x6a7              ; =1703
	WORD $0x4e040d17 // dup.4s	v23, w8
	WORD $0x12808e28 // mov	w8, #-0x472             ; =-1138
	WORD $0x4e040d18 // dup.4s	v24, w8
	WORD $0x52800188 // mov	w8, #0xc                ; =12
	WORD $0x9b087c28 // mul	x8, x1, x8
	WORD $0xf90093e8 // str	x8, [sp, #0x120]
	WORD $0x3ce86804 // ldr	q4, [x0, x8]
	WORD $0x4eb89c93 // mul.4s	v19, v4, v24
	WORD $0x52800288 // mov	w8, #0x14               ; =20
	WORD $0x9b087c28 // mul	x8, x1, x8
	WORD $0xf90097e8 // str	x8, [sp, #0x128]
	WORD $0x3ce86805 // ldr	q5, [x0, x8]
	WORD $0x4eb794b3 // mla.4s	v19, v5, v23
	WORD $0x52808e48 // mov	w8, #0x472              ; =1138
	WORD $0x4e040d03 // dup.4s	v3, w8
	WORD $0x4eb79c96 // mul.4s	v22, v4, v23
	WORD $0x4ea394b6 // mla.4s	v22, v5, v3
	WORD $0x5280c5e8 // mov	w8, #0x62f              ; =1583
	WORD $0x4e040d04 // dup.4s	v4, w8
	WORD $0x1280a248 // mov	w8, #-0x513             ; =-1299
	WORD $0x4e040d05 // dup.4s	v5, w8
	WORD $0x528001c8 // mov	w8, #0xe                ; =14
	WORD $0x9b087c28 // mul	x8, x1, x8
	WORD $0xf9008be8 // str	x8, [sp, #0x110]
	WORD $0x3ce86811 // ldr	q17, [x0, x8]
	WORD $0x4ea59e21 // mul.4s	v1, v17, v5
	WORD $0x52800248 // mov	w8, #0x12               ; =18
	WORD $0x9b087c28 // mul	x8, x1, x8
	WORD $0xf9008fe8 // str	x8, [sp, #0x118]
	WORD $0x3ce86805 // ldr	q5, [x0, x8]
	WORD $0x4ea494a1 // mla.4s	v1, v5, v4
	WORD $0x3d803fe1 // str	q1, [sp, #0xf0]
	WORD $0x5280a268 // mov	w8, #0x513              ; =1299
	WORD $0x4e040d12 // dup.4s	v18, w8
	WORD $0x4ea49e21 // mul.4s	v1, v17, v4
	WORD $0x4eb294a1 // mla.4s	v1, v5, v18
	WORD $0x3d803be1 // str	q1, [sp, #0xe0]
	WORD $0x52807c68 // mov	w8, #0x3e3              ; =995
	WORD $0x4e040d05 // dup.4s	v5, w8
	WORD $0xd37ef423 // lsl	x3, x1, #2
	WORD $0x8b010062 // add	x2, x3, x1
	WORD $0x3ce2681b // ldr	q27, [x0, x2]
	WORD $0x4ea59f64 // mul.4s	v4, v27, v5
	WORD $0x4f030775 // movi.4s	v21, #0x7b
	WORD $0x128048c8 // mov	w8, #-0x247             ; =-583
	WORD $0x4e040d12 // dup.4s	v18, w8
	WORD $0x52809888 // mov	w8, #0x4c4              ; =1220
	WORD $0x4e040d1a // dup.4s	v26, w8
	WORD $0x52800368 // mov	w8, #0x1b               ; =27
	WORD $0x9b087c28 // mul	x8, x1, x8
	WORD $0xf90087e8 // str	x8, [sp, #0x108]
	WORD $0x3ce86811 // ldr	q17, [x0, x8]
	WORD $0x4eb59624 // mla.4s	v4, v17, v21
	WORD $0x1280cd88 // mov	w8, #-0x66d             ; =-1645
	WORD $0x4e040d15 // dup.4s	v21, w8
	WORD $0x528001a8 // mov	w8, #0xd                ; =13
	WORD $0x9b087c24 // mul	x4, x1, x8
	WORD $0x3ce4681d // ldr	q29, [x0, x4]
	WORD $0x52800268 // mov	w8, #0x13               ; =19
	WORD $0x9b087c31 // mul	x17, x1, x8
	WORD $0x3cf16809 // ldr	q9, [x0, x17]
	WORD $0x4eba9fa1 // mul.4s	v1, v29, v26
	WORD $0x4eb59521 // mla.4s	v1, v9, v21
	WORD $0x3d8017e1 // str	q1, [sp, #0x50]
	WORD $0x6f01056a // mvni.4s	v10, #0x2b
	WORD $0x12804b08 // mov	w8, #-0x259             ; =-601
	WORD $0x4e040d19 // dup.4s	v25, w8
	WORD $0xd37ff833 // lsl	x19, x1, #1
	WORD $0x8b010267 // add	x7, x19, x1
	WORD $0x3ce76815 // ldr	q21, [x0, x7]
	WORD $0x4eb99eac // mul.4s	v12, v21, v25
	WORD $0x52804b28 // mov	w8, #0x259              ; =601
	WORD $0x4e040d0d // dup.4s	v13, w8
	WORD $0x528003a8 // mov	w8, #0x1d               ; =29
	WORD $0x9b087c28 // mul	x8, x1, x8
	WORD $0xf90083e8 // str	x8, [sp, #0x100]
	WORD $0x3ce86819 // ldr	q25, [x0, x8]
	WORD $0x4eaa972c // mla.4s	v12, v25, v10
	WORD $0x4eaa9eaa // mul.4s	v10, v21, v10
	WORD $0x4ead972a // mla.4s	v10, v25, v13
	WORD $0x5280f8c8 // mov	w8, #0x7c6              ; =1990
	WORD $0x4e040d0d // dup.4s	v13, w8
	WORD $0x4f343599 // srsra.4s	v25, v12, #0xc
	WORD $0x52800168 // mov	w8, #0xb                ; =11
	WORD $0x9b087c26 // mul	x6, x1, x8
	WORD $0x3ce6680c // ldr	q12, [x0, x6]
	WORD $0x4ead9d8d // mul.4s	v13, v12, v13
	WORD $0x4f343555 // srsra.4s	v21, v10, #0xc
	WORD $0x5280cda8 // mov	w8, #0x66d              ; =1645
	WORD $0x4e040d0a // dup.4s	v10, w8
	WORD $0x4eaa9fbf // mul.4s	v31, v29, v10
	WORD $0x528002a8 // mov	w8, #0x15               ; =21
	WORD $0x9b087c25 // mul	x5, x1, x8
	WORD $0x3ce5680f // ldr	q15, [x0, x5]
	WORD $0x4eb295ed // mla.4s	v13, v15, v18
	WORD $0x4eba953f // mla.4s	v31, v9, v26
	WORD $0x1280f8a8 // mov	w8, #-0x7c6             ; =-1990
	WORD $0x4e040d1a // dup.4s	v26, w8
	WORD $0x4eb29d92 // mul.4s	v18, v12, v18
	WORD $0x4eba95f2 // mla.4s	v18, v15, v26
	WORD $0x3ce36809 // ldr	q9, [x0, x3]
	WORD $0x3d8007e0 // str	q0, [sp, #0x10]
	WORD $0x4ea09d3a // mul.4s	v26, v9, v0
	WORD $0x4f342484 // srshr.4s	v4, v4, #0xc
	WORD $0x6eb18482 // sub.4s	v2, v4, v17
	WORD $0x4f3425a4 // srshr.4s	v4, v13, #0xc
	WORD $0x6eac8484 // sub.4s	v4, v4, v12
	WORD $0x4eaf8494 // add.4s	v20, v4, v15
	WORD $0xad01d3e2 // stp	q2, q20, [sp, #0x30]
	WORD $0x4eac85ec // add.4s	v12, v15, v12
	WORD $0x4f352424 // srshr.4s	v4, v1, #0xb
	WORD $0x4f34364c // srsra.4s	v12, v18, #0xc
	WORD $0x6f030752 // mvni.4s	v18, #0x7a
	WORD $0x4eb29f72 // mul.4s	v18, v27, v18
	WORD $0x4ea59632 // mla.4s	v18, v17, v5
	WORD $0x4f34365b // srsra.4s	v27, v18, #0xc
	WORD $0x6eb48445 // sub.4s	v5, v2, v20
	WORD $0x4eb064a5 // smax.4s	v5, v5, v16
	WORD $0x4ea66ca5 // smin.4s	v5, v5, v6
	WORD $0x6eac8771 // sub.4s	v17, v27, v12
	WORD $0x4eb06631 // smax.4s	v17, v17, v16
	WORD $0x4ea66e31 // smin.4s	v17, v17, v6
	WORD $0x4eb79caf // mul.4s	v15, v5, v23
	WORD $0x4ea3962f // mla.4s	v15, v17, v3
	WORD $0x4f3527e3 // srshr.4s	v3, v31, #0xb
	WORD $0x6ea48724 // sub.4s	v4, v25, v4
	WORD $0x4eb06484 // smax.4s	v4, v4, v16
	WORD $0x4ea66c92 // smin.4s	v18, v4, v6
	WORD $0x6ea386a3 // sub.4s	v3, v21, v3
	WORD $0x4eb06463 // smax.4s	v3, v3, v16
	WORD $0x4ea66c63 // smin.4s	v3, v3, v6
	WORD $0x4eb89cb4 // mul.4s	v20, v5, v24
	WORD $0x4eb79634 // mla.4s	v20, v17, v23
	WORD $0x1280d4c8 // mov	w8, #-0x6a7             ; =-1703
	WORD $0x4e040d05 // dup.4s	v5, w8
	WORD $0x4ea59e4a // mul.4s	v10, v18, v5
	WORD $0x4eb8946a // mla.4s	v10, v3, v24
	WORD $0x4eb89e41 // mul.4s	v1, v18, v24
	WORD $0x4f0205e2 // movi.4s	v2, #0x4f
	WORD $0x4eb79461 // mla.4s	v1, v3, v23
	WORD $0x3d800be1 // str	q1, [sp, #0x20]
	WORD $0x52800388 // mov	w8, #0x1c               ; =28
	WORD $0x9b087c34 // mul	x20, x1, x8
	WORD $0x3cf46803 // ldr	q3, [x0, x20]
	WORD $0x4ea2947a // mla.4s	v26, v3, v2
	WORD $0x4f342757 // srshr.4s	v23, v26, #0xc
	WORD $0x6ea386f8 // sub.4s	v24, v23, v3
	WORD $0x6f0205c1 // mvni.4s	v1, #0x4e
	WORD $0x4ea19d3a // mul.4s	v26, v9, v1
	WORD $0x4ea0947a // mla.4s	v26, v3, v0
	WORD $0x4eb064e3 // smax.4s	v3, v7, v16
	WORD $0x4ea66c62 // smin.4s	v2, v3, v6
	WORD $0x4eb06783 // smax.4s	v3, v28, v16
	WORD $0x4ea66c63 // smin.4s	v3, v3, v6
	WORD $0x4eb067c7 // smax.4s	v7, v30, v16
	WORD $0x4ea66ce7 // smin.4s	v7, v7, v6
	WORD $0x4eb0651c // smax.4s	v28, v8, v16
	WORD $0x4ea66f9c // smin.4s	v28, v28, v6
	WORD $0x4f343749 // srsra.4s	v9, v26, #0xc
	WORD $0x4f35267a // srshr.4s	v26, v19, #0xb
	WORD $0x6eba871a // sub.4s	v26, v24, v26
	WORD $0x4f353678 // srsra.4s	v24, v19, #0xb
	WORD $0x4f3526d3 // srshr.4s	v19, v22, #0xb
	WORD $0x4eb06718 // smax.4s	v24, v24, v16
	WORD $0x4ea66f1e // smin.4s	v30, v24, v6
	WORD $0x4eb06758 // smax.4s	v24, v26, v16
	WORD $0x4ea66f18 // smin.4s	v24, v24, v6
	WORD $0x6eb38533 // sub.4s	v19, v9, v19
	WORD $0x4f3536c9 // srsra.4s	v9, v22, #0xb
	WORD $0x4eb06536 // smax.4s	v22, v9, v16
	WORD $0x4ea66eda // smin.4s	v26, v22, v6
	WORD $0x4eb06673 // smax.4s	v19, v19, v16
	WORD $0x4ea66e73 // smin.4s	v19, v19, v6
	WORD $0x6eb88676 // sub.4s	v22, v19, v24
	WORD $0x4f0506a0 // movi.4s	v0, #0xb5
	WORD $0x4ea09ec9 // mul.4s	v9, v22, v0
	WORD $0x4eb88673 // add.4s	v19, v19, v24
	WORD $0x4ea09e73 // mul.4s	v19, v19, v0
	WORD $0x4f0506b1 // movi.4s	v17, #0xb5
	WORD $0x4f382676 // srshr.4s	v22, v19, #0x8
	WORD $0x6eb68476 // sub.4s	v22, v3, v22
	WORD $0x4ea31c78 // mov.16b	v24, v3
	WORD $0x4f383678 // srsra.4s	v24, v19, #0x8
	WORD $0x4f382523 // srshr.4s	v3, v9, #0x8
	WORD $0x6ea384e8 // sub.4s	v8, v7, v3
	WORD $0x4f383527 // srsra.4s	v7, v9, #0x8
	WORD $0x4ebc87d2 // add.4s	v18, v30, v28
	WORD $0x6ebe8789 // sub.4s	v9, v28, v30
	WORD $0x4ea2875c // add.4s	v28, v26, v2
	WORD $0x6eba845e // sub.4s	v30, v2, v26
	WORD $0x3cf36813 // ldr	q19, [x0, x19]
	WORD $0x528003c8 // mov	w8, #0x1e               ; =30
	WORD $0x9b087c35 // mul	x21, x1, x8
	WORD $0x52803228 // mov	w8, #0x191              ; =401
	WORD $0x3cf56802 // ldr	q2, [x0, x21]
	WORD $0x4e040d1a // dup.4s	v26, w8
	WORD $0x4eba9e60 // mul.4s	v0, v19, v26
	WORD $0x4f000697 // movi.4s	v23, #0x14
	WORD $0x4eb79440 // mla.4s	v0, v2, v23
	WORD $0x6f000677 // mvni.4s	v23, #0x13
	WORD $0x4eb79e77 // mul.4s	v23, v19, v23
	WORD $0x4eba9457 // mla.4s	v23, v2, v26
	WORD $0x4f342400 // srshr.4s	v0, v0, #0xc
	WORD $0x6ea28405 // sub.4s	v5, v0, v2
	WORD $0x52800148 // mov	w8, #0xa                ; =10
	WORD $0x9b087c38 // mul	x24, x1, x8
	WORD $0x528002c8 // mov	w8, #0x16               ; =22
	WORD $0x9b087c36 // mul	x22, x1, x8
	WORD $0x5280f168 // mov	w8, #0x78b              ; =1931
	WORD $0x3cf86801 // ldr	q1, [x0, x24]
	WORD $0x3cf6681a // ldr	q26, [x0, x22]
	WORD $0x4e040d02 // dup.4s	v2, w8
	WORD $0x52803c88 // mov	w8, #0x1e4              ; =484
	WORD $0x4ea29c20 // mul.4s	v0, v1, v2
	WORD $0x4e040d1d // dup.4s	v29, w8
	WORD $0x4ebd9740 // mla.4s	v0, v26, v29
	WORD $0x12803c68 // mov	w8, #-0x1e4             ; =-484
	WORD $0x4e040d1d // dup.4s	v29, w8
	WORD $0x4ebd9c3d // mul.4s	v29, v1, v29
	WORD $0x4ea2975d // mla.4s	v29, v26, v2
	WORD $0x4f342400 // srshr.4s	v0, v0, #0xc
	WORD $0x6eba8403 // sub.4s	v3, v0, v26
	WORD $0x528000c8 // mov	w8, #0x6                ; =6
	WORD $0x9b087c39 // mul	x25, x1, x8
	WORD $0x52800348 // mov	w8, #0x1a               ; =26
	WORD $0x9b087c37 // mul	x23, x1, x8
	WORD $0x3cf96802 // ldr	q2, [x0, x25]
	WORD $0x12809488 // mov	w8, #-0x4a5             ; =-1189
	WORD $0x4e040d1a // dup.4s	v26, w8
	WORD $0x4eba9c5a // mul.4s	v26, v2, v26
	WORD $0x3cf76800 // ldr	q0, [x0, x23]
	WORD $0x6f0505e4 // mvni.4s	v4, #0xaf
	WORD $0x4ea4941a // mla.4s	v26, v0, v4
	WORD $0x528094a8 // mov	w8, #0x4a5              ; =1189
	WORD $0x4ea49c44 // mul.4s	v4, v2, v4
	WORD $0x4e040d0d // dup.4s	v13, w8
	WORD $0x4ead9404 // mla.4s	v4, v0, v13
	WORD $0x4f343740 // srsra.4s	v0, v26, #0xc
	WORD $0x4f343482 // srsra.4s	v2, v4, #0xc
	WORD $0x4f3437a1 // srsra.4s	v1, v29, #0xc
	WORD $0x4f3436f3 // srsra.4s	v19, v23, #0xc
	WORD $0x3dc03ff7 // ldr	q23, [sp, #0xf0]
	WORD $0x4f3526e4 // srshr.4s	v4, v23, #0xb
	WORD $0x6ea484a4 // sub.4s	v4, v5, v4
	WORD $0x4f3536e5 // srsra.4s	v5, v23, #0xb
	WORD $0x6ea38417 // sub.4s	v23, v0, v3
	WORD $0x4ea38403 // add.4s	v3, v0, v3
	WORD $0x4ea2843a // add.4s	v26, v1, v2
	WORD $0x6ea18440 // sub.4s	v0, v2, v1
	WORD $0x3dc03be2 // ldr	q2, [sp, #0xe0]
	WORD $0x4f352441 // srshr.4s	v1, v2, #0xb
	WORD $0x6ea18661 // sub.4s	v1, v19, v1
	WORD $0x4f353453 // srsra.4s	v19, v2, #0xb
	WORD $0x4eb06482 // smax.4s	v2, v4, v16
	WORD $0x4ea66c42 // smin.4s	v2, v2, v6
	WORD $0x4eb06421 // smax.4s	v1, v1, v16
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x4eae9c44 // mul.4s	v4, v2, v14
	WORD $0x4eab9424 // mla.4s	v4, v1, v11
	WORD $0x4f342484 // srshr.4s	v4, v4, #0xc
	WORD $0x6ea28484 // sub.4s	v4, v4, v2
	WORD $0x4eab9c42 // mul.4s	v2, v2, v11
	WORD $0x3dc04ffd // ldr	q29, [sp, #0x130]
	WORD $0x4ebd9422 // mla.4s	v2, v1, v29
	WORD $0x4f343441 // srsra.4s	v1, v2, #0xc
	WORD $0x4eb066e2 // smax.4s	v2, v23, v16
	WORD $0x4ea66c42 // smin.4s	v2, v2, v6
	WORD $0x4eb06400 // smax.4s	v0, v0, v16
	WORD $0x4ea66c17 // smin.4s	v23, v0, v6
	WORD $0x1280c3c8 // mov	w8, #-0x61f             ; =-1567
	WORD $0x4e040d00 // dup.4s	v0, w8
	WORD $0x4ea09c5d // mul.4s	v29, v2, v0
	WORD $0x4eae96fd // mla.4s	v29, v23, v14
	WORD $0x4f3427bd // srshr.4s	v29, v29, #0xc
	WORD $0x6eb787bd // sub.4s	v29, v29, v23
	WORD $0x4eae9c4d // mul.4s	v13, v2, v14
	WORD $0x4eab96ed // mla.4s	v13, v23, v11
	WORD $0x4f3425b7 // srshr.4s	v23, v13, #0xc
	WORD $0x6ea286e2 // sub.4s	v2, v23, v2
	WORD $0x4ea487b7 // add.4s	v23, v29, v4
	WORD $0x6ebd8484 // sub.4s	v4, v4, v29
	WORD $0x4eb064a5 // smax.4s	v5, v5, v16
	WORD $0x4ea66ca5 // smin.4s	v5, v5, v6
	WORD $0x4eb06463 // smax.4s	v3, v3, v16
	WORD $0x4ea66c63 // smin.4s	v3, v3, v6
	WORD $0x4ea5847d // add.4s	v29, v3, v5
	WORD $0x6ea384a3 // sub.4s	v3, v5, v3
	WORD $0x6ea28425 // sub.4s	v5, v1, v2
	WORD $0x4ea18442 // add.4s	v2, v2, v1
	WORD $0x4eb06741 // smax.4s	v1, v26, v16
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x4eb06673 // smax.4s	v19, v19, v16
	WORD $0x4ea66e73 // smin.4s	v19, v19, v6
	WORD $0x6ea1867a // sub.4s	v26, v19, v1
	WORD $0x4ea18673 // add.4s	v19, v19, v1
	WORD $0x4eb06481 // smax.4s	v1, v4, v16
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x4eb064a4 // smax.4s	v4, v5, v16
	WORD $0x4ea66c84 // smin.4s	v4, v4, v6
	WORD $0x6ea18485 // sub.4s	v5, v4, v1
	WORD $0x4ea18481 // add.4s	v1, v4, v1
	WORD $0x4eb06463 // smax.4s	v3, v3, v16
	WORD $0x4ea66c63 // smin.4s	v3, v3, v6
	WORD $0x4eb06744 // smax.4s	v4, v26, v16
	WORD $0x4ea66c84 // smin.4s	v4, v4, v6
	WORD $0x6ea3849a // sub.4s	v26, v4, v3
	WORD $0x4ea38483 // add.4s	v3, v4, v3
	WORD $0x4eb064e4 // smax.4s	v4, v7, v16
	WORD $0x4ea66c84 // smin.4s	v4, v4, v6
	WORD $0x4eb19c21 // mul.4s	v1, v1, v17
	WORD $0x4f382427 // srshr.4s	v7, v1, #0x8
	WORD $0x6ea78487 // sub.4s	v7, v4, v7
	WORD $0x4f383424 // srsra.4s	v4, v1, #0x8
	WORD $0x3d803fe4 // str	q4, [sp, #0xf0]
	WORD $0x4eb06641 // smax.4s	v1, v18, v16
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x4eb19c63 // mul.4s	v3, v3, v17
	WORD $0x4f382464 // srshr.4s	v4, v3, #0x8
	WORD $0x6ea48424 // sub.4s	v4, v1, v4
	WORD $0xad059fe4 // stp	q4, q7, [sp, #0xb0]
	WORD $0x4f383461 // srsra.4s	v1, v3, #0x8
	WORD $0x3d8037e1 // str	q1, [sp, #0xd0]
	WORD $0x4eb06521 // smax.4s	v1, v9, v16
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x4eb19f43 // mul.4s	v3, v26, v17
	WORD $0x4f382464 // srshr.4s	v4, v3, #0x8
	WORD $0x6ea48427 // sub.4s	v7, v1, v4
	WORD $0x4f383461 // srsra.4s	v1, v3, #0x8
	WORD $0x4eb06503 // smax.4s	v3, v8, v16
	WORD $0x4ea66c68 // smin.4s	v8, v3, v6
	WORD $0x4eb19ca3 // mul.4s	v3, v5, v17
	WORD $0x4f382464 // srshr.4s	v4, v3, #0x8
	WORD $0x6ea48504 // sub.4s	v4, v8, v4
	WORD $0xad041fe4 // stp	q4, q7, [sp, #0x80]
	WORD $0x4f383468 // srsra.4s	v8, v3, #0x8
	WORD $0x4eb067c3 // smax.4s	v3, v30, v16
	WORD $0x4ea66c63 // smin.4s	v3, v3, v6
	WORD $0x4eb067a4 // smax.4s	v4, v29, v16
	WORD $0x4ea66c84 // smin.4s	v4, v4, v6
	WORD $0x4ea3849e // add.4s	v30, v4, v3
	WORD $0x6ea48465 // sub.4s	v5, v3, v4
	WORD $0x4eb066c3 // smax.4s	v3, v22, v16
	WORD $0x4ea66c63 // smin.4s	v3, v3, v6
	WORD $0x4eb066e4 // smax.4s	v4, v23, v16
	WORD $0x4ea66c84 // smin.4s	v4, v4, v6
	WORD $0x4ea38489 // add.4s	v9, v4, v3
	WORD $0x6ea48476 // sub.4s	v22, v3, v4
	WORD $0x4eb06703 // smax.4s	v3, v24, v16
	WORD $0x4ea66c63 // smin.4s	v3, v3, v6
	WORD $0x4eb06442 // smax.4s	v2, v2, v16
	WORD $0x4ea66c42 // smin.4s	v2, v2, v6
	WORD $0x4ea38444 // add.4s	v4, v2, v3
	WORD $0x3d803be4 // str	q4, [sp, #0xe0]
	WORD $0x6ea28462 // sub.4s	v2, v3, v2
	WORD $0xad030be5 // stp	q5, q2, [sp, #0x60]
	WORD $0xd37be83a // lsl	x26, x1, #5
	WORD $0xcb01001b // sub	x27, x0, x1
	WORD $0x4eb06782 // smax.4s	v2, v28, v16
	WORD $0x4ea66c42 // smin.4s	v2, v2, v6
	WORD $0x4eb06663 // smax.4s	v3, v19, v16
	WORD $0x4ea66c63 // smin.4s	v3, v3, v6
	WORD $0x3ce16813 // ldr	q19, [x0, x1]
	WORD $0x3cfa6b64 // ldr	q4, [x27, x26]
	WORD $0x4ea28465 // add.4s	v5, v3, v2
	WORD $0x3d802be5 // str	q5, [sp, #0xa0]
	WORD $0x6ea3845a // sub.4s	v26, v2, v3
	WORD $0x4f060522 // movi.4s	v2, #0xc9
	WORD $0x4ea29e63 // mul.4s	v3, v19, v2
	WORD $0x4f0004a5 // movi.4s	v5, #0x5
	WORD $0x4ea59483 // mla.4s	v3, v4, v5
	WORD $0x6f000485 // mvni.4s	v5, #0x4
	WORD $0x4ea59e65 // mul.4s	v5, v19, v5
	WORD $0x4ea29485 // mla.4s	v5, v4, v2
	WORD $0x4f342462 // srshr.4s	v2, v3, #0xc
	WORD $0x6ea48442 // sub.4s	v2, v2, v4
	WORD $0x8b0101ed // add	x13, x15, x1
	WORD $0x528002e8 // mov	w8, #0x17               ; =23
	WORD $0x9b087c3e // mul	x30, x1, x8
	WORD $0x5280dae8 // mov	w8, #0x6d7              ; =1751
	WORD $0x3ced6803 // ldr	q3, [x0, x13]
	WORD $0x3cfe6804 // ldr	q4, [x0, x30]
	WORD $0x52803129 // mov	w9, #0x189              ; =393
	WORD $0x4e040d07 // dup.4s	v7, w8
	WORD $0x4ea79c71 // mul.4s	v17, v3, v7
	WORD $0x4e040d37 // dup.4s	v23, w9
	WORD $0x4eb79491 // mla.4s	v17, v4, v23
	WORD $0x12803108 // mov	w8, #-0x189             ; =-393
	WORD $0x4e040d17 // dup.4s	v23, w8
	WORD $0x4eb79c77 // mul.4s	v23, v3, v23
	WORD $0x4ea79497 // mla.4s	v23, v4, v7
	WORD $0x4f342627 // srshr.4s	v7, v17, #0xc
	WORD $0x6ea484e4 // sub.4s	v4, v7, v4
	WORD $0x52800328 // mov	w8, #0x19               ; =25
	WORD $0x9b087c2e // mul	x14, x1, x8
	WORD $0xcb0101ea // sub	x10, x15, x1
	WORD $0x1280ac69 // mov	w9, #-0x564             ; =-1380
	WORD $0x3cea6807 // ldr	q7, [x0, x10]
	WORD $0x3cee6811 // ldr	q17, [x0, x14]
	WORD $0x4e040d3c // dup.4s	v28, w9
	WORD $0x4ebc9cfc // mul.4s	v28, v7, v28
	WORD $0x6f0705dd // mvni.4s	v29, #0xee
	WORD $0x4ebd963c // mla.4s	v28, v17, v29
	WORD $0x5280ac89 // mov	w9, #0x564              ; =1380
	WORD $0x4e040d2d // dup.4s	v13, w9
	WORD $0x4ebd9cfd // mul.4s	v29, v7, v29
	WORD $0x4ead963d // mla.4s	v29, v17, v13
	WORD $0x4f343791 // srsra.4s	v17, v28, #0xc
	WORD $0x4f3437a7 // srsra.4s	v7, v29, #0xc
	WORD $0x4f3436e3 // srsra.4s	v3, v23, #0xc
	WORD $0xcb01020b // sub	x11, x16, x1
	WORD $0x8b01020c // add	x12, x16, x1
	WORD $0x12808488 // mov	w8, #-0x425             ; =-1061
	WORD $0x5280a829 // mov	w9, #0x541              ; =1345
	WORD $0x4e040d17 // dup.4s	v23, w8
	WORD $0x3ceb681c // ldr	q28, [x0, x11]
	WORD $0x3cec681d // ldr	q29, [x0, x12]
	WORD $0x4e040d2d // dup.4s	v13, w9
	WORD $0x4ead9f8d // mul.4s	v13, v28, v13
	WORD $0x4eb797ad // mla.4s	v13, v29, v23
	WORD $0x4eb79f97 // mul.4s	v23, v28, v23
	WORD $0x1280a808 // mov	w8, #-0x541             ; =-1345
	WORD $0x4e040d18 // dup.4s	v24, w8
	WORD $0x4eb897b7 // mla.4s	v23, v29, v24
	WORD $0x4f3425b8 // srshr.4s	v24, v13, #0xc
	WORD $0x6ebc8718 // sub.4s	v24, v24, v28
	WORD $0x4ebd8718 // add.4s	v24, v24, v29
	WORD $0x4ebc87bc // add.4s	v28, v29, v28
	WORD $0x4f3436fc // srsra.4s	v28, v23, #0xc
	WORD $0x4f3434b3 // srsra.4s	v19, v5, #0xc
	WORD $0x4ea28705 // add.4s	v5, v24, v2
	WORD $0x6eb88457 // sub.4s	v23, v2, v24
	WORD $0x6ea48638 // sub.4s	v24, v17, v4
	WORD $0x4ea48624 // add.4s	v4, v17, v4
	WORD $0xad418bf1 // ldp	q17, q2, [sp, #0x30]
	WORD $0x4eb18451 // add.4s	v17, v2, v17
	WORD $0x3dc017e2 // ldr	q2, [sp, #0x50]
	WORD $0x4f353459 // srsra.4s	v25, v2, #0xb
	WORD $0x4f3537f5 // srsra.4s	v21, v31, #0xb
	WORD $0x4eac876c // add.4s	v12, v27, v12
	WORD $0x4ea78462 // add.4s	v2, v3, v7
	WORD $0x6ea384e3 // sub.4s	v3, v7, v3
	WORD $0x6ebc8667 // sub.4s	v7, v19, v28
	WORD $0x4ebc867d // add.4s	v29, v19, v28
	WORD $0x4eb066f3 // smax.4s	v19, v23, v16
	WORD $0x4ea66e73 // smin.4s	v19, v19, v6
	WORD $0x4eb064e7 // smax.4s	v7, v7, v16
	WORD $0x4ea66cff // smin.4s	v31, v7, v6
	WORD $0x4f0205f2 // movi.4s	v18, #0x4f
	WORD $0x4eb29e67 // mul.4s	v7, v19, v18
	WORD $0x3dc007fb // ldr	q27, [sp, #0x10]
	WORD $0x4ebb97e7 // mla.4s	v7, v31, v27
	WORD $0x4f3424e7 // srshr.4s	v7, v7, #0xc
	WORD $0x6eb384e7 // sub.4s	v7, v7, v19
	WORD $0x4ebb9e73 // mul.4s	v19, v19, v27
	WORD $0x6f0205d7 // mvni.4s	v23, #0x4e
	WORD $0x4eb797f3 // mla.4s	v19, v31, v23
	WORD $0x4f34367f // srsra.4s	v31, v19, #0xc
	WORD $0x4eb06713 // smax.4s	v19, v24, v16
	WORD $0x4ea66e73 // smin.4s	v19, v19, v6
	WORD $0x4eb06463 // smax.4s	v3, v3, v16
	WORD $0x128063c8 // mov	w8, #-0x31f             ; =-799
	WORD $0x4e040d17 // dup.4s	v23, w8
	WORD $0x4ea66c63 // smin.4s	v3, v3, v6
	WORD $0x4eb79e77 // mul.4s	v23, v19, v23
	WORD $0x4eb29477 // mla.4s	v23, v3, v18
	WORD $0x4eb29e72 // mul.4s	v18, v19, v18
	WORD $0x4ebb9472 // mla.4s	v18, v3, v27
	WORD $0x4f3426f7 // srshr.4s	v23, v23, #0xc
	WORD $0x6ea386e3 // sub.4s	v3, v23, v3
	WORD $0x4f342652 // srshr.4s	v18, v18, #0xc
	WORD $0x6eb3865c // sub.4s	v28, v18, v19
	WORD $0x4ea7847b // add.4s	v27, v3, v7
	WORD $0x6ea384ed // sub.4s	v13, v7, v3
	WORD $0x4eb064a3 // smax.4s	v3, v5, v16
	WORD $0x4ea66c63 // smin.4s	v3, v3, v6
	WORD $0x4eb06484 // smax.4s	v4, v4, v16
	WORD $0x4ea66c84 // smin.4s	v4, v4, v6
	WORD $0x4ea38497 // add.4s	v23, v4, v3
	WORD $0x6ea48473 // sub.4s	v19, v3, v4
	WORD $0x4f352545 // srshr.4s	v5, v10, #0xb
	WORD $0x4f352683 // srshr.4s	v3, v20, #0xb
	WORD $0x6ea384aa // sub.4s	v10, v5, v3
	WORD $0x4f353685 // srsra.4s	v5, v20, #0xb
	WORD $0x4eb06623 // smax.4s	v3, v17, v16
	WORD $0x4ea66c63 // smin.4s	v3, v3, v6
	WORD $0x4eb06724 // smax.4s	v4, v25, v16
	WORD $0x4ea66c87 // smin.4s	v7, v4, v6
	WORD $0x6ea384e4 // sub.4s	v4, v7, v3
	WORD $0x4ea384f2 // add.4s	v18, v7, v3
	WORD $0x3dc00be3 // ldr	q3, [sp, #0x20]
	WORD $0x4f352471 // srshr.4s	v17, v3, #0xb
	WORD $0x4f3525e3 // srshr.4s	v3, v15, #0xb
	WORD $0x6ea38623 // sub.4s	v3, v17, v3
	WORD $0x4f3535f1 // srsra.4s	v17, v15, #0xb
	WORD $0x4eb066a7 // smax.4s	v7, v21, v16
	WORD $0x4ea66ce7 // smin.4s	v7, v7, v6
	WORD $0x4eb06594 // smax.4s	v20, v12, v16
	WORD $0x4ea66e94 // smin.4s	v20, v20, v6
	WORD $0x4ea78699 // add.4s	v25, v20, v7
	WORD $0x6eb484e7 // sub.4s	v7, v7, v20
	WORD $0x6ebc87f4 // sub.4s	v20, v31, v28
	WORD $0x4ebf879c // add.4s	v28, v28, v31
	WORD $0x4eb06442 // smax.4s	v2, v2, v16
	WORD $0x4ea66c42 // smin.4s	v2, v2, v6
	WORD $0x4eb067b5 // smax.4s	v21, v29, v16
	WORD $0x4ea66eb5 // smin.4s	v21, v21, v6
	WORD $0x6ea286b8 // sub.4s	v24, v21, v2
	WORD $0x4ea286bd // add.4s	v29, v21, v2
	WORD $0x4eb065a2 // smax.4s	v2, v13, v16
	WORD $0x4ea66c55 // smin.4s	v21, v2, v6
	WORD $0x4eb06682 // smax.4s	v2, v20, v16
	WORD $0x4ea66c5f // smin.4s	v31, v2, v6
	WORD $0x4eae9ea2 // mul.4s	v2, v21, v14
	WORD $0x4eab97e2 // mla.4s	v2, v31, v11
	WORD $0x4f342442 // srshr.4s	v2, v2, #0xc
	WORD $0x6eb58442 // sub.4s	v2, v2, v21
	WORD $0x4eab9eb4 // mul.4s	v20, v21, v11
	WORD $0x3dc04ff5 // ldr	q21, [sp, #0x130]
	WORD $0x4eb597f4 // mla.4s	v20, v31, v21
	WORD $0x4f34369f // srsra.4s	v31, v20, #0xc
	WORD $0x4eb06673 // smax.4s	v19, v19, v16
	WORD $0x4ea66e73 // smin.4s	v19, v19, v6
	WORD $0x4eb06714 // smax.4s	v20, v24, v16
	WORD $0x4ea66e8c // smin.4s	v12, v20, v6
	WORD $0x4eae9e74 // mul.4s	v20, v19, v14
	WORD $0x4eab9594 // mla.4s	v20, v12, v11
	WORD $0x4f342694 // srshr.4s	v20, v20, #0xc
	WORD $0x6eb38694 // sub.4s	v20, v20, v19
	WORD $0x4eab9e73 // mul.4s	v19, v19, v11
	WORD $0x4eb59593 // mla.4s	v19, v12, v21
	WORD $0x4f34366c // srsra.4s	v12, v19, #0xc
	WORD $0x4eb06484 // smax.4s	v4, v4, v16
	WORD $0x4ea66c84 // smin.4s	v4, v4, v6
	WORD $0x4eb064e7 // smax.4s	v7, v7, v16
	WORD $0x4ea66ce7 // smin.4s	v7, v7, v6
	WORD $0x4ea09c93 // mul.4s	v19, v4, v0
	WORD $0x4eae94f3 // mla.4s	v19, v7, v14
	WORD $0x4f342673 // srshr.4s	v19, v19, #0xc
	WORD $0x6ea78675 // sub.4s	v21, v19, v7
	WORD $0x4eae9c93 // mul.4s	v19, v4, v14
	WORD $0x4eab94f3 // mla.4s	v19, v7, v11
	WORD $0x4f342667 // srshr.4s	v7, v19, #0xc
	WORD $0x6ea484e4 // sub.4s	v4, v7, v4
	WORD $0x4eb06547 // smax.4s	v7, v10, v16
	WORD $0x4ea66ce7 // smin.4s	v7, v7, v6
	WORD $0x4eb06463 // smax.4s	v3, v3, v16
	WORD $0x4ea66c63 // smin.4s	v3, v3, v6
	WORD $0x4ea09ce0 // mul.4s	v0, v7, v0
	WORD $0x4eae9460 // mla.4s	v0, v3, v14
	WORD $0x4eae9cf3 // mul.4s	v19, v7, v14
	WORD $0x4eab9473 // mla.4s	v19, v3, v11
	WORD $0x4f342400 // srshr.4s	v0, v0, #0xc
	WORD $0x6ea38400 // sub.4s	v0, v0, v3
	WORD $0x4f342663 // srshr.4s	v3, v19, #0xc
	WORD $0x6ea78463 // sub.4s	v3, v3, v7
	WORD $0x4eb486b3 // add.4s	v19, v21, v20
	WORD $0x6eb58694 // sub.4s	v20, v20, v21
	WORD $0x4ea28407 // add.4s	v7, v0, v2
	WORD $0x6ea08458 // sub.4s	v24, v2, v0
	WORD $0x4eb06760 // smax.4s	v0, v27, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x4eb064a2 // smax.4s	v2, v5, v16
	WORD $0x4ea66c42 // smin.4s	v2, v2, v6
	WORD $0x4ea08445 // add.4s	v5, v2, v0
	WORD $0x6ea2841b // sub.4s	v27, v0, v2
	WORD $0x4eb066e0 // smax.4s	v0, v23, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x4eb06642 // smax.4s	v2, v18, v16
	WORD $0x4ea66c42 // smin.4s	v2, v2, v6
	WORD $0x4ea08455 // add.4s	v21, v2, v0
	WORD $0x6ea28402 // sub.4s	v2, v0, v2
	WORD $0x6ea48592 // sub.4s	v18, v12, v4
	WORD $0x4eac8480 // add.4s	v0, v4, v12
	WORD $0x6ea387f7 // sub.4s	v23, v31, v3
	WORD $0x4ebf8463 // add.4s	v3, v3, v31
	WORD $0x4eb06624 // smax.4s	v4, v17, v16
	WORD $0x4ea66c84 // smin.4s	v4, v4, v6
	WORD $0x4eb06791 // smax.4s	v17, v28, v16
	WORD $0x4ea66e31 // smin.4s	v17, v17, v6
	WORD $0x6ea4863c // sub.4s	v28, v17, v4
	WORD $0x4ea48624 // add.4s	v4, v17, v4
	WORD $0x3d804fe4 // str	q4, [sp, #0x130]
	WORD $0x4eb06731 // smax.4s	v17, v25, v16
	WORD $0x4ea66e31 // smin.4s	v17, v17, v6
	WORD $0x4eb067b9 // smax.4s	v25, v29, v16
	WORD $0x4ea66f39 // smin.4s	v25, v25, v6
	WORD $0x6eb1873d // sub.4s	v29, v25, v17
	WORD $0x4eb18724 // add.4s	v4, v25, v17
	WORD $0x4eb06694 // smax.4s	v20, v20, v16
	WORD $0x4ea66e94 // smin.4s	v20, v20, v6
	WORD $0x4eb06652 // smax.4s	v18, v18, v16
	WORD $0x4ea66e52 // smin.4s	v18, v18, v6
	WORD $0x6eb48659 // sub.4s	v25, v18, v20
	WORD $0x4eb48652 // add.4s	v18, v18, v20
	WORD $0x4eb06714 // smax.4s	v20, v24, v16
	WORD $0x4ea66e94 // smin.4s	v20, v20, v6
	WORD $0x4eb066f7 // smax.4s	v23, v23, v16
	WORD $0x4ea66ef7 // smin.4s	v23, v23, v6
	WORD $0x6eb486f8 // sub.4s	v24, v23, v20
	WORD $0x4eb486f4 // add.4s	v20, v23, v20
	WORD $0x4eb06777 // smax.4s	v23, v27, v16
	WORD $0x4ea66ef7 // smin.4s	v23, v23, v6
	WORD $0x4eb0679b // smax.4s	v27, v28, v16
	WORD $0x4ea66f7b // smin.4s	v27, v27, v6
	WORD $0x6eb7877f // sub.4s	v31, v27, v23
	WORD $0x4eb7877b // add.4s	v27, v27, v23
	WORD $0x4eb06442 // smax.4s	v2, v2, v16
	WORD $0x4ea66c42 // smin.4s	v2, v2, v6
	WORD $0x4eb067b7 // smax.4s	v23, v29, v16
	WORD $0x4ea66ef7 // smin.4s	v23, v23, v6
	WORD $0x6ea286ea // sub.4s	v10, v23, v2
	WORD $0x4ea286e2 // add.4s	v2, v23, v2
	WORD $0x4f0506b1 // movi.4s	v17, #0xb5
	WORD $0x4eb19f3c // mul.4s	v28, v25, v17
	WORD $0x4eb19e57 // mul.4s	v23, v18, v17
	WORD $0x4eb19f1d // mul.4s	v29, v24, v17
	WORD $0x4eb19e99 // mul.4s	v25, v20, v17
	WORD $0x4eb19fff // mul.4s	v31, v31, v17
	WORD $0x4eb19f7b // mul.4s	v27, v27, v17
	WORD $0x4eb19d4a // mul.4s	v10, v10, v17
	WORD $0x4eb19c4c // mul.4s	v12, v2, v17
	WORD $0x4eb06421 // smax.4s	v1, v1, v16
	WORD $0x4ea66c2b // smin.4s	v11, v1, v6
	WORD $0x4f3826f2 // srshr.4s	v18, v23, #0x8
	WORD $0x6eb28562 // sub.4s	v2, v11, v18
	WORD $0x4f3836eb // srsra.4s	v11, v23, #0x8
	WORD $0x4eb06501 // smax.4s	v1, v8, v16
	WORD $0x4ea66c28 // smin.4s	v8, v1, v6
	WORD $0x4f382721 // srshr.4s	v1, v25, #0x8
	WORD $0x6ea18501 // sub.4s	v1, v8, v1
	WORD $0xad020be1 // stp	q1, q2, [sp, #0x40]
	WORD $0x4f383728 // srsra.4s	v8, v25, #0x8
	WORD $0x4eb06521 // smax.4s	v1, v9, v16
	WORD $0x4ea66c29 // smin.4s	v9, v1, v6
	WORD $0x4f382761 // srshr.4s	v1, v27, #0x8
	WORD $0x6ea18521 // sub.4s	v1, v9, v1
	WORD $0x3d800fe1 // str	q1, [sp, #0x30]
	WORD $0x4f383769 // srsra.4s	v9, v27, #0x8
	WORD $0x4eb067c1 // smax.4s	v1, v30, v16
	WORD $0x4ea66c2d // smin.4s	v13, v1, v6
	WORD $0x4f382581 // srshr.4s	v1, v12, #0x8
	WORD $0x6ea185bb // sub.4s	v27, v13, v1
	WORD $0x4f38358d // srsra.4s	v13, v12, #0x8
	WORD $0x3dc01be1 // ldr	q1, [sp, #0x60]
	WORD $0x4eb06421 // smax.4s	v1, v1, v16
	WORD $0x4ea66c2c // smin.4s	v12, v1, v6
	WORD $0x4f382541 // srshr.4s	v1, v10, #0x8
	WORD $0x6ea18594 // sub.4s	v20, v12, v1
	WORD $0x4f38354c // srsra.4s	v12, v10, #0x8
	WORD $0x4eb066c1 // smax.4s	v1, v22, v16
	WORD $0x4ea66c2a // smin.4s	v10, v1, v6
	WORD $0x4f3827e1 // srshr.4s	v1, v31, #0x8
	WORD $0x6ea18556 // sub.4s	v22, v10, v1
	WORD $0x4f3837ea // srsra.4s	v10, v31, #0x8
	WORD $0x3dc023e1 // ldr	q1, [sp, #0x80]
	WORD $0x4eb06421 // smax.4s	v1, v1, v16
	WORD $0x4ea66c3f // smin.4s	v31, v1, v6
	WORD $0x4f3827a1 // srshr.4s	v1, v29, #0x8
	WORD $0x6ea187fe // sub.4s	v30, v31, v1
	WORD $0x4f3837bf // srsra.4s	v31, v29, #0x8
	WORD $0x3dc027e1 // ldr	q1, [sp, #0x90]
	WORD $0x4eb06421 // smax.4s	v1, v1, v16
	WORD $0x4ea66c2e // smin.4s	v14, v1, v6
	WORD $0x4f382781 // srshr.4s	v1, v28, #0x8
	WORD $0x6ea185dd // sub.4s	v29, v14, v1
	WORD $0x4f38378e // srsra.4s	v14, v28, #0x8
	WORD $0x4eb06741 // smax.4s	v1, v26, v16
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x4eb066a2 // smax.4s	v2, v21, v16
	WORD $0x4ea66c42 // smin.4s	v2, v2, v6
	WORD $0x4ea1845a // add.4s	v26, v2, v1
	WORD $0x6ea28435 // sub.4s	v21, v1, v2
	WORD $0x3dc01fe1 // ldr	q1, [sp, #0x70]
	WORD $0x4eb06421 // smax.4s	v1, v1, v16
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x4eb064a2 // smax.4s	v2, v5, v16
	WORD $0x4ea66c42 // smin.4s	v2, v2, v6
	WORD $0x4ea1844f // add.4s	v15, v2, v1
	WORD $0x6ea28425 // sub.4s	v5, v1, v2
	WORD $0x3dc033e1 // ldr	q1, [sp, #0xc0]
	WORD $0x4eb06421 // smax.4s	v1, v1, v16
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x4eb064e2 // smax.4s	v2, v7, v16
	WORD $0x4ea66c47 // smin.4s	v7, v2, v6
	WORD $0x4ea184e2 // add.4s	v2, v7, v1
	WORD $0x6ea78438 // sub.4s	v24, v1, v7
	WORD $0x3dc02fe1 // ldr	q1, [sp, #0xb0]
	WORD $0x4eb06421 // smax.4s	v1, v1, v16
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x4eb06667 // smax.4s	v7, v19, v16
	WORD $0x4ea66ce7 // smin.4s	v7, v7, v6
	WORD $0x4ea184f3 // add.4s	v19, v7, v1
	WORD $0x6ea7843c // sub.4s	v28, v1, v7
	WORD $0x3dc037e1 // ldr	q1, [sp, #0xd0]
	WORD $0x4eb06421 // smax.4s	v1, v1, v16
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x4eb06400 // smax.4s	v0, v0, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x4ea18407 // add.4s	v7, v0, v1
	WORD $0x6ea08431 // sub.4s	v17, v1, v0
	WORD $0x3dc03fe0 // ldr	q0, [sp, #0xf0]
	WORD $0x4eb06400 // smax.4s	v0, v0, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x4eb06463 // smax.4s	v3, v3, v16
	WORD $0x4ea66c63 // smin.4s	v3, v3, v6
	WORD $0x4ea08461 // add.4s	v1, v3, v0
	WORD $0x6ea38403 // sub.4s	v3, v0, v3
	WORD $0x3dc02be0 // ldr	q0, [sp, #0xa0]
	WORD $0x4eb06400 // smax.4s	v0, v0, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x4eb06484 // smax.4s	v4, v4, v16
	WORD $0x4ea66c84 // smin.4s	v4, v4, v6
	WORD $0x4ea08492 // add.4s	v18, v4, v0
	WORD $0x4eb06652 // smax.4s	v18, v18, v16
	WORD $0x4ea66e52 // smin.4s	v18, v18, v6
	WORD $0x3d800012 // str	q18, [x0]
	WORD $0x3dc03bf2 // ldr	q18, [sp, #0xe0]
	WORD $0x4eb06652 // smax.4s	v18, v18, v16
	WORD $0x4ea66e52 // smin.4s	v18, v18, v6
	WORD $0x3dc04ff7 // ldr	q23, [sp, #0x130]
	WORD $0x4eb066f7 // smax.4s	v23, v23, v16
	WORD $0x4ea66ef7 // smin.4s	v23, v23, v6
	WORD $0x4eb286f9 // add.4s	v25, v23, v18
	WORD $0x4eb06739 // smax.4s	v25, v25, v16
	WORD $0x4ea66f39 // smin.4s	v25, v25, v6
	WORD $0x3ca16819 // str	q25, [x0, x1]
	WORD $0x4eb06421 // smax.4s	v1, v1, v16
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x3cb36801 // str	q1, [x0, x19]
	WORD $0x4eb064e1 // smax.4s	v1, v7, v16
	WORD $0x4ea66c21 // smin.4s	v1, v1, v6
	WORD $0x3ca76801 // str	q1, [x0, x7]
	WORD $0x6eb78641 // sub.4s	v1, v18, v23
	WORD $0x6ea48404 // sub.4s	v4, v0, v4
	WORD $0x4eb06560 // smax.4s	v0, v11, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3ca36800 // str	q0, [x0, x3]
	WORD $0x4eb06500 // smax.4s	v0, v8, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3ca26800 // str	q0, [x0, x2]
	WORD $0x4eb06520 // smax.4s	v0, v9, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cb96800 // str	q0, [x0, x25]
	WORD $0x4eb065a0 // smax.4s	v0, v13, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3caa6800 // str	q0, [x0, x10]
	WORD $0x4eb06580 // smax.4s	v0, v12, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3caf6800 // str	q0, [x0, x15]
	WORD $0x4eb06540 // smax.4s	v0, v10, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cad6800 // str	q0, [x0, x13]
	WORD $0x4eb067e0 // smax.4s	v0, v31, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cb86800 // str	q0, [x0, x24]
	WORD $0x4eb065c0 // smax.4s	v0, v14, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3ca66800 // str	q0, [x0, x6]
	WORD $0x4eb06660 // smax.4s	v0, v19, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0xf94093e8 // ldr	x8, [sp, #0x120]
	WORD $0x3ca86800 // str	q0, [x0, x8]
	WORD $0x4eb06440 // smax.4s	v0, v2, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3ca46800 // str	q0, [x0, x4]
	WORD $0x4eb065e0 // smax.4s	v0, v15, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0xa95123e9 // ldp	x9, x8, [sp, #0x110]
	WORD $0x3ca96800 // str	q0, [x0, x9]
	WORD $0x4eb06740 // smax.4s	v0, v26, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cab6800 // str	q0, [x0, x11]
	WORD $0x4eb066a0 // smax.4s	v0, v21, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cb06800 // str	q0, [x0, x16]
	WORD $0x4eb064a0 // smax.4s	v0, v5, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cac6800 // str	q0, [x0, x12]
	WORD $0x4eb06700 // smax.4s	v0, v24, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3ca86800 // str	q0, [x0, x8]
	WORD $0x4eb06780 // smax.4s	v0, v28, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cb16800 // str	q0, [x0, x17]
	WORD $0x4eb067a0 // smax.4s	v0, v29, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0xf94097e8 // ldr	x8, [sp, #0x128]
	WORD $0x3ca86800 // str	q0, [x0, x8]
	WORD $0x4eb067c0 // smax.4s	v0, v30, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3ca56800 // str	q0, [x0, x5]
	WORD $0x4eb066c0 // smax.4s	v0, v22, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cb66800 // str	q0, [x0, x22]
	WORD $0x4eb06680 // smax.4s	v0, v20, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cbe6800 // str	q0, [x0, x30]
	WORD $0x4eb06760 // smax.4s	v0, v27, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0xf940c7e8 // ldr	x8, [sp, #0x188]
	WORD $0x3ca86800 // str	q0, [x0, x8]
	WORD $0x3dc00fe0 // ldr	q0, [sp, #0x30]
	WORD $0x4eb06400 // smax.4s	v0, v0, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cae6800 // str	q0, [x0, x14]
	WORD $0x3dc013e0 // ldr	q0, [sp, #0x40]
	WORD $0x4eb06400 // smax.4s	v0, v0, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cb76800 // str	q0, [x0, x23]
	WORD $0x3dc017e0 // ldr	q0, [sp, #0x50]
	WORD $0x4eb06400 // smax.4s	v0, v0, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0xa95027e8 // ldp	x8, x9, [sp, #0x100]
	WORD $0x3ca96800 // str	q0, [x0, x9]
	WORD $0x4eb06620 // smax.4s	v0, v17, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cb46800 // str	q0, [x0, x20]
	WORD $0x4eb06460 // smax.4s	v0, v3, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3ca86800 // str	q0, [x0, x8]
	WORD $0x4eb06420 // smax.4s	v0, v1, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cb56800 // str	q0, [x0, x21]
	WORD $0x4eb06480 // smax.4s	v0, v4, v16
	WORD $0x4ea66c00 // smin.4s	v0, v0, v6
	WORD $0x3cba6b60 // str	q0, [x27, x26]
	WORD $0xa95d7bfd // ldp	x29, x30, [sp, #0x1d0]
	WORD $0xa95c4ff4 // ldp	x20, x19, [sp, #0x1c0]
	WORD $0xa95b57f6 // ldp	x22, x21, [sp, #0x1b0]
	WORD $0xa95a5ff8 // ldp	x24, x23, [sp, #0x1a0]
	WORD $0xa95967fa // ldp	x26, x25, [sp, #0x190]
	WORD $0xf940c3fb // ldr	x27, [sp, #0x180]
	WORD $0x6d5723e9 // ldp	d9, d8, [sp, #0x170]
	WORD $0x6d562beb // ldp	d11, d10, [sp, #0x160]
	WORD $0x6d5533ed // ldp	d13, d12, [sp, #0x150]
	WORD $0x6d543bef // ldp	d15, d14, [sp, #0x140]
	WORD $0x910783ff // add	sp, sp, #0x1e0
	WORD $0xd65f03c0 // ret
