// NEON-accelerated inverse DCT32 four-row kernel.
//
// Four adjacent stride-1 rows are transposed in 4x4 blocks (trn1/trn2 + zip)
// so coefficient index i of the four rows shares the four int32 lanes of one
// .4s register, then the same int32-lane butterfly as the four-column kernel
// runs: dav1d's high-bitdepth inverse transform shape (dav1d
// src/arm/64/itx16.S: inv_dct_4s_x16_neon with its transpose_4x4s load), with
// mul/mla/mls .4s multiplies, srshr rounding and smax+smin stage clamps.
// Working in int32 lanes without widening is exact because the row-pass
// inputs are pre-clamped to the stage range (|v| <= 2^19 across all supported
// bit depths) and the (cospi-4096)-rewritten butterflies keep the multiply
// accumulator below 2^31; the adapter enforces the clamp-bound precondition
// and falls back otherwise. Bit-for-bit identical to inverseDCT32Row run on
// each row (asserted by the row dispatch differential tests).
//
// The body is generated by transliterating the pure-Go butterfly to NEON
// intrinsics, compiling with the system C compiler at -O2 and transcribing
// the disassembly verbatim as WORD-encoded opcodes. Pure straight-line leaf
// code with a 704-byte manual spill frame below the (empty) Go frame, inside
// the nosplit stack budget.
//
// SPDX-License-Identifier: BSD-2-Clause
//
// See LICENSE for the BSD-2-Clause grant and NOTICE for the AOM attribution.

//go:build arm64 && !purego

#include "textflag.h"

// func inverseDCT32Row4NEON(r0, r1, r2, r3 *int32, min, max int64)
// Transforms four stride-1 rows (each >= 32 int32) in place. Row k occupies
// int32 lane k. Bit-for-bit identical to inverseDCT32Row run on each row.
TEXT ·inverseDCT32Row4NEON(SB), NOSPLIT, $0-48
	MOVD r0+0(FP), R0
	MOVD r1+8(FP), R1
	MOVD r2+16(FP), R2
	MOVD r3+24(FP), R3
	MOVD min+32(FP), R4
	MOVD max+40(FP), R5
	WORD $0x6dbb3bef // stp	d15, d14, [sp, #-0x50]!
	WORD $0x6d0133ed // stp	d13, d12, [sp, #0x10]
	WORD $0x6d022beb // stp	d11, d10, [sp, #0x20]
	WORD $0x6d0323e9 // stp	d9, d8, [sp, #0x30]
	WORD $0xa9046ffc // stp	x28, x27, [sp, #0x40]
	WORD $0xd109c3ff // sub	sp, sp, #0x270
	WORD $0x3dc00401 // ldr	q1, [x0, #0x10]
	WORD $0x3dc00420 // ldr	q0, [x1, #0x10]
	WORD $0xad0d03e1 // stp	q1, q0, [sp, #0x1a0]
	WORD $0x4e806831 // trn2.4s	v17, v1, v0
	WORD $0x3dc00440 // ldr	q0, [x2, #0x10]
	WORD $0xad1183f1 // stp	q17, q0, [sp, #0x230]
	WORD $0x3dc00461 // ldr	q1, [x3, #0x10]
	WORD $0x3d8097e1 // str	q1, [sp, #0x250]
	WORD $0x4e816801 // trn2.4s	v1, v0, v1
	WORD $0x3d808be1 // str	q1, [sp, #0x220]
	WORD $0x6e180431 // mov.d	v17[1], v1[0]
	WORD $0x3dc00c00 // ldr	q0, [x0, #0x30]
	WORD $0x3dc00c21 // ldr	q1, [x1, #0x30]
	WORD $0x4e812802 // trn1.4s	v2, v0, v1
	WORD $0x4e816804 // trn2.4s	v4, v0, v1
	WORD $0x3dc00c40 // ldr	q0, [x2, #0x30]
	WORD $0xad419c61 // ldp	q1, q7, [x3, #0x30]
	WORD $0x4e812803 // trn1.4s	v3, v0, v1
	WORD $0x4e816806 // trn2.4s	v6, v0, v1
	WORD $0xad1013e6 // stp	q6, q4, [sp, #0x200]
	WORD $0x4ec37845 // zip2.2d	v5, v2, v3
	WORD $0x4ea21c40 // mov.16b	v0, v2
	WORD $0x6e180460 // mov.d	v0[1], v3[0]
	WORD $0x4ea41c81 // mov.16b	v1, v4
	WORD $0x6e1804c1 // mov.d	v1[1], v6[0]
	WORD $0xad420c02 // ldp	q2, q3, [x0, #0x40]
	WORD $0xad421824 // ldp	q4, q6, [x1, #0x40]
	WORD $0x4e842853 // trn1.4s	v19, v2, v4
	WORD $0x4e846852 // trn2.4s	v18, v2, v4
	WORD $0xad0e4bf3 // stp	q19, q18, [sp, #0x1c0]
	WORD $0xad421042 // ldp	q2, q4, [x2, #0x40]
	WORD $0x3dc01470 // ldr	q16, [x3, #0x50]
	WORD $0x4e872854 // trn1.4s	v20, v2, v7
	WORD $0x4e876842 // trn2.4s	v2, v2, v7
	WORD $0xad0f0bf4 // stp	q20, q2, [sp, #0x1e0]
	WORD $0x4ed47a67 // zip2.2d	v7, v19, v20
	WORD $0x4ec27a42 // zip2.2d	v2, v18, v2
	WORD $0x4e862872 // trn1.4s	v18, v3, v6
	WORD $0x4e866874 // trn2.4s	v20, v3, v6
	WORD $0x4e902883 // trn1.4s	v3, v4, v16
	WORD $0xad0c4be3 // stp	q3, q18, [sp, #0x180]
	WORD $0x4e90689f // trn2.4s	v31, v4, v16
	WORD $0x4eb21e46 // mov.16b	v6, v18
	WORD $0x6e180466 // mov.d	v6[1], v3[0]
	WORD $0xad434003 // ldp	q3, q16, [x0, #0x60]
	WORD $0x3d8007f0 // str	q16, [sp, #0x10]
	WORD $0xad434824 // ldp	q4, q18, [x1, #0x60]
	WORD $0xad0b13e3 // stp	q3, q4, [sp, #0x160]
	WORD $0x3d800ff2 // str	q18, [sp, #0x30]
	WORD $0x4e846875 // trn2.4s	v21, v3, v4
	WORD $0x3d801bf5 // str	q21, [sp, #0x60]
	WORD $0x5280d4e8 // mov	w8, #0x6a7              ; =1703
	WORD $0x4e040d13 // dup.4s	v19, w8
	WORD $0x5280c5e8 // mov	w8, #0x62f              ; =1583
	WORD $0x4e040d03 // dup.4s	v3, w8
	WORD $0x1280a248 // mov	w8, #-0x513             ; =-1299
	WORD $0x4e040d04 // dup.4s	v4, w8
	WORD $0x4ea49ca4 // mul.4s	v4, v5, v4
	WORD $0x4ea394e4 // mla.4s	v4, v7, v3
	WORD $0x3d8057e4 // str	q4, [sp, #0x150]
	WORD $0x5280a268 // mov	w8, #0x513              ; =1299
	WORD $0x4e040d04 // dup.4s	v4, w8
	WORD $0x4ea39ca3 // mul.4s	v3, v5, v3
	WORD $0x4ea494e3 // mla.4s	v3, v7, v4
	WORD $0x3d8053e3 // str	q3, [sp, #0x140]
	WORD $0x52809888 // mov	w8, #0x4c4              ; =1220
	WORD $0x4e040d03 // dup.4s	v3, w8
	WORD $0x1280cd88 // mov	w8, #-0x66d             ; =-1645
	WORD $0x4e040d04 // dup.4s	v4, w8
	WORD $0x4ea39c25 // mul.4s	v5, v1, v3
	WORD $0x4ea49445 // mla.4s	v5, v2, v4
	WORD $0x3d809be5 // str	q5, [sp, #0x260]
	WORD $0x5280cda8 // mov	w8, #0x66d              ; =1645
	WORD $0x4e040d04 // dup.4s	v4, w8
	WORD $0x4ea49c2b // mul.4s	v11, v1, v4
	WORD $0x12808e28 // mov	w8, #-0x472             ; =-1138
	WORD $0x4e040d1a // dup.4s	v26, w8
	WORD $0x4ea3944b // mla.4s	v11, v2, v3
	WORD $0x3d802feb // str	q11, [sp, #0xb0]
	WORD $0x4eba9c0a // mul.4s	v10, v0, v26
	WORD $0x4eb31e64 // mov.16b	v4, v19
	WORD $0x4eb394ca // mla.4s	v10, v6, v19
	WORD $0x52808e48 // mov	w8, #0x472              ; =1138
	WORD $0x4e040d07 // dup.4s	v7, w8
	WORD $0x4eb39c13 // mul.4s	v19, v0, v19
	WORD $0x4ea794d3 // mla.4s	v19, v6, v7
	WORD $0x52807c68 // mov	w8, #0x3e3              ; =995
	WORD $0xad431840 // ldp	q0, q6, [x2, #0x60]
	WORD $0x3d8003e6 // str	q6, [sp]
	WORD $0xad435861 // ldp	q1, q22, [x3, #0x60]
	WORD $0xad0203e1 // stp	q1, q0, [sp, #0x40]
	WORD $0x3d800bf6 // str	q22, [sp, #0x20]
	WORD $0x4e816801 // trn2.4s	v1, v0, v1
	WORD $0x3d801fe1 // str	q1, [sp, #0x70]
	WORD $0x4ec17aa0 // zip2.2d	v0, v21, v1
	WORD $0x4e040d01 // dup.4s	v1, w8
	WORD $0x4ea19e22 // mul.4s	v2, v17, v1
	WORD $0x4f030763 // movi.4s	v3, #0x7b
	WORD $0x4ea39402 // mla.4s	v2, v0, v3
	WORD $0x6f030743 // mvni.4s	v3, #0x7a
	WORD $0x4ea39e25 // mul.4s	v5, v17, v3
	WORD $0x4ea19405 // mla.4s	v5, v0, v1
	WORD $0x4f342441 // srshr.4s	v1, v2, #0xc
	WORD $0x6ea08422 // sub.4s	v2, v1, v0
	WORD $0x3d8047e2 // str	q2, [sp, #0x110]
	WORD $0x4e926a08 // trn2.4s	v8, v16, v18
	WORD $0x4e9668cf // trn2.4s	v15, v6, v22
	WORD $0x4ea81d0d // mov.16b	v13, v8
	WORD $0x6e1805ed // mov.d	v13[1], v15[0]
	WORD $0x12804b08 // mov	w8, #-0x259             ; =-601
	WORD $0x3dc00019 // ldr	q25, [x0]
	WORD $0x3dc00037 // ldr	q23, [x1]
	WORD $0x3dc00058 // ldr	q24, [x2]
	WORD $0x3dc00076 // ldr	q22, [x3]
	WORD $0x4e976b3d // trn2.4s	v29, v25, v23
	WORD $0x4e966b1e // trn2.4s	v30, v24, v22
	WORD $0x4e040d00 // dup.4s	v0, w8
	WORD $0x4ede7bae // zip2.2d	v14, v29, v30
	WORD $0x4ea09dc0 // mul.4s	v0, v14, v0
	WORD $0x6f010561 // mvni.4s	v1, #0x2b
	WORD $0x4ea195a0 // mla.4s	v0, v13, v1
	WORD $0x4ea19dc1 // mul.4s	v1, v14, v1
	WORD $0x52804b28 // mov	w8, #0x259              ; =601
	WORD $0x4e040d03 // dup.4s	v3, w8
	WORD $0x4ea395a1 // mla.4s	v1, v13, v3
	WORD $0x4f34340d // srsra.4s	v13, v0, #0xc
	WORD $0x4f34342e // srsra.4s	v14, v1, #0xc
	WORD $0x4eb41e90 // mov.16b	v16, v20
	WORD $0x4eb41e80 // mov.16b	v0, v20
	WORD $0x4ebf1fe3 // mov.16b	v3, v31
	WORD $0x6e1807e0 // mov.d	v0[1], v31[0]
	WORD $0x5280f8c8 // mov	w8, #0x7c6              ; =1990
	WORD $0x3dc0080c // ldr	q12, [x0, #0x20]
	WORD $0x3dc00835 // ldr	q21, [x1, #0x20]
	WORD $0x3dc00854 // ldr	q20, [x2, #0x20]
	WORD $0x3dc00866 // ldr	q6, [x3, #0x20]
	WORD $0x4e95699b // trn2.4s	v27, v12, v21
	WORD $0x4e866a9c // trn2.4s	v28, v20, v6
	WORD $0x4edc7b61 // zip2.2d	v1, v27, v28
	WORD $0x4e040d12 // dup.4s	v18, w8
	WORD $0x4eb29c32 // mul.4s	v18, v1, v18
	WORD $0x128048c8 // mov	w8, #-0x247             ; =-583
	WORD $0x4e040d1f // dup.4s	v31, w8
	WORD $0x4ebf9412 // mla.4s	v18, v0, v31
	WORD $0x4ebf9c3f // mul.4s	v31, v1, v31
	WORD $0x1280f8a8 // mov	w8, #-0x7c6             ; =-1990
	WORD $0x4e040d09 // dup.4s	v9, w8
	WORD $0x4ea9941f // mla.4s	v31, v0, v9
	WORD $0x4f342652 // srshr.4s	v18, v18, #0xc
	WORD $0x6ea18652 // sub.4s	v18, v18, v1
	WORD $0x4ea08652 // add.4s	v18, v18, v0
	WORD $0x3d804bf2 // str	q18, [sp, #0x120]
	WORD $0x4ea18400 // add.4s	v0, v0, v1
	WORD $0x4f3437e0 // srsra.4s	v0, v31, #0xc
	WORD $0x4ea01c1f // mov.16b	v31, v0
	WORD $0x3d8043e0 // str	q0, [sp, #0x100]
	WORD $0x4f3434b1 // srsra.4s	v17, v5, #0xc
	WORD $0x4e040c80 // dup.4s	v0, w4
	WORD $0x6eb28441 // sub.4s	v1, v2, v18
	WORD $0x4ea06425 // smax.4s	v5, v1, v0
	WORD $0x4e040ca1 // dup.4s	v1, w5
	WORD $0x4ea16ca5 // smin.4s	v5, v5, v1
	WORD $0x6ebf8632 // sub.4s	v18, v17, v31
	WORD $0x4ea06652 // smax.4s	v18, v18, v0
	WORD $0x4ea16e52 // smin.4s	v18, v18, v1
	WORD $0x4ea49ca2 // mul.4s	v2, v5, v4
	WORD $0x4ea79642 // mla.4s	v2, v18, v7
	WORD $0x3d804fe2 // str	q2, [sp, #0x130]
	WORD $0x4eba9ca2 // mul.4s	v2, v5, v26
	WORD $0x4ea49642 // mla.4s	v2, v18, v4
	WORD $0xad06c7e2 // stp	q2, q17, [sp, #0xd0]
	WORD $0x3dc09be2 // ldr	q2, [sp, #0x260]
	WORD $0x4f352445 // srshr.4s	v5, v2, #0xb
	WORD $0x6ea585a5 // sub.4s	v5, v13, v5
	WORD $0x4ea064a5 // smax.4s	v5, v5, v0
	WORD $0x4ea16ca5 // smin.4s	v5, v5, v1
	WORD $0x4f352567 // srshr.4s	v7, v11, #0xb
	WORD $0x6ea785c7 // sub.4s	v7, v14, v7
	WORD $0x4ea064e7 // smax.4s	v7, v7, v0
	WORD $0x4ea16ce7 // smin.4s	v7, v7, v1
	WORD $0x1280d4c8 // mov	w8, #-0x6a7             ; =-1703
	WORD $0x4e040d12 // dup.4s	v18, w8
	WORD $0x4eb29ca2 // mul.4s	v2, v5, v18
	WORD $0x4eba94e2 // mla.4s	v2, v7, v26
	WORD $0x3d8033e2 // str	q2, [sp, #0xc0]
	WORD $0x4eba9ca2 // mul.4s	v2, v5, v26
	WORD $0x4ea494e2 // mla.4s	v2, v7, v4
	WORD $0x3d803fe2 // str	q2, [sp, #0xf0]
	WORD $0xad5117e7 // ldp	q7, q5, [sp, #0x220]
	WORD $0x4ec778a9 // zip2.2d	v9, v5, v7
	WORD $0xad5017e7 // ldp	q7, q5, [sp, #0x200]
	WORD $0x4ec778a4 // zip2.2d	v4, v5, v7
	WORD $0xad4c17e7 // ldp	q7, q5, [sp, #0x180]
	WORD $0x4ec778b2 // zip2.2d	v18, v5, v7
	WORD $0x4ec37a02 // zip2.2d	v2, v16, v3
	WORD $0xad0493e2 // stp	q2, q4, [sp, #0x90]
	WORD $0x4ecf7902 // zip2.2d	v2, v8, v15
	WORD $0x3d8023e2 // str	q2, [sp, #0x80]
	WORD $0x4e972b37 // trn1.4s	v23, v25, v23
	WORD $0x4e962b16 // trn1.4s	v22, v24, v22
	WORD $0x4ed67af0 // zip2.2d	v16, v23, v22
	WORD $0x6e1806d7 // mov.d	v23[1], v22[0]
	WORD $0x6e1807dd // mov.d	v29[1], v30[0]
	WORD $0xad4d13e2 // ldp	q2, q4, [sp, #0x1a0]
	WORD $0x4e842859 // trn1.4s	v25, v2, v4
	WORD $0xad5213e5 // ldp	q5, q4, [sp, #0x240]
	WORD $0x4e8428a7 // trn1.4s	v7, v5, v4
	WORD $0x4ec77b36 // zip2.2d	v22, v25, v7
	WORD $0x6e1804f9 // mov.d	v25[1], v7[0]
	WORD $0x4e95298c // trn1.4s	v12, v12, v21
	WORD $0x4e862a83 // trn1.4s	v3, v20, v6
	WORD $0x4ec37998 // zip2.2d	v24, v12, v3
	WORD $0x6e18046c // mov.d	v12[1], v3[0]
	WORD $0x4ebb1f71 // mov.16b	v17, v27
	WORD $0x6e180791 // mov.d	v17[1], v28[0]
	WORD $0xad4e57e6 // ldp	q6, q21, [sp, #0x1c0]
	WORD $0xad4f0be3 // ldp	q3, q2, [sp, #0x1e0]
	WORD $0x6e180466 // mov.d	v6[1], v3[0]
	WORD $0x6e180455 // mov.d	v21[1], v2[0]
	WORD $0xad4b0be3 // ldp	q3, q2, [sp, #0x160]
	WORD $0x4e822874 // trn1.4s	v20, v3, v2
	WORD $0xad420be4 // ldp	q4, q2, [sp, #0x40]
	WORD $0x4e842847 // trn1.4s	v7, v2, v4
	WORD $0x4ec77a88 // zip2.2d	v8, v20, v7
	WORD $0x6e1804f4 // mov.d	v20[1], v7[0]
	WORD $0xad430bff // ldp	q31, q2, [sp, #0x60]
	WORD $0x6e18045f // mov.d	v31[1], v2[0]
	WORD $0xad4113e2 // ldp	q2, q4, [sp, #0x20]
	WORD $0xad4017e3 // ldp	q3, q5, [sp]
	WORD $0x4e8428ba // trn1.4s	v26, v5, v4
	WORD $0x4e82287b // trn1.4s	v27, v3, v2
	WORD $0x4edb7b45 // zip2.2d	v5, v26, v27
	WORD $0x6e18077a // mov.d	v26[1], v27[0]
	WORD $0x4eb784cf // add.4s	v15, v6, v23
	WORD $0x6ea686e6 // sub.4s	v6, v23, v6
	WORD $0x5280c3e8 // mov	w8, #0x61f              ; =1567
	WORD $0x52802709 // mov	w9, #0x138              ; =312
	WORD $0x4e040d07 // dup.4s	v7, w8
	WORD $0x4ea79d97 // mul.4s	v23, v12, v7
	WORD $0x4e040d3e // dup.4s	v30, w9
	WORD $0x4ebe9697 // mla.4s	v23, v20, v30
	WORD $0x4f3426f7 // srshr.4s	v23, v23, #0xc
	WORD $0x6eb486e3 // sub.4s	v3, v23, v20
	WORD $0x128026e8 // mov	w8, #-0x138             ; =-312
	WORD $0x4e040d1c // dup.4s	v28, w8
	WORD $0x4ebc9d97 // mul.4s	v23, v12, v28
	WORD $0x3d805ffc // str	q28, [sp, #0x170]
	WORD $0x4ea79697 // mla.4s	v23, v20, v7
	WORD $0x4f3436ec // srsra.4s	v12, v23, #0xc
	WORD $0x4f0506bb // movi.4s	v27, #0xb5
	WORD $0x4ebb9df4 // mul.4s	v20, v15, v27
	WORD $0x4f382697 // srshr.4s	v23, v20, #0x8
	WORD $0x6eac86ef // sub.4s	v15, v23, v12
	WORD $0x4f38368c // srsra.4s	v12, v20, #0x8
	WORD $0x4ebb9cc6 // mul.4s	v6, v6, v27
	WORD $0x4f3824d4 // srshr.4s	v20, v6, #0x8
	WORD $0x6ea38694 // sub.4s	v20, v20, v3
	WORD $0x4f3834c3 // srsra.4s	v3, v6, #0x8
	WORD $0x528063e8 // mov	w8, #0x31f              ; =799
	WORD $0x4e040d0b // dup.4s	v11, w8
	WORD $0x4eab9f26 // mul.4s	v6, v25, v11
	WORD $0x4f0205e2 // movi.4s	v2, #0x4f
	WORD $0x4ea29746 // mla.4s	v6, v26, v2
	WORD $0x4f3424c6 // srshr.4s	v6, v6, #0xc
	WORD $0x6eba84c2 // sub.4s	v2, v6, v26
	WORD $0x6f0205c4 // mvni.4s	v4, #0x4e
	WORD $0x4ea49f26 // mul.4s	v6, v25, v4
	WORD $0x4eab9746 // mla.4s	v6, v26, v11
	WORD $0x4f3434d9 // srsra.4s	v25, v6, #0xc
	WORD $0x4f352546 // srshr.4s	v6, v10, #0xb
	WORD $0x6ea68446 // sub.4s	v6, v2, v6
	WORD $0x4f353542 // srsra.4s	v2, v10, #0xb
	WORD $0x4f35267a // srshr.4s	v26, v19, #0xb
	WORD $0x6eba873a // sub.4s	v26, v25, v26
	WORD $0x4f353679 // srsra.4s	v25, v19, #0xb
	WORD $0x4ea064c6 // smax.4s	v6, v6, v0
	WORD $0x4ea16cc6 // smin.4s	v6, v6, v1
	WORD $0x4ea06753 // smax.4s	v19, v26, v0
	WORD $0x4ea16e73 // smin.4s	v19, v19, v1
	WORD $0x6ea6867a // sub.4s	v26, v19, v6
	WORD $0x4ea68666 // add.4s	v6, v19, v6
	WORD $0x4ea06463 // smax.4s	v3, v3, v0
	WORD $0x4ea16c77 // smin.4s	v23, v3, v1
	WORD $0x4ebb9cca // mul.4s	v10, v6, v27
	WORD $0x4f382543 // srshr.4s	v3, v10, #0x8
	WORD $0x6ea386e3 // sub.4s	v3, v23, v3
	WORD $0x3d8087e3 // str	q3, [sp, #0x210]
	WORD $0x4f383557 // srsra.4s	v23, v10, #0x8
	WORD $0x4ea06693 // smax.4s	v19, v20, v0
	WORD $0x4ea16e73 // smin.4s	v19, v19, v1
	WORD $0x4ebb9f54 // mul.4s	v20, v26, v27
	WORD $0x4f38269a // srshr.4s	v26, v20, #0x8
	WORD $0x6eba866a // sub.4s	v10, v19, v26
	WORD $0x4f383693 // srsra.4s	v19, v20, #0x8
	WORD $0x4ea065f4 // smax.4s	v20, v15, v0
	WORD $0x4ea16e9a // smin.4s	v26, v20, v1
	WORD $0x4ea06442 // smax.4s	v2, v2, v0
	WORD $0x4ea16c42 // smin.4s	v2, v2, v1
	WORD $0x4eba8454 // add.4s	v20, v2, v26
	WORD $0x6ea2875a // sub.4s	v26, v26, v2
	WORD $0x4ea06582 // smax.4s	v2, v12, v0
	WORD $0x4ea16c42 // smin.4s	v2, v2, v1
	WORD $0x4ea06739 // smax.4s	v25, v25, v0
	WORD $0x4ea16f39 // smin.4s	v25, v25, v1
	WORD $0x4ea2872c // add.4s	v12, v25, v2
	WORD $0x6eb98459 // sub.4s	v25, v2, v25
	WORD $0x52803228 // mov	w8, #0x191              ; =401
	WORD $0x4e040d02 // dup.4s	v2, w8
	WORD $0x4ea29e0f // mul.4s	v15, v16, v2
	WORD $0x4f000683 // movi.4s	v3, #0x14
	WORD $0x4ea394af // mla.4s	v15, v5, v3
	WORD $0x6f000663 // mvni.4s	v3, #0x13
	WORD $0x4ea39e03 // mul.4s	v3, v16, v3
	WORD $0x4ea294a3 // mla.4s	v3, v5, v2
	WORD $0x4f3425e2 // srshr.4s	v2, v15, #0xc
	WORD $0x6ea58446 // sub.4s	v6, v2, v5
	WORD $0x5280f168 // mov	w8, #0x78b              ; =1931
	WORD $0x52803c89 // mov	w9, #0x1e4              ; =484
	WORD $0x4e040d05 // dup.4s	v5, w8
	WORD $0x12803c68 // mov	w8, #-0x1e4             ; =-484
	WORD $0x4ea59f0f // mul.4s	v15, v24, v5
	WORD $0x4e040d22 // dup.4s	v2, w9
	WORD $0x4e040d04 // dup.4s	v4, w8
	WORD $0x4ea2964f // mla.4s	v15, v18, v2
	WORD $0x4ea49f02 // mul.4s	v2, v24, v4
	WORD $0x4ea59642 // mla.4s	v2, v18, v5
	WORD $0x4f3425e4 // srshr.4s	v4, v15, #0xc
	WORD $0x6eb28484 // sub.4s	v4, v4, v18
	WORD $0x12809488 // mov	w8, #-0x4a5             ; =-1189
	WORD $0x4e040d05 // dup.4s	v5, w8
	WORD $0x4ea59ec5 // mul.4s	v5, v22, v5
	WORD $0x6f0505f2 // mvni.4s	v18, #0xaf
	WORD $0x4eb29505 // mla.4s	v5, v8, v18
	WORD $0x528094a8 // mov	w8, #0x4a5              ; =1189
	WORD $0x4eb29ed2 // mul.4s	v18, v22, v18
	WORD $0x4e040d0f // dup.4s	v15, w8
	WORD $0x4eaf9512 // mla.4s	v18, v8, v15
	WORD $0x4f3434a8 // srsra.4s	v8, v5, #0xc
	WORD $0x4f343656 // srsra.4s	v22, v18, #0xc
	WORD $0x4f343458 // srsra.4s	v24, v2, #0xc
	WORD $0x4f343470 // srsra.4s	v16, v3, #0xc
	WORD $0x3dc057e3 // ldr	q3, [sp, #0x150]
	WORD $0x4f352462 // srshr.4s	v2, v3, #0xb
	WORD $0x6ea284c2 // sub.4s	v2, v6, v2
	WORD $0x4f353466 // srsra.4s	v6, v3, #0xb
	WORD $0x6ea48503 // sub.4s	v3, v8, v4
	WORD $0x4ea48504 // add.4s	v4, v8, v4
	WORD $0x4eb68705 // add.4s	v5, v24, v22
	WORD $0x6eb886d2 // sub.4s	v18, v22, v24
	WORD $0x3dc053f8 // ldr	q24, [sp, #0x140]
	WORD $0x4f352716 // srshr.4s	v22, v24, #0xb
	WORD $0x6eb68616 // sub.4s	v22, v16, v22
	WORD $0x4f353710 // srsra.4s	v16, v24, #0xb
	WORD $0x4ea06442 // smax.4s	v2, v2, v0
	WORD $0x4ea16c42 // smin.4s	v2, v2, v1
	WORD $0x4ea066d6 // smax.4s	v22, v22, v0
	WORD $0x4ea16ed6 // smin.4s	v22, v22, v1
	WORD $0x4ebe9c58 // mul.4s	v24, v2, v30
	WORD $0x4ea796d8 // mla.4s	v24, v22, v7
	WORD $0x4f342718 // srshr.4s	v24, v24, #0xc
	WORD $0x6ea28718 // sub.4s	v24, v24, v2
	WORD $0x4ea79c42 // mul.4s	v2, v2, v7
	WORD $0x4ebc96c2 // mla.4s	v2, v22, v28
	WORD $0x4f343456 // srsra.4s	v22, v2, #0xc
	WORD $0x4ea06462 // smax.4s	v2, v3, v0
	WORD $0x4ea16c42 // smin.4s	v2, v2, v1
	WORD $0x4ea06643 // smax.4s	v3, v18, v0
	WORD $0x4ea16c63 // smin.4s	v3, v3, v1
	WORD $0x1280c3c8 // mov	w8, #-0x61f             ; =-1567
	WORD $0x4e040d08 // dup.4s	v8, w8
	WORD $0x4ea89c52 // mul.4s	v18, v2, v8
	WORD $0x4ebe9472 // mla.4s	v18, v3, v30
	WORD $0x4f342652 // srshr.4s	v18, v18, #0xc
	WORD $0x6ea38652 // sub.4s	v18, v18, v3
	WORD $0x4ebe9c4f // mul.4s	v15, v2, v30
	WORD $0x4ea7946f // mla.4s	v15, v3, v7
	WORD $0x4f3425e3 // srshr.4s	v3, v15, #0xc
	WORD $0x6ea28462 // sub.4s	v2, v3, v2
	WORD $0x4eb88643 // add.4s	v3, v18, v24
	WORD $0x6eb28712 // sub.4s	v18, v24, v18
	WORD $0x4ea064c6 // smax.4s	v6, v6, v0
	WORD $0x4ea16cc6 // smin.4s	v6, v6, v1
	WORD $0x4ea06484 // smax.4s	v4, v4, v0
	WORD $0x4ea16c84 // smin.4s	v4, v4, v1
	WORD $0x4ea68498 // add.4s	v24, v4, v6
	WORD $0x6ea484c4 // sub.4s	v4, v6, v4
	WORD $0x6ea286c6 // sub.4s	v6, v22, v2
	WORD $0x4eb68456 // add.4s	v22, v2, v22
	WORD $0x4ea064a2 // smax.4s	v2, v5, v0
	WORD $0x4ea16c42 // smin.4s	v2, v2, v1
	WORD $0x4ea06605 // smax.4s	v5, v16, v0
	WORD $0x4ea16ca5 // smin.4s	v5, v5, v1
	WORD $0x6ea284b0 // sub.4s	v16, v5, v2
	WORD $0x4ea284af // add.4s	v15, v5, v2
	WORD $0x4ea06642 // smax.4s	v2, v18, v0
	WORD $0x4ea16c42 // smin.4s	v2, v2, v1
	WORD $0x4ea064c5 // smax.4s	v5, v6, v0
	WORD $0x4ea16ca5 // smin.4s	v5, v5, v1
	WORD $0x6ea284a6 // sub.4s	v6, v5, v2
	WORD $0x4ea284a2 // add.4s	v2, v5, v2
	WORD $0x4ea06484 // smax.4s	v4, v4, v0
	WORD $0x4ea16c84 // smin.4s	v4, v4, v1
	WORD $0x4ea06605 // smax.4s	v5, v16, v0
	WORD $0x4ea16ca5 // smin.4s	v5, v5, v1
	WORD $0x6ea484b0 // sub.4s	v16, v5, v4
	WORD $0x4ea484a4 // add.4s	v4, v5, v4
	WORD $0x4ea06665 // smax.4s	v5, v19, v0
	WORD $0x4ea16ca5 // smin.4s	v5, v5, v1
	WORD $0x4ebb9c42 // mul.4s	v2, v2, v27
	WORD $0x4f382452 // srshr.4s	v18, v2, #0x8
	WORD $0x6eb284b2 // sub.4s	v18, v5, v18
	WORD $0x4f383445 // srsra.4s	v5, v2, #0x8
	WORD $0x3d8097e5 // str	q5, [sp, #0x250]
	WORD $0x4ea06682 // smax.4s	v2, v20, v0
	WORD $0x4ea16c42 // smin.4s	v2, v2, v1
	WORD $0x4ebb9c84 // mul.4s	v4, v4, v27
	WORD $0x4f382485 // srshr.4s	v5, v4, #0x8
	WORD $0x6ea58445 // sub.4s	v5, v2, v5
	WORD $0xad114be5 // stp	q5, q18, [sp, #0x220]
	WORD $0x4f383482 // srsra.4s	v2, v4, #0x8
	WORD $0x3d8093e2 // str	q2, [sp, #0x240]
	WORD $0x4ea06742 // smax.4s	v2, v26, v0
	WORD $0x4ea16c42 // smin.4s	v2, v2, v1
	WORD $0x4ebb9e04 // mul.4s	v4, v16, v27
	WORD $0x4f382485 // srshr.4s	v5, v4, #0x8
	WORD $0x6ea58445 // sub.4s	v5, v2, v5
	WORD $0x3d807fe5 // str	q5, [sp, #0x1f0]
	WORD $0x4f383482 // srsra.4s	v2, v4, #0x8
	WORD $0x4ea06544 // smax.4s	v4, v10, v0
	WORD $0x4ea16c85 // smin.4s	v5, v4, v1
	WORD $0x4ebb9cc4 // mul.4s	v4, v6, v27
	WORD $0x4f382486 // srshr.4s	v6, v4, #0x8
	WORD $0x6ea684a6 // sub.4s	v6, v5, v6
	WORD $0x3d807be6 // str	q6, [sp, #0x1e0]
	WORD $0x4f383485 // srsra.4s	v5, v4, #0x8
	WORD $0x4ea06724 // smax.4s	v4, v25, v0
	WORD $0x4ea16c84 // smin.4s	v4, v4, v1
	WORD $0x4ea06706 // smax.4s	v6, v24, v0
	WORD $0x4ea16cc6 // smin.4s	v6, v6, v1
	WORD $0x4ea484d0 // add.4s	v16, v6, v4
	WORD $0x6ea68484 // sub.4s	v4, v4, v6
	WORD $0x3d806fe4 // str	q4, [sp, #0x1b0]
	WORD $0x3dc087e4 // ldr	q4, [sp, #0x210]
	WORD $0x4ea06484 // smax.4s	v4, v4, v0
	WORD $0x4ea16c84 // smin.4s	v4, v4, v1
	WORD $0x4ea06463 // smax.4s	v3, v3, v0
	WORD $0x4ea16c63 // smin.4s	v3, v3, v1
	WORD $0x4ea48466 // add.4s	v6, v3, v4
	WORD $0xad0c43e6 // stp	q6, q16, [sp, #0x180]
	WORD $0x6ea38483 // sub.4s	v3, v4, v3
	WORD $0x3d806be3 // str	q3, [sp, #0x1a0]
	WORD $0x4ea066e3 // smax.4s	v3, v23, v0
	WORD $0x4ea16c63 // smin.4s	v3, v3, v1
	WORD $0x4ea066c4 // smax.4s	v4, v22, v0
	WORD $0x4ea16c84 // smin.4s	v4, v4, v1
	WORD $0x4ea38486 // add.4s	v6, v4, v3
	WORD $0x3d8083e6 // str	q6, [sp, #0x200]
	WORD $0x6ea48463 // sub.4s	v3, v3, v4
	WORD $0x3d8077e3 // str	q3, [sp, #0x1d0]
	WORD $0x4ea06583 // smax.4s	v3, v12, v0
	WORD $0x4ea16c63 // smin.4s	v3, v3, v1
	WORD $0x4ea065e4 // smax.4s	v4, v15, v0
	WORD $0x4ea16c84 // smin.4s	v4, v4, v1
	WORD $0x4ea38486 // add.4s	v6, v4, v3
	WORD $0x3d8087e6 // str	q6, [sp, #0x210]
	WORD $0x6ea48463 // sub.4s	v3, v3, v4
	WORD $0x3d8073e3 // str	q3, [sp, #0x1c0]
	WORD $0x4f060523 // movi.4s	v3, #0xc9
	WORD $0x4ea39fa4 // mul.4s	v4, v29, v3
	WORD $0x4f0004a6 // movi.4s	v6, #0x5
	WORD $0xad444ff0 // ldp	q16, q19, [sp, #0x80]
	WORD $0x4ea69604 // mla.4s	v4, v16, v6
	WORD $0x6f000486 // mvni.4s	v6, #0x4
	WORD $0x4ea69fa6 // mul.4s	v6, v29, v6
	WORD $0x4ea39606 // mla.4s	v6, v16, v3
	WORD $0x4f342483 // srshr.4s	v3, v4, #0xc
	WORD $0x6eb08463 // sub.4s	v3, v3, v16
	WORD $0x5280dae8 // mov	w8, #0x6d7              ; =1751
	WORD $0x52803129 // mov	w9, #0x189              ; =393
	WORD $0x4e040d04 // dup.4s	v4, w8
	WORD $0x4ea49e30 // mul.4s	v16, v17, v4
	WORD $0x4e040d32 // dup.4s	v18, w9
	WORD $0x4eb29670 // mla.4s	v16, v19, v18
	WORD $0x12803108 // mov	w8, #-0x189             ; =-393
	WORD $0x4e040d12 // dup.4s	v18, w8
	WORD $0x4eb29e32 // mul.4s	v18, v17, v18
	WORD $0x4ea49672 // mla.4s	v18, v19, v4
	WORD $0x4f342604 // srshr.4s	v4, v16, #0xc
	WORD $0x1280ac68 // mov	w8, #-0x564             ; =-1380
	WORD $0x4e040d10 // dup.4s	v16, w8
	WORD $0x6eb38484 // sub.4s	v4, v4, v19
	WORD $0x4eb09d30 // mul.4s	v16, v9, v16
	WORD $0x6f0705d3 // mvni.4s	v19, #0xee
	WORD $0x4eb397f0 // mla.4s	v16, v31, v19
	WORD $0x5280ac88 // mov	w8, #0x564              ; =1380
	WORD $0x4eb39d33 // mul.4s	v19, v9, v19
	WORD $0x4e040d14 // dup.4s	v20, w8
	WORD $0x4eb497f3 // mla.4s	v19, v31, v20
	WORD $0x4f34361f // srsra.4s	v31, v16, #0xc
	WORD $0x4f343669 // srsra.4s	v9, v19, #0xc
	WORD $0x4f343651 // srsra.4s	v17, v18, #0xc
	WORD $0x12808488 // mov	w8, #-0x425             ; =-1061
	WORD $0x5280a829 // mov	w9, #0x541              ; =1345
	WORD $0x4e040d30 // dup.4s	v16, w9
	WORD $0x3dc02bf4 // ldr	q20, [sp, #0xa0]
	WORD $0x4eb09e90 // mul.4s	v16, v20, v16
	WORD $0x4e040d12 // dup.4s	v18, w8
	WORD $0x4eb296b0 // mla.4s	v16, v21, v18
	WORD $0x1280a808 // mov	w8, #-0x541             ; =-1345
	WORD $0x4e040d13 // dup.4s	v19, w8
	WORD $0x4eb29e92 // mul.4s	v18, v20, v18
	WORD $0x4eb396b2 // mla.4s	v18, v21, v19
	WORD $0x4f342610 // srshr.4s	v16, v16, #0xc
	WORD $0x6eb48610 // sub.4s	v16, v16, v20
	WORD $0x4eb58610 // add.4s	v16, v16, v21
	WORD $0x4eb486b5 // add.4s	v21, v21, v20
	WORD $0x4f343655 // srsra.4s	v21, v18, #0xc
	WORD $0x4f3434dd // srsra.4s	v29, v6, #0xc
	WORD $0x4ea38616 // add.4s	v22, v16, v3
	WORD $0x6eb08463 // sub.4s	v3, v3, v16
	WORD $0x6ea487e6 // sub.4s	v6, v31, v4
	WORD $0x4ea487e4 // add.4s	v4, v31, v4
	WORD $0xad48c3f2 // ldp	q18, q16, [sp, #0x110]
	WORD $0x4eb28619 // add.4s	v25, v16, v18
	WORD $0x3dc09bf0 // ldr	q16, [sp, #0x260]
	WORD $0x4f35360d // srsra.4s	v13, v16, #0xb
	WORD $0x3dc02ff0 // ldr	q16, [sp, #0xb0]
	WORD $0x4f35360e // srsra.4s	v14, v16, #0xb
	WORD $0x3dc043f0 // ldr	q16, [sp, #0x100]
	WORD $0x3dc03bf2 // ldr	q18, [sp, #0xe0]
	WORD $0x4eb08654 // add.4s	v20, v18, v16
	WORD $0x4ea98633 // add.4s	v19, v17, v9
	WORD $0x6eb18530 // sub.4s	v16, v9, v17
	WORD $0x6eb587b1 // sub.4s	v17, v29, v21
	WORD $0x4eb587b5 // add.4s	v21, v29, v21
	WORD $0x4ea06463 // smax.4s	v3, v3, v0
	WORD $0x4ea16c63 // smin.4s	v3, v3, v1
	WORD $0x4ea06631 // smax.4s	v17, v17, v0
	WORD $0x4ea16e32 // smin.4s	v18, v17, v1
	WORD $0x4f0205f7 // movi.4s	v23, #0x4f
	WORD $0x4eb79c71 // mul.4s	v17, v3, v23
	WORD $0x4eab9651 // mla.4s	v17, v18, v11
	WORD $0x4f342631 // srshr.4s	v17, v17, #0xc
	WORD $0x6ea38631 // sub.4s	v17, v17, v3
	WORD $0x4eab9c63 // mul.4s	v3, v3, v11
	WORD $0x6f0205d8 // mvni.4s	v24, #0x4e
	WORD $0x4eb89643 // mla.4s	v3, v18, v24
	WORD $0x4f343472 // srsra.4s	v18, v3, #0xc
	WORD $0x4ea064c3 // smax.4s	v3, v6, v0
	WORD $0x4ea16c63 // smin.4s	v3, v3, v1
	WORD $0x4ea06606 // smax.4s	v6, v16, v0
	WORD $0x4ea16cc6 // smin.4s	v6, v6, v1
	WORD $0x128063c8 // mov	w8, #-0x31f             ; =-799
	WORD $0x4e040d10 // dup.4s	v16, w8
	WORD $0x4eb09c70 // mul.4s	v16, v3, v16
	WORD $0x4eb794d0 // mla.4s	v16, v6, v23
	WORD $0x4eb79c77 // mul.4s	v23, v3, v23
	WORD $0x4eab94d7 // mla.4s	v23, v6, v11
	WORD $0x4f342610 // srshr.4s	v16, v16, #0xc
	WORD $0x6ea68610 // sub.4s	v16, v16, v6
	WORD $0x4f3426e6 // srshr.4s	v6, v23, #0xc
	WORD $0x6ea384d7 // sub.4s	v23, v6, v3
	WORD $0x4eb18606 // add.4s	v6, v16, v17
	WORD $0x6eb0863a // sub.4s	v26, v17, v16
	WORD $0x4ea066c3 // smax.4s	v3, v22, v0
	WORD $0x4ea16c63 // smin.4s	v3, v3, v1
	WORD $0x4ea06484 // smax.4s	v4, v4, v0
	WORD $0x4ea16c90 // smin.4s	v16, v4, v1
	WORD $0x4ea38604 // add.4s	v4, v16, v3
	WORD $0x6eb08478 // sub.4s	v24, v3, v16
	WORD $0xad4647e3 // ldp	q3, q17, [sp, #0xc0]
	WORD $0x4f352470 // srshr.4s	v16, v3, #0xb
	WORD $0x4f352623 // srshr.4s	v3, v17, #0xb
	WORD $0x6ea3861c // sub.4s	v28, v16, v3
	WORD $0x4f353630 // srsra.4s	v16, v17, #0xb
	WORD $0x4ea06723 // smax.4s	v3, v25, v0
	WORD $0x4ea16c63 // smin.4s	v3, v3, v1
	WORD $0x4ea065b1 // smax.4s	v17, v13, v0
	WORD $0x4ea16e31 // smin.4s	v17, v17, v1
	WORD $0x6ea38639 // sub.4s	v25, v17, v3
	WORD $0x4ea38631 // add.4s	v17, v17, v3
	WORD $0x3dc03fe3 // ldr	q3, [sp, #0xf0]
	WORD $0x4f352463 // srshr.4s	v3, v3, #0xb
	WORD $0x3dc04ffb // ldr	q27, [sp, #0x130]
	WORD $0x4f352776 // srshr.4s	v22, v27, #0xb
	WORD $0x6eb68476 // sub.4s	v22, v3, v22
	WORD $0x4f353763 // srsra.4s	v3, v27, #0xb
	WORD $0x4ea065db // smax.4s	v27, v14, v0
	WORD $0x4ea16f7b // smin.4s	v27, v27, v1
	WORD $0x4ea06694 // smax.4s	v20, v20, v0
	WORD $0x4ea16e9d // smin.4s	v29, v20, v1
	WORD $0x4ebb87b4 // add.4s	v20, v29, v27
	WORD $0x6ebd877b // sub.4s	v27, v27, v29
	WORD $0x6eb7865d // sub.4s	v29, v18, v23
	WORD $0x4eb286f2 // add.4s	v18, v23, v18
	WORD $0x4ea06673 // smax.4s	v19, v19, v0
	WORD $0x4ea16e73 // smin.4s	v19, v19, v1
	WORD $0x4ea066b5 // smax.4s	v21, v21, v0
	WORD $0x4ea16eb5 // smin.4s	v21, v21, v1
	WORD $0x6eb386bf // sub.4s	v31, v21, v19
	WORD $0x4eb386b7 // add.4s	v23, v21, v19
	WORD $0x4ea06753 // smax.4s	v19, v26, v0
	WORD $0x4ea16e75 // smin.4s	v21, v19, v1
	WORD $0x4ea067b3 // smax.4s	v19, v29, v0
	WORD $0x4ea16e73 // smin.4s	v19, v19, v1
	WORD $0x4ebe9eba // mul.4s	v26, v21, v30
	WORD $0x4ea7967a // mla.4s	v26, v19, v7
	WORD $0x4f34275a // srshr.4s	v26, v26, #0xc
	WORD $0x6eb5875a // sub.4s	v26, v26, v21
	WORD $0x4ea79eb5 // mul.4s	v21, v21, v7
	WORD $0x3dc05fe9 // ldr	q9, [sp, #0x170]
	WORD $0x4ea99675 // mla.4s	v21, v19, v9
	WORD $0x4f3436b3 // srsra.4s	v19, v21, #0xc
	WORD $0x4ea06715 // smax.4s	v21, v24, v0
	WORD $0x4ea16eb8 // smin.4s	v24, v21, v1
	WORD $0x4ea067f5 // smax.4s	v21, v31, v0
	WORD $0x4ea16eb5 // smin.4s	v21, v21, v1
	WORD $0x4ebe9f1d // mul.4s	v29, v24, v30
	WORD $0x4ea796bd // mla.4s	v29, v21, v7
	WORD $0x4f3427bd // srshr.4s	v29, v29, #0xc
	WORD $0x6eb887bd // sub.4s	v29, v29, v24
	WORD $0x4ea79f18 // mul.4s	v24, v24, v7
	WORD $0x4ea996b8 // mla.4s	v24, v21, v9
	WORD $0x4f343715 // srsra.4s	v21, v24, #0xc
	WORD $0x4ea06738 // smax.4s	v24, v25, v0
	WORD $0x4ea16f18 // smin.4s	v24, v24, v1
	WORD $0x4ea06779 // smax.4s	v25, v27, v0
	WORD $0x4ea16f39 // smin.4s	v25, v25, v1
	WORD $0x4ea89f1b // mul.4s	v27, v24, v8
	WORD $0x4ebe973b // mla.4s	v27, v25, v30
	WORD $0x4f34277b // srshr.4s	v27, v27, #0xc
	WORD $0x6eb9877b // sub.4s	v27, v27, v25
	WORD $0x4ebe9f1f // mul.4s	v31, v24, v30
	WORD $0x4ea7973f // mla.4s	v31, v25, v7
	WORD $0x4f3427f9 // srshr.4s	v25, v31, #0xc
	WORD $0x6eb88738 // sub.4s	v24, v25, v24
	WORD $0x4ea06799 // smax.4s	v25, v28, v0
	WORD $0x4ea16f39 // smin.4s	v25, v25, v1
	WORD $0x4ea066d6 // smax.4s	v22, v22, v0
	WORD $0x4ea16ed6 // smin.4s	v22, v22, v1
	WORD $0x4ea89f3c // mul.4s	v28, v25, v8
	WORD $0x4ebe96dc // mla.4s	v28, v22, v30
	WORD $0x4ebe9f3e // mul.4s	v30, v25, v30
	WORD $0x4ea796de // mla.4s	v30, v22, v7
	WORD $0x4f342787 // srshr.4s	v7, v28, #0xc
	WORD $0x6eb684f6 // sub.4s	v22, v7, v22
	WORD $0x4f3427c7 // srshr.4s	v7, v30, #0xc
	WORD $0x6eb984f9 // sub.4s	v25, v7, v25
	WORD $0x4ebd877c // add.4s	v28, v27, v29
	WORD $0x6ebb87bb // sub.4s	v27, v29, v27
	WORD $0x4eba86c7 // add.4s	v7, v22, v26
	WORD $0x6eb6875a // sub.4s	v26, v26, v22
	WORD $0x4ea064c6 // smax.4s	v6, v6, v0
	WORD $0x4ea16cc6 // smin.4s	v6, v6, v1
	WORD $0x4ea06610 // smax.4s	v16, v16, v0
	WORD $0x4ea16e16 // smin.4s	v22, v16, v1
	WORD $0x4ea686d0 // add.4s	v16, v22, v6
	WORD $0x6eb684c6 // sub.4s	v6, v6, v22
	WORD $0x4ea06484 // smax.4s	v4, v4, v0
	WORD $0x4ea16c84 // smin.4s	v4, v4, v1
	WORD $0x4ea06631 // smax.4s	v17, v17, v0
	WORD $0x4ea16e31 // smin.4s	v17, v17, v1
	WORD $0x4ea48636 // add.4s	v22, v17, v4
	WORD $0x6eb18484 // sub.4s	v4, v4, v17
	WORD $0x6eb886bd // sub.4s	v29, v21, v24
	WORD $0x4eb58715 // add.4s	v21, v24, v21
	WORD $0x6eb98678 // sub.4s	v24, v19, v25
	WORD $0x4eb38731 // add.4s	v17, v25, v19
	WORD $0x4ea06463 // smax.4s	v3, v3, v0
	WORD $0x4ea16c63 // smin.4s	v3, v3, v1
	WORD $0x4ea06652 // smax.4s	v18, v18, v0
	WORD $0x4ea16e52 // smin.4s	v18, v18, v1
	WORD $0x6ea38659 // sub.4s	v25, v18, v3
	WORD $0x4ea38652 // add.4s	v18, v18, v3
	WORD $0x4ea06683 // smax.4s	v3, v20, v0
	WORD $0x4ea16c63 // smin.4s	v3, v3, v1
	WORD $0x4ea066f3 // smax.4s	v19, v23, v0
	WORD $0x4ea16e73 // smin.4s	v19, v19, v1
	WORD $0x6ea38674 // sub.4s	v20, v19, v3
	WORD $0x4ea38673 // add.4s	v19, v19, v3
	WORD $0x4ea06763 // smax.4s	v3, v27, v0
	WORD $0x4ea16c63 // smin.4s	v3, v3, v1
	WORD $0x4ea067b7 // smax.4s	v23, v29, v0
	WORD $0x4ea16ef7 // smin.4s	v23, v23, v1
	WORD $0x6ea386fb // sub.4s	v27, v23, v3
	WORD $0x4ea386e3 // add.4s	v3, v23, v3
	WORD $0x4ea06757 // smax.4s	v23, v26, v0
	WORD $0x4ea16ef7 // smin.4s	v23, v23, v1
	WORD $0x4ea06718 // smax.4s	v24, v24, v0
	WORD $0x4ea16f18 // smin.4s	v24, v24, v1
	WORD $0x6eb7871d // sub.4s	v29, v24, v23
	WORD $0x4eb78717 // add.4s	v23, v24, v23
	WORD $0x4ea064c6 // smax.4s	v6, v6, v0
	WORD $0x4ea16cc6 // smin.4s	v6, v6, v1
	WORD $0x4ea06738 // smax.4s	v24, v25, v0
	WORD $0x4ea16f18 // smin.4s	v24, v24, v1
	WORD $0x6ea6871e // sub.4s	v30, v24, v6
	WORD $0x4ea68706 // add.4s	v6, v24, v6
	WORD $0x4ea06484 // smax.4s	v4, v4, v0
	WORD $0x4ea16c84 // smin.4s	v4, v4, v1
	WORD $0x4ea06694 // smax.4s	v20, v20, v0
	WORD $0x4ea16e94 // smin.4s	v20, v20, v1
	WORD $0x6ea4869f // sub.4s	v31, v20, v4
	WORD $0x4ea48694 // add.4s	v20, v20, v4
	WORD $0x4f0506a8 // movi.4s	v8, #0xb5
	WORD $0x4ea89f7a // mul.4s	v26, v27, v8
	WORD $0x4ea89c63 // mul.4s	v3, v3, v8
	WORD $0x4ea89fb9 // mul.4s	v25, v29, v8
	WORD $0x4ea89ee4 // mul.4s	v4, v23, v8
	WORD $0x4ea89fd8 // mul.4s	v24, v30, v8
	WORD $0x4ea89cc6 // mul.4s	v6, v6, v8
	WORD $0x4ea89ff7 // mul.4s	v23, v31, v8
	WORD $0x4ea89e94 // mul.4s	v20, v20, v8
	WORD $0x4ea06442 // smax.4s	v2, v2, v0
	WORD $0x4ea16c4a // smin.4s	v10, v2, v1
	WORD $0x4f382462 // srshr.4s	v2, v3, #0x8
	WORD $0x6ea28542 // sub.4s	v2, v10, v2
	WORD $0x3d809be2 // str	q2, [sp, #0x260]
	WORD $0x4f38346a // srsra.4s	v10, v3, #0x8
	WORD $0x4ea064a2 // smax.4s	v2, v5, v0
	WORD $0x4ea16c4c // smin.4s	v12, v2, v1
	WORD $0x4f382482 // srshr.4s	v2, v4, #0x8
	WORD $0x6ea28583 // sub.4s	v3, v12, v2
	WORD $0x4f38348c // srsra.4s	v12, v4, #0x8
	WORD $0x3dc063e2 // ldr	q2, [sp, #0x180]
	WORD $0x4ea06442 // smax.4s	v2, v2, v0
	WORD $0x4ea16c4f // smin.4s	v15, v2, v1
	WORD $0x4f3824c2 // srshr.4s	v2, v6, #0x8
	WORD $0x6ea285e2 // sub.4s	v2, v15, v2
	WORD $0xad0b8be3 // stp	q3, q2, [sp, #0x170]
	WORD $0x4f3834cf // srsra.4s	v15, v6, #0x8
	WORD $0x3dc067e2 // ldr	q2, [sp, #0x190]
	WORD $0x4ea06442 // smax.4s	v2, v2, v0
	WORD $0x4ea16c44 // smin.4s	v4, v2, v1
	WORD $0x4f382685 // srshr.4s	v5, v20, #0x8
	WORD $0x6ea58486 // sub.4s	v6, v4, v5
	WORD $0x4f383684 // srsra.4s	v4, v20, #0x8
	WORD $0xad4d0fe2 // ldp	q2, q3, [sp, #0x1a0]
	WORD $0x4ea06465 // smax.4s	v5, v3, v0
	WORD $0x4ea16cbf // smin.4s	v31, v5, v1
	WORD $0x4f3826e5 // srshr.4s	v5, v23, #0x8
	WORD $0x6ea587f4 // sub.4s	v20, v31, v5
	WORD $0x4f3836ff // srsra.4s	v31, v23, #0x8
	WORD $0x4ea06445 // smax.4s	v5, v2, v0
	WORD $0x4ea16ca8 // smin.4s	v8, v5, v1
	WORD $0x4f382705 // srshr.4s	v5, v24, #0x8
	WORD $0x6ea58517 // sub.4s	v23, v8, v5
	WORD $0x4f383708 // srsra.4s	v8, v24, #0x8
	WORD $0xad4f0be3 // ldp	q3, q2, [sp, #0x1e0]
	WORD $0x4ea06465 // smax.4s	v5, v3, v0
	WORD $0x4ea16cab // smin.4s	v11, v5, v1
	WORD $0x4f382725 // srshr.4s	v5, v25, #0x8
	WORD $0x6ea58578 // sub.4s	v24, v11, v5
	WORD $0x4f38372b // srsra.4s	v11, v25, #0x8
	WORD $0x4ea06445 // smax.4s	v5, v2, v0
	WORD $0x4ea16cad // smin.4s	v13, v5, v1
	WORD $0x4f382745 // srshr.4s	v5, v26, #0x8
	WORD $0x6ea585b9 // sub.4s	v25, v13, v5
	WORD $0x4f38374d // srsra.4s	v13, v26, #0x8
	WORD $0xad4e0be3 // ldp	q3, q2, [sp, #0x1c0]
	WORD $0x4ea06465 // smax.4s	v5, v3, v0
	WORD $0x4ea16ca5 // smin.4s	v5, v5, v1
	WORD $0x4ea066d6 // smax.4s	v22, v22, v0
	WORD $0x4ea16ed6 // smin.4s	v22, v22, v1
	WORD $0x4ea586dd // add.4s	v29, v22, v5
	WORD $0x6eb684b6 // sub.4s	v22, v5, v22
	WORD $0x4ea06445 // smax.4s	v5, v2, v0
	WORD $0x4ea16ca5 // smin.4s	v5, v5, v1
	WORD $0x4ea06610 // smax.4s	v16, v16, v0
	WORD $0x4ea16e10 // smin.4s	v16, v16, v1
	WORD $0x4ea5861e // add.4s	v30, v16, v5
	WORD $0x6eb084ba // sub.4s	v26, v5, v16
	WORD $0xad510fe2 // ldp	q2, q3, [sp, #0x220]
	WORD $0x4ea06465 // smax.4s	v5, v3, v0
	WORD $0x4ea16ca5 // smin.4s	v5, v5, v1
	WORD $0x4ea064e7 // smax.4s	v7, v7, v0
	WORD $0x4ea16ce7 // smin.4s	v7, v7, v1
	WORD $0x4ea584e9 // add.4s	v9, v7, v5
	WORD $0x6ea784bb // sub.4s	v27, v5, v7
	WORD $0x4ea06445 // smax.4s	v5, v2, v0
	WORD $0x4ea16ca5 // smin.4s	v5, v5, v1
	WORD $0x4ea06787 // smax.4s	v7, v28, v0
	WORD $0x4ea16ce7 // smin.4s	v7, v7, v1
	WORD $0x4ea584ee // add.4s	v14, v7, v5
	WORD $0x6ea784bc // sub.4s	v28, v5, v7
	WORD $0xad520be3 // ldp	q3, q2, [sp, #0x240]
	WORD $0x4ea06465 // smax.4s	v5, v3, v0
	WORD $0x4ea16ca5 // smin.4s	v5, v5, v1
	WORD $0x4ea066a7 // smax.4s	v7, v21, v0
	WORD $0x4ea16ce7 // smin.4s	v7, v7, v1
	WORD $0x4ea584f5 // add.4s	v21, v7, v5
	WORD $0x6ea784a5 // sub.4s	v5, v5, v7
	WORD $0x4ea06447 // smax.4s	v7, v2, v0
	WORD $0x4ea16ce7 // smin.4s	v7, v7, v1
	WORD $0x4ea06630 // smax.4s	v16, v17, v0
	WORD $0x4ea16e10 // smin.4s	v16, v16, v1
	WORD $0x4ea78611 // add.4s	v17, v16, v7
	WORD $0x6eb084e7 // sub.4s	v7, v7, v16
	WORD $0x3dc083e2 // ldr	q2, [sp, #0x200]
	WORD $0x4ea06450 // smax.4s	v16, v2, v0
	WORD $0x4ea16e10 // smin.4s	v16, v16, v1
	WORD $0x4ea06652 // smax.4s	v18, v18, v0
	WORD $0x4ea16e52 // smin.4s	v18, v18, v1
	WORD $0x4eb08643 // add.4s	v3, v18, v16
	WORD $0x6eb28610 // sub.4s	v16, v16, v18
	WORD $0x3dc087e2 // ldr	q2, [sp, #0x210]
	WORD $0x4ea06452 // smax.4s	v18, v2, v0
	WORD $0x4ea16e52 // smin.4s	v18, v18, v1
	WORD $0x4ea06673 // smax.4s	v19, v19, v0
	WORD $0x4ea16e73 // smin.4s	v19, v19, v1
	WORD $0x4eb28662 // add.4s	v2, v19, v18
	WORD $0x6eb38652 // sub.4s	v18, v18, v19
	WORD $0x4ea06442 // smax.4s	v2, v2, v0
	WORD $0x4ea16c42 // smin.4s	v2, v2, v1
	WORD $0x4ea06463 // smax.4s	v3, v3, v0
	WORD $0x4ea16c63 // smin.4s	v3, v3, v1
	WORD $0x4e832853 // trn1.4s	v19, v2, v3
	WORD $0x4e836842 // trn2.4s	v2, v2, v3
	WORD $0x4ea06623 // smax.4s	v3, v17, v0
	WORD $0x4ea16c63 // smin.4s	v3, v3, v1
	WORD $0x4ea066b1 // smax.4s	v17, v21, v0
	WORD $0x4ea16e31 // smin.4s	v17, v17, v1
	WORD $0x4e912875 // trn1.4s	v21, v3, v17
	WORD $0x4e916863 // trn2.4s	v3, v3, v17
	WORD $0x4ed57a71 // zip2.2d	v17, v19, v21
	WORD $0x6e1806b3 // mov.d	v19[1], v21[0]
	WORD $0x4ec37855 // zip2.2d	v21, v2, v3
	WORD $0x6e180462 // mov.d	v2[1], v3[0]
	WORD $0x3d800013 // str	q19, [x0]
	WORD $0x3d800022 // str	q2, [x1]
	WORD $0x3d800051 // str	q17, [x2]
	WORD $0x4ea06542 // smax.4s	v2, v10, v0
	WORD $0x4ea16c42 // smin.4s	v2, v2, v1
	WORD $0x4ea06583 // smax.4s	v3, v12, v0
	WORD $0x4ea16c63 // smin.4s	v3, v3, v1
	WORD $0x4ea065f1 // smax.4s	v17, v15, v0
	WORD $0x4ea16e31 // smin.4s	v17, v17, v1
	WORD $0x4ea06484 // smax.4s	v4, v4, v0
	WORD $0x4ea16c84 // smin.4s	v4, v4, v1
	WORD $0x3d800075 // str	q21, [x3]
	WORD $0x4e832853 // trn1.4s	v19, v2, v3
	WORD $0x4e836842 // trn2.4s	v2, v2, v3
	WORD $0x4e842a23 // trn1.4s	v3, v17, v4
	WORD $0x4e846a24 // trn2.4s	v4, v17, v4
	WORD $0x4ec37a71 // zip2.2d	v17, v19, v3
	WORD $0x6e180473 // mov.d	v19[1], v3[0]
	WORD $0x4ec47843 // zip2.2d	v3, v2, v4
	WORD $0x6e180482 // mov.d	v2[1], v4[0]
	WORD $0x3d800413 // str	q19, [x0, #0x10]
	WORD $0x3d800422 // str	q2, [x1, #0x10]
	WORD $0x3d800451 // str	q17, [x2, #0x10]
	WORD $0x4ea067e2 // smax.4s	v2, v31, v0
	WORD $0x4ea16c42 // smin.4s	v2, v2, v1
	WORD $0x4ea06504 // smax.4s	v4, v8, v0
	WORD $0x4ea16c84 // smin.4s	v4, v4, v1
	WORD $0x4ea06571 // smax.4s	v17, v11, v0
	WORD $0x4ea16e31 // smin.4s	v17, v17, v1
	WORD $0x4ea065b3 // smax.4s	v19, v13, v0
	WORD $0x4ea16e73 // smin.4s	v19, v19, v1
	WORD $0x3d800463 // str	q3, [x3, #0x10]
	WORD $0x4e842843 // trn1.4s	v3, v2, v4
	WORD $0x4e846842 // trn2.4s	v2, v2, v4
	WORD $0x4e932a24 // trn1.4s	v4, v17, v19
	WORD $0x4e936a31 // trn2.4s	v17, v17, v19
	WORD $0x4ec47873 // zip2.2d	v19, v3, v4
	WORD $0x6e180483 // mov.d	v3[1], v4[0]
	WORD $0x4ed17844 // zip2.2d	v4, v2, v17
	WORD $0x6e180622 // mov.d	v2[1], v17[0]
	WORD $0x3d800803 // str	q3, [x0, #0x20]
	WORD $0x3d800822 // str	q2, [x1, #0x20]
	WORD $0x3d800853 // str	q19, [x2, #0x20]
	WORD $0x4ea065c2 // smax.4s	v2, v14, v0
	WORD $0x4ea16c42 // smin.4s	v2, v2, v1
	WORD $0x4ea06523 // smax.4s	v3, v9, v0
	WORD $0x4ea16c63 // smin.4s	v3, v3, v1
	WORD $0x4ea067d1 // smax.4s	v17, v30, v0
	WORD $0x4ea16e31 // smin.4s	v17, v17, v1
	WORD $0x4ea067b3 // smax.4s	v19, v29, v0
	WORD $0x4ea16e73 // smin.4s	v19, v19, v1
	WORD $0x3d800864 // str	q4, [x3, #0x20]
	WORD $0x4e832844 // trn1.4s	v4, v2, v3
	WORD $0x4e836842 // trn2.4s	v2, v2, v3
	WORD $0x4e932a23 // trn1.4s	v3, v17, v19
	WORD $0x4e936a31 // trn2.4s	v17, v17, v19
	WORD $0x4ec37893 // zip2.2d	v19, v4, v3
	WORD $0x6e180464 // mov.d	v4[1], v3[0]
	WORD $0x4ed17843 // zip2.2d	v3, v2, v17
	WORD $0x6e180622 // mov.d	v2[1], v17[0]
	WORD $0x3d800c04 // str	q4, [x0, #0x30]
	WORD $0x3d800c22 // str	q2, [x1, #0x30]
	WORD $0x3d800c53 // str	q19, [x2, #0x30]
	WORD $0x4ea066c2 // smax.4s	v2, v22, v0
	WORD $0x4ea16c42 // smin.4s	v2, v2, v1
	WORD $0x4ea06744 // smax.4s	v4, v26, v0
	WORD $0x4ea16c84 // smin.4s	v4, v4, v1
	WORD $0x4ea06771 // smax.4s	v17, v27, v0
	WORD $0x4ea16e31 // smin.4s	v17, v17, v1
	WORD $0x4ea06793 // smax.4s	v19, v28, v0
	WORD $0x4ea16e73 // smin.4s	v19, v19, v1
	WORD $0x3d800c63 // str	q3, [x3, #0x30]
	WORD $0x4e842843 // trn1.4s	v3, v2, v4
	WORD $0x4e846842 // trn2.4s	v2, v2, v4
	WORD $0x4e932a24 // trn1.4s	v4, v17, v19
	WORD $0x4e936a31 // trn2.4s	v17, v17, v19
	WORD $0x4ec47873 // zip2.2d	v19, v3, v4
	WORD $0x6e180483 // mov.d	v3[1], v4[0]
	WORD $0x4ed17844 // zip2.2d	v4, v2, v17
	WORD $0x6e180622 // mov.d	v2[1], v17[0]
	WORD $0x3d801003 // str	q3, [x0, #0x40]
	WORD $0x3d801022 // str	q2, [x1, #0x40]
	WORD $0x3d801053 // str	q19, [x2, #0x40]
	WORD $0x4ea06722 // smax.4s	v2, v25, v0
	WORD $0x4ea16c42 // smin.4s	v2, v2, v1
	WORD $0x4ea06703 // smax.4s	v3, v24, v0
	WORD $0x4ea16c63 // smin.4s	v3, v3, v1
	WORD $0x4ea066f1 // smax.4s	v17, v23, v0
	WORD $0x4ea16e31 // smin.4s	v17, v17, v1
	WORD $0x4ea06693 // smax.4s	v19, v20, v0
	WORD $0x4ea16e73 // smin.4s	v19, v19, v1
	WORD $0x3d801064 // str	q4, [x3, #0x40]
	WORD $0x4e832844 // trn1.4s	v4, v2, v3
	WORD $0x4e836842 // trn2.4s	v2, v2, v3
	WORD $0x4e932a23 // trn1.4s	v3, v17, v19
	WORD $0x4e936a31 // trn2.4s	v17, v17, v19
	WORD $0x4ec37893 // zip2.2d	v19, v4, v3
	WORD $0x6e180464 // mov.d	v4[1], v3[0]
	WORD $0x4ed17843 // zip2.2d	v3, v2, v17
	WORD $0x6e180622 // mov.d	v2[1], v17[0]
	WORD $0x3d801404 // str	q4, [x0, #0x50]
	WORD $0x3d801422 // str	q2, [x1, #0x50]
	WORD $0x3d801453 // str	q19, [x2, #0x50]
	WORD $0x4ea064c2 // smax.4s	v2, v6, v0
	WORD $0x4ea16c42 // smin.4s	v2, v2, v1
	WORD $0xad4b93e6 // ldp	q6, q4, [sp, #0x170]
	WORD $0x4ea06484 // smax.4s	v4, v4, v0
	WORD $0x4ea16c84 // smin.4s	v4, v4, v1
	WORD $0x4ea064c6 // smax.4s	v6, v6, v0
	WORD $0x4ea16cc6 // smin.4s	v6, v6, v1
	WORD $0x3dc09bf1 // ldr	q17, [sp, #0x260]
	WORD $0x4ea06631 // smax.4s	v17, v17, v0
	WORD $0x4ea16e31 // smin.4s	v17, v17, v1
	WORD $0x3d801463 // str	q3, [x3, #0x50]
	WORD $0x4e842843 // trn1.4s	v3, v2, v4
	WORD $0x4e846842 // trn2.4s	v2, v2, v4
	WORD $0x4e9128c4 // trn1.4s	v4, v6, v17
	WORD $0x4e9168c6 // trn2.4s	v6, v6, v17
	WORD $0x4ec47871 // zip2.2d	v17, v3, v4
	WORD $0x6e180483 // mov.d	v3[1], v4[0]
	WORD $0x4ec67844 // zip2.2d	v4, v2, v6
	WORD $0x6e1804c2 // mov.d	v2[1], v6[0]
	WORD $0x3d801803 // str	q3, [x0, #0x60]
	WORD $0x3d801822 // str	q2, [x1, #0x60]
	WORD $0x3d801851 // str	q17, [x2, #0x60]
	WORD $0x4ea064a2 // smax.4s	v2, v5, v0
	WORD $0x4ea16c42 // smin.4s	v2, v2, v1
	WORD $0x4ea064e3 // smax.4s	v3, v7, v0
	WORD $0x4ea16c63 // smin.4s	v3, v3, v1
	WORD $0x4ea06605 // smax.4s	v5, v16, v0
	WORD $0x4ea16ca5 // smin.4s	v5, v5, v1
	WORD $0x3d801864 // str	q4, [x3, #0x60]
	WORD $0x4ea06640 // smax.4s	v0, v18, v0
	WORD $0x4ea16c00 // smin.4s	v0, v0, v1
	WORD $0x4e832841 // trn1.4s	v1, v2, v3
	WORD $0x4e8028a4 // trn1.4s	v4, v5, v0
	WORD $0x4ec47826 // zip2.2d	v6, v1, v4
	WORD $0x6e180481 // mov.d	v1[1], v4[0]
	WORD $0x3d801c01 // str	q1, [x0, #0x70]
	WORD $0x4e836841 // trn2.4s	v1, v2, v3
	WORD $0x4e8068a0 // trn2.4s	v0, v5, v0
	WORD $0x4ec07822 // zip2.2d	v2, v1, v0
	WORD $0x6e180401 // mov.d	v1[1], v0[0]
	WORD $0x3d801c21 // str	q1, [x1, #0x70]
	WORD $0x3d801c46 // str	q6, [x2, #0x70]
	WORD $0x3d801c62 // str	q2, [x3, #0x70]
	WORD $0x9109c3ff // add	sp, sp, #0x270
	WORD $0xa9446ffc // ldp	x28, x27, [sp, #0x40]
	WORD $0x6d4323e9 // ldp	d9, d8, [sp, #0x30]
	WORD $0x6d422beb // ldp	d11, d10, [sp, #0x20]
	WORD $0x6d4133ed // ldp	d13, d12, [sp, #0x10]
	WORD $0x6cc53bef // ldp	d15, d14, [sp], #0x50
	WORD $0xd65f03c0 // ret
