// NEON-accelerated inverse DCT4 four-column kernel.
//
// Four adjacent columns of the row-major scratch buffer ride the four int32
// lanes of each .4s register, following dav1d's high-bitdepth inverse
// transform shape (dav1d src/arm/64/itx16.S: the mul/mla/mls + srshr + smax/smin
// idiom) but with libaom's exact round_shift arithmetic: bit-for-bit identical
// to inverseDCT4 run on each column (not dav1d's sqrdmulh approximation).
// Working in int32 lanes without widening is exact here because the column-pass
// inputs are pre-clamped to the stage range (|v| <= 2^19 across all supported
// bit depths) and the (cospi-4096)-rewritten butterfly keeps the multiply
// accumulator below 2^31 (the adapter enforces the clamp-bound precondition and
// falls back otherwise). Asserted exhaustively by the column dispatch
// differential tests.
//
// The body is generated by transliterating the pure-Go inverseDCT4 butterfly to
// NEON intrinsics (tools/itxgen/gen.py + kernels.c goav1_idct4_col4), compiling
// with the system C compiler at -O2 and transcribing the disassembly verbatim
// as WORD-encoded opcodes, because Go's arm64 assembler does not expose the
// signed-rounding-shift mnemonics. The kernel is pure straight-line leaf code
// (no branches, no calls, no stack frame); it touches only caller-saved SIMD
// registers (never the callee-saved d8-d15) and caller-saved GPRs (leaving g in
// R28 and the link register untouched), and stays well within the nosplit stack
// budget.
//
// SPDX-License-Identifier: BSD-2-Clause
//
// See LICENSE for the BSD-2-Clause grant and NOTICE for the AOM attribution.

//go:build arm64 && !purego

#include "textflag.h"

// func inverseDCT4Col4NEON(base *int32, rowStrideBytes, min, max int64)
// Transforms four adjacent columns (col..col+3) of the row-major scratch
// buffer in place. base points at scratch[col]; rows are rowStrideBytes
// apart. The four columns occupy int32 lanes 0-3. Bit-for-bit identical to
// inverseDCT4 run on each column.
TEXT ·inverseDCT4Col4NEON(SB), NOSPLIT, $0-32
	MOVD base+0(FP), R0
	MOVD rowStrideBytes+8(FP), R1
	MOVD min+16(FP), R2
	MOVD max+24(FP), R3
	WORD $0x3dc00000 // ldr	q0, [x0]
	WORD $0x3ce16801 // ldr	q1, [x0, x1]
	WORD $0xd37ff828 // lsl	x8, x1, #1
	WORD $0x3ce86802 // ldr	q2, [x0, x8]
	WORD $0x8b010109 // add	x9, x8, x1
	WORD $0x3ce96803 // ldr	q3, [x0, x9]
	WORD $0x4e040c44 // dup.4s	v4, w2
	WORD $0x4e040c65 // dup.4s	v5, w3
	WORD $0x4ea08446 // add.4s	v6, v2, v0
	WORD $0x4f0506a7 // movi.4s	v7, #0xb5
	WORD $0x4ea79cc6 // mul.4s	v6, v6, v7
	WORD $0x4f3824d0 // srshr.4s	v16, v6, #0x8
	WORD $0x6ea28400 // sub.4s	v0, v0, v2
	WORD $0x4ea79c00 // mul.4s	v0, v0, v7
	WORD $0x4f382402 // srshr.4s	v2, v0, #0x8
	WORD $0x5280c3ea // mov	w10, #0x61f             ; =1567
	WORD $0x4e040d47 // dup.4s	v7, w10
	WORD $0x4ea79c31 // mul.4s	v17, v1, v7
	WORD $0x5280270a // mov	w10, #0x138             ; =312
	WORD $0x4e040d52 // dup.4s	v18, w10
	WORD $0x4eb29471 // mla.4s	v17, v3, v18
	WORD $0x4f342631 // srshr.4s	v17, v17, #0xc
	WORD $0x6ea38631 // sub.4s	v17, v17, v3
	WORD $0x128026ea // mov	w10, #-0x138            ; =-312
	WORD $0x4e040d52 // dup.4s	v18, w10
	WORD $0x4eb29c32 // mul.4s	v18, v1, v18
	WORD $0x4ea79472 // mla.4s	v18, v3, v7
	WORD $0x4f343641 // srsra.4s	v1, v18, #0xc
	WORD $0x6ea18603 // sub.4s	v3, v16, v1
	WORD $0x4f3834c1 // srsra.4s	v1, v6, #0x8
	WORD $0x4ea46421 // smax.4s	v1, v1, v4
	WORD $0x4ea56c21 // smin.4s	v1, v1, v5
	WORD $0x6eb18442 // sub.4s	v2, v2, v17
	WORD $0x4f383411 // srsra.4s	v17, v0, #0x8
	WORD $0x4ea46620 // smax.4s	v0, v17, v4
	WORD $0x4ea56c00 // smin.4s	v0, v0, v5
	WORD $0x4ea46442 // smax.4s	v2, v2, v4
	WORD $0x4ea56c42 // smin.4s	v2, v2, v5
	WORD $0x3d800001 // str	q1, [x0]
	WORD $0x3ca16800 // str	q0, [x0, x1]
	WORD $0x4ea46460 // smax.4s	v0, v3, v4
	WORD $0x4ea56c00 // smin.4s	v0, v0, v5
	WORD $0x3ca86802 // str	q2, [x0, x8]
	WORD $0x3ca96800 // str	q0, [x0, x9]
	WORD $0xd65f03c0 // ret
