// NEON-accelerated inverse DCT8 four-column kernel.
//
// Four adjacent columns of the row-major scratch buffer ride the four int32
// lanes of each .4s register, following dav1d's high-bitdepth inverse
// transform shape (dav1d src/arm/64/itx16.S: the mul/mla/mls + srshr + smax/smin
// idiom) but with libaom's exact round_shift arithmetic: every butterfly
// multiply is a plain mul/mla/mls .4s, every rounding shift is srshr/srsra .4s
// and every stage clamp is smax+smin against the stage bounds. Working in int32
// lanes without widening is exact here because the column-pass inputs are
// pre-clamped to the stage range (|v| <= 2^19 across all supported bit depths)
// and every cospi pair in the (cospi-4096)-rewritten butterflies keeps the
// multiply accumulator below 2^31 (the adapter enforces the clamp-bound
// precondition and falls back otherwise). The fixed-point products, rounding
// shifts and clamps are bit-for-bit identical to running the pure-Go
// inverseDCT8 on each column, asserted exhaustively by the column dispatch
// differential tests.
//
// The body is generated by transliterating the pure-Go inverseDCT8 butterfly to
// NEON intrinsics (tools/itxgen/gen.py + kernels.c goav1_idct8_col4), compiling
// with the system C compiler at -O2 and transcribing the disassembly verbatim
// as WORD-encoded opcodes, because Go's arm64 assembler does not expose the
// signed-rounding-shift mnemonics. The kernel is pure straight-line leaf code
// (no branches, no calls, no stack frame); it touches only caller-saved SIMD
// registers (never the callee-saved d8-d15) and caller-saved GPRs (leaving g in
// R28 and the link register untouched), and stays well within the nosplit stack
// budget.
//
// SPDX-License-Identifier: BSD-2-Clause
//
// See LICENSE for the BSD-2-Clause grant and NOTICE for the AOM attribution.

//go:build arm64 && !purego

#include "textflag.h"

// func inverseDCT8Col4NEON(base *int32, rowStrideBytes, min, max int64)
// Transforms four adjacent columns (col..col+3) of the row-major scratch
// buffer in place. base points at scratch[col]; rows are rowStrideBytes
// apart. The four columns occupy int32 lanes 0-3. Bit-for-bit identical to
// inverseDCT8 run on each column.
TEXT ·inverseDCT8Col4NEON(SB), NOSPLIT, $0-32
	MOVD base+0(FP), R0
	MOVD rowStrideBytes+8(FP), R1
	MOVD min+16(FP), R2
	MOVD max+24(FP), R3
	WORD $0x3dc00002 // ldr	q2, [x0]
	WORD $0x3ce16803 // ldr	q3, [x0, x1]
	WORD $0xd37ff828 // lsl	x8, x1, #1
	WORD $0x3ce86805 // ldr	q5, [x0, x8]
	WORD $0x8b010109 // add	x9, x8, x1
	WORD $0x3ce96810 // ldr	q16, [x0, x9]
	WORD $0xd37ef42a // lsl	x10, x1, #2
	WORD $0x3cea6806 // ldr	q6, [x0, x10]
	WORD $0x8b01014b // add	x11, x10, x1
	WORD $0x3ceb6811 // ldr	q17, [x0, x11]
	WORD $0x528000cc // mov	w12, #0x6               ; =6
	WORD $0x9b0c7c2c // mul	x12, x1, x12
	WORD $0x3cec6807 // ldr	q7, [x0, x12]
	WORD $0xd37df02d // lsl	x13, x1, #3
	WORD $0xcb01000e // sub	x14, x0, x1
	WORD $0x3ced69d2 // ldr	q18, [x14, x13]
	WORD $0x4e040c40 // dup.4s	v0, w2
	WORD $0x4e040c61 // dup.4s	v1, w3
	WORD $0x4ea284d3 // add.4s	v19, v6, v2
	WORD $0x4f0506a4 // movi.4s	v4, #0xb5
	WORD $0x4ea49e73 // mul.4s	v19, v19, v4
	WORD $0x4f382674 // srshr.4s	v20, v19, #0x8
	WORD $0x6ea68442 // sub.4s	v2, v2, v6
	WORD $0x4ea49c46 // mul.4s	v6, v2, v4
	WORD $0x4f3824d5 // srshr.4s	v21, v6, #0x8
	WORD $0x5280c3ef // mov	w15, #0x61f             ; =1567
	WORD $0x4e040de2 // dup.4s	v2, w15
	WORD $0x4ea29cb6 // mul.4s	v22, v5, v2
	WORD $0x5280270f // mov	w15, #0x138             ; =312
	WORD $0x4e040df7 // dup.4s	v23, w15
	WORD $0x4eb794f6 // mla.4s	v22, v7, v23
	WORD $0x4f3426d6 // srshr.4s	v22, v22, #0xc
	WORD $0x6ea786d6 // sub.4s	v22, v22, v7
	WORD $0x128026ef // mov	w15, #-0x138            ; =-312
	WORD $0x4e040df7 // dup.4s	v23, w15
	WORD $0x4eb79cb7 // mul.4s	v23, v5, v23
	WORD $0x4ea294f7 // mla.4s	v23, v7, v2
	WORD $0x4f3436e5 // srsra.4s	v5, v23, #0xc
	WORD $0x6ea58694 // sub.4s	v20, v20, v5
	WORD $0x4f383665 // srsra.4s	v5, v19, #0x8
	WORD $0x4ea064a2 // smax.4s	v2, v5, v0
	WORD $0x4ea16c42 // smin.4s	v2, v2, v1
	WORD $0x6eb686a5 // sub.4s	v5, v21, v22
	WORD $0x4f3834d6 // srsra.4s	v22, v6, #0x8
	WORD $0x4ea066c6 // smax.4s	v6, v22, v0
	WORD $0x4ea16cc7 // smin.4s	v7, v6, v1
	WORD $0x4ea064a5 // smax.4s	v5, v5, v0
	WORD $0x4ea16ca6 // smin.4s	v6, v5, v1
	WORD $0x4ea06685 // smax.4s	v5, v20, v0
	WORD $0x4ea16ca5 // smin.4s	v5, v5, v1
	WORD $0x528063ef // mov	w15, #0x31f             ; =799
	WORD $0x4e040df3 // dup.4s	v19, w15
	WORD $0x4eb39c74 // mul.4s	v20, v3, v19
	WORD $0x4f0205f5 // movi.4s	v21, #0x4f
	WORD $0x4eb59654 // mla.4s	v20, v18, v21
	WORD $0x4f342694 // srshr.4s	v20, v20, #0xc
	WORD $0x5280d4ef // mov	w15, #0x6a7             ; =1703
	WORD $0x4e040df5 // dup.4s	v21, w15
	WORD $0x12808e2f // mov	w15, #-0x472            ; =-1138
	WORD $0x4e040df6 // dup.4s	v22, w15
	WORD $0x6eb28694 // sub.4s	v20, v20, v18
	WORD $0x4eb69e16 // mul.4s	v22, v16, v22
	WORD $0x4eb59636 // mla.4s	v22, v17, v21
	WORD $0x52808e4f // mov	w15, #0x472             ; =1138
	WORD $0x4e040df7 // dup.4s	v23, w15
	WORD $0x4f3526d8 // srshr.4s	v24, v22, #0xb
	WORD $0x4eb59e10 // mul.4s	v16, v16, v21
	WORD $0x4eb79630 // mla.4s	v16, v17, v23
	WORD $0x4f352611 // srshr.4s	v17, v16, #0xb
	WORD $0x6f0205d5 // mvni.4s	v21, #0x4e
	WORD $0x4eb59c75 // mul.4s	v21, v3, v21
	WORD $0x4eb39655 // mla.4s	v21, v18, v19
	WORD $0x4f3436a3 // srsra.4s	v3, v21, #0xc
	WORD $0x6eb88692 // sub.4s	v18, v20, v24
	WORD $0x4f3536d4 // srsra.4s	v20, v22, #0xb
	WORD $0x4ea06693 // smax.4s	v19, v20, v0
	WORD $0x4ea16e73 // smin.4s	v19, v19, v1
	WORD $0x4ea06652 // smax.4s	v18, v18, v0
	WORD $0x4ea16e52 // smin.4s	v18, v18, v1
	WORD $0x6eb18471 // sub.4s	v17, v3, v17
	WORD $0x4f353603 // srsra.4s	v3, v16, #0xb
	WORD $0x4ea06463 // smax.4s	v3, v3, v0
	WORD $0x4ea16c63 // smin.4s	v3, v3, v1
	WORD $0x4ea06630 // smax.4s	v16, v17, v0
	WORD $0x4ea16e10 // smin.4s	v16, v16, v1
	WORD $0x6eb28611 // sub.4s	v17, v16, v18
	WORD $0x4ea49e31 // mul.4s	v17, v17, v4
	WORD $0x4f382634 // srshr.4s	v20, v17, #0x8
	WORD $0x4eb28610 // add.4s	v16, v16, v18
	WORD $0x4ea49e04 // mul.4s	v4, v16, v4
	WORD $0x4f382490 // srshr.4s	v16, v4, #0x8
	WORD $0x4ea28472 // add.4s	v18, v3, v2
	WORD $0x4ea06652 // smax.4s	v18, v18, v0
	WORD $0x4ea16e52 // smin.4s	v18, v18, v1
	WORD $0x6eb084f0 // sub.4s	v16, v7, v16
	WORD $0x4f383487 // srsra.4s	v7, v4, #0x8
	WORD $0x4ea064e4 // smax.4s	v4, v7, v0
	WORD $0x4ea16c84 // smin.4s	v4, v4, v1
	WORD $0x6eb484c7 // sub.4s	v7, v6, v20
	WORD $0x4f383626 // srsra.4s	v6, v17, #0x8
	WORD $0x4ea064c6 // smax.4s	v6, v6, v0
	WORD $0x4ea16cc6 // smin.4s	v6, v6, v1
	WORD $0x4ea58671 // add.4s	v17, v19, v5
	WORD $0x4ea06631 // smax.4s	v17, v17, v0
	WORD $0x4ea16e31 // smin.4s	v17, v17, v1
	WORD $0x6eb384a5 // sub.4s	v5, v5, v19
	WORD $0x4ea064a5 // smax.4s	v5, v5, v0
	WORD $0x4ea16ca5 // smin.4s	v5, v5, v1
	WORD $0x4ea064e7 // smax.4s	v7, v7, v0
	WORD $0x4ea16ce7 // smin.4s	v7, v7, v1
	WORD $0x4ea06610 // smax.4s	v16, v16, v0
	WORD $0x4ea16e10 // smin.4s	v16, v16, v1
	WORD $0x6ea38442 // sub.4s	v2, v2, v3
	WORD $0x3d800012 // str	q18, [x0]
	WORD $0x3ca16804 // str	q4, [x0, x1]
	WORD $0x3ca86806 // str	q6, [x0, x8]
	WORD $0x3ca96811 // str	q17, [x0, x9]
	WORD $0x3caa6805 // str	q5, [x0, x10]
	WORD $0x3cab6807 // str	q7, [x0, x11]
	WORD $0x4ea06440 // smax.4s	v0, v2, v0
	WORD $0x4ea16c00 // smin.4s	v0, v0, v1
	WORD $0x3cac6810 // str	q16, [x0, x12]
	WORD $0x3cad69c0 // str	q0, [x14, x13]
	WORD $0xd65f03c0 // ret
