// Code generated by gen_fdct_neon.py. DO NOT EDIT.
// SPDX-License-Identifier: BSD-2-Clause
//
// See LICENSE for the BSD-2-Clause grant.

//go:build arm64 && !purego

#include "textflag.h"

// NEON forward 8x8 DCT_DCT (fwd_txfm2d shape: shift {2,-1,0}, cos_bit 13).
// The column pass runs the av1_fdct8 butterfly network over row vectors
// (lanes are columns), the 8x8 int32 matrix is transposed in registers,
// and the row pass reruns the network; storing its outputs row-by-row
// lands the coeff[c*stride+r] layout directly. Weights are MUL/MLA/MLS
// by element from two constant vectors; rounding uses SRSHR #13 (the
// products stay far inside int32 for 8-bit residuals, so this matches
// the 64-bit reference arithmetic exactly).

#define CTXIN 0
#define CTXINSTRIDE 8
#define CTXOUT 16
#define CTXOUTSTRIDE 24

// func fdct8x8NEONAsm(ctx *fdct8x8NEONCtx)
TEXT ·fdct8x8NEONAsm(SB), NOSPLIT, $0-8
	MOVD ctx+0(FP), R0
	MOVD CTXIN(R0), R1
	MOVD CTXINSTRIDE(R0), R2  // residual stride in elements
	MOVD CTXOUT(R0), R3
	MOVD CTXOUTSTRIDE(R0), R4 // coeff stride in elements
	MOVD $·fdct8Cospi(SB), R5
	VLD1 (R5), [V30.S4, V31.S4]
	LSL  $1, R2 // stride bytes (int16)
	LSL  $2, R4 // stride bytes (int32)

	// Load the eight residual rows, widening with the shift[0]=2 fused
	// into SSHLL: lo lanes (columns 0-3) in V0-V7, hi in V8-V15.
	VLD1 (R1), [V16.H8]
	WORD $0x0f12a600 // sshll v0.4s, v16.4h, #2
	WORD $0x4f12a608 // sshll2 v8.4s, v16.8h, #2
	ADD R2, R1
	VLD1 (R1), [V16.H8]
	WORD $0x0f12a601 // sshll v1.4s, v16.4h, #2
	WORD $0x4f12a609 // sshll2 v9.4s, v16.8h, #2
	ADD R2, R1
	VLD1 (R1), [V16.H8]
	WORD $0x0f12a602 // sshll v2.4s, v16.4h, #2
	WORD $0x4f12a60a // sshll2 v10.4s, v16.8h, #2
	ADD R2, R1
	VLD1 (R1), [V16.H8]
	WORD $0x0f12a603 // sshll v3.4s, v16.4h, #2
	WORD $0x4f12a60b // sshll2 v11.4s, v16.8h, #2
	ADD R2, R1
	VLD1 (R1), [V16.H8]
	WORD $0x0f12a604 // sshll v4.4s, v16.4h, #2
	WORD $0x4f12a60c // sshll2 v12.4s, v16.8h, #2
	ADD R2, R1
	VLD1 (R1), [V16.H8]
	WORD $0x0f12a605 // sshll v5.4s, v16.4h, #2
	WORD $0x4f12a60d // sshll2 v13.4s, v16.8h, #2
	ADD R2, R1
	VLD1 (R1), [V16.H8]
	WORD $0x0f12a606 // sshll v6.4s, v16.4h, #2
	WORD $0x4f12a60e // sshll2 v14.4s, v16.8h, #2
	ADD R2, R1
	VLD1 (R1), [V16.H8]
	WORD $0x0f12a607 // sshll v7.4s, v16.4h, #2
	WORD $0x4f12a60f // sshll2 v15.4s, v16.8h, #2

	// Column pass, both lane groups, then the -1 shift (symmetric).
	WORD $0x4f00043d // movi v29.4s, #1
	WORD $0x4ea78410 // add v16.4s, v0.4s, v7.4s
	WORD $0x4ea68431 // add v17.4s, v1.4s, v6.4s
	WORD $0x4ea58452 // add v18.4s, v2.4s, v5.4s
	WORD $0x4ea48473 // add v19.4s, v3.4s, v4.4s
	WORD $0x6ea48474 // sub v20.4s, v3.4s, v4.4s
	WORD $0x6ea58455 // sub v21.4s, v2.4s, v5.4s
	WORD $0x6ea68436 // sub v22.4s, v1.4s, v6.4s
	WORD $0x6ea78417 // sub v23.4s, v0.4s, v7.4s
	WORD $0x4eb38600 // add v0.4s, v16.4s, v19.4s
	WORD $0x4eb28621 // add v1.4s, v17.4s, v18.4s
	WORD $0x6eb28622 // sub v2.4s, v17.4s, v18.4s
	WORD $0x6eb38603 // sub v3.4s, v16.4s, v19.4s
	WORD $0x4eb41e84 // mov v4.16b, v20.16b
	WORD $0x4f9e82d8 // mul v24.4s, v22.4s, v30.s[0]
	WORD $0x6f9e42b8 // mls v24.4s, v21.4s, v30.s[0]
	WORD $0x4f332705 // srshr v5.4s, v24.4s, #13
	WORD $0x4f9e82d8 // mul v24.4s, v22.4s, v30.s[0]
	WORD $0x6f9e02b8 // mla v24.4s, v21.4s, v30.s[0]
	WORD $0x4f332706 // srshr v6.4s, v24.4s, #13
	WORD $0x4eb71ee7 // mov v7.16b, v23.16b
	WORD $0x4f9e8018 // mul v24.4s, v0.4s, v30.s[0]
	WORD $0x6f9e0038 // mla v24.4s, v1.4s, v30.s[0]
	WORD $0x4f332710 // srshr v16.4s, v24.4s, #13
	WORD $0x4f9e8018 // mul v24.4s, v0.4s, v30.s[0]
	WORD $0x6f9e4038 // mls v24.4s, v1.4s, v30.s[0]
	WORD $0x4f332711 // srshr v17.4s, v24.4s, #13
	WORD $0x4f9e8858 // mul v24.4s, v2.4s, v30.s[2]
	WORD $0x6fbe0078 // mla v24.4s, v3.4s, v30.s[1]
	WORD $0x4f332712 // srshr v18.4s, v24.4s, #13
	WORD $0x4f9e8878 // mul v24.4s, v3.4s, v30.s[2]
	WORD $0x6fbe4058 // mls v24.4s, v2.4s, v30.s[1]
	WORD $0x4f332713 // srshr v19.4s, v24.4s, #13
	WORD $0x4ea58494 // add v20.4s, v4.4s, v5.4s
	WORD $0x6ea58495 // sub v21.4s, v4.4s, v5.4s
	WORD $0x6ea684f6 // sub v22.4s, v7.4s, v6.4s
	WORD $0x4ea684f7 // add v23.4s, v7.4s, v6.4s
	WORD $0x4eb01e00 // mov v0.16b, v16.16b
	WORD $0x4eb11e24 // mov v4.16b, v17.16b
	WORD $0x4eb21e42 // mov v2.16b, v18.16b
	WORD $0x4eb31e66 // mov v6.16b, v19.16b
	WORD $0x4f9f8a98 // mul v24.4s, v20.4s, v31.s[2]
	WORD $0x6fbe0af8 // mla v24.4s, v23.4s, v30.s[3]
	WORD $0x4f332701 // srshr v1.4s, v24.4s, #13
	WORD $0x4f9f82b8 // mul v24.4s, v21.4s, v31.s[0]
	WORD $0x6fbf02d8 // mla v24.4s, v22.4s, v31.s[1]
	WORD $0x4f332705 // srshr v5.4s, v24.4s, #13
	WORD $0x4f9f82d8 // mul v24.4s, v22.4s, v31.s[0]
	WORD $0x6fbf42b8 // mls v24.4s, v21.4s, v31.s[1]
	WORD $0x4f332703 // srshr v3.4s, v24.4s, #13
	WORD $0x4f9f8af8 // mul v24.4s, v23.4s, v31.s[2]
	WORD $0x6fbe4a98 // mls v24.4s, v20.4s, v30.s[3]
	WORD $0x4f332707 // srshr v7.4s, v24.4s, #13
	WORD $0x4f210410 // sshr v16.4s, v0.4s, #31
	WORD $0x4eb08400 // add v0.4s, v0.4s, v16.4s
	WORD $0x4ebd8400 // add v0.4s, v0.4s, v29.4s
	WORD $0x4f3f0400 // sshr v0.4s, v0.4s, #1
	WORD $0x4f210430 // sshr v16.4s, v1.4s, #31
	WORD $0x4eb08421 // add v1.4s, v1.4s, v16.4s
	WORD $0x4ebd8421 // add v1.4s, v1.4s, v29.4s
	WORD $0x4f3f0421 // sshr v1.4s, v1.4s, #1
	WORD $0x4f210450 // sshr v16.4s, v2.4s, #31
	WORD $0x4eb08442 // add v2.4s, v2.4s, v16.4s
	WORD $0x4ebd8442 // add v2.4s, v2.4s, v29.4s
	WORD $0x4f3f0442 // sshr v2.4s, v2.4s, #1
	WORD $0x4f210470 // sshr v16.4s, v3.4s, #31
	WORD $0x4eb08463 // add v3.4s, v3.4s, v16.4s
	WORD $0x4ebd8463 // add v3.4s, v3.4s, v29.4s
	WORD $0x4f3f0463 // sshr v3.4s, v3.4s, #1
	WORD $0x4f210490 // sshr v16.4s, v4.4s, #31
	WORD $0x4eb08484 // add v4.4s, v4.4s, v16.4s
	WORD $0x4ebd8484 // add v4.4s, v4.4s, v29.4s
	WORD $0x4f3f0484 // sshr v4.4s, v4.4s, #1
	WORD $0x4f2104b0 // sshr v16.4s, v5.4s, #31
	WORD $0x4eb084a5 // add v5.4s, v5.4s, v16.4s
	WORD $0x4ebd84a5 // add v5.4s, v5.4s, v29.4s
	WORD $0x4f3f04a5 // sshr v5.4s, v5.4s, #1
	WORD $0x4f2104d0 // sshr v16.4s, v6.4s, #31
	WORD $0x4eb084c6 // add v6.4s, v6.4s, v16.4s
	WORD $0x4ebd84c6 // add v6.4s, v6.4s, v29.4s
	WORD $0x4f3f04c6 // sshr v6.4s, v6.4s, #1
	WORD $0x4f2104f0 // sshr v16.4s, v7.4s, #31
	WORD $0x4eb084e7 // add v7.4s, v7.4s, v16.4s
	WORD $0x4ebd84e7 // add v7.4s, v7.4s, v29.4s
	WORD $0x4f3f04e7 // sshr v7.4s, v7.4s, #1
	WORD $0x4eaf8510 // add v16.4s, v8.4s, v15.4s
	WORD $0x4eae8531 // add v17.4s, v9.4s, v14.4s
	WORD $0x4ead8552 // add v18.4s, v10.4s, v13.4s
	WORD $0x4eac8573 // add v19.4s, v11.4s, v12.4s
	WORD $0x6eac8574 // sub v20.4s, v11.4s, v12.4s
	WORD $0x6ead8555 // sub v21.4s, v10.4s, v13.4s
	WORD $0x6eae8536 // sub v22.4s, v9.4s, v14.4s
	WORD $0x6eaf8517 // sub v23.4s, v8.4s, v15.4s
	WORD $0x4eb38608 // add v8.4s, v16.4s, v19.4s
	WORD $0x4eb28629 // add v9.4s, v17.4s, v18.4s
	WORD $0x6eb2862a // sub v10.4s, v17.4s, v18.4s
	WORD $0x6eb3860b // sub v11.4s, v16.4s, v19.4s
	WORD $0x4eb41e8c // mov v12.16b, v20.16b
	WORD $0x4f9e82d8 // mul v24.4s, v22.4s, v30.s[0]
	WORD $0x6f9e42b8 // mls v24.4s, v21.4s, v30.s[0]
	WORD $0x4f33270d // srshr v13.4s, v24.4s, #13
	WORD $0x4f9e82d8 // mul v24.4s, v22.4s, v30.s[0]
	WORD $0x6f9e02b8 // mla v24.4s, v21.4s, v30.s[0]
	WORD $0x4f33270e // srshr v14.4s, v24.4s, #13
	WORD $0x4eb71eef // mov v15.16b, v23.16b
	WORD $0x4f9e8118 // mul v24.4s, v8.4s, v30.s[0]
	WORD $0x6f9e0138 // mla v24.4s, v9.4s, v30.s[0]
	WORD $0x4f332710 // srshr v16.4s, v24.4s, #13
	WORD $0x4f9e8118 // mul v24.4s, v8.4s, v30.s[0]
	WORD $0x6f9e4138 // mls v24.4s, v9.4s, v30.s[0]
	WORD $0x4f332711 // srshr v17.4s, v24.4s, #13
	WORD $0x4f9e8958 // mul v24.4s, v10.4s, v30.s[2]
	WORD $0x6fbe0178 // mla v24.4s, v11.4s, v30.s[1]
	WORD $0x4f332712 // srshr v18.4s, v24.4s, #13
	WORD $0x4f9e8978 // mul v24.4s, v11.4s, v30.s[2]
	WORD $0x6fbe4158 // mls v24.4s, v10.4s, v30.s[1]
	WORD $0x4f332713 // srshr v19.4s, v24.4s, #13
	WORD $0x4ead8594 // add v20.4s, v12.4s, v13.4s
	WORD $0x6ead8595 // sub v21.4s, v12.4s, v13.4s
	WORD $0x6eae85f6 // sub v22.4s, v15.4s, v14.4s
	WORD $0x4eae85f7 // add v23.4s, v15.4s, v14.4s
	WORD $0x4eb01e08 // mov v8.16b, v16.16b
	WORD $0x4eb11e2c // mov v12.16b, v17.16b
	WORD $0x4eb21e4a // mov v10.16b, v18.16b
	WORD $0x4eb31e6e // mov v14.16b, v19.16b
	WORD $0x4f9f8a98 // mul v24.4s, v20.4s, v31.s[2]
	WORD $0x6fbe0af8 // mla v24.4s, v23.4s, v30.s[3]
	WORD $0x4f332709 // srshr v9.4s, v24.4s, #13
	WORD $0x4f9f82b8 // mul v24.4s, v21.4s, v31.s[0]
	WORD $0x6fbf02d8 // mla v24.4s, v22.4s, v31.s[1]
	WORD $0x4f33270d // srshr v13.4s, v24.4s, #13
	WORD $0x4f9f82d8 // mul v24.4s, v22.4s, v31.s[0]
	WORD $0x6fbf42b8 // mls v24.4s, v21.4s, v31.s[1]
	WORD $0x4f33270b // srshr v11.4s, v24.4s, #13
	WORD $0x4f9f8af8 // mul v24.4s, v23.4s, v31.s[2]
	WORD $0x6fbe4a98 // mls v24.4s, v20.4s, v30.s[3]
	WORD $0x4f33270f // srshr v15.4s, v24.4s, #13
	WORD $0x4f210510 // sshr v16.4s, v8.4s, #31
	WORD $0x4eb08508 // add v8.4s, v8.4s, v16.4s
	WORD $0x4ebd8508 // add v8.4s, v8.4s, v29.4s
	WORD $0x4f3f0508 // sshr v8.4s, v8.4s, #1
	WORD $0x4f210530 // sshr v16.4s, v9.4s, #31
	WORD $0x4eb08529 // add v9.4s, v9.4s, v16.4s
	WORD $0x4ebd8529 // add v9.4s, v9.4s, v29.4s
	WORD $0x4f3f0529 // sshr v9.4s, v9.4s, #1
	WORD $0x4f210550 // sshr v16.4s, v10.4s, #31
	WORD $0x4eb0854a // add v10.4s, v10.4s, v16.4s
	WORD $0x4ebd854a // add v10.4s, v10.4s, v29.4s
	WORD $0x4f3f054a // sshr v10.4s, v10.4s, #1
	WORD $0x4f210570 // sshr v16.4s, v11.4s, #31
	WORD $0x4eb0856b // add v11.4s, v11.4s, v16.4s
	WORD $0x4ebd856b // add v11.4s, v11.4s, v29.4s
	WORD $0x4f3f056b // sshr v11.4s, v11.4s, #1
	WORD $0x4f210590 // sshr v16.4s, v12.4s, #31
	WORD $0x4eb0858c // add v12.4s, v12.4s, v16.4s
	WORD $0x4ebd858c // add v12.4s, v12.4s, v29.4s
	WORD $0x4f3f058c // sshr v12.4s, v12.4s, #1
	WORD $0x4f2105b0 // sshr v16.4s, v13.4s, #31
	WORD $0x4eb085ad // add v13.4s, v13.4s, v16.4s
	WORD $0x4ebd85ad // add v13.4s, v13.4s, v29.4s
	WORD $0x4f3f05ad // sshr v13.4s, v13.4s, #1
	WORD $0x4f2105d0 // sshr v16.4s, v14.4s, #31
	WORD $0x4eb085ce // add v14.4s, v14.4s, v16.4s
	WORD $0x4ebd85ce // add v14.4s, v14.4s, v29.4s
	WORD $0x4f3f05ce // sshr v14.4s, v14.4s, #1
	WORD $0x4f2105f0 // sshr v16.4s, v15.4s, #31
	WORD $0x4eb085ef // add v15.4s, v15.4s, v16.4s
	WORD $0x4ebd85ef // add v15.4s, v15.4s, v29.4s
	WORD $0x4f3f05ef // sshr v15.4s, v15.4s, #1

	// Transpose the 8x8 int32 matrix held as rows (V0-V7 | V8-V15).
	WORD $0x4e812810 // trn1 v16.4s, v0.4s, v1.4s
	WORD $0x4e816811 // trn2 v17.4s, v0.4s, v1.4s
	WORD $0x4e832852 // trn1 v18.4s, v2.4s, v3.4s
	WORD $0x4e836853 // trn2 v19.4s, v2.4s, v3.4s
	WORD $0x4ed23a00 // zip1 v0.2d, v16.2d, v18.2d
	WORD $0x4ed33a21 // zip1 v1.2d, v17.2d, v19.2d
	WORD $0x4ed27a02 // zip2 v2.2d, v16.2d, v18.2d
	WORD $0x4ed37a23 // zip2 v3.2d, v17.2d, v19.2d
	WORD $0x4e892910 // trn1 v16.4s, v8.4s, v9.4s
	WORD $0x4e896911 // trn2 v17.4s, v8.4s, v9.4s
	WORD $0x4e8b2952 // trn1 v18.4s, v10.4s, v11.4s
	WORD $0x4e8b6953 // trn2 v19.4s, v10.4s, v11.4s
	WORD $0x4ed23a08 // zip1 v8.2d, v16.2d, v18.2d
	WORD $0x4ed33a29 // zip1 v9.2d, v17.2d, v19.2d
	WORD $0x4ed27a0a // zip2 v10.2d, v16.2d, v18.2d
	WORD $0x4ed37a2b // zip2 v11.2d, v17.2d, v19.2d
	WORD $0x4e852890 // trn1 v16.4s, v4.4s, v5.4s
	WORD $0x4e856891 // trn2 v17.4s, v4.4s, v5.4s
	WORD $0x4e8728d2 // trn1 v18.4s, v6.4s, v7.4s
	WORD $0x4e8768d3 // trn2 v19.4s, v6.4s, v7.4s
	WORD $0x4ed23a04 // zip1 v4.2d, v16.2d, v18.2d
	WORD $0x4ed33a25 // zip1 v5.2d, v17.2d, v19.2d
	WORD $0x4ed27a06 // zip2 v6.2d, v16.2d, v18.2d
	WORD $0x4ed37a27 // zip2 v7.2d, v17.2d, v19.2d
	WORD $0x4e8d2990 // trn1 v16.4s, v12.4s, v13.4s
	WORD $0x4e8d6991 // trn2 v17.4s, v12.4s, v13.4s
	WORD $0x4e8f29d2 // trn1 v18.4s, v14.4s, v15.4s
	WORD $0x4e8f69d3 // trn2 v19.4s, v14.4s, v15.4s
	WORD $0x4ed23a0c // zip1 v12.2d, v16.2d, v18.2d
	WORD $0x4ed33a2d // zip1 v13.2d, v17.2d, v19.2d
	WORD $0x4ed27a0e // zip2 v14.2d, v16.2d, v18.2d
	WORD $0x4ed37a2f // zip2 v15.2d, v17.2d, v19.2d

	// Row pass: lo lane group is (V0-V3, V8-V11), hi is (V4-V7, V12-V15).
	WORD $0x4eab8410 // add v16.4s, v0.4s, v11.4s
	WORD $0x4eaa8431 // add v17.4s, v1.4s, v10.4s
	WORD $0x4ea98452 // add v18.4s, v2.4s, v9.4s
	WORD $0x4ea88473 // add v19.4s, v3.4s, v8.4s
	WORD $0x6ea88474 // sub v20.4s, v3.4s, v8.4s
	WORD $0x6ea98455 // sub v21.4s, v2.4s, v9.4s
	WORD $0x6eaa8436 // sub v22.4s, v1.4s, v10.4s
	WORD $0x6eab8417 // sub v23.4s, v0.4s, v11.4s
	WORD $0x4eb38600 // add v0.4s, v16.4s, v19.4s
	WORD $0x4eb28621 // add v1.4s, v17.4s, v18.4s
	WORD $0x6eb28622 // sub v2.4s, v17.4s, v18.4s
	WORD $0x6eb38603 // sub v3.4s, v16.4s, v19.4s
	WORD $0x4eb41e88 // mov v8.16b, v20.16b
	WORD $0x4f9e82d8 // mul v24.4s, v22.4s, v30.s[0]
	WORD $0x6f9e42b8 // mls v24.4s, v21.4s, v30.s[0]
	WORD $0x4f332709 // srshr v9.4s, v24.4s, #13
	WORD $0x4f9e82d8 // mul v24.4s, v22.4s, v30.s[0]
	WORD $0x6f9e02b8 // mla v24.4s, v21.4s, v30.s[0]
	WORD $0x4f33270a // srshr v10.4s, v24.4s, #13
	WORD $0x4eb71eeb // mov v11.16b, v23.16b
	WORD $0x4f9e8018 // mul v24.4s, v0.4s, v30.s[0]
	WORD $0x6f9e0038 // mla v24.4s, v1.4s, v30.s[0]
	WORD $0x4f332710 // srshr v16.4s, v24.4s, #13
	WORD $0x4f9e8018 // mul v24.4s, v0.4s, v30.s[0]
	WORD $0x6f9e4038 // mls v24.4s, v1.4s, v30.s[0]
	WORD $0x4f332711 // srshr v17.4s, v24.4s, #13
	WORD $0x4f9e8858 // mul v24.4s, v2.4s, v30.s[2]
	WORD $0x6fbe0078 // mla v24.4s, v3.4s, v30.s[1]
	WORD $0x4f332712 // srshr v18.4s, v24.4s, #13
	WORD $0x4f9e8878 // mul v24.4s, v3.4s, v30.s[2]
	WORD $0x6fbe4058 // mls v24.4s, v2.4s, v30.s[1]
	WORD $0x4f332713 // srshr v19.4s, v24.4s, #13
	WORD $0x4ea98514 // add v20.4s, v8.4s, v9.4s
	WORD $0x6ea98515 // sub v21.4s, v8.4s, v9.4s
	WORD $0x6eaa8576 // sub v22.4s, v11.4s, v10.4s
	WORD $0x4eaa8577 // add v23.4s, v11.4s, v10.4s
	WORD $0x4eb01e00 // mov v0.16b, v16.16b
	WORD $0x4eb11e28 // mov v8.16b, v17.16b
	WORD $0x4eb21e42 // mov v2.16b, v18.16b
	WORD $0x4eb31e6a // mov v10.16b, v19.16b
	WORD $0x4f9f8a98 // mul v24.4s, v20.4s, v31.s[2]
	WORD $0x6fbe0af8 // mla v24.4s, v23.4s, v30.s[3]
	WORD $0x4f332701 // srshr v1.4s, v24.4s, #13
	WORD $0x4f9f82b8 // mul v24.4s, v21.4s, v31.s[0]
	WORD $0x6fbf02d8 // mla v24.4s, v22.4s, v31.s[1]
	WORD $0x4f332709 // srshr v9.4s, v24.4s, #13
	WORD $0x4f9f82d8 // mul v24.4s, v22.4s, v31.s[0]
	WORD $0x6fbf42b8 // mls v24.4s, v21.4s, v31.s[1]
	WORD $0x4f332703 // srshr v3.4s, v24.4s, #13
	WORD $0x4f9f8af8 // mul v24.4s, v23.4s, v31.s[2]
	WORD $0x6fbe4a98 // mls v24.4s, v20.4s, v30.s[3]
	WORD $0x4f33270b // srshr v11.4s, v24.4s, #13
	WORD $0x4eaf8490 // add v16.4s, v4.4s, v15.4s
	WORD $0x4eae84b1 // add v17.4s, v5.4s, v14.4s
	WORD $0x4ead84d2 // add v18.4s, v6.4s, v13.4s
	WORD $0x4eac84f3 // add v19.4s, v7.4s, v12.4s
	WORD $0x6eac84f4 // sub v20.4s, v7.4s, v12.4s
	WORD $0x6ead84d5 // sub v21.4s, v6.4s, v13.4s
	WORD $0x6eae84b6 // sub v22.4s, v5.4s, v14.4s
	WORD $0x6eaf8497 // sub v23.4s, v4.4s, v15.4s
	WORD $0x4eb38604 // add v4.4s, v16.4s, v19.4s
	WORD $0x4eb28625 // add v5.4s, v17.4s, v18.4s
	WORD $0x6eb28626 // sub v6.4s, v17.4s, v18.4s
	WORD $0x6eb38607 // sub v7.4s, v16.4s, v19.4s
	WORD $0x4eb41e8c // mov v12.16b, v20.16b
	WORD $0x4f9e82d8 // mul v24.4s, v22.4s, v30.s[0]
	WORD $0x6f9e42b8 // mls v24.4s, v21.4s, v30.s[0]
	WORD $0x4f33270d // srshr v13.4s, v24.4s, #13
	WORD $0x4f9e82d8 // mul v24.4s, v22.4s, v30.s[0]
	WORD $0x6f9e02b8 // mla v24.4s, v21.4s, v30.s[0]
	WORD $0x4f33270e // srshr v14.4s, v24.4s, #13
	WORD $0x4eb71eef // mov v15.16b, v23.16b
	WORD $0x4f9e8098 // mul v24.4s, v4.4s, v30.s[0]
	WORD $0x6f9e00b8 // mla v24.4s, v5.4s, v30.s[0]
	WORD $0x4f332710 // srshr v16.4s, v24.4s, #13
	WORD $0x4f9e8098 // mul v24.4s, v4.4s, v30.s[0]
	WORD $0x6f9e40b8 // mls v24.4s, v5.4s, v30.s[0]
	WORD $0x4f332711 // srshr v17.4s, v24.4s, #13
	WORD $0x4f9e88d8 // mul v24.4s, v6.4s, v30.s[2]
	WORD $0x6fbe00f8 // mla v24.4s, v7.4s, v30.s[1]
	WORD $0x4f332712 // srshr v18.4s, v24.4s, #13
	WORD $0x4f9e88f8 // mul v24.4s, v7.4s, v30.s[2]
	WORD $0x6fbe40d8 // mls v24.4s, v6.4s, v30.s[1]
	WORD $0x4f332713 // srshr v19.4s, v24.4s, #13
	WORD $0x4ead8594 // add v20.4s, v12.4s, v13.4s
	WORD $0x6ead8595 // sub v21.4s, v12.4s, v13.4s
	WORD $0x6eae85f6 // sub v22.4s, v15.4s, v14.4s
	WORD $0x4eae85f7 // add v23.4s, v15.4s, v14.4s
	WORD $0x4eb01e04 // mov v4.16b, v16.16b
	WORD $0x4eb11e2c // mov v12.16b, v17.16b
	WORD $0x4eb21e46 // mov v6.16b, v18.16b
	WORD $0x4eb31e6e // mov v14.16b, v19.16b
	WORD $0x4f9f8a98 // mul v24.4s, v20.4s, v31.s[2]
	WORD $0x6fbe0af8 // mla v24.4s, v23.4s, v30.s[3]
	WORD $0x4f332705 // srshr v5.4s, v24.4s, #13
	WORD $0x4f9f82b8 // mul v24.4s, v21.4s, v31.s[0]
	WORD $0x6fbf02d8 // mla v24.4s, v22.4s, v31.s[1]
	WORD $0x4f33270d // srshr v13.4s, v24.4s, #13
	WORD $0x4f9f82d8 // mul v24.4s, v22.4s, v31.s[0]
	WORD $0x6fbf42b8 // mls v24.4s, v21.4s, v31.s[1]
	WORD $0x4f332707 // srshr v7.4s, v24.4s, #13
	WORD $0x4f9f8af8 // mul v24.4s, v23.4s, v31.s[2]
	WORD $0x6fbe4a98 // mls v24.4s, v20.4s, v30.s[3]
	WORD $0x4f33270f // srshr v15.4s, v24.4s, #13

	// Store: vector for output frequency c carries rows; lo half lanes
	// r0-3 and hi half lanes r4-7 of coeff[c*stride+r].
	VST1 [V0.S4], (R3)
	ADD $16, R3
	VST1 [V4.S4], (R3)
	SUB $16, R3
	ADD R4, R3
	VST1 [V1.S4], (R3)
	ADD $16, R3
	VST1 [V5.S4], (R3)
	SUB $16, R3
	ADD R4, R3
	VST1 [V2.S4], (R3)
	ADD $16, R3
	VST1 [V6.S4], (R3)
	SUB $16, R3
	ADD R4, R3
	VST1 [V3.S4], (R3)
	ADD $16, R3
	VST1 [V7.S4], (R3)
	SUB $16, R3
	ADD R4, R3
	VST1 [V8.S4], (R3)
	ADD $16, R3
	VST1 [V12.S4], (R3)
	SUB $16, R3
	ADD R4, R3
	VST1 [V9.S4], (R3)
	ADD $16, R3
	VST1 [V13.S4], (R3)
	SUB $16, R3
	ADD R4, R3
	VST1 [V10.S4], (R3)
	ADD $16, R3
	VST1 [V14.S4], (R3)
	SUB $16, R3
	ADD R4, R3
	VST1 [V11.S4], (R3)
	ADD $16, R3
	VST1 [V15.S4], (R3)
	SUB $16, R3
	RET

// fdct8Cospi holds the Q13 weights consumed by element index:
// v30 = [cospi32, cospi16, cospi48, cospi8], v31 = [cospi24, cospi40, cospi56, 0].
GLOBL ·fdct8Cospi(SB), RODATA|NOPTR, $32
DATA ·fdct8Cospi+0(SB)/4, $5793
DATA ·fdct8Cospi+4(SB)/4, $7568
DATA ·fdct8Cospi+8(SB)/4, $3135
DATA ·fdct8Cospi+12(SB)/4, $8035
DATA ·fdct8Cospi+16(SB)/4, $6811
DATA ·fdct8Cospi+20(SB)/4, $4551
DATA ·fdct8Cospi+24(SB)/4, $1598
DATA ·fdct8Cospi+28(SB)/4, $0


// NEON forward 4x4 DCT_DCT (fwd_txfm2d shape: shift {2,0,0}, cos_bit 13).
// One lane group: the column pass runs av1_fdct4 over the four row vectors
// (lanes are columns), the 4x4 int32 matrix transposes in registers, the
// row pass reruns the network, and its output row vectors are the
// coeff[c*stride+r] columns directly. Weights come from the shared
// fdct8Cospi table (s[0]=cospi32, s[1]=cospi16, s[2]=cospi48); rounding
// is SRSHR #13, exact for 8-bit residual ranges.

// func fdct4x4NEONAsm(ctx *fdct8x8NEONCtx)
TEXT ·fdct4x4NEONAsm(SB), NOSPLIT, $0-8
	MOVD ctx+0(FP), R0
	MOVD CTXIN(R0), R1
	MOVD CTXINSTRIDE(R0), R2  // residual stride in elements
	MOVD CTXOUT(R0), R3
	MOVD CTXOUTSTRIDE(R0), R4 // coeff stride in elements
	MOVD $·fdct8Cospi(SB), R5
	VLD1 (R5), [V30.S4]
	LSL  $1, R2 // stride bytes (int16)
	LSL  $2, R4 // stride bytes (int32)

	// Load the four residual rows, fusing shift[0]=2 into SSHLL.
	VLD1 (R1), [V16.H4]
	WORD $0x0f12a600 // sshll v0.4s, v16.4h, #2
	ADD  R2, R1
	VLD1 (R1), [V16.H4]
	WORD $0x0f12a601 // sshll v1.4s, v16.4h, #2
	ADD  R2, R1
	VLD1 (R1), [V16.H4]
	WORD $0x0f12a602 // sshll v2.4s, v16.4h, #2
	ADD  R2, R1
	VLD1 (R1), [V16.H4]
	WORD $0x0f12a603 // sshll v3.4s, v16.4h, #2

	// Column pass: stage 1 sums/differences, stage 2 butterflies.
	WORD $0x4ea38410 // add v16.4s, v0.4s, v3.4s
	WORD $0x4ea28431 // add v17.4s, v1.4s, v2.4s
	WORD $0x6ea28432 // sub v18.4s, v1.4s, v2.4s
	WORD $0x6ea38413 // sub v19.4s, v0.4s, v3.4s
	WORD $0x4f9e8218 // mul v24.4s, v16.4s, v30.s[0]
	WORD $0x6f9e0238 // mla v24.4s, v17.4s, v30.s[0]
	WORD $0x4f332704 // srshr v4.4s, v24.4s, #13
	WORD $0x4f9e8219 // mul v25.4s, v16.4s, v30.s[0]
	WORD $0x6f9e4239 // mls v25.4s, v17.4s, v30.s[0]
	WORD $0x4f332725 // srshr v5.4s, v25.4s, #13
	WORD $0x4f9e8a58 // mul v24.4s, v18.4s, v30.s[2]
	WORD $0x6fbe0278 // mla v24.4s, v19.4s, v30.s[1]
	WORD $0x4f332706 // srshr v6.4s, v24.4s, #13
	WORD $0x4f9e8a79 // mul v25.4s, v19.4s, v30.s[2]
	WORD $0x6fbe4259 // mls v25.4s, v18.4s, v30.s[1]
	WORD $0x4f332727 // srshr v7.4s, v25.4s, #13

	// Transpose the bit-reversed rows (v4=t0, v6=t2, v5=t1, v7=t3).
	WORD $0x4e862890 // trn1 v16.4s, v4.4s, v6.4s
	WORD $0x4e866891 // trn2 v17.4s, v4.4s, v6.4s
	WORD $0x4e8728b2 // trn1 v18.4s, v5.4s, v7.4s
	WORD $0x4e8768b3 // trn2 v19.4s, v5.4s, v7.4s
	WORD $0x4ed23a00 // zip1 v0.2d, v16.2d, v18.2d
	WORD $0x4ed33a21 // zip1 v1.2d, v17.2d, v19.2d
	WORD $0x4ed27a02 // zip2 v2.2d, v16.2d, v18.2d
	WORD $0x4ed37a23 // zip2 v3.2d, v17.2d, v19.2d

	// Row pass: same network.
	WORD $0x4ea38410 // add v16.4s, v0.4s, v3.4s
	WORD $0x4ea28431 // add v17.4s, v1.4s, v2.4s
	WORD $0x6ea28432 // sub v18.4s, v1.4s, v2.4s
	WORD $0x6ea38413 // sub v19.4s, v0.4s, v3.4s
	WORD $0x4f9e8218 // mul v24.4s, v16.4s, v30.s[0]
	WORD $0x6f9e0238 // mla v24.4s, v17.4s, v30.s[0]
	WORD $0x4f332704 // srshr v4.4s, v24.4s, #13
	WORD $0x4f9e8219 // mul v25.4s, v16.4s, v30.s[0]
	WORD $0x6f9e4239 // mls v25.4s, v17.4s, v30.s[0]
	WORD $0x4f332725 // srshr v5.4s, v25.4s, #13
	WORD $0x4f9e8a58 // mul v24.4s, v18.4s, v30.s[2]
	WORD $0x6fbe0278 // mla v24.4s, v19.4s, v30.s[1]
	WORD $0x4f332706 // srshr v6.4s, v24.4s, #13
	WORD $0x4f9e8a79 // mul v25.4s, v19.4s, v30.s[2]
	WORD $0x6fbe4259 // mls v25.4s, v18.4s, v30.s[1]
	WORD $0x4f332727 // srshr v7.4s, v25.4s, #13

	// Store coeff columns: t0, t2, t1, t3 are coeff rows 0..3.
	VST1 [V4.S4], (R3)
	ADD  R4, R3
	VST1 [V6.S4], (R3)
	ADD  R4, R3
	VST1 [V5.S4], (R3)
	ADD  R4, R3
	VST1 [V7.S4], (R3)
	RET
