// Code generated by gen_invglue_neon.py. DO NOT EDIT.
// SPDX-License-Identifier: BSD-2-Clause
//
// See LICENSE for the BSD-2-Clause grant.

//go:build arm64 && !purego

#include "textflag.h"

#define G_PTR 0
#define G_N 8
#define G_NSHIFT 16
#define G_MIN 24
#define G_MAX 32

// clampRoundNEONAsm rounds-and-shifts every int32 lane right by -NShift
// (zero passes through) and clamps to [Min, Max] in place; N is a
// multiple of eight.
TEXT ·clampRoundNEONAsm(SB), NOSPLIT, $0-8
	MOVD ctx+0(FP), R0
	MOVD G_PTR(R0), R1
	MOVD R1, R2
	MOVD G_N(R0), R3
	MOVD G_NSHIFT(R0), R4
	WORD $0x4e040c90 // dup v16.4s, w4
	MOVD G_MIN(R0), R5
	WORD $0x4e040cb1 // dup v17.4s, w5
	MOVD G_MAX(R0), R6
	WORD $0x4e040cd2 // dup v18.4s, w6
clamp_loop:
	WORD $0x4cdfa820 // ld1 {v0.4s, v1.4s}, [x1], #32
	WORD $0x4eb05400 // srshl v0.4s, v0.4s, v16.4s
	WORD $0x4eb05421 // srshl v1.4s, v1.4s, v16.4s
	WORD $0x4eb16400 // smax v0.4s, v0.4s, v17.4s
	WORD $0x4eb16421 // smax v1.4s, v1.4s, v17.4s
	WORD $0x4eb26c00 // smin v0.4s, v0.4s, v18.4s
	WORD $0x4eb26c21 // smin v1.4s, v1.4s, v18.4s
	WORD $0x4c9fa840 // st1 {v0.4s, v1.4s}, [x2], #32
	SUBS $8, R3, R3
	BNE clamp_loop
	RET

#define S_DST 0
#define S_DSTSTRIDE 8
#define S_SRC 16
#define S_WIDTH 24
#define S_HEIGHT 32

// narrowStoreNEONAsm writes the final residual rows: every int32 lane is
// rounding-shifted right by four and saturated to int16. Width is four or
// a multiple of eight; src rows are contiguous, dst rows DstStride int16
// elements apart.
TEXT ·narrowStoreNEONAsm(SB), NOSPLIT, $0-8
	MOVD ctx+0(FP), R0
	MOVD S_DST(R0), R1
	MOVD S_DSTSTRIDE(R0), R2
	MOVD S_SRC(R0), R3
	MOVD S_WIDTH(R0), R4
	MOVD S_HEIGHT(R0), R5
	MOVD $-4, R6
	WORD $0x4e040cd0 // dup v16.4s, w6
	LSL $1, R2, R2
	CMP $4, R4
	BEQ narrow_w4
narrow_row:
	MOVD R1, R7
	MOVD R4, R8
narrow_col:
	WORD $0x4cdfa860 // ld1 {v0.4s, v1.4s}, [x3], #32
	WORD $0x4eb05400 // srshl v0.4s, v0.4s, v16.4s
	WORD $0x4eb05421 // srshl v1.4s, v1.4s, v16.4s
	WORD $0x0e614802 // sqxtn v2.4h, v0.4s
	WORD $0x4e614822 // sqxtn2 v2.8h, v1.4s
	WORD $0x4c9f74e2 // st1 {v2.8h}, [x7], #16
	SUBS $8, R8, R8
	BNE narrow_col
	ADD R2, R1, R1
	SUBS $1, R5, R5
	BNE narrow_row
	RET
narrow_w4:
	MOVD R1, R7
	WORD $0x4cdf7860 // ld1 {v0.4s}, [x3], #16
	WORD $0x4eb05400 // srshl v0.4s, v0.4s, v16.4s
	WORD $0x0e614802 // sqxtn v2.4h, v0.4s
	WORD $0x0c9f74e2 // st1 {v2.4h}, [x7], #8
	ADD R2, R1, R1
	SUBS $1, R5, R5
	BNE narrow_w4
	RET
