// SPDX-License-Identifier: BSD-2-Clause
//
// See LICENSE for the BSD-2-Clause grant.

// Code generated by an offline NEON encoder; do not edit by hand.
// Every WORD below is the little-endian encoding of the mnemonic in its
// trailing comment, assembled and verified with the system assembler. The
// kernel is bit-exact with filterBlockPureGo (see filter.go); the Go wrapper
// in filter_neon_arm64.go restricts it to 8-wide blocks.

//go:build arm64 && !purego

#include "textflag.h"

#define DST 0
#define INPUT 8
#define DSTSTR 16
#define HEIGHT 24
#define PRI0 32
#define PRI1 40
#define SEC0 48
#define SEC1 56
#define SEC2 64
#define SEC3 72
#define PRITAP0 80
#define PRITAP1 88
#define SECTAP0 96
#define SECTAP1 104
#define PRISTRENGTH 112
#define SECSTRENGTH 120
#define PRISHIFT 128
#define SECSHIFT 136
#define ENABLEPRIMARY 144
#define ENABLESECONDARY 152
#define CLIPPING 160

// func filterBlockNEONAsm(ctx *filterBlockNEONCtx)
TEXT ·filterBlockNEONAsm(SB), NOSPLIT, $0-8
	MOVD ctx+0(FP), R0
	MOVD DST(R0), R1
	MOVD INPUT(R0), R2
	MOVD DSTSTR(R0), R3
	LSL  $1, R3, R3
	MOVD HEIGHT(R0), R4
	MOVD PRISTRENGTH(R0), R12
	WORD $0x4e020d81 // dup v1.8h, w12
	MOVD PRISHIFT(R0), R12
	NEG R12, R12
	WORD $0x4e020d82 // dup v2.8h, w12
	MOVD SECSTRENGTH(R0), R12
	WORD $0x4e020d83 // dup v3.8h, w12
	MOVD SECSHIFT(R0), R12
	NEG R12, R12
	WORD $0x4e020d84 // dup v4.8h, w12
	WORD $0x4f008405 // movi v5.8h, #0
	WORD $0x4f02a406 // movi v6.8h, #0x40, lsl #8
	MOVD PRITAP0(R0), R12
	WORD $0x4e021d87 // mov v7.h[0], w12
	MOVD PRITAP1(R0), R12
	WORD $0x4e061d87 // mov v7.h[1], w12
	MOVD SECTAP0(R0), R12
	WORD $0x4e0a1d87 // mov v7.h[2], w12
	MOVD SECTAP1(R0), R12
	WORD $0x4e0e1d87 // mov v7.h[3], w12
	MOVD ENABLEPRIMARY(R0), R20
	MOVD ENABLESECONDARY(R0), R21
	MOVD CLIPPING(R0), R22
	MOVD PRI0(R0), R6
	LSL $1, R6, R6
	MOVD PRI1(R0), R7
	LSL $1, R7, R7
	MOVD SEC0(R0), R8
	LSL $1, R8, R8
	MOVD SEC1(R0), R9
	LSL $1, R9, R9
	MOVD SEC2(R0), R10
	LSL $1, R10, R10
	MOVD SEC3(R0), R11
	LSL $1, R11, R11
	MOVD R2, R5
	MOVD $288, R14

rowLoop:
	CBZ R4, done
	WORD $0x4c4074a0 // ld1 {v0.8h}, [x5]
	WORD $0x4f000410 // movi v16.4s, #0
	WORD $0x4f000411 // movi v17.4s, #0
	CBZ R22, plainPath
	WORD $0x4ea01c12 // mov v18.16b, v0.16b
	WORD $0x4ea01c13 // mov v19.16b, v0.16b
	ADD R6, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e668e9a // cmeq v26.8h, v20.8h, v6.8h
	WORD $0x4eb41e9b // mov v27.16b, v20.16b
	WORD $0x6eba1cbb // bit v27.16b, v5.16b, v26.16b
	WORD $0x4e7b6652 // smax v18.8h, v18.8h, v27.8h
	WORD $0x4e746e73 // smin v19.8h, v19.8h, v20.8h
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6246b6 // ushl v22.8h, v21.8h, v2.8h
	WORD $0x6e768437 // sub v23.8h, v1.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f472330 // smlal v16.4s, v25.4h, v7.h[0]
	WORD $0x4f472331 // smlal2 v17.4s, v25.8h, v7.h[0]
	SUB R6, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e668e9a // cmeq v26.8h, v20.8h, v6.8h
	WORD $0x4eb41e9b // mov v27.16b, v20.16b
	WORD $0x6eba1cbb // bit v27.16b, v5.16b, v26.16b
	WORD $0x4e7b6652 // smax v18.8h, v18.8h, v27.8h
	WORD $0x4e746e73 // smin v19.8h, v19.8h, v20.8h
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6246b6 // ushl v22.8h, v21.8h, v2.8h
	WORD $0x6e768437 // sub v23.8h, v1.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f472330 // smlal v16.4s, v25.4h, v7.h[0]
	WORD $0x4f472331 // smlal2 v17.4s, v25.8h, v7.h[0]
	ADD R7, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e668e9a // cmeq v26.8h, v20.8h, v6.8h
	WORD $0x4eb41e9b // mov v27.16b, v20.16b
	WORD $0x6eba1cbb // bit v27.16b, v5.16b, v26.16b
	WORD $0x4e7b6652 // smax v18.8h, v18.8h, v27.8h
	WORD $0x4e746e73 // smin v19.8h, v19.8h, v20.8h
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6246b6 // ushl v22.8h, v21.8h, v2.8h
	WORD $0x6e768437 // sub v23.8h, v1.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f572330 // smlal v16.4s, v25.4h, v7.h[1]
	WORD $0x4f572331 // smlal2 v17.4s, v25.8h, v7.h[1]
	SUB R7, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e668e9a // cmeq v26.8h, v20.8h, v6.8h
	WORD $0x4eb41e9b // mov v27.16b, v20.16b
	WORD $0x6eba1cbb // bit v27.16b, v5.16b, v26.16b
	WORD $0x4e7b6652 // smax v18.8h, v18.8h, v27.8h
	WORD $0x4e746e73 // smin v19.8h, v19.8h, v20.8h
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6246b6 // ushl v22.8h, v21.8h, v2.8h
	WORD $0x6e768437 // sub v23.8h, v1.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f572330 // smlal v16.4s, v25.4h, v7.h[1]
	WORD $0x4f572331 // smlal2 v17.4s, v25.8h, v7.h[1]
	ADD R8, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e668e9a // cmeq v26.8h, v20.8h, v6.8h
	WORD $0x4eb41e9b // mov v27.16b, v20.16b
	WORD $0x6eba1cbb // bit v27.16b, v5.16b, v26.16b
	WORD $0x4e7b6652 // smax v18.8h, v18.8h, v27.8h
	WORD $0x4e746e73 // smin v19.8h, v19.8h, v20.8h
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6446b6 // ushl v22.8h, v21.8h, v4.8h
	WORD $0x6e768477 // sub v23.8h, v3.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f672330 // smlal v16.4s, v25.4h, v7.h[2]
	WORD $0x4f672331 // smlal2 v17.4s, v25.8h, v7.h[2]
	SUB R8, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e668e9a // cmeq v26.8h, v20.8h, v6.8h
	WORD $0x4eb41e9b // mov v27.16b, v20.16b
	WORD $0x6eba1cbb // bit v27.16b, v5.16b, v26.16b
	WORD $0x4e7b6652 // smax v18.8h, v18.8h, v27.8h
	WORD $0x4e746e73 // smin v19.8h, v19.8h, v20.8h
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6446b6 // ushl v22.8h, v21.8h, v4.8h
	WORD $0x6e768477 // sub v23.8h, v3.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f672330 // smlal v16.4s, v25.4h, v7.h[2]
	WORD $0x4f672331 // smlal2 v17.4s, v25.8h, v7.h[2]
	ADD R10, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e668e9a // cmeq v26.8h, v20.8h, v6.8h
	WORD $0x4eb41e9b // mov v27.16b, v20.16b
	WORD $0x6eba1cbb // bit v27.16b, v5.16b, v26.16b
	WORD $0x4e7b6652 // smax v18.8h, v18.8h, v27.8h
	WORD $0x4e746e73 // smin v19.8h, v19.8h, v20.8h
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6446b6 // ushl v22.8h, v21.8h, v4.8h
	WORD $0x6e768477 // sub v23.8h, v3.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f672330 // smlal v16.4s, v25.4h, v7.h[2]
	WORD $0x4f672331 // smlal2 v17.4s, v25.8h, v7.h[2]
	SUB R10, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e668e9a // cmeq v26.8h, v20.8h, v6.8h
	WORD $0x4eb41e9b // mov v27.16b, v20.16b
	WORD $0x6eba1cbb // bit v27.16b, v5.16b, v26.16b
	WORD $0x4e7b6652 // smax v18.8h, v18.8h, v27.8h
	WORD $0x4e746e73 // smin v19.8h, v19.8h, v20.8h
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6446b6 // ushl v22.8h, v21.8h, v4.8h
	WORD $0x6e768477 // sub v23.8h, v3.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f672330 // smlal v16.4s, v25.4h, v7.h[2]
	WORD $0x4f672331 // smlal2 v17.4s, v25.8h, v7.h[2]
	ADD R9, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e668e9a // cmeq v26.8h, v20.8h, v6.8h
	WORD $0x4eb41e9b // mov v27.16b, v20.16b
	WORD $0x6eba1cbb // bit v27.16b, v5.16b, v26.16b
	WORD $0x4e7b6652 // smax v18.8h, v18.8h, v27.8h
	WORD $0x4e746e73 // smin v19.8h, v19.8h, v20.8h
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6446b6 // ushl v22.8h, v21.8h, v4.8h
	WORD $0x6e768477 // sub v23.8h, v3.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f772330 // smlal v16.4s, v25.4h, v7.h[3]
	WORD $0x4f772331 // smlal2 v17.4s, v25.8h, v7.h[3]
	SUB R9, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e668e9a // cmeq v26.8h, v20.8h, v6.8h
	WORD $0x4eb41e9b // mov v27.16b, v20.16b
	WORD $0x6eba1cbb // bit v27.16b, v5.16b, v26.16b
	WORD $0x4e7b6652 // smax v18.8h, v18.8h, v27.8h
	WORD $0x4e746e73 // smin v19.8h, v19.8h, v20.8h
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6446b6 // ushl v22.8h, v21.8h, v4.8h
	WORD $0x6e768477 // sub v23.8h, v3.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f772330 // smlal v16.4s, v25.4h, v7.h[3]
	WORD $0x4f772331 // smlal2 v17.4s, v25.8h, v7.h[3]
	ADD R11, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e668e9a // cmeq v26.8h, v20.8h, v6.8h
	WORD $0x4eb41e9b // mov v27.16b, v20.16b
	WORD $0x6eba1cbb // bit v27.16b, v5.16b, v26.16b
	WORD $0x4e7b6652 // smax v18.8h, v18.8h, v27.8h
	WORD $0x4e746e73 // smin v19.8h, v19.8h, v20.8h
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6446b6 // ushl v22.8h, v21.8h, v4.8h
	WORD $0x6e768477 // sub v23.8h, v3.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f772330 // smlal v16.4s, v25.4h, v7.h[3]
	WORD $0x4f772331 // smlal2 v17.4s, v25.8h, v7.h[3]
	SUB R11, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e668e9a // cmeq v26.8h, v20.8h, v6.8h
	WORD $0x4eb41e9b // mov v27.16b, v20.16b
	WORD $0x6eba1cbb // bit v27.16b, v5.16b, v26.16b
	WORD $0x4e7b6652 // smax v18.8h, v18.8h, v27.8h
	WORD $0x4e746e73 // smin v19.8h, v19.8h, v20.8h
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6446b6 // ushl v22.8h, v21.8h, v4.8h
	WORD $0x6e768477 // sub v23.8h, v3.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f772330 // smlal v16.4s, v25.4h, v7.h[3]
	WORD $0x4f772331 // smlal2 v17.4s, v25.8h, v7.h[3]
	WORD $0x4f21061c // sshr v28.4s, v16.4s, #31
	WORD $0x4f21063d // sshr v29.4s, v17.4s, #31
	WORD $0x4f00051e // movi v30.4s, #8
	WORD $0x4ebe8610 // add v16.4s, v16.4s, v30.4s
	WORD $0x4ebe8631 // add v17.4s, v17.4s, v30.4s
	WORD $0x4ebc8610 // add v16.4s, v16.4s, v28.4s
	WORD $0x4ebd8631 // add v17.4s, v17.4s, v29.4s
	WORD $0x4f3c0610 // sshr v16.4s, v16.4s, #4
	WORD $0x4f3c0631 // sshr v17.4s, v17.4s, #4
	WORD $0x2f10a41e // ushll v30.4s, v0.4h, #0
	WORD $0x6f10a41f // ushll2 v31.4s, v0.8h, #0
	WORD $0x4ebe8610 // add v16.4s, v16.4s, v30.4s
	WORD $0x4ebf8631 // add v17.4s, v17.4s, v31.4s
	WORD $0x0f10a67e // sxtl v30.4s, v19.4h
	WORD $0x4f10a67f // sxtl2 v31.4s, v19.8h
	WORD $0x4ebe6610 // smax v16.4s, v16.4s, v30.4s
	WORD $0x4ebf6631 // smax v17.4s, v17.4s, v31.4s
	WORD $0x0f10a65e // sxtl v30.4s, v18.4h
	WORD $0x4f10a65f // sxtl2 v31.4s, v18.8h
	WORD $0x4ebe6e10 // smin v16.4s, v16.4s, v30.4s
	WORD $0x4ebf6e31 // smin v17.4s, v17.4s, v31.4s
	WORD $0x0e612a00 // xtn v0.4h, v16.4s
	WORD $0x4e612a20 // xtn2 v0.8h, v17.4s
	WORD $0x4c007420 // st1 {v0.8h}, [x1]
	B nextRow
plainPath:
	CBZ R20, plainNoPrimary
	ADD R6, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6246b6 // ushl v22.8h, v21.8h, v2.8h
	WORD $0x6e768437 // sub v23.8h, v1.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f472330 // smlal v16.4s, v25.4h, v7.h[0]
	WORD $0x4f472331 // smlal2 v17.4s, v25.8h, v7.h[0]
	SUB R6, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6246b6 // ushl v22.8h, v21.8h, v2.8h
	WORD $0x6e768437 // sub v23.8h, v1.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f472330 // smlal v16.4s, v25.4h, v7.h[0]
	WORD $0x4f472331 // smlal2 v17.4s, v25.8h, v7.h[0]
	ADD R7, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6246b6 // ushl v22.8h, v21.8h, v2.8h
	WORD $0x6e768437 // sub v23.8h, v1.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f572330 // smlal v16.4s, v25.4h, v7.h[1]
	WORD $0x4f572331 // smlal2 v17.4s, v25.8h, v7.h[1]
	SUB R7, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6246b6 // ushl v22.8h, v21.8h, v2.8h
	WORD $0x6e768437 // sub v23.8h, v1.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f572330 // smlal v16.4s, v25.4h, v7.h[1]
	WORD $0x4f572331 // smlal2 v17.4s, v25.8h, v7.h[1]
plainNoPrimary:
	CBZ R21, plainNoSecondary
	ADD R8, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6446b6 // ushl v22.8h, v21.8h, v4.8h
	WORD $0x6e768477 // sub v23.8h, v3.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f672330 // smlal v16.4s, v25.4h, v7.h[2]
	WORD $0x4f672331 // smlal2 v17.4s, v25.8h, v7.h[2]
	SUB R8, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6446b6 // ushl v22.8h, v21.8h, v4.8h
	WORD $0x6e768477 // sub v23.8h, v3.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f672330 // smlal v16.4s, v25.4h, v7.h[2]
	WORD $0x4f672331 // smlal2 v17.4s, v25.8h, v7.h[2]
	ADD R10, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6446b6 // ushl v22.8h, v21.8h, v4.8h
	WORD $0x6e768477 // sub v23.8h, v3.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f672330 // smlal v16.4s, v25.4h, v7.h[2]
	WORD $0x4f672331 // smlal2 v17.4s, v25.8h, v7.h[2]
	SUB R10, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6446b6 // ushl v22.8h, v21.8h, v4.8h
	WORD $0x6e768477 // sub v23.8h, v3.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f672330 // smlal v16.4s, v25.4h, v7.h[2]
	WORD $0x4f672331 // smlal2 v17.4s, v25.8h, v7.h[2]
	ADD R9, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6446b6 // ushl v22.8h, v21.8h, v4.8h
	WORD $0x6e768477 // sub v23.8h, v3.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f772330 // smlal v16.4s, v25.4h, v7.h[3]
	WORD $0x4f772331 // smlal2 v17.4s, v25.8h, v7.h[3]
	SUB R9, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6446b6 // ushl v22.8h, v21.8h, v4.8h
	WORD $0x6e768477 // sub v23.8h, v3.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f772330 // smlal v16.4s, v25.4h, v7.h[3]
	WORD $0x4f772331 // smlal2 v17.4s, v25.8h, v7.h[3]
	ADD R11, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6446b6 // ushl v22.8h, v21.8h, v4.8h
	WORD $0x6e768477 // sub v23.8h, v3.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f772330 // smlal v16.4s, v25.4h, v7.h[3]
	WORD $0x4f772331 // smlal2 v17.4s, v25.8h, v7.h[3]
	SUB R11, R5, R13
	WORD $0x4c4075b4 // ld1 {v20.8h}, [x13]
	WORD $0x6e608694 // sub v20.8h, v20.8h, v0.8h
	WORD $0x4e60ba95 // abs v21.8h, v20.8h
	WORD $0x6e6446b6 // ushl v22.8h, v21.8h, v4.8h
	WORD $0x6e768477 // sub v23.8h, v3.8h, v22.8h
	WORD $0x4e6566f7 // smax v23.8h, v23.8h, v5.8h
	WORD $0x4e756ef7 // smin v23.8h, v23.8h, v21.8h
	WORD $0x6e60baf8 // neg v24.8h, v23.8h
	WORD $0x4e60aa99 // cmlt v25.8h, v20.8h, #0
	WORD $0x6e771f19 // bsl v25.16b, v24.16b, v23.16b
	WORD $0x0f772330 // smlal v16.4s, v25.4h, v7.h[3]
	WORD $0x4f772331 // smlal2 v17.4s, v25.8h, v7.h[3]
plainNoSecondary:
	WORD $0x4f21061c // sshr v28.4s, v16.4s, #31
	WORD $0x4f21063d // sshr v29.4s, v17.4s, #31
	WORD $0x4f00051e // movi v30.4s, #8
	WORD $0x4ebe8610 // add v16.4s, v16.4s, v30.4s
	WORD $0x4ebe8631 // add v17.4s, v17.4s, v30.4s
	WORD $0x4ebc8610 // add v16.4s, v16.4s, v28.4s
	WORD $0x4ebd8631 // add v17.4s, v17.4s, v29.4s
	WORD $0x4f3c0610 // sshr v16.4s, v16.4s, #4
	WORD $0x4f3c0631 // sshr v17.4s, v17.4s, #4
	WORD $0x2f10a41e // ushll v30.4s, v0.4h, #0
	WORD $0x6f10a41f // ushll2 v31.4s, v0.8h, #0
	WORD $0x4ebe8610 // add v16.4s, v16.4s, v30.4s
	WORD $0x4ebf8631 // add v17.4s, v17.4s, v31.4s
	WORD $0x0e612a00 // xtn v0.4h, v16.4s
	WORD $0x4e612a20 // xtn2 v0.8h, v17.4s
	WORD $0x4c007420 // st1 {v0.8h}, [x1]
nextRow:
	ADD R14, R5, R5
	ADD R3, R1, R1
	SUB $1, R4, R4
	CBNZ R4, rowLoop
done:
	RET
