// SPDX-License-Identifier: BSD-2-Clause
//
// See LICENSE for the BSD-2-Clause grant.

// Code generated by an offline NEON encoder; do not edit by hand.
// Every WORD below is the little-endian encoding of the mnemonic in its
// trailing comment, assembled and verified with the system assembler. The
// kernel is bit-exact with dequantColumnPureGo (see dequant.go); the Go
// wrapper in dequant_neon_arm64.go handles the n%8 tail with the scalar
// reference and never invokes the asm when blocks8 == 0.

//go:build arm64 && !purego

#include "textflag.h"

#define DST 0
#define COEFF 8
#define BLOCKS8 16
#define SCALE 24
#define TXEG 32
#define DQMIN 40
#define DQMAX 48

// func dequantColumnNEONAsm(ctx *dequantColumnNEONCtx)
TEXT ·dequantColumnNEONAsm(SB), NOSPLIT, $0-8
	MOVD ctx+0(FP), R0
	MOVD DST(R0), R1
	MOVD COEFF(R0), R2
	MOVD BLOCKS8(R0), R3
	MOVD SCALE(R0), R8
	MOVD TXEG(R0), R9
	MOVD DQMIN(R0), R10
	MOVD DQMAX(R0), R11

	WORD $0x4f07d7e7 // movi v7.4s, #0xff, msl #16
	WORD $0x4e040d04 // dup v4.4s, w8   (scale)
	WORD $0x4e040d30 // dup v16.4s, w9  (-txScale)
	WORD $0x4e040d51 // dup v17.4s, w10 (dqMin)
	WORD $0x4e040d72 // dup v18.4s, w11 (dqMax)

loop:
	CBZ R3, done
	WORD $0x4c407440 // ld1 {v0.8h}, [x2]
	WORD $0x0f10a405 // sxtl v5.4s, v0.4h   (widen low 4 coeffs to int32)
	WORD $0x4f10a406 // sxtl2 v6.4s, v0.8h  (widen high 4 coeffs to int32)
	WORD $0x4ea0b8a2 // abs v2.4s, v5.4s    (magnitude, INT16_MIN-safe in int32)
	WORD $0x4ea0b8c3 // abs v3.4s, v6.4s
	WORD $0x4ea49c42 // mul v2.4s, v2.4s, v4.4s
	WORD $0x4ea49c63 // mul v3.4s, v3.4s, v4.4s
	WORD $0x4e271c42 // and v2.16b, v2.16b, v7.16b
	WORD $0x4e271c63 // and v3.16b, v3.16b, v7.16b
	WORD $0x4eb04442 // sshl v2.4s, v2.4s, v16.4s
	WORD $0x4eb04463 // sshl v3.4s, v3.4s, v16.4s
	WORD $0x4f2104a5 // sshr v5.4s, v5.4s, #31
	WORD $0x4f2104c6 // sshr v6.4s, v6.4s, #31
	WORD $0x6e251c42 // eor v2.16b, v2.16b, v5.16b
	WORD $0x6e261c63 // eor v3.16b, v3.16b, v6.16b
	WORD $0x6ea58442 // sub v2.4s, v2.4s, v5.4s
	WORD $0x6ea68463 // sub v3.4s, v3.4s, v6.4s
	WORD $0x4eb26c42 // smin v2.4s, v2.4s, v18.4s
	WORD $0x4eb26c63 // smin v3.4s, v3.4s, v18.4s
	WORD $0x4eb16442 // smax v2.4s, v2.4s, v17.4s
	WORD $0x4eb16463 // smax v3.4s, v3.4s, v17.4s
	WORD $0x4c00a822 // st1 {v2.4s, v3.4s}, [x1]

	ADD $16, R2, R2 // advance coeff by 8 int16
	ADD $32, R1, R1 // advance dst by 8 int32
	SUB $1, R3, R3
	B   loop

done:
	RET
