// SPDX-License-Identifier: BSD-2-Clause
//
// See LICENSE for the BSD-2-Clause grant.

// Code generated by an offline NEON encoder; do not edit by hand.
// Every WORD below is the little-endian encoding of the mnemonic in its
// trailing comment, assembled and verified with the system assembler. The
// kernel is bit-exact with blendGrainRowPureGo (see blend_overlap.go); the Go
// wrapper in blend_overlap_neon_arm64.go handles the (<8)-lane tail.

//go:build arm64 && !purego

#include "textflag.h"

#define DST 0
#define PREV 8
#define CUR 16
#define GROUPS 24
#define PREVWEIGHT 32
#define CURWEIGHT 36
#define GRAINMIN 40
#define GRAINMAX 44

// func blendGrainRowNEONAsm(ctx *blendGrainRowNEONCtx)
//
// v = prev*prevWeight + cur*curWeight in 32-bit lanes, then SRSHR #5 reproduces
// roundPowerOfTwo(v, 5) and SMAX/SMIN reproduce clipInt(v, grainMin, grainMax).
TEXT ·blendGrainRowNEONAsm(SB), NOSPLIT, $0-8
	MOVD ctx+0(FP), R0
	MOVD DST(R0), R1
	MOVD PREV(R0), R2
	MOVD CUR(R0), R3
	MOVD GROUPS(R0), R4

	MOVW PREVWEIGHT(R0), R5
	WORD $0x4e040ca6 // dup v6.4s, w5   prevWeight
	MOVW CURWEIGHT(R0), R5
	WORD $0x4e040ca7 // dup v7.4s, w5   curWeight
	MOVW GRAINMIN(R0), R5
	WORD $0x4e040cb0 // dup v16.4s, w5  grainMin
	MOVW GRAINMAX(R0), R5
	WORD $0x4e040cb1 // dup v17.4s, w5  grainMax

loop:
	CBZ R4, done
	WORD $0x4c407440 // ld1 {v0.8h}, [x2]   prev
	WORD $0x4c407461 // ld1 {v1.8h}, [x3]   cur

	WORD $0x0f10a402 // sshll  v2.4s, v0.4h, #0   prev lo
	WORD $0x4f10a403 // sshll2 v3.4s, v0.8h, #0   prev hi
	WORD $0x0f10a424 // sshll  v4.4s, v1.4h, #0   cur lo
	WORD $0x4f10a425 // sshll2 v5.4s, v1.8h, #0   cur hi

	WORD $0x4ea69c42 // mul v2.4s, v2.4s, v6.4s   prev_lo*prevWeight
	WORD $0x4ea79482 // mla v2.4s, v4.4s, v7.4s   + cur_lo*curWeight
	WORD $0x4ea69c63 // mul v3.4s, v3.4s, v6.4s   prev_hi*prevWeight
	WORD $0x4ea794a3 // mla v3.4s, v5.4s, v7.4s   + cur_hi*curWeight
	WORD $0x4f3b2442 // srshr v2.4s, v2.4s, #5    roundPowerOfTwo(.,5)
	WORD $0x4f3b2463 // srshr v3.4s, v3.4s, #5
	WORD $0x4eb06442 // smax v2.4s, v2.4s, v16.4s clip low
	WORD $0x4eb06463 // smax v3.4s, v3.4s, v16.4s
	WORD $0x4eb16c42 // smin v2.4s, v2.4s, v17.4s clip high
	WORD $0x4eb16c63 // smin v3.4s, v3.4s, v17.4s
	WORD $0x0e612842 // xtn  v2.4h, v2.4s
	WORD $0x4e612862 // xtn2 v2.8h, v3.4s
	WORD $0x4c007422 // st1 {v2.8h}, [x1]   dst

	ADD $16, R1, R1
	ADD $16, R2, R2
	ADD $16, R3, R3
	SUB $1, R4, R4
	B   loop

done:
	RET
