// SPDX-License-Identifier: BSD-2-Clause
//
// See LICENSE for the BSD-2-Clause grant.

// Code generated by an offline NEON encoder; do not edit by hand.
// Every WORD below is the little-endian encoding of the mnemonic in its
// trailing comment, assembled and verified with the system assembler. The
// kernel is bit-exact with scaleLUT10 (see scaling.go); the Go wrapper in
// build_scale_neon_arm64.go handles the (<8)-lane tail.

//go:build arm64 && !purego

#include "textflag.h"

#define SCALE 0
#define SRC 8
#define LUT 16
#define GROUPS 24

// func buildScaleRow10NEONAsm(ctx *buildScaleNEONCtx)
//
// 10-bit: interpolate between lut[x] and lut[x+1] with weight (idx&3)/4 via a
// signed rounding shift, mirroring scaleLUT10. The second gather index is
// capped at 255 so end==start when x==255 (interpolation collapses to lut[255]).
TEXT ·buildScaleRow10NEONAsm(SB), NOSPLIT, $0-8
	MOVD ctx+0(FP), R0
	MOVD SCALE(R0), R1
	MOVD SRC(R0), R2
	MOVD LUT(R0), R3
	MOVD GROUPS(R0), R4

	MOVD $1023, R5
	WORD $0x4e020cbc // dup v28.8h, w5   (1023 = 10-bit clamp)
	MOVD $3, R5
	WORD $0x4e020cbd // dup v29.8h, w5   (3 = rem mask, per 16-bit lane)
	MOVD $255, R5
	WORD $0x4e020cbe // dup v30.8h, w5   (255 = xhi cap and 0x00ff mask)
	MOVD $1, R5
	WORD $0x4e020cbf // dup v31.8h, w5   (1)

loop10:
	CBZ R4, done10
	WORD $0x4c407440 // ld1 {v0.8h}, [x2]           src samples
	WORD $0x6e7c6c00 // umin v0.8h, v0.8h, v28.8h    idx = min(src,1023)
	WORD $0x6f1e0401 // ushr v1.8h, v0.8h, #2        x = idx>>2
	WORD $0x4e3d1c02 // and v2.16b, v0.16b, v29.16b  rem = idx&3
	WORD $0x4e7f8423 // add v3.8h, v1.8h, v31.8h     x+1
	WORD $0x6e7e6c63 // umin v3.8h, v3.8h, v30.8h    xhi = min(x+1,255)

	// start = lut[x] into v4 low bytes.
	WORD $0x0e023c26 // umov w6, v1.h[0]
	ADD  R3, R6, R6
	WORD $0x0d4000c4 // ld1 {v4.b}[0], [x6]
	WORD $0x0e063c26 // umov w6, v1.h[1]
	ADD  R3, R6, R6
	WORD $0x0d4004c4 // ld1 {v4.b}[1], [x6]
	WORD $0x0e0a3c26 // umov w6, v1.h[2]
	ADD  R3, R6, R6
	WORD $0x0d4008c4 // ld1 {v4.b}[2], [x6]
	WORD $0x0e0e3c26 // umov w6, v1.h[3]
	ADD  R3, R6, R6
	WORD $0x0d400cc4 // ld1 {v4.b}[3], [x6]
	WORD $0x0e123c26 // umov w6, v1.h[4]
	ADD  R3, R6, R6
	WORD $0x0d4010c4 // ld1 {v4.b}[4], [x6]
	WORD $0x0e163c26 // umov w6, v1.h[5]
	ADD  R3, R6, R6
	WORD $0x0d4014c4 // ld1 {v4.b}[5], [x6]
	WORD $0x0e1a3c26 // umov w6, v1.h[6]
	ADD  R3, R6, R6
	WORD $0x0d4018c4 // ld1 {v4.b}[6], [x6]
	WORD $0x0e1e3c26 // umov w6, v1.h[7]
	ADD  R3, R6, R6
	WORD $0x0d401cc4 // ld1 {v4.b}[7], [x6]

	// end = lut[xhi] into v5 low bytes.
	WORD $0x0e023c66 // umov w6, v3.h[0]
	ADD  R3, R6, R6
	WORD $0x0d4000c5 // ld1 {v5.b}[0], [x6]
	WORD $0x0e063c66 // umov w6, v3.h[1]
	ADD  R3, R6, R6
	WORD $0x0d4004c5 // ld1 {v5.b}[1], [x6]
	WORD $0x0e0a3c66 // umov w6, v3.h[2]
	ADD  R3, R6, R6
	WORD $0x0d4008c5 // ld1 {v5.b}[2], [x6]
	WORD $0x0e0e3c66 // umov w6, v3.h[3]
	ADD  R3, R6, R6
	WORD $0x0d400cc5 // ld1 {v5.b}[3], [x6]
	WORD $0x0e123c66 // umov w6, v3.h[4]
	ADD  R3, R6, R6
	WORD $0x0d4010c5 // ld1 {v5.b}[4], [x6]
	WORD $0x0e163c66 // umov w6, v3.h[5]
	ADD  R3, R6, R6
	WORD $0x0d4014c5 // ld1 {v5.b}[5], [x6]
	WORD $0x0e1a3c66 // umov w6, v3.h[6]
	ADD  R3, R6, R6
	WORD $0x0d4018c5 // ld1 {v5.b}[6], [x6]
	WORD $0x0e1e3c66 // umov w6, v3.h[7]
	ADD  R3, R6, R6
	WORD $0x0d401cc5 // ld1 {v5.b}[7], [x6]

	WORD $0x2f08a484 // uxtl v4.8h, v4.8b            start (u16)
	WORD $0x2f08a4a5 // uxtl v5.8h, v5.8b            end   (u16)
	WORD $0x6e6484a6 // sub v6.8h, v5.8h, v4.8h      diff = end-start (signed)
	WORD $0x4e629cc6 // mul v6.8h, v6.8h, v2.8h      prod = diff*rem
	WORD $0x4f1e24c6 // srshr v6.8h, v6.8h, #2       roundPowerOfTwo(prod,2)
	WORD $0x4e6484c6 // add v6.8h, v6.8h, v4.8h      + start
	WORD $0x4e3e1cc6 // and v6.16b, v6.16b, v30.16b  & 0x00ff (uint8 truncate)
	WORD $0x4c007426 // st1 {v6.8h}, [x1]            scale

	ADD $16, R1, R1
	ADD $16, R2, R2
	SUB $1, R4, R4
	B   loop10

done10:
	RET
