// SPDX-License-Identifier: BSD-2-Clause
//
// See LICENSE for the BSD-2-Clause grant.

// Code generated by an offline NEON encoder; do not edit by hand.
// Every WORD below is the little-endian encoding of the mnemonic in its
// trailing comment, assembled and verified with the system assembler. The
// kernels are bit-exact with blendA64MaskPureGo (see blend.go) for the two
// supported mask layouts: no subsampling and 2x2 (subX && subY).
//
// Per group of eight columns:
//   - the per-pixel weight m is gathered (mask byte for no-sub; the round2 of
//     the four 2x2 neighbours for subX&&subY, via uaddlp + urshr #2),
//   - dst = (m*s0 + (64-m)*s1 + 32) >> 6 is computed in u32 lanes, matching
//     blendA64 / roundPowerOfTwoPositive(...,6) exactly,
//   - a violation accumulator records any s0>max, s1>max, or m>64 lane so the
//     Go wrapper returns ErrInvalidBlock, matching the reference verdict.
//
// v7 holds the constant 64, v28 the broadcast max. Registers v0..v7 and
// v16..v28 are used (no v8..v15 callee-saved clobber).

//go:build arm64 && !purego

#include "textflag.h"

// func blendA64NoSubNEONAsm(dst *uint16, dstStride uintptr, src0 *uint16, src0Stride uintptr, src1 *uint16, src1Stride uintptr, mask *uint8, maskStride uintptr, maxv uint32, groups uintptr, height uintptr) uint32
TEXT ·blendA64NoSubNEONAsm(SB), NOSPLIT, $0-92
	MOVD dst+0(FP), R0
	MOVD dstStride+8(FP), R1
	MOVD src0+16(FP), R2
	MOVD src0Stride+24(FP), R3
	MOVD src1+32(FP), R4
	MOVD src1Stride+40(FP), R5
	MOVD mask+48(FP), R6
	MOVD maskStride+56(FP), R7
	MOVW maxv+64(FP), R13
	MOVD groups+72(FP), R8
	MOVD height+80(FP), R9

	WORD $0x4f00e419 // movi v25.16b, #0   (violation accumulator)
	WORD $0x4e020dbc // dup v28.8h, w13    (max broadcast)
	WORD $0x4f028407 // movi v7.8h, #64

rowLoopN:
	CBZ  R9, doneN
	MOVD R0, R10 // dst cursor
	MOVD R2, R11 // src0 cursor
	MOVD R4, R12 // src1 cursor
	MOVD R6, R14 // mask cursor
	MOVD R8, R15 // groups remaining

colLoopN:
	CBZ  R15, rowAdvN
	WORD $0x4c407560 // ld1 {v0.8h}, [x11]   (src0)
	WORD $0x4c407581 // ld1 {v1.8h}, [x12]   (src1)
	WORD $0x0c4071c2 // ld1 {v2.8b}, [x14]   (mask)
	WORD $0x2f08a442 // uxtl v2.8h, v2.8b

	WORD $0x6e7c341a // cmhi v26.8h, v0.8h, v28.8h
	WORD $0x4eba1f39 // orr v25.16b, v25.16b, v26.16b
	WORD $0x6e7c343a // cmhi v26.8h, v1.8h, v28.8h
	WORD $0x4eba1f39 // orr v25.16b, v25.16b, v26.16b
	WORD $0x6e67345a // cmhi v26.8h, v2.8h, v7.8h
	WORD $0x4eba1f39 // orr v25.16b, v25.16b, v26.16b

	WORD $0x2f10a403 // uxtl v3.4s, v0.4h
	WORD $0x6f10a404 // uxtl2 v4.4s, v0.8h
	WORD $0x2f10a430 // uxtl v16.4s, v1.4h
	WORD $0x6f10a431 // uxtl2 v17.4s, v1.8h
	WORD $0x2f10a445 // uxtl v5.4s, v2.4h
	WORD $0x6f10a452 // uxtl2 v18.4s, v2.8h
	WORD $0x6e6284f3 // sub v19.8h, v7.8h, v2.8h
	WORD $0x2f10a674 // uxtl v20.4s, v19.4h
	WORD $0x6f10a675 // uxtl2 v21.4s, v19.8h
	WORD $0x4ea59c63 // mul v3.4s, v3.4s, v5.4s
	WORD $0x4eb29c84 // mul v4.4s, v4.4s, v18.4s
	WORD $0x4eb49603 // mla v3.4s, v16.4s, v20.4s
	WORD $0x4eb59624 // mla v4.4s, v17.4s, v21.4s
	WORD $0x4f010416 // movi v22.4s, #32
	WORD $0x4eb68463 // add v3.4s, v3.4s, v22.4s
	WORD $0x4eb68484 // add v4.4s, v4.4s, v22.4s
	WORD $0x6f3a0463 // ushr v3.4s, v3.4s, #6
	WORD $0x6f3a0484 // ushr v4.4s, v4.4s, #6
	WORD $0x0e612863 // xtn v3.4h, v3.4s
	WORD $0x4e612883 // xtn2 v3.8h, v4.4s
	WORD $0x4c007543 // st1 {v3.8h}, [x10]

	ADD  $16, R10, R10
	ADD  $16, R11, R11
	ADD  $16, R12, R12
	ADD  $8, R14, R14
	SUB  $1, R15, R15
	B    colLoopN

rowAdvN:
	ADD  R1, R0, R0
	ADD  R3, R2, R2
	ADD  R5, R4, R4
	ADD  R7, R6, R6
	SUB  $1, R9, R9
	B    rowLoopN

doneN:
	WORD $0x6e70ab3a // umaxv h26, v25.8h
	WORD $0x0e023f4e // umov w14, v26.h[0]
	MOVW R14, ret+88(FP)
	RET

// func blendA64SubXYNEONAsm(dst *uint16, dstStride uintptr, src0 *uint16, src0Stride uintptr, src1 *uint16, src1Stride uintptr, mask *uint8, maskStride uintptr, maxv uint32, groups uintptr, height uintptr) uint32
//
// 2x2 subsampled mask: each of the eight output weights is the round2 of the
// four neighbours mask[2r,2c], mask[2r+1,2c], mask[2r,2c+1], mask[2r+1,2c+1].
TEXT ·blendA64SubXYNEONAsm(SB), NOSPLIT, $0-92
	MOVD dst+0(FP), R0
	MOVD dstStride+8(FP), R1
	MOVD src0+16(FP), R2
	MOVD src0Stride+24(FP), R3
	MOVD src1+32(FP), R4
	MOVD src1Stride+40(FP), R5
	MOVD mask+48(FP), R6
	MOVD maskStride+56(FP), R7
	MOVW maxv+64(FP), R13
	MOVD groups+72(FP), R8
	MOVD height+80(FP), R9

	WORD $0x4f00e419 // movi v25.16b, #0
	WORD $0x4e020dbc // dup v28.8h, w13
	WORD $0x4f028407 // movi v7.8h, #64

rowLoopS:
	CBZ  R9, doneS
	MOVD R0, R10      // dst cursor
	MOVD R2, R11      // src0 cursor
	MOVD R4, R12      // src1 cursor
	MOVD R6, R14      // mask row 0 cursor
	ADD  R7, R14, R16 // mask row 1 cursor = mask0 + maskStride
	MOVD R8, R15      // groups remaining

colLoopS:
	CBZ  R15, rowAdvS
	WORD $0x4c407560 // ld1 {v0.8h}, [x11]   (src0)
	WORD $0x4c407581 // ld1 {v1.8h}, [x12]   (src1)
	WORD $0x4c4071c2 // ld1 {v2.16b}, [x14]  (mask row 0, 16 bytes)
	WORD $0x4c407217 // ld1 {v23.16b}, [x16] (mask row 1, 16 bytes)
	WORD $0x6e202842 // uaddlp v2.8h, v2.16b
	WORD $0x6e202af7 // uaddlp v23.8h, v23.16b
	WORD $0x4e778442 // add v2.8h, v2.8h, v23.8h
	WORD $0x6f1e2442 // urshr v2.8h, v2.8h, #2

	WORD $0x6e7c341a // cmhi v26.8h, v0.8h, v28.8h
	WORD $0x4eba1f39 // orr v25.16b, v25.16b, v26.16b
	WORD $0x6e7c343a // cmhi v26.8h, v1.8h, v28.8h
	WORD $0x4eba1f39 // orr v25.16b, v25.16b, v26.16b
	WORD $0x6e67345a // cmhi v26.8h, v2.8h, v7.8h
	WORD $0x4eba1f39 // orr v25.16b, v25.16b, v26.16b

	WORD $0x2f10a403 // uxtl v3.4s, v0.4h
	WORD $0x6f10a404 // uxtl2 v4.4s, v0.8h
	WORD $0x2f10a430 // uxtl v16.4s, v1.4h
	WORD $0x6f10a431 // uxtl2 v17.4s, v1.8h
	WORD $0x2f10a445 // uxtl v5.4s, v2.4h
	WORD $0x6f10a452 // uxtl2 v18.4s, v2.8h
	WORD $0x6e6284f3 // sub v19.8h, v7.8h, v2.8h
	WORD $0x2f10a674 // uxtl v20.4s, v19.4h
	WORD $0x6f10a675 // uxtl2 v21.4s, v19.8h
	WORD $0x4ea59c63 // mul v3.4s, v3.4s, v5.4s
	WORD $0x4eb29c84 // mul v4.4s, v4.4s, v18.4s
	WORD $0x4eb49603 // mla v3.4s, v16.4s, v20.4s
	WORD $0x4eb59624 // mla v4.4s, v17.4s, v21.4s
	WORD $0x4f010416 // movi v22.4s, #32
	WORD $0x4eb68463 // add v3.4s, v3.4s, v22.4s
	WORD $0x4eb68484 // add v4.4s, v4.4s, v22.4s
	WORD $0x6f3a0463 // ushr v3.4s, v3.4s, #6
	WORD $0x6f3a0484 // ushr v4.4s, v4.4s, #6
	WORD $0x0e612863 // xtn v3.4h, v3.4s
	WORD $0x4e612883 // xtn2 v3.8h, v4.4s
	WORD $0x4c007543 // st1 {v3.8h}, [x10]

	ADD  $16, R10, R10
	ADD  $16, R11, R11
	ADD  $16, R12, R12
	ADD  $16, R14, R14
	ADD  $16, R16, R16
	SUB  $1, R15, R15
	B    colLoopS

rowAdvS:
	ADD  R1, R0, R0
	ADD  R3, R2, R2
	ADD  R5, R4, R4
	ADD  R7, R6, R6
	ADD  R7, R6, R6
	SUB  $1, R9, R9
	B    rowLoopS

doneS:
	WORD $0x6e70ab3a // umaxv h26, v25.8h
	WORD $0x0e023f4e // umov w14, v26.h[0]
	MOVW R14, ret+88(FP)
	RET
