package tile

import "github.com/thesyncim/goav1/internal/av1/motion"

const (
	MaxMVRefCandidates   = 2
	MaxRefMVStackSize    = 8
	UsableRefMVStackSize = 4
	RefMVCategoryLevel   = 640
)

// ReferenceMVCandidate mirrors libaom's CANDIDATE_MV/ref_mv_weight entry.
type ReferenceMVCandidate struct {
	This     motion.Vector
	Compound motion.Vector
	Weight   uint16
}

// ReferenceMVStack is the candidate stack generated by the reference-MV search.
type ReferenceMVStack struct {
	Candidates [MaxRefMVStackSize]ReferenceMVCandidate
	Count      int
}

// InterMVReferenceSet contains the stack-derived MV bases needed before MV
// residual syntax is applied.
type InterMVReferenceSet struct {
	Nearest  [2]motion.Vector
	Near     [2]motion.Vector
	Residual [2]motion.Vector
}

// DRLContext returns libaom's av1_drl_ctx()/dav1d's get_drl_context() value.
func (stack ReferenceMVStack) DRLContext(refIdx int) (int, error) {
	if err := stack.validate(); err != nil {
		return 0, err
	}
	if refIdx < 0 || refIdx+1 >= stack.Count {
		return 0, ErrInvalidDecodeState
	}
	cur := stack.Candidates[refIdx].Weight >= RefMVCategoryLevel
	next := stack.Candidates[refIdx+1].Weight >= RefMVCategoryLevel
	switch {
	case cur && next:
		return 0, nil
	case cur && !next:
		return 1, nil
	case !cur && !next:
		return 2, nil
	default:
		return 0, nil
	}
}

// DRLContexts returns the three contexts read_drl_idx may consult.
func (stack ReferenceMVStack) DRLContexts() ([3]int, error) {
	var contexts [3]int
	if err := stack.validate(); err != nil {
		return contexts, err
	}
	for i := range contexts {
		if i+1 >= stack.Count {
			break
		}
		ctx, err := stack.DRLContext(i)
		if err != nil {
			return contexts, err
		}
		contexts[i] = ctx
	}
	return contexts, nil
}

// DRLRequestForMode builds the DRL syntax request for a decoded inter mode.
func (stack ReferenceMVStack) DRLRequestForMode(mode InterModeResult) (DRLRequest, error) {
	if mode.Compound {
		if !mode.CompoundMode.Valid() {
			return DRLRequest{}, ErrInvalidDecodeState
		}
	} else if !mode.Mode.Valid() {
		return DRLRequest{}, ErrInvalidDecodeState
	}
	contexts, err := stack.DRLContexts()
	if err != nil {
		return DRLRequest{}, err
	}
	return DRLRequest{
		Mode:         mode.Mode,
		CompoundMode: mode.CompoundMode,
		Compound:     mode.Compound,
		RefMVCount:   stack.Count,
		Contexts:     contexts,
	}, nil
}

// BestSingleReferenceMVs returns av1_find_best_ref_mvs()'s nearest/near pair.
func (stack ReferenceMVStack) BestSingleReferenceMVs(allowHighPrecision bool, forceInteger bool) (motion.Vector, motion.Vector, error) {
	if err := stack.validateCount(MaxMVRefCandidates); err != nil {
		return motion.Vector{}, motion.Vector{}, err
	}
	nearest := motion.LowerPrecision(stack.Candidates[0].This, allowHighPrecision, forceInteger)
	near := motion.LowerPrecision(stack.Candidates[1].This, allowHighPrecision, forceInteger)
	return nearest, near, nil
}

// ResolveInterMVReferences ports the stack-selection part of libaom's
// read_inter_block_mode_info()/assign_mv() path before MV residual bits.
func (stack ReferenceMVStack) ResolveInterMVReferences(mode InterModeResult, refMVIndex int, allowHighPrecision bool, forceInteger bool) (InterMVReferenceSet, error) {
	if err := stack.validate(); err != nil {
		return InterMVReferenceSet{}, err
	}
	if refMVIndex < 0 || refMVIndex >= UsableRefMVStackSize {
		return InterMVReferenceSet{}, ErrInvalidDecodeState
	}
	if mode.Compound {
		return stack.resolveCompoundInterMVReferences(mode.CompoundMode, refMVIndex, allowHighPrecision, forceInteger)
	}
	return stack.resolveSingleInterMVReferences(mode.Mode, refMVIndex, allowHighPrecision, forceInteger)
}

func (stack ReferenceMVStack) resolveSingleInterMVReferences(mode InterMode, refMVIndex int, allowHighPrecision bool, forceInteger bool) (InterMVReferenceSet, error) {
	if !mode.Valid() || mode == InterModeGlobalMV {
		return InterMVReferenceSet{}, ErrInvalidDecodeState
	}
	nearest, near, err := stack.BestSingleReferenceMVs(allowHighPrecision, forceInteger)
	if err != nil {
		return InterMVReferenceSet{}, err
	}
	if mode == InterModeNearMV && refMVIndex > 0 {
		candidate, err := stack.candidate(1 + refMVIndex)
		if err != nil {
			return InterMVReferenceSet{}, err
		}
		near = candidate.This
	}
	refs := InterMVReferenceSet{
		Nearest:  [2]motion.Vector{nearest},
		Near:     [2]motion.Vector{near},
		Residual: [2]motion.Vector{nearest},
	}
	if mode == InterModeNewMV && stack.Count > 1 {
		candidate, err := stack.candidate(refMVIndex)
		if err != nil {
			return InterMVReferenceSet{}, err
		}
		refs.Residual[0] = candidate.This
	}
	return refs, nil
}

func (stack ReferenceMVStack) resolveCompoundInterMVReferences(mode CompoundInterMode, refMVIndex int, allowHighPrecision bool, forceInteger bool) (InterMVReferenceSet, error) {
	if !mode.Valid() || mode == CompoundInterModeGlobalGlobal {
		return InterMVReferenceSet{}, ErrInvalidDecodeState
	}
	nearestCandidate, err := stack.candidate(0)
	if err != nil {
		return InterMVReferenceSet{}, err
	}
	nearCandidate, err := stack.candidate(1 + refMVIndex)
	if err != nil {
		return InterMVReferenceSet{}, err
	}
	refs := InterMVReferenceSet{
		Nearest: [2]motion.Vector{
			motion.LowerPrecision(nearestCandidate.This, allowHighPrecision, forceInteger),
			motion.LowerPrecision(nearestCandidate.Compound, allowHighPrecision, forceInteger),
		},
		Near: [2]motion.Vector{
			motion.LowerPrecision(nearCandidate.This, allowHighPrecision, forceInteger),
			motion.LowerPrecision(nearCandidate.Compound, allowHighPrecision, forceInteger),
		},
	}
	refs.Residual = refs.Nearest

	components, err := mode.Components()
	if err != nil {
		return InterMVReferenceSet{}, err
	}
	residualIndex := refMVIndex
	if mode == CompoundInterModeNearNew || mode == CompoundInterModeNewNear {
		residualIndex = 1 + refMVIndex
	}
	residualCandidate, err := stack.candidate(residualIndex)
	if err != nil {
		return InterMVReferenceSet{}, err
	}
	if components.First == InterModeNewMV {
		refs.Residual[0] = residualCandidate.This
	}
	if components.Second == InterModeNewMV {
		refs.Residual[1] = residualCandidate.Compound
	}
	return refs, nil
}

func (stack ReferenceMVStack) candidate(index int) (ReferenceMVCandidate, error) {
	if err := stack.validate(); err != nil {
		return ReferenceMVCandidate{}, err
	}
	if index < 0 || index >= stack.Count {
		return ReferenceMVCandidate{}, ErrInvalidDecodeState
	}
	return stack.Candidates[index], nil
}

func (stack ReferenceMVStack) validate() error {
	if stack.Count < 0 || stack.Count > MaxRefMVStackSize {
		return ErrInvalidDecodeState
	}
	return nil
}

func (stack ReferenceMVStack) validateCount(need int) error {
	if err := stack.validate(); err != nil {
		return err
	}
	if need < 0 || need > MaxRefMVStackSize || stack.Count < need {
		return ErrInvalidDecodeState
	}
	return nil
}
