package tile

import (
	"github.com/thesyncim/goav1/internal/av1/motion"
	"github.com/thesyncim/goav1/internal/av1/parser"
)

const (
	MaxMVRefCandidates   = 2
	MaxRefMVStackSize    = 8
	UsableRefMVStackSize = 4
	RefMVCategoryLevel   = 640
)

// InterMotionResult is the decoded inter mode plus its final motion vectors.
//
// Field order is chosen to minimize padding: the 4-byte-aligned MV pair comes
// first, then the byte-granular sub-structs and flag pack into the trailing
// 8 bytes with no interior gap (24 bytes total vs 28 for the naive ordering).
// This struct lives in large [MaxBlockModeSlots] and
// [MaxBlockModeSlots][MaxBlockModeSlots] grids inside BlockModeContext, so the
// 4-byte shrink removes several KiB from that hot context.
type InterMotionResult struct {
	MV         [2]motion.Vector
	References InterReferencesResult
	Mode       InterModeResult
	InterIntra bool
}

// ReferenceMVCandidate mirrors libaom's CANDIDATE_MV/ref_mv_weight entry.
type ReferenceMVCandidate struct {
	This     motion.Vector
	Compound motion.Vector
	Weight   uint16
}

// ReferenceMVStack is the candidate stack generated by the reference-MV search.
type ReferenceMVStack struct {
	Candidates     [MaxRefMVStackSize]ReferenceMVCandidate
	Count          uint8
	SingleRefMVs   [MaxMVRefCandidates]motion.Vector
	SingleRefValid bool
}

// ReferenceMVStackRequest selects the spatial MV stack for one inter block.
type ReferenceMVStackRequest struct {
	TemporalMVs *TemporalMotionField

	MICol uint32
	MIRow uint32

	TileMIColStart uint32
	TileMIRowStart uint32
	TileMIColEnd   uint32
	TileMIRowEnd   uint32

	// FrameMIRows and FrameMICols are the frame's MI grid extent, used to clamp
	// stack candidates to the frame boundary (libaom clamp_mv_ref).
	FrameMIRows uint32
	FrameMICols uint32

	GlobalMVs  [2]motion.Vector
	References InterReferencesResult

	Size             BlockSize
	X4               uint8
	Y4               uint8
	HaveTop          bool
	HaveLeft         bool
	HaveTopRight     bool
	GlobalMotionType [2]parser.GlobalMotionType
	RefSignBias      [referenceFrameCount]bool

	OrderHintBits        uint8
	CurrentOrderHint     uint8
	ReferenceOrderHints  [referenceFrameCount]uint8
	AllowHighPrecisionMV bool

	ForceIntegerMV              bool
	UseRefFrameMVS              bool
	TemporalMVSampleUnavailable bool
}

type ReferenceMVStackResult struct {
	Stack         ReferenceMVStack
	ModeContext   uint16
	NearestCount  uint8
	RowMatches    uint8
	ColumnMatches uint8
	NewMVMatches  uint8
}

type referenceMVStackSearch struct {
	Stack         ReferenceMVStack
	RowMatches    int
	ColumnMatches int
	NewMVMatches  int
}

// IntrabcReferenceDVStack returns the spatial DV candidates used by intrabc's
// INTRA_FRAME mv-ref search. Intrabc stores decoded DVs in the same neighbor
// grids as inter motion, but without inter reference frames.
func (c *BlockModeContext) IntrabcReferenceDVStack(req ReferenceMVStackRequest) (ReferenceMVStack, error) {
	dims, err := validateIntrabcReferenceDVStackRequest(req)
	if err != nil {
		return ReferenceMVStack{}, err
	}
	searchMaxRowOffset, searchMaxColOffset, _, _ := referenceMVSearchOffsets(req, dims)
	processedRows := 0
	processedCols := 0
	var stack ReferenceMVStack
	if req.HaveTop && absInt(searchMaxRowOffset) >= 1 {
		c.scanAboveIntrabcDVs(req, dims, searchMaxRowOffset, &processedRows, &stack)
	}
	if req.HaveLeft && absInt(searchMaxColOffset) >= 1 {
		c.scanLeftIntrabcDVs(req, dims, searchMaxColOffset, &processedCols, &stack)
	}
	if req.HaveTopRight {
		if candidate, _, ok := c.topRightInterMotion(req, dims); ok {
			stack.addOrWeight(ReferenceMVCandidate{This: candidate.MV[0]}, 4)
		}
	}
	nearestCount := int(stack.Count)
	for i := range nearestCount {
		stack.Candidates[i].Weight += RefMVCategoryLevel
	}
	// Pass the full tile-clamped offsets (not the in-SB grid-capped variants)
	// so cross-superblock outer scans reach into the prior SB's interior via
	// the SBTopInterMotionGrid / SBLeftInterMotionGrid snapshots, mirroring
	// libaom's frame-wide mi grid.
	c.scanOuterIntrabcDVs(req, dims, searchMaxRowOffset, searchMaxColOffset, processedRows, processedCols, &stack)
	sortReferenceMVStack(&stack, 0, nearestCount)
	sortReferenceMVStack(&stack, nearestCount, int(stack.Count))
	return stack, nil
}

// InterMVReferenceSet contains the stack-derived MV bases needed before MV
// residual syntax is applied.
type InterMVReferenceSet struct {
	Nearest  [2]motion.Vector
	Near     [2]motion.Vector
	Residual [2]motion.Vector
}

// DRLContext returns libaom's av1_drl_ctx()/dav1d's get_drl_context() value.
func (stack ReferenceMVStack) DRLContext(refIdx int) (int, error) {
	if err := stack.validate(); err != nil {
		return 0, err
	}
	if refIdx < 0 || refIdx+1 >= int(stack.Count) {
		return 0, ErrInvalidDecodeState
	}
	cur := stack.Candidates[refIdx].Weight >= RefMVCategoryLevel
	next := stack.Candidates[refIdx+1].Weight >= RefMVCategoryLevel
	switch {
	case cur && next:
		return 0, nil
	case cur && !next:
		return 1, nil
	case !cur && !next:
		return 2, nil
	default:
		return 0, nil
	}
}

// DRLContexts returns the three contexts read_drl_idx may consult.
func (stack ReferenceMVStack) DRLContexts() ([3]uint8, error) {
	var contexts [3]uint8
	if err := stack.validate(); err != nil {
		return contexts, err
	}
	for i := range contexts {
		if i+1 >= int(stack.Count) {
			break
		}
		ctx, err := stack.DRLContext(i)
		if err != nil {
			return contexts, err
		}
		contexts[i] = uint8(ctx)
	}
	return contexts, nil
}

// DRLRequestForMode builds the DRL syntax request for a decoded inter mode.
func (stack ReferenceMVStack) DRLRequestForMode(mode InterModeResult) (DRLRequest, error) {
	if mode.Compound {
		if !mode.CompoundMode.Valid() {
			return DRLRequest{}, ErrInvalidDecodeState
		}
	} else if !mode.Mode.Valid() {
		return DRLRequest{}, ErrInvalidDecodeState
	}
	contexts, err := stack.DRLContexts()
	if err != nil {
		return DRLRequest{}, err
	}
	return DRLRequest{
		Mode:         mode.Mode,
		CompoundMode: mode.CompoundMode,
		Compound:     mode.Compound,
		RefMVCount:   stack.Count,
		Contexts:     contexts,
	}, nil
}

// BestSingleReferenceMVs returns av1_find_best_ref_mvs()'s nearest/near pair.
func (stack ReferenceMVStack) BestSingleReferenceMVs(allowHighPrecision bool, forceInteger bool) (motion.Vector, motion.Vector, error) {
	if stack.SingleRefValid {
		nearest := motion.LowerPrecision(stack.SingleRefMVs[0], allowHighPrecision, forceInteger)
		near := motion.LowerPrecision(stack.SingleRefMVs[1], allowHighPrecision, forceInteger)
		return nearest, near, nil
	}
	if err := stack.validateCount(MaxMVRefCandidates); err != nil {
		return motion.Vector{}, motion.Vector{}, err
	}
	nearest := motion.LowerPrecision(stack.Candidates[0].This, allowHighPrecision, forceInteger)
	near := motion.LowerPrecision(stack.Candidates[1].This, allowHighPrecision, forceInteger)
	return nearest, near, nil
}

// ResolveInterMVReferences ports the stack-selection part of libaom's
// read_inter_block_mode_info()/assign_mv() path before MV residual bits.
func (stack ReferenceMVStack) ResolveInterMVReferences(mode InterModeResult, refMVIndex int, allowHighPrecision bool, forceInteger bool) (InterMVReferenceSet, error) {
	if err := stack.validate(); err != nil {
		return InterMVReferenceSet{}, err
	}
	if refMVIndex < 0 || refMVIndex >= UsableRefMVStackSize {
		return InterMVReferenceSet{}, ErrInvalidDecodeState
	}
	if mode.Compound {
		return stack.resolveCompoundInterMVReferences(mode.CompoundMode, refMVIndex, allowHighPrecision, forceInteger)
	}
	return stack.resolveSingleInterMVReferences(mode.Mode, refMVIndex, allowHighPrecision, forceInteger)
}

func (stack ReferenceMVStack) resolveSingleInterMVReferences(mode InterMode, refMVIndex int, allowHighPrecision bool, forceInteger bool) (InterMVReferenceSet, error) {
	if !mode.Valid() || mode == InterModeGlobalMV {
		return InterMVReferenceSet{}, ErrInvalidDecodeState
	}
	nearest, near, err := stack.BestSingleReferenceMVs(allowHighPrecision, forceInteger)
	if err != nil {
		return InterMVReferenceSet{}, err
	}
	if mode == InterModeNearMV && refMVIndex > 0 {
		candidate, err := stack.candidate(1 + refMVIndex)
		if err != nil {
			return InterMVReferenceSet{}, err
		}
		near = candidate.This
	}
	refs := InterMVReferenceSet{
		Nearest:  [2]motion.Vector{nearest},
		Near:     [2]motion.Vector{near},
		Residual: [2]motion.Vector{nearest},
	}
	if mode == InterModeNewMV && stack.Count > 1 {
		candidate, err := stack.candidate(refMVIndex)
		if err != nil {
			return InterMVReferenceSet{}, err
		}
		refs.Residual[0] = candidate.This
	}
	return refs, nil
}

func (stack ReferenceMVStack) resolveCompoundInterMVReferences(mode CompoundInterMode, refMVIndex int, allowHighPrecision bool, forceInteger bool) (InterMVReferenceSet, error) {
	if !mode.Valid() || mode == CompoundInterModeGlobalGlobal {
		return InterMVReferenceSet{}, ErrInvalidDecodeState
	}
	nearestCandidate, err := stack.candidate(0)
	if err != nil {
		return InterMVReferenceSet{}, err
	}
	refs := InterMVReferenceSet{
		Nearest: [2]motion.Vector{
			motion.LowerPrecision(nearestCandidate.This, allowHighPrecision, forceInteger),
			motion.LowerPrecision(nearestCandidate.Compound, allowHighPrecision, forceInteger),
		},
	}
	refs.Near = refs.Nearest
	if mode == CompoundInterModeNearNear || mode == CompoundInterModeNearNew || mode == CompoundInterModeNewNear {
		nearCandidate, err := stack.candidate(1 + refMVIndex)
		if err != nil {
			return InterMVReferenceSet{}, err
		}
		refs.Near = [2]motion.Vector{
			motion.LowerPrecision(nearCandidate.This, allowHighPrecision, forceInteger),
			motion.LowerPrecision(nearCandidate.Compound, allowHighPrecision, forceInteger),
		}
	}
	refs.Residual = refs.Nearest

	components, err := mode.Components()
	if err != nil {
		return InterMVReferenceSet{}, err
	}
	residualIndex := refMVIndex
	if mode == CompoundInterModeNearNew || mode == CompoundInterModeNewNear {
		residualIndex = 1 + refMVIndex
	}
	residualCandidate, err := stack.candidate(residualIndex)
	if err != nil {
		return InterMVReferenceSet{}, err
	}
	if components.First == InterModeNewMV {
		refs.Residual[0] = residualCandidate.This
	}
	if components.Second == InterModeNewMV {
		refs.Residual[1] = residualCandidate.Compound
	}
	return refs, nil
}

func (stack ReferenceMVStack) candidate(index int) (ReferenceMVCandidate, error) {
	if err := stack.validate(); err != nil {
		return ReferenceMVCandidate{}, err
	}
	if index < 0 || index >= int(stack.Count) {
		return ReferenceMVCandidate{}, ErrInvalidDecodeState
	}
	return stack.Candidates[index], nil
}

func (stack ReferenceMVStack) validate() error {
	if stack.Count > MaxRefMVStackSize {
		return ErrInvalidDecodeState
	}
	return nil
}

// MarkInterMotion updates the top/left context once a block's inter MVs are known.
func (c *BlockModeContext) MarkInterMotion(size BlockSize, x4 int, y4 int, result InterMotionResult, hasChroma bool) error {
	if err := validateInterMotion(result); err != nil {
		return err
	}
	if err := c.MarkInter(size, x4, y4, result.References, hasChroma); err != nil {
		return err
	}
	dims, ok := size.Dimensions()
	if !ok {
		return ErrInvalidDecodeState
	}
	for i := 0; i < int(dims.W4); i++ {
		c.AboveInterMotion[x4+i] = result
		c.AboveMotionValid[x4+i] = 1
		c.AboveBlockSize[x4+i] = size
	}
	for i := 0; i < int(dims.H4); i++ {
		c.LeftInterMotion[y4+i] = result
		c.LeftMotionValid[y4+i] = 1
		c.LeftBlockSize[y4+i] = size
	}
	c.markGridInterMotion(size, x4, y4, result, dims)
	return nil
}

// MarkIntrabcMotion updates top/left motion context for intra-block-copy DVs.
func (c *BlockModeContext) MarkIntrabcMotion(size BlockSize, x4 int, y4 int, result InterMotionResult, hasChroma bool) error {
	if c == nil || !result.Mode.Mode.Valid() {
		return ErrInvalidDecodeState
	}
	dims, ok := size.Dimensions()
	if !ok || x4 < 0 || y4 < 0 ||
		x4+int(dims.W4) > MaxBlockModeSlots ||
		y4+int(dims.H4) > MaxBlockModeSlots {
		return ErrInvalidDecodeState
	}
	for i := 0; i < int(dims.W4); i++ {
		c.AboveIntra[x4+i] = 0
		c.AboveMode[x4+i] = IntraModeDC
		if hasChroma {
			c.AboveChromaIntra[x4+i] = 0
			c.AboveChromaMode[x4+i] = ChromaIntraModeDC
		}
		c.AboveRef[0][x4+i] = ReferenceFrameNone
		c.AboveRef[1][x4+i] = ReferenceFrameNone
		c.AboveCompound[x4+i] = 0
		c.AboveInterMotion[x4+i] = result
		c.AboveMotionValid[x4+i] = 1
		c.AboveInterp[x4+i] = motion.InterpFilters{}
		c.AboveInterpValid[x4+i] = 0
		c.AboveBlockSize[x4+i] = size
		c.AbovePaletteY[x4+i] = paletteContext{}
		c.AbovePaletteUV[x4+i] = paletteContext{}
	}
	for i := 0; i < int(dims.H4); i++ {
		c.LeftIntra[y4+i] = 0
		c.LeftMode[y4+i] = IntraModeDC
		if hasChroma {
			c.LeftChromaIntra[y4+i] = 0
			c.LeftChromaMode[y4+i] = ChromaIntraModeDC
		}
		c.LeftRef[0][y4+i] = ReferenceFrameNone
		c.LeftRef[1][y4+i] = ReferenceFrameNone
		c.LeftCompound[y4+i] = 0
		c.LeftInterMotion[y4+i] = result
		c.LeftMotionValid[y4+i] = 1
		c.LeftInterp[y4+i] = motion.InterpFilters{}
		c.LeftInterpValid[y4+i] = 0
		c.LeftBlockSize[y4+i] = size
		c.LeftPaletteY[y4+i] = paletteContext{}
		c.LeftPaletteUV[y4+i] = paletteContext{}
	}
	c.markGridInterMotion(size, x4, y4, result, dims)
	return nil
}

func (c *BlockModeContext) markGridInterMotion(size BlockSize, x4 int, y4 int, result InterMotionResult, dims BlockDimensions) {
	for y := y4; y < y4+int(dims.H4); y++ {
		if y < 0 || y >= MaxBlockModeSlots {
			continue
		}
		for x := x4; x < x4+int(dims.W4); x++ {
			if x < 0 || x >= MaxBlockModeSlots {
				continue
			}
			c.GridInterMotion[y][x] = result
			c.GridMotionValid[y][x] = 1
			c.GridBlockSize[y][x] = size
			c.GridBlockSizeVisited[y][x] = 1
		}
	}
}

// clearGridInterMotion marks the block's grid cells as having no motion
// candidate (MotionValid=0) while preserving the block size so outer ref-MV
// scans can still advance by the candidate's mi_size step. libaom's
// scan_row_mbmi / scan_col_mbmi advance i += len = AOMMIN(xd->size,
// mi_size_*[candidate->bsize]) regardless of whether the candidate is inter
// or intra, so an intra neighbor consumes its full extent in the scan and
// blocks deeper in the column/row are skipped. Zeroing GridBlockSize would
// collapse the step to 1 (4x4) and let goav1's outer scan oversample cells
// libaom never visits, producing a spurious column/row match.
func (c *BlockModeContext) clearGridInterMotion(size BlockSize, x4 int, y4 int, dims BlockDimensions) {
	for y := y4; y < y4+int(dims.H4); y++ {
		if y < 0 || y >= MaxBlockModeSlots {
			continue
		}
		for x := x4; x < x4+int(dims.W4); x++ {
			if x < 0 || x >= MaxBlockModeSlots {
				continue
			}
			c.GridInterMotion[y][x] = InterMotionResult{}
			c.GridMotionValid[y][x] = 0
			c.GridBlockSize[y][x] = size
			c.GridBlockSizeVisited[y][x] = 1
		}
	}
}

// BuildReferenceMVStack ports the spatial part of libaom's setup_ref_mv_list()
// for the immediate above row and left column tracked by BlockModeContext.
func (c *BlockModeContext) BuildReferenceMVStack(req ReferenceMVStackRequest) (ReferenceMVStackResult, error) {
	if c == nil {
		return ReferenceMVStackResult{}, ErrInvalidDecodeState
	}
	dims, err := validateReferenceMVStackRequest(req)
	if err != nil {
		return ReferenceMVStackResult{}, err
	}

	searchMaxRowOffset, searchMaxColOffset, gridMaxRowOffset, gridMaxColOffset := referenceMVSearchOffsets(req, dims)
	processedRows := 0
	processedCols := 0
	var search referenceMVStackSearch
	if req.HaveTop && absInt(searchMaxRowOffset) >= 1 {
		c.scanAboveReferenceMVs(req, dims, searchMaxRowOffset, &processedRows, &search)
	}
	if req.HaveLeft && absInt(searchMaxColOffset) >= 1 {
		c.scanLeftReferenceMVs(req, dims, searchMaxColOffset, &processedCols, &search)
	}
	if req.HaveTopRight {
		c.scanTopRightReferenceMV(req, dims, &search)
	}
	nearestMatch := boolInt(search.RowMatches > 0) + boolInt(search.ColumnMatches > 0)
	nearestCount := search.Stack.Count
	for i := 0; i < int(nearestCount); i++ {
		search.Stack.Candidates[i].Weight += RefMVCategoryLevel
	}
	modeContextFlags := uint16(0)
	temporalUnavailable := req.TemporalMVSampleUnavailable
	if req.UseRefFrameMVS && req.TemporalMVs != nil {
		temporal, err := req.temporalReferenceMVs(dims, &search.Stack)
		if err != nil {
			return ReferenceMVStackResult{}, err
		}
		temporalUnavailable = !temporal.FirstAvailable
		if temporal.GlobalMVDifferent {
			modeContextFlags |= 1 << globalMVOffset
		}
	}
	if req.UseRefFrameMVS && temporalUnavailable {
		modeContextFlags |= 1 << globalMVOffset
	}
	c.scanOuterReferenceMVs(req, dims, gridMaxRowOffset, gridMaxColOffset, processedRows, processedCols, &search)
	refMatchCount := boolInt(search.RowMatches > 0) + boolInt(search.ColumnMatches > 0)
	modeContext := referenceMVModeContext(nearestMatch, refMatchCount, search.NewMVMatches) | modeContextFlags
	sortReferenceMVStack(&search.Stack, 0, int(nearestCount))

	if req.References.Compound {
		c.extendCompoundReferenceMVStack(req, dims, searchMaxRowOffset, searchMaxColOffset, &search.Stack)
	} else {
		c.extendSingleReferenceMVStack(req, dims, searchMaxRowOffset, searchMaxColOffset, &search.Stack)
	}
	sortReferenceMVStack(&search.Stack, int(nearestCount), int(search.Stack.Count))
	// Clamp every finalized stack candidate to the frame boundary, mirroring
	// libaom's clamp_mv_ref loop at the end of setup_ref_mv_list. This bounds
	// predictors used by NEW/NEAREST/NEAR modes (and the single-ref mv_ref_list
	// cache built next) so a spatial or temporal candidate pointing far past the
	// frame edge cannot drift the reconstructed MV off libaom.
	req.clampReferenceMVStack(dims, &search.Stack)
	if !req.References.Compound {
		// Refresh the single-ref MV cache from the post-sort stack so
		// NEARESTMV/NEARMV decoders read the highest-weighted slot.
		// libaom's av1_setup_ref_mv_list populates mv_ref_list FROM the
		// sorted ref_mv_stack; priming SingleRefMVs inside
		// extendSingleReferenceMVStack let insertion order leak into the
		// nearest/near cache, e.g. quantizer_00 frame 1 mi=(46,10).
		search.Stack.setSingleRefMVs(req.GlobalMVs[0])
	}
	result := ReferenceMVStackResult{
		Stack:         search.Stack,
		ModeContext:   modeContext,
		NearestCount:  nearestCount,
		RowMatches:    uint8(search.RowMatches),
		ColumnMatches: uint8(search.ColumnMatches),
		NewMVMatches:  uint8(search.NewMVMatches),
	}
	if debugRefMVEnabled {
		debugReferenceMVStack(req, &result)
	}
	return result, nil
}

const (
	refMVRowCols       = 3
	refMVMaxScanBlock4 = 16

	// mvBorder is libaom's MV_BORDER: 16 pixels expressed in 1/8-pel units.
	mvBorder = 16 << 3
	// miSize is the side of one MI unit in luma pixels (libaom MI_SIZE).
	miSize = 4
)

// clampReferenceMVStack clamps every finalized stack candidate's MV to the
// frame boundary, porting libaom's clamp_mv_ref (av1/common/mvref_common.h).
// The per-block limits derive from the block's distance to each frame edge
// (mb_to_*_edge in set_mi_row_col) widened by the block size and MV_BORDER.
// When the frame MI extent is unknown (zero) the clamp is skipped so callers
// that do not populate FrameMI* keep their prior behaviour.
func (req ReferenceMVStackRequest) clampReferenceMVStack(dims BlockDimensions, stack *ReferenceMVStack) {
	if stack == nil || req.FrameMIRows == 0 || req.FrameMICols == 0 {
		return
	}
	bw := int32(dims.W4) * miSize
	bh := int32(dims.H4) * miSize
	miCol := int32(req.MICol)
	miRow := int32(req.MIRow)
	// mb_to_*_edge in 1/8-pel units: GET_MV_SUBPEL(x) == x * 8.
	mbToLeft := -((miCol * miSize) << 3)
	mbToRight := (int32(req.FrameMICols) - int32(dims.W4) - miCol) * miSize << 3
	mbToTop := -((miRow * miSize) << 3)
	mbToBottom := (int32(req.FrameMIRows) - int32(dims.H4) - miRow) * miSize << 3
	colMin := mbToLeft - (bw << 3) - mvBorder
	colMax := mbToRight + (bw << 3) + mvBorder
	rowMin := mbToTop - (bh << 3) - mvBorder
	rowMax := mbToBottom + (bh << 3) + mvBorder
	for i := 0; i < int(stack.Count); i++ {
		stack.Candidates[i].This = clampMVToLimits(stack.Candidates[i].This, rowMin, rowMax, colMin, colMax)
		if req.References.Compound {
			stack.Candidates[i].Compound = clampMVToLimits(stack.Candidates[i].Compound, rowMin, rowMax, colMin, colMax)
		}
	}
}

func clampMVToLimits(mv motion.Vector, rowMin, rowMax, colMin, colMax int32) motion.Vector {
	col := int32(mv.Col)
	if col < colMin {
		col = colMin
	} else if col > colMax {
		col = colMax
	}
	row := int32(mv.Row)
	if row < rowMin {
		row = rowMin
	} else if row > rowMax {
		row = rowMax
	}
	mv.Row = int16(row)
	mv.Col = int16(col)
	return mv
}

type temporalReferenceMVResult struct {
	FirstAvailable    bool
	GlobalMVDifferent bool
}

func (req ReferenceMVStackRequest) temporalReferenceMVs(dims BlockDimensions, stack *ReferenceMVStack) (temporalReferenceMVResult, error) {
	if req.TemporalMVs == nil {
		return temporalReferenceMVResult{}, nil
	}
	if err := req.TemporalMVs.validate(); err != nil {
		return temporalReferenceMVResult{}, err
	}
	voffset := maxInt(2, int(dims.H4))
	hoffset := maxInt(2, int(dims.W4))
	blkRowEnd := minInt(int(dims.H4), 16)
	blkColEnd := minInt(int(dims.W4), 16)
	stepH := 2
	if dims.H4 >= 16 {
		stepH = 4
	}
	stepW := 2
	if dims.W4 >= 16 {
		stepW = 4
	}

	var result temporalReferenceMVResult
	for blkRow := 0; blkRow < blkRowEnd; blkRow += stepH {
		for blkCol := 0; blkCol < blkColEnd; blkCol += stepW {
			added, different, err := req.addTemporalReferenceMV(blkRow, blkCol, stack)
			if err != nil {
				return temporalReferenceMVResult{}, err
			}
			if blkRow == 0 && blkCol == 0 {
				result.FirstAvailable = added
				// libaom only sets the GLOBALMV mode-context bit based on the
				// (blk_row=0, blk_col=0) temporal sample. Earlier goav1 OR'd
				// `different` across the whole scan and the extension
				// positions, which produced a different mode_context whenever
				// a non-(0,0) temporal MV deviated from the global MV by 16+
				// quarter pels and incorrectly steered inter mode reads to
				// zeromv_cdf[1] instead of zeromv_cdf[0] for blocks with no
				// (0,0) temporal sample available.
				if different {
					result.GlobalMVDifferent = true
				}
			}
		}
	}

	allowExtension := dims.H4 >= 2 && dims.H4 < 16 && dims.W4 >= 2 && dims.W4 < 16
	if allowExtension {
		positions := [3][2]int{
			{voffset, -2},
			{voffset, hoffset},
			{voffset - 2, hoffset},
		}
		// libaom gates each extension temporal sample on check_sb_border: the
		// offset position must stay inside the current 64x64 superblock
		// (sb_mi_size = mi_size_wide[BLOCK_64X64] = 16). Without this, a block
		// at an SB left/top edge samples a position in the neighbouring SB,
		// re-adding a temporal candidate that libaom skips and inflating its
		// ref_mv weight (e.g. av1-1-b8-05-mv coded frame 2 mi=(0,48): the
		// (voffset,-2) sample crosses the SB-left border, double-counting a
		// candidate to weight 4 and flipping the NEW_NEWMV drl selection).
		const sbMISize = 16
		sbRow := int(req.MIRow) & (sbMISize - 1)
		sbCol := int(req.MICol) & (sbMISize - 1)
		for _, pos := range positions {
			if sbRow+pos[0] < 0 || sbRow+pos[0] >= sbMISize ||
				sbCol+pos[1] < 0 || sbCol+pos[1] >= sbMISize {
				continue
			}
			if _, _, err := req.addTemporalReferenceMV(pos[0], pos[1], stack); err != nil {
				return temporalReferenceMVResult{}, err
			}
		}
	}
	return result, nil
}

func (req ReferenceMVStackRequest) addTemporalReferenceMV(blkRow int, blkCol int, stack *ReferenceMVStack) (bool, bool, error) {
	rowOffset := blkRow
	if req.MIRow&1 == 0 {
		rowOffset++
	}
	colOffset := blkCol
	if req.MICol&1 == 0 {
		colOffset++
	}
	absRow := int64(req.MIRow) + int64(rowOffset)
	absCol := int64(req.MICol) + int64(colOffset)
	if absRow < int64(req.TileMIRowStart) || absRow >= int64(req.TileMIRowEnd) ||
		absCol < int64(req.TileMIColStart) || absCol >= int64(req.TileMIColEnd) {
		return false, false, nil
	}
	sampleRow := int(absRow >> 1)
	sampleCol := int(absCol >> 1)
	if sampleRow < 0 || sampleRow >= req.TemporalMVs.Rows ||
		sampleCol < 0 || sampleCol >= req.TemporalMVs.Cols {
		return false, false, nil
	}
	sample := req.TemporalMVs.Entries[sampleRow*req.TemporalMVs.Stride+sampleCol]
	if !sample.Valid {
		return false, false, nil
	}

	first, err := req.temporalProjectedMV(sample, 0)
	if err != nil {
		return false, false, err
	}
	different := temporalMVDifferent(first, req.GlobalMVs[0])
	candidate := ReferenceMVCandidate{This: first}
	if req.References.Compound {
		second, err := req.temporalProjectedMV(sample, 1)
		if err != nil {
			return false, false, err
		}
		candidate.Compound = second
		different = different || temporalMVDifferent(second, req.GlobalMVs[1])
	}
	stack.addOrWeight(candidate, 2)
	return true, different, nil
}

func (req ReferenceMVStackRequest) temporalProjectedMV(sample TemporalMotionEntry, refIndex int) (motion.Vector, error) {
	ref := req.References.Ref[refIndex]
	if !ref.Valid() {
		return motion.Vector{}, ErrInvalidDecodeState
	}
	currentOffset, err := motionFieldRelativeOrderHint(req.OrderHintBits, req.CurrentOrderHint, req.ReferenceOrderHints[ref])
	if err != nil {
		return motion.Vector{}, err
	}
	projected, err := motionFieldProjectMV(sample.MV, currentOffset, int(sample.RefFrameOffset))
	if err != nil {
		return motion.Vector{}, err
	}
	return motion.LowerPrecision(projected, req.AllowHighPrecisionMV, req.ForceIntegerMV), nil
}

func temporalMVDifferent(a motion.Vector, b motion.Vector) bool {
	return absInt32(int32(a.Row)-int32(b.Row)) >= 16 ||
		absInt32(int32(a.Col)-int32(b.Col)) >= 16
}

func absInt32(v int32) int32 {
	if v < 0 {
		return -v
	}
	return v
}

func (c *BlockModeContext) scanAboveReferenceMVs(req ReferenceMVStackRequest, dims BlockDimensions, maxRowOffset int, processedRows *int, result *referenceMVStackSearch) {
	x4 := int(req.X4)
	end := minInt(int(dims.W4), MaxBlockModeSlots-x4)
	end = minInt(end, refMVMaxScanBlock4)
	// libaom's scan_row_mbmi() caps the above-row sweep at
	// end_mi = AOMMIN(xd->width, mi_cols - mi_col): a block flush against
	// the frame's right boundary must not fold neighbors that lie past the
	// last coded MI column into the ref-MV stack. goav1's per-SB neighbor
	// snapshot still holds right-padding cells for partial superblocks, so
	// without this clamp a partial right-edge block (e.g. 226x226 frame 1
	// mi=(16,56) BLOCK_16X32) reads a stale above-right candidate that
	// libaom never sees, shifting the whole DRL-indexed stack by one.
	//
	// The vertical analog (scan_col_mbmi's mi_rows - mi_row cap) is NOT
	// applied to scanLeftReferenceMVs: goav1's left-column snapshot already
	// reflects the frame-clamped neighbor block sizes for partial-bottom
	// superblocks, and adding the cap there regresses the row-unaligned
	// quantizer_63 stream (mi 160x90, partial bottom SB) which is byte-exact
	// without it.
	if req.TileMIColEnd > req.MICol {
		end = minInt(end, int(req.TileMIColEnd-req.MICol))
	}
	for off := 0; off < end; {
		slot := x4 + off
		size := c.AboveBlockSize[slot]
		sizeW4 := blockSizeWidth4(size)
		sizeH4 := blockSizeHeight4(size)
		// libaom's scan_row_mbmi sets the iteration stride and
		// processed_rows from the neighbor's block size regardless of
		// whether the neighbor is inter or intra. Gating these updates on
		// AboveMotionValid kept processedRows at zero when the nearest above
		// row was intra, which let the outer scan re-enter row offsets
		// libaom already covered and prematurely promote processedRows on a
		// duplicate candidate, hiding the row=-5 outer sample that libaom
		// adds to the ref-MV stack.
		//
		// As in scanLeftReferenceMVs, libaom computes len = AOMMIN(xd->width,
		// n4_w) and uses len*weight without clamping len to end_mi (the cap
		// only gates loop termination). A neighbor wider than the remaining
		// budget must keep its full-len weight, so step is bounded only by the
		// neighbor's own block width (sizeW4).
		step := minInt(int(dims.W4), sizeW4)
		if dims.W4 >= refMVMaxScanBlock4 {
			step = maxInt(step, 4)
		}
		if step <= 0 {
			step = 1
		}
		weight := 2
		if dims.W4 >= 2 && int(dims.W4) <= sizeW4 {
			inc := minInt(-maxRowOffset, sizeH4)
			weight = maxInt(weight, inc)
			*processedRows = inc
		}
		if c.AboveIntra[slot] == 0 && c.AboveMotionValid[slot] != 0 {
			matches, newMatches := result.Stack.addDirectCandidate(c.AboveInterMotion[slot], c.AboveBlockSize[slot], req.References, uint16(step*weight), req.GlobalMVs, req.GlobalMotionType)
			result.RowMatches += matches
			result.NewMVMatches += newMatches
		}
		off += step
	}
}

func (c *BlockModeContext) scanLeftReferenceMVs(req ReferenceMVStackRequest, dims BlockDimensions, maxColOffset int, processedCols *int, result *referenceMVStackSearch) {
	y4 := int(req.Y4)
	end := minInt(int(dims.H4), MaxBlockModeSlots-y4)
	end = minInt(end, refMVMaxScanBlock4)
	// libaom's scan_col_mbmi() caps the left-column sweep at
	// end_mi = AOMMIN(xd->height, mi_rows - mi_row): a block flush against the
	// frame's bottom boundary must not fold neighbors below the last coded MI
	// row into the ref-MV stack. This is the vertical analog of the
	// scan_row_mbmi cap in scanAboveReferenceMVs. Without it, a block at the
	// bottom edge of a partial superblock (e.g. svc_L2T2 frame 1 mi=(88,96)
	// BLOCK_32X16 in a 90-MI-row enhancement frame, where mi_rows - mi_row = 2
	// caps end_mi to 2) reads its left-column snapshot past the frame bottom
	// and folds a spurious (0,0) neighbor into the nearest scan, inflating its
	// weight by REF_CAT_LEVEL (652) and displacing libaom's outer candidates so
	// the 5-entry stack collapses to 4 and the DRL context/sort desyncs the
	// arithmetic decoder for the rest of the frame.
	//
	// The cap only bounds the LOOP TERMINATION (libaom checks i < end_mi at the
	// top of the loop), NOT the per-candidate step/weight. libaom computes
	// len = AOMMIN(xd->height, mi_size_high[bsize]) for the candidate it reads
	// and advances i += len, using len*weight without clamping len to end_mi.
	// Clamping the step to the capped end would shrink the first candidate's
	// weight (e.g. quantizer_63 frame 1 mi=(80,16): first left neighbor has
	// len=16 but end_mi=10, so the weight must stay 16*w, not 10*w), which
	// would re-sort the stack and desync. So loopEnd gates termination while
	// step is clamped only by the snapshot bound (end), matching libaom.
	loopEnd := end
	if req.TileMIRowEnd > req.MIRow {
		loopEnd = minInt(loopEnd, int(req.TileMIRowEnd-req.MIRow))
	}
	for off := 0; off < loopEnd; {
		slot := y4 + off
		size := c.LeftBlockSize[slot]
		sizeW4 := blockSizeWidth4(size)
		sizeH4 := blockSizeHeight4(size)
		// See scanAboveReferenceMVs: the iteration stride and processedCols
		// update from the neighbor's block size regardless of inter/intra so
		// the outer column scan respects libaom's processed_cols stride.
		//
		// libaom's scan_col_mbmi computes len = AOMMIN(xd->height, n4_h)
		// (capped to mi_size_high[BLOCK_64X64]=16 via the use_step_16 branch),
		// uses len*weight as the candidate weight, and advances i += len. len
		// is NOT clamped to end_mi: when the neighbor is taller than the
		// remaining loop budget (e.g. svc_L2T1 frame 5 mi=(0,64) ref GOLDEN: a
		// 32-MI-tall left neighbor against end_mi=16 keeps len=32 → weight
		// 192+REF_CAT=832), the candidate keeps its full-len weight and the
		// loop simply terminates on the next i < end_mi check. Clamping step to
		// end-off here shrank the weight (96+REF_CAT=736), re-sorting the stack
		// and desyncing the arithmetic decoder. So step is bounded only by the
		// neighbor's own block size (sizeH4), matching libaom's len.
		step := minInt(int(dims.H4), sizeH4)
		if dims.H4 >= refMVMaxScanBlock4 {
			step = maxInt(step, 4)
		}
		if step <= 0 {
			step = 1
		}
		weight := 2
		if dims.H4 >= 2 && int(dims.H4) <= sizeH4 {
			inc := minInt(-maxColOffset, sizeW4)
			weight = maxInt(weight, inc)
			*processedCols = inc
		}
		if c.LeftIntra[slot] == 0 && c.LeftMotionValid[slot] != 0 {
			matches, newMatches := result.Stack.addDirectCandidate(c.LeftInterMotion[slot], c.LeftBlockSize[slot], req.References, uint16(step*weight), req.GlobalMVs, req.GlobalMotionType)
			result.ColumnMatches += matches
			result.NewMVMatches += newMatches
		}
		off += step
	}
}

func (c *BlockModeContext) scanAboveIntrabcDVs(req ReferenceMVStackRequest, dims BlockDimensions, maxRowOffset int, processedRows *int, stack *ReferenceMVStack) {
	x4 := int(req.X4)
	end := minInt(int(dims.W4), MaxBlockModeSlots-x4)
	end = minInt(end, refMVMaxScanBlock4)
	for off := 0; off < end; {
		slot := x4 + off
		size := c.AboveBlockSize[slot]
		step := c.aboveCandidateStep(slot, end-off)
		weight := 2
		if c.AboveMotionValid[slot] != 0 {
			sizeW4 := blockSizeWidth4(size)
			sizeH4 := blockSizeHeight4(size)
			step = minInt(int(dims.W4), sizeW4)
			if dims.W4 >= refMVMaxScanBlock4 {
				step = maxInt(step, 4)
			}
			if step > end-off {
				step = end - off
			}
			if step <= 0 {
				step = 1
			}
			if dims.W4 >= 2 && int(dims.W4) <= sizeW4 {
				inc := minInt(-maxRowOffset, sizeH4)
				weight = maxInt(weight, inc)
				*processedRows = inc
			}
			stack.addOrWeight(ReferenceMVCandidate{This: c.AboveInterMotion[slot].MV[0]}, uint16(step*weight))
		}
		off += step
	}
}

func (c *BlockModeContext) scanLeftIntrabcDVs(req ReferenceMVStackRequest, dims BlockDimensions, maxColOffset int, processedCols *int, stack *ReferenceMVStack) {
	y4 := int(req.Y4)
	end := minInt(int(dims.H4), MaxBlockModeSlots-y4)
	end = minInt(end, refMVMaxScanBlock4)
	for off := 0; off < end; {
		slot := y4 + off
		size := c.LeftBlockSize[slot]
		step := c.leftCandidateStep(slot, end-off)
		weight := 2
		if c.LeftMotionValid[slot] != 0 {
			sizeW4 := blockSizeWidth4(size)
			sizeH4 := blockSizeHeight4(size)
			step = minInt(int(dims.H4), sizeH4)
			if dims.H4 >= refMVMaxScanBlock4 {
				step = maxInt(step, 4)
			}
			if step > end-off {
				step = end - off
			}
			if step <= 0 {
				step = 1
			}
			if dims.H4 >= 2 && int(dims.H4) <= sizeH4 {
				inc := minInt(-maxColOffset, sizeW4)
				weight = maxInt(weight, inc)
				*processedCols = inc
			}
			stack.addOrWeight(ReferenceMVCandidate{This: c.LeftInterMotion[slot].MV[0]}, uint16(step*weight))
		}
		off += step
	}
}

func (c *BlockModeContext) scanTopRightReferenceMV(req ReferenceMVStackRequest, dims BlockDimensions, result *referenceMVStackSearch) {
	// libaom's av1_find_mv_refs gates the top-right scan_blk_mbmi() on
	// is_inside(tile, mi_col + xd->width, mi_row - 1): the candidate at
	// (mi_row-1, mi_col+W4) must lie inside the current tile. Blocks on the
	// tile's right edge (mi_col + W4 == mi_col_end) therefore contribute no
	// top-right candidate, even when has_top_right() returned 1. Without this
	// guard goav1 read the SB's right-padding MI grid cell and folded a stale
	// neighbor into both the ref-MV stack and newmv_count, corrupting the
	// inter mode_context (e.g. 208x208 frame 1 mi=(32,51): newmv_ctx 4 vs 5).
	if int(req.MICol)+int(dims.W4) >= int(req.TileMIColEnd) ||
		int(req.MIRow)-1 < int(req.TileMIRowStart) {
		return
	}
	candidate, size, ok := c.topRightInterMotion(req, dims)
	if !ok {
		return
	}
	matches, newMatches := result.Stack.addDirectCandidate(candidate, size, req.References, 4, req.GlobalMVs, req.GlobalMotionType)
	result.RowMatches += matches
	result.NewMVMatches += newMatches
}

func referenceMVSearchOffsets(req ReferenceMVStackRequest, dims BlockDimensions) (int, int, int, int) {
	rowAdj := 0
	if dims.H4 < 2 && req.MIRow&1 != 0 {
		rowAdj = 1
	}
	colAdj := 0
	if dims.W4 < 2 && req.MICol&1 != 0 {
		colAdj = 1
	}
	maxRowOffset := 0
	if req.HaveTop {
		searchRows := refMVRowCols
		if dims.H4 < 2 {
			searchRows = 2
		}
		maxRowOffset = -(searchRows << 1) + rowAdj
		if req.TileMIRowEnd > req.TileMIRowStart && req.MIRow >= req.TileMIRowStart && req.MIRow < req.TileMIRowEnd {
			maxRowOffset = clampInt(maxRowOffset, int(req.TileMIRowStart)-int(req.MIRow), int(req.TileMIRowEnd)-int(req.MIRow)-1)
		}
	}
	maxColOffset := 0
	if req.HaveLeft {
		searchCols := refMVRowCols
		if dims.W4 < 2 {
			searchCols = 2
		}
		maxColOffset = -(searchCols << 1) + colAdj
		if req.TileMIColEnd > req.TileMIColStart && req.MICol >= req.TileMIColStart && req.MICol < req.TileMIColEnd {
			maxColOffset = clampInt(maxColOffset, int(req.TileMIColStart)-int(req.MICol), int(req.TileMIColEnd)-int(req.MICol)-1)
		}
	}
	// gridMaxRowOffset and gridMaxColOffset are intentionally NOT clamped by
	// -Y4 / -X4 so the inter ref-MV outer row/column scan can reach into the
	// SB above / SB to the left through the SBTop* / SBLeft* snapshots (see
	// crossSBGridNeighborBlockSize). libaom's frame-wide mi grid exposes those
	// cells transparently; goav1 stages them via the carrier's Above/Left
	// snapshots at SB-store time.
	//
	// Without the column extension a block at the left edge of an SB
	// (e.g. quantizer_00 frame 1 mi=(32,0) BLOCK_16X8) would drop libaom's
	// outer_col[-3] and outer_col[-5] candidates. Without the matching row
	// extension a block near the top edge of an SB (e.g. quantizer_00 frame 1
	// mi=(4,34) BLOCK_4X8 Y4=2) would drop libaom's outer_row[-3] candidate,
	// undercounting refmv_count and shifting the DRL CDF off libaom one cell.
	//
	// The tile-relative clamps on maxRowOffset/maxColOffset above keep the
	// cross-SB lookup from crossing a tile boundary; the per-SB carrier always
	// lives in the same tile as the consuming SB.
	gridMaxRowOffset := maxRowOffset
	gridMaxColOffset := maxColOffset
	return maxRowOffset, maxColOffset, gridMaxRowOffset, gridMaxColOffset
}

func (c *BlockModeContext) scanOuterReferenceMVs(req ReferenceMVStackRequest, dims BlockDimensions, maxRowOffset int, maxColOffset int, processedRows int, processedCols int, result *referenceMVStackSearch) {
	var dummyNewMV int
	c.scanGridBlockReferenceMV(req, -1, -1, &result.RowMatches, &dummyNewMV, &result.Stack)
	rowAdj := 0
	if dims.H4 < 2 && req.MIRow&1 != 0 {
		rowAdj = 1
	}
	colAdj := 0
	if dims.W4 < 2 && req.MICol&1 != 0 {
		colAdj = 1
	}
	for idx := 2; idx <= refMVRowCols; idx++ {
		rowOffset := -(idx << 1) + 1 + rowAdj
		colOffset := -(idx << 1) + 1 + colAdj
		if absInt(rowOffset) <= absInt(maxRowOffset) && absInt(rowOffset) > processedRows {
			c.scanGridRowReferenceMVs(req, dims, rowOffset, maxRowOffset, &processedRows, &result.RowMatches, &dummyNewMV, &result.Stack)
		}
		if absInt(colOffset) <= absInt(maxColOffset) && absInt(colOffset) > processedCols {
			c.scanGridColReferenceMVs(req, dims, colOffset, maxColOffset, &processedCols, &result.ColumnMatches, &dummyNewMV, &result.Stack)
		}
	}
}

func (c *BlockModeContext) scanOuterIntrabcDVs(req ReferenceMVStackRequest, dims BlockDimensions, maxRowOffset int, maxColOffset int, processedRows int, processedCols int, stack *ReferenceMVStack) {
	c.scanGridBlockIntrabcDV(req, -1, -1, 4, stack)
	rowAdj := 0
	if dims.H4 < 2 && req.MIRow&1 != 0 {
		rowAdj = 1
	}
	colAdj := 0
	if dims.W4 < 2 && req.MICol&1 != 0 {
		colAdj = 1
	}
	for idx := 2; idx <= refMVRowCols; idx++ {
		rowOffset := -(idx << 1) + 1 + rowAdj
		colOffset := -(idx << 1) + 1 + colAdj
		if absInt(rowOffset) <= absInt(maxRowOffset) && absInt(rowOffset) > processedRows {
			c.scanGridRowIntrabcDVs(req, dims, rowOffset, maxRowOffset, &processedRows, stack)
		}
		if absInt(colOffset) <= absInt(maxColOffset) && absInt(colOffset) > processedCols {
			c.scanGridColIntrabcDVs(req, dims, colOffset, maxColOffset, &processedCols, stack)
		}
	}
}

func (c *BlockModeContext) scanGridRowReferenceMVs(req ReferenceMVStackRequest, dims BlockDimensions, rowOffset int, maxRowOffset int, processedRows *int, matches *int, newMatches *int, stack *ReferenceMVStack) {
	x4 := int(req.X4)
	y4 := int(req.Y4)
	end := minInt(int(dims.W4), MaxBlockModeSlots-x4)
	end = minInt(end, refMVMaxScanBlock4)
	colOffset := 0
	if absInt(rowOffset) > 1 {
		colOffset = 1
		if req.MICol&1 != 0 && dims.W4 < 2 {
			colOffset--
		}
	}
	for i := 0; i < end; {
		x := x4 + colOffset + i
		y := y4 + rowOffset
		// libaom's scan_row_mbmi always advances i += AOMMIN(xd->width,
		// mi_size_wide[candidate->bsize]) regardless of whether the candidate
		// is inter or intra. Use the recorded size for the step even when
		// the cell has no usable motion candidate so the scan never
		// re-samples cells already covered by an intra neighbor's mi_size.
		// Cross-SB cells (y<0) fall back to the SB-top snapshot so rows in
		// the prior SB are visible to the scan, mirroring scanGridColReferenceMVs
		// which uses the SB-left snapshot for x<0. libaom's frame-wide mi grid
		// covers these cells transparently; the per-SB carrier stages them at
		// SB-store time and the tile-relative clamp on maxRowOffset prevents
		// the lookup from crossing a tile boundary.
		size, sizeKnown := c.crossSBGridNeighborBlockSize(req, x, y)
		if !sizeKnown {
			i++
			continue
		}
		sizeW4 := blockSizeWidth4(size)
		sizeH4 := blockSizeHeight4(size)
		step := minInt(int(dims.W4), sizeW4)
		if dims.W4 >= refMVMaxScanBlock4 {
			step = maxInt(step, 4)
		} else if absInt(rowOffset) > 1 {
			step = maxInt(step, 2)
		}
		if step <= 0 {
			step = 1
		}
		// libaom's scan_row_mbmi updates weight and processed_rows
		// unconditionally based on the candidate's bsize, then defers the
		// inter/ref-frame check to add_ref_mv_candidate. Mirror that here so
		// a deeper outer row scan (row_offset=-5 after an intra cell at
		// row_offset=-3) does not re-enter cells libaom's processed_rows
		// gate would skip. See the matching note in scanGridColReferenceMVs.
		weight := 2
		if dims.W4 >= 2 && int(dims.W4) <= sizeW4 {
			inc := minInt(-maxRowOffset+rowOffset+1, sizeH4)
			weight = maxInt(weight, inc)
			*processedRows = inc - rowOffset - 1
		}
		candidate, _, ok := c.crossSBInterGridInterMotion(req, x, y)
		if !ok {
			i += step
			continue
		}
		m, n := stack.addDirectCandidate(candidate, size, req.References, uint16(step*weight), req.GlobalMVs, req.GlobalMotionType)
		*matches += m
		*newMatches += n
		i += step
	}
}

func (c *BlockModeContext) scanGridRowIntrabcDVs(req ReferenceMVStackRequest, dims BlockDimensions, rowOffset int, maxRowOffset int, processedRows *int, stack *ReferenceMVStack) {
	x4 := int(req.X4)
	y4 := int(req.Y4)
	end := minInt(int(dims.W4), MaxBlockModeSlots-x4)
	end = minInt(end, refMVMaxScanBlock4)
	colOffset := 0
	if absInt(rowOffset) > 1 {
		colOffset = 1
		if req.MICol&1 != 0 && dims.W4 < 2 {
			colOffset--
		}
	}
	for i := 0; i < end; {
		x := x4 + colOffset + i
		y := y4 + rowOffset
		candidate, size, ok := c.crossSBIntrabcGridInterMotion(req, x, y)
		if !ok {
			// Match libaom's scan_row_mbmi which advances by AOMMAX(len, 2)
			// when |rowOffset|>1 (use_step_16=false). Without the size info
			// for non-intrabc cells the conservative fallback is +2 so we
			// skip the whole 8x8 hosting the cell rather than oversampling.
			if absInt(rowOffset) > 1 {
				i += 2
			} else {
				i++
			}
			continue
		}
		sizeW4 := blockSizeWidth4(size)
		sizeH4 := blockSizeHeight4(size)
		step := minInt(int(dims.W4), sizeW4)
		if dims.W4 >= refMVMaxScanBlock4 {
			step = maxInt(step, 4)
		} else if absInt(rowOffset) > 1 {
			step = maxInt(step, 2)
		}
		if step <= 0 {
			step = 1
		}
		weight := 2
		if dims.W4 >= 2 && int(dims.W4) <= sizeW4 {
			inc := minInt(-maxRowOffset+rowOffset+1, sizeH4)
			weight = maxInt(weight, inc)
			*processedRows = inc - rowOffset - 1
		}
		stack.addOrWeight(ReferenceMVCandidate{This: candidate.MV[0]}, uint16(step*weight))
		i += step
	}
}

func (c *BlockModeContext) scanGridColReferenceMVs(req ReferenceMVStackRequest, dims BlockDimensions, colOffset int, maxColOffset int, processedCols *int, matches *int, newMatches *int, stack *ReferenceMVStack) {
	x4 := int(req.X4)
	y4 := int(req.Y4)
	end := minInt(int(dims.H4), MaxBlockModeSlots-y4)
	end = minInt(end, refMVMaxScanBlock4)
	rowOffset := 0
	if absInt(colOffset) > 1 {
		rowOffset = 1
		if req.MIRow&1 != 0 && dims.H4 < 2 {
			rowOffset--
		}
	}
	for i := 0; i < end; {
		x := x4 + colOffset
		y := y4 + rowOffset + i
		// libaom's scan_col_mbmi always advances i += AOMMIN(xd->height,
		// mi_size_high[candidate->bsize]) regardless of whether the candidate
		// is inter or intra. Use the recorded size for the step even when
		// the cell has no usable motion candidate so the scan never
		// re-samples cells already covered by an intra neighbor's mi_size.
		// Cross-SB cells (x<0) fall back to the SB-left snapshot so columns
		// in the prior SB are visible to the scan.
		size, sizeKnown := c.crossSBGridNeighborBlockSize(req, x, y)
		if !sizeKnown {
			i++
			continue
		}
		sizeW4 := blockSizeWidth4(size)
		sizeH4 := blockSizeHeight4(size)
		step := minInt(int(dims.H4), sizeH4)
		if dims.H4 >= refMVMaxScanBlock4 {
			step = maxInt(step, 4)
		} else if absInt(colOffset) > 1 {
			step = maxInt(step, 2)
		}
		if step <= 0 {
			step = 1
		}
		// libaom's scan_col_mbmi updates weight and processed_cols
		// unconditionally based on the candidate's bsize, then defers the
		// inter/ref-frame check to add_ref_mv_candidate. Mirror that here:
		// advance processedCols from the cell's recorded size even when the
		// cell is intra or carries no matching motion candidate. Without this
		// advance, a deeper outer column scan (e.g. col_offset=-5 after an
		// intra cell at col_offset=-3) re-enters cells libaom's processed_cols
		// gate would skip and inflates the ref_mv_count, drifting the DRL CDF.
		weight := 2
		if dims.H4 >= 2 && int(dims.H4) <= sizeH4 {
			inc := minInt(-maxColOffset+colOffset+1, sizeW4)
			weight = maxInt(weight, inc)
			*processedCols = inc - colOffset - 1
		}
		candidate, _, ok := c.crossSBInterGridInterMotion(req, x, y)
		if !ok {
			i += step
			continue
		}
		m, n := stack.addDirectCandidate(candidate, size, req.References, uint16(step*weight), req.GlobalMVs, req.GlobalMotionType)
		*matches += m
		*newMatches += n
		i += step
	}
}

func (c *BlockModeContext) scanGridColIntrabcDVs(req ReferenceMVStackRequest, dims BlockDimensions, colOffset int, maxColOffset int, processedCols *int, stack *ReferenceMVStack) {
	x4 := int(req.X4)
	y4 := int(req.Y4)
	end := minInt(int(dims.H4), MaxBlockModeSlots-y4)
	end = minInt(end, refMVMaxScanBlock4)
	rowOffset := 0
	if absInt(colOffset) > 1 {
		rowOffset = 1
		if req.MIRow&1 != 0 && dims.H4 < 2 {
			rowOffset--
		}
	}
	for i := 0; i < end; {
		x := x4 + colOffset
		y := y4 + rowOffset + i
		candidate, size, ok := c.crossSBIntrabcGridInterMotion(req, x, y)
		if !ok {
			// Match libaom's scan_col_mbmi which advances by AOMMAX(len, 2)
			// when |colOffset|>1 (use_step_16=false). Without the size info
			// for non-intrabc cells the conservative fallback is +2 so we
			// skip the whole 8x8 hosting the cell rather than oversampling.
			if absInt(colOffset) > 1 {
				i += 2
			} else {
				i++
			}
			continue
		}
		sizeW4 := blockSizeWidth4(size)
		sizeH4 := blockSizeHeight4(size)
		step := minInt(int(dims.H4), sizeH4)
		if dims.H4 >= refMVMaxScanBlock4 {
			step = maxInt(step, 4)
		} else if absInt(colOffset) > 1 {
			step = maxInt(step, 2)
		}
		if step <= 0 {
			step = 1
		}
		weight := 2
		if dims.H4 >= 2 && int(dims.H4) <= sizeH4 {
			inc := minInt(-maxColOffset+colOffset+1, sizeW4)
			weight = maxInt(weight, inc)
			*processedCols = inc - colOffset - 1
		}
		stack.addOrWeight(ReferenceMVCandidate{This: candidate.MV[0]}, uint16(step*weight))
		i += step
	}
}

func (c *BlockModeContext) scanGridBlockReferenceMV(req ReferenceMVStackRequest, rowOffset int, colOffset int, matches *int, newMatches *int, stack *ReferenceMVStack) {
	x := int(req.X4) + colOffset
	y := int(req.Y4) + rowOffset
	candidate, size, ok := c.gridInterMotion(x, y)
	if !ok {
		// Fall back to the cross-SB snapshots when the lookup crosses the
		// current superblock's boundary. libaom's frame-level mi grid covers
		// these neighbors via xd->mi[row_offset*stride + col_offset]; goav1
		// stages the prior-SB cells in SBTop* / SBLeft* / SBDiagonal* at SB
		// store time, gated by per-snapshot Valid bits.
		//
		// The case-by-case fallback handles:
		//   - y<0, x<0 (top-left diagonal cell) via SBDiagonal: needed for
		//     monochrome frame 3 mi=(16,64) where the SB(3,0) bottom-right
		//     corner cell at (15,63) hosts an inter LAST block contributing
		//     RowMatches=1; without the fallback ctx=51 (refCtx=3) instead of
		//     libaom's 67 (refCtx=4).
		//   - y<0, x>=0 (strictly-above cell within the current SB column)
		//     via SBTop: needed for cdf_update frame 1 mi=(64,2) where the
		//     outer (-1,-1) scan reads the SB-above bottom row to find a
		//     duplicate of the LEFT candidate's MV and bump its weight, which
		//     flips the post-sort NEAR slot from stack[1]=(7,21) (the LEFT
		//     entry) to stack[1]=(9,-71) (the ABOVE entry). Without the
		//     fallback the decoded NEAR MV is (7,21) instead of (9,-71),
		//     which then propagates into subsequent block decisions and
		//     desyncs the entropy stream starting at the (68,0) seq=228966
		//     newmv/drl divergence.
		//   - x<0, y>=0 (strictly-left cell within the current SB row) via
		//     SBLeft, mirroring the SBTop case for the column dimension.
		//
		// The SB-top fallback must be gated on req.HaveTop AND mi_row >
		// tile_row_start (the cell's mi-row mi_row+y must not cross the tile
		// boundary). libaom's is_inside() applies the same per-direction
		// check.
		if y < 0 && x >= 0 {
			if !req.HaveTop {
				return
			}
			// Tile-row check: mi_row + y must be >= tile_row_start. The
			// SB-top snapshot only carries the prior-SB grid contents, but
			// the candidate at that cell is invalid (across the tile) if the
			// current block sits at the first SB row of its tile.
			if int64(req.MIRow)+int64(y) < int64(req.TileMIRowStart) {
				return
			}
			depth := -y - 1
			if depth < 0 || depth >= intrabcCrossSBHistory ||
				x >= MaxBlockModeSlots ||
				c.SBTopMotionValidGrid[depth][x] == 0 {
				return
			}
			candidate = c.SBTopInterMotionGrid[depth][x]
			size = c.SBTopBlockSizeGrid[depth][x]
		} else if y < 0 {
			// Diagonal up-left cell: served from the SBDiagonal carrier
			// snapshotted from the SB that finished decoding directly
			// up-and-to-the-left of the current SB. Mirrors the intrabc
			// diagonal lookup in crossSBIntrabcGridInterMotion.
			if !req.HaveTop || !req.HaveLeft {
				return
			}
			d := -y - 1
			e := -x - 1
			if d < 0 || d >= intrabcCrossSBHistory ||
				e < 0 || e >= intrabcCrossSBHistory ||
				c.SBDiagonalMotionValidGrid[d][e] == 0 {
				return
			}
			candidate = c.SBDiagonalInterMotionGrid[d][e]
			size = c.SBDiagonalBlockSizeGrid[d][e]
		} else {
			if !req.HaveLeft {
				return
			}
			depth := -x - 1
			if depth < 0 || depth >= intrabcCrossSBHistory ||
				y >= MaxBlockModeSlots ||
				c.SBLeftMotionValidGrid[depth][y] == 0 {
				return
			}
			candidate = c.SBLeftInterMotionGrid[depth][y]
			size = c.SBLeftBlockSizeGrid[depth][y]
		}
	}
	m, n := stack.addDirectCandidate(candidate, size, req.References, 4, req.GlobalMVs, req.GlobalMotionType)
	*matches += m
	*newMatches += n
}

func (c *BlockModeContext) scanGridBlockIntrabcDV(req ReferenceMVStackRequest, rowOffset int, colOffset int, weight uint16, stack *ReferenceMVStack) {
	x := int(req.X4) + colOffset
	y := int(req.Y4) + rowOffset
	if y < 0 && x < 0 {
		// Diagonal cell across both SB borders: libaom's mi grid cell at
		// (mi_col-1-e, mi_row-1-d). Recovered via SBDiagonalInterMotionGrid
		// snapshotted from the SB diagonally up-left of the current SB.
		candidate, _, ok := c.crossSBIntrabcGridInterMotion(req, x, y)
		if !ok {
			return
		}
		stack.addOrWeight(ReferenceMVCandidate{This: candidate.MV[0]}, weight)
		return
	}
	if y < 0 {
		// Cross-SB-row lookup: consult the SB-top snapshot of the row
		// directly above the current superblock. This mirrors libaom's
		// frame-level mi grid, which is unaffected by in-SB block decode.
		if !req.HaveTop || x < 0 || x >= MaxBlockModeSlots || c.SBTopMotionValid[x] == 0 {
			return
		}
		stack.addOrWeight(ReferenceMVCandidate{This: c.SBTopInterMotion[x].MV[0]}, weight)
		return
	}
	if x < 0 {
		// Cross-SB-column lookup: consult the SB-left snapshot of the column
		// directly to the left of the current superblock. Same rationale as
		// the SB-top snapshot but for the row dimension.
		if !req.HaveLeft || y < 0 || y >= MaxBlockModeSlots || c.SBLeftMotionValid[y] == 0 {
			return
		}
		stack.addOrWeight(ReferenceMVCandidate{This: c.SBLeftInterMotion[y].MV[0]}, weight)
		return
	}
	candidate, _, ok := c.gridInterMotion(x, y)
	if !ok {
		return
	}
	stack.addOrWeight(ReferenceMVCandidate{This: candidate.MV[0]}, weight)
}

func (c *BlockModeContext) gridInterMotion(x4 int, y4 int) (InterMotionResult, BlockSize, bool) {
	if x4 < 0 || y4 < 0 || x4 >= MaxBlockModeSlots || y4 >= MaxBlockModeSlots ||
		c.GridMotionValid[y4][x4] == 0 {
		return InterMotionResult{}, 0, false
	}
	return c.GridInterMotion[y4][x4], c.GridBlockSize[y4][x4], true
}

// gridNeighborBlockSize returns the block size recorded at (x4, y4)
// regardless of whether the cell carries a usable motion candidate.
// MarkIntra records the intra block's size in GridBlockSize while clearing
// GridMotionValid so outer ref-MV scans can advance by libaom's
// `i += mi_size_*[candidate->bsize]` stride past intra neighbors without
// oversampling cells the candidate already covers. Returns (size, true) when
// a Mark*() recorded a size at the slot, (0, false) when the slot is out of
// range. The "size present" signal is the gridBlockSizeVisited bitmap, which
// flips only when markGridInterMotion / clearGridInterMotion writes the slot.
func (c *BlockModeContext) gridNeighborBlockSize(x4 int, y4 int) (BlockSize, bool) {
	if x4 < 0 || y4 < 0 || x4 >= MaxBlockModeSlots || y4 >= MaxBlockModeSlots {
		return 0, false
	}
	if c.GridBlockSizeVisited[y4][x4] == 0 {
		return 0, false
	}
	return c.GridBlockSize[y4][x4], true
}

// crossSBGridNeighborBlockSize mirrors gridNeighborBlockSize but transparently
// falls back to the SB-top / SB-left / SB-diagonal snapshots when the lookup
// crosses the current superblock boundary. libaom's mi grid is frame-wide so
// scan_row_mbmi / scan_col_mbmi see prior-SB neighbors without ceremony; goav1
// keeps a per-SB grid and stages the prior SB's bottom rows in SBTop*Grid /
// its right columns in SBLeft*Grid (depth 0 = adjacent cell, depth d = d+1
// cells away). Used by the inter ref-MV outer row/column scan so a block at
// the top edge (Y4=0) or left edge (X4=0) of an SB still observes deep outer
// offsets (-3, -5) that would otherwise be clipped at the SB boundary.
func (c *BlockModeContext) crossSBGridNeighborBlockSize(req ReferenceMVStackRequest, x4, y4 int) (BlockSize, bool) {
	if c == nil {
		return 0, false
	}
	if y4 < 0 && x4 < 0 {
		if !req.HaveTop || !req.HaveLeft {
			return 0, false
		}
		d := -y4 - 1
		e := -x4 - 1
		if d < 0 || d >= intrabcCrossSBHistory || e < 0 || e >= intrabcCrossSBHistory {
			return 0, false
		}
		// Use BlockSizeVisited (not MotionValid) so intra neighbors in the
		// prior SB still consume their mi_size when the outer scan steps
		// across them. libaom's scan_row/col_mbmi advances i += len based
		// on the candidate's bsize regardless of whether the candidate is
		// inter or intra; if we gated the lookup on MotionValid here the
		// intra cell looked "unknown" and the scan fell back to a single-
		// mi step, then re-entered cells the intra neighbor already covered
		// and may pick up a stray inter MV one row deeper. mfmv frame 1
		// block mi=(64,18) outer_col[-5] hit this: libaom visits (19,59)
		// (intra bsize=BLOCK_16X8, len=2) and exits with col_match=0, while
		// goav1 stepped to (20,59) (inter, mv=(-4,23)) and inflated
		// col_match to 1.
		if c.SBDiagonalBlockSizeVisitedGrid[d][e] == 0 {
			return 0, false
		}
		return c.SBDiagonalBlockSizeGrid[d][e], true
	}
	if y4 < 0 {
		if !req.HaveTop {
			return 0, false
		}
		depth := -y4 - 1
		if depth < 0 || depth >= intrabcCrossSBHistory ||
			x4 < 0 || x4 >= MaxBlockModeSlots ||
			c.SBTopBlockSizeVisitedGrid[depth][x4] == 0 {
			return 0, false
		}
		return c.SBTopBlockSizeGrid[depth][x4], true
	}
	if x4 < 0 {
		if !req.HaveLeft {
			return 0, false
		}
		depth := -x4 - 1
		if depth < 0 || depth >= intrabcCrossSBHistory ||
			y4 < 0 || y4 >= MaxBlockModeSlots ||
			c.SBLeftBlockSizeVisitedGrid[depth][y4] == 0 {
			return 0, false
		}
		return c.SBLeftBlockSizeGrid[depth][y4], true
	}
	return c.gridNeighborBlockSize(x4, y4)
}

// crossSBInterGridInterMotion mirrors gridInterMotion but consults the SB-top
// / SB-left / SB-diagonal snapshots when the lookup crosses the superblock
// boundary. Symmetric to crossSBIntrabcGridInterMotion but returns the full
// InterMotionResult so the inter ref-MV outer row/column scan can match the
// candidate's reference frame, mode (NEWMV detection), and motion vector
// against the current block's reference list.
func (c *BlockModeContext) crossSBInterGridInterMotion(req ReferenceMVStackRequest, x4, y4 int) (InterMotionResult, BlockSize, bool) {
	return c.crossSBIntrabcGridInterMotion(req, x4, y4)
}

// crossSBIntrabcGridInterMotion returns the InterMotionResult and block size
// at (x4, y4) honoring cross-superblock fallback to the prior SB snapshots for
// the intrabc outer mv-ref scan. When y4 < 0 the row lives in the SB above
// (consult SBTopInterMotionGrid); when x4 < 0 the column lives in the SB to
// the left (SBLeftInterMotionGrid). Both negative is the diagonal cell, only
// recoverable via the top-row snapshot the prior SB column shares with the
// row above. Returns (result, size, false) when no candidate is available.
func (c *BlockModeContext) crossSBIntrabcGridInterMotion(req ReferenceMVStackRequest, x4, y4 int) (InterMotionResult, BlockSize, bool) {
	if c == nil {
		return InterMotionResult{}, 0, false
	}
	if y4 < 0 && x4 < 0 {
		// Diagonal cell at frame position (mi_col-1-e, mi_row-1-d) inside
		// the SB up-and-to-the-left. Recovered from SBDiagonalInterMotionGrid,
		// loaded from the carrier's Diagonal slot for the current root column.
		// Requires both HaveTop and HaveLeft because the diagonal SB shares
		// one row with the above SB and one column with the left SB; without
		// either the (-1,-1) cell falls outside the tile.
		if !req.HaveTop || !req.HaveLeft {
			return InterMotionResult{}, 0, false
		}
		d := -y4 - 1
		e := -x4 - 1
		if d < 0 || d >= intrabcCrossSBHistory || e < 0 || e >= intrabcCrossSBHistory {
			return InterMotionResult{}, 0, false
		}
		if c.SBDiagonalMotionValidGrid[d][e] == 0 {
			return InterMotionResult{}, 0, false
		}
		return c.SBDiagonalInterMotionGrid[d][e], c.SBDiagonalBlockSizeGrid[d][e], true
	}
	if y4 < 0 {
		if !req.HaveTop {
			return InterMotionResult{}, 0, false
		}
		depth := -y4 - 1
		if depth < 0 || depth >= intrabcCrossSBHistory ||
			x4 < 0 || x4 >= MaxBlockModeSlots ||
			c.SBTopMotionValidGrid[depth][x4] == 0 {
			return InterMotionResult{}, 0, false
		}
		return c.SBTopInterMotionGrid[depth][x4], c.SBTopBlockSizeGrid[depth][x4], true
	}
	if x4 < 0 {
		if !req.HaveLeft {
			return InterMotionResult{}, 0, false
		}
		depth := -x4 - 1
		if depth < 0 || depth >= intrabcCrossSBHistory ||
			y4 < 0 || y4 >= MaxBlockModeSlots ||
			c.SBLeftMotionValidGrid[depth][y4] == 0 {
			return InterMotionResult{}, 0, false
		}
		return c.SBLeftInterMotionGrid[depth][y4], c.SBLeftBlockSizeGrid[depth][y4], true
	}
	return c.gridInterMotion(x4, y4)
}

func (c *BlockModeContext) topRightInterMotion(req ReferenceMVStackRequest, dims BlockDimensions) (InterMotionResult, BlockSize, bool) {
	x := int(req.X4) + int(dims.W4)
	y := int(req.Y4) - 1
	if y >= 0 {
		candidate, size, ok := c.gridInterMotion(x, y)
		return candidate, size, ok
	}
	if !req.HaveTop || x < 0 {
		return InterMotionResult{}, 0, false
	}
	if x >= MaxBlockModeSlots {
		// Block sits at the current SB's right edge with sbSizeMIB ==
		// MaxBlockModeSlots, so the topright cell at frame
		// mi(mi_row-1, mi_col+W4) lives in the SB-above-and-to-the-right.
		// AboveInterMotion cannot represent slot >= MaxBlockModeSlots, so the
		// SB-above-right snapshot loaded from carrier.Above[rootColIndex+1] at
		// SB load time supplies the cell. Slot indexed by offset within the
		// right SB, i.e. x - MaxBlockModeSlots when sbSizeMIB ==
		// MaxBlockModeSlots. Mirrors libaom xd->mi[-stride + xd->width].
		if !c.SBTopRightValid {
			return InterMotionResult{}, 0, false
		}
		slot := x - MaxBlockModeSlots
		if slot < 0 || slot >= MaxBlockModeSlots {
			return InterMotionResult{}, 0, false
		}
		if c.SBTopRightIntra[slot] != 0 || c.SBTopRightMotionValid[slot] == 0 {
			return InterMotionResult{}, 0, false
		}
		return c.SBTopRightInterMotion[slot], c.SBTopRightBlockSize[slot], true
	}
	if c.AboveIntra[x] != 0 || c.AboveMotionValid[x] == 0 {
		return InterMotionResult{}, 0, false
	}
	return c.AboveInterMotion[x], c.AboveBlockSize[x], true
}

func blockSizeWidth4(size BlockSize) int {
	dims, ok := size.Dimensions()
	if !ok || dims.W4 == 0 {
		return 1
	}
	return int(dims.W4)
}

func blockSizeHeight4(size BlockSize) int {
	dims, ok := size.Dimensions()
	if !ok || dims.H4 == 0 {
		return 1
	}
	return int(dims.H4)
}

// referenceMVExtensionSize ports libaom's mi_size cap on the single/compound
// ref-MV extension scans (av1_setup_ref_mv_list, mvref_common.c):
//
//	int mi_width  = AOMMIN(mi_size_wide[BLOCK_64X64], xd->width);
//	mi_width      = AOMMIN(mi_width, mi_cols - mi_col);
//	int mi_height = AOMMIN(mi_size_high[BLOCK_64X64], xd->height);
//	mi_height     = AOMMIN(mi_height, mi_rows - mi_row);
//	const int mi_size = AOMMIN(mi_width, mi_height);
//
// The BLOCK_64X64 cap (16 MI) is the key clamp the earlier dims.W4/dims.H4
// loop bounds were missing: a 128x128 block scanned its full 32-MI edge and
// folded a second left/above neighbor into the stack that libaom never reads,
// inflating ref_mv_count and reading a spurious DRL bit (svc L2T1/L2T2
// frame 1 mi=(0,32) BLOCK_128X128). The frame-edge clamp uses the tile end as
// the readable-neighbor bound (tiles never extend past the frame, so it equals
// libaom's mi_cols/mi_rows for the last tile and is dominated by the 16-MI cap
// for interior blocks).
func referenceMVExtensionSize(req ReferenceMVStackRequest, dims BlockDimensions) int {
	const block64MI = 16
	miWidth := minInt(block64MI, int(dims.W4))
	if req.TileMIColEnd > req.MICol {
		miWidth = minInt(miWidth, int(req.TileMIColEnd-req.MICol))
	}
	miHeight := minInt(block64MI, int(dims.H4))
	if req.TileMIRowEnd > req.MIRow {
		miHeight = minInt(miHeight, int(req.TileMIRowEnd-req.MIRow))
	}
	return minInt(miWidth, miHeight)
}

func (c *BlockModeContext) extendSingleReferenceMVStack(req ReferenceMVStackRequest, dims BlockDimensions, maxRowOffset int, maxColOffset int, stack *ReferenceMVStack) {
	miSize := referenceMVExtensionSize(req, dims)
	if req.HaveTop && absInt(maxRowOffset) >= 1 {
		x4 := int(req.X4)
		for off := 0; off < miSize && stack.Count < MaxMVRefCandidates; {
			slot := x4 + off
			step := c.aboveCandidateStep(slot, miSize-off)
			if c.AboveIntra[slot] == 0 && c.AboveMotionValid[slot] != 0 {
				stack.addSingleFallbackCandidate(c.AboveInterMotion[slot], req.References.Ref[0], req.RefSignBias)
			}
			off += step
		}
	}
	if req.HaveLeft && absInt(maxColOffset) >= 1 {
		y4 := int(req.Y4)
		for off := 0; off < miSize && stack.Count < MaxMVRefCandidates; {
			slot := y4 + off
			step := c.leftCandidateStep(slot, miSize-off)
			if c.LeftIntra[slot] == 0 && c.LeftMotionValid[slot] != 0 {
				stack.addSingleFallbackCandidate(c.LeftInterMotion[slot], req.References.Ref[0], req.RefSignBias)
			}
			off += step
		}
	}
	// SingleRefMVs is seeded by BuildReferenceMVStack after the final stack
	// sort so the nearest/near cache reflects libaom's mv_ref_list, which
	// libaom populates from the sorted ref_mv_stack, not the per-helper
	// insertion order.
}

func (c *BlockModeContext) extendCompoundReferenceMVStack(req ReferenceMVStackRequest, dims BlockDimensions, maxRowOffset int, maxColOffset int, stack *ReferenceMVStack) {
	if stack.Count >= MaxMVRefCandidates {
		return
	}
	var refs compoundReferenceLists
	c.collectCompoundReferenceLists(req, dims, maxRowOffset, maxColOffset, &refs)
	comp := refs.compoundList(req)
	if stack.Count == 1 {
		candidate := ReferenceMVCandidate{This: comp[0][0], Compound: comp[0][1], Weight: 2}
		if stack.Candidates[0].This == candidate.This && stack.Candidates[0].Compound == candidate.Compound {
			candidate = ReferenceMVCandidate{This: comp[1][0], Compound: comp[1][1], Weight: 2}
		}
		stack.Candidates[stack.Count] = candidate
		stack.Count++
		return
	}
	for stack.Count < MaxMVRefCandidates {
		idx := stack.Count
		stack.Candidates[stack.Count] = ReferenceMVCandidate{This: comp[idx][0], Compound: comp[idx][1], Weight: 2}
		stack.Count++
	}
}

func (c *BlockModeContext) collectCompoundReferenceLists(req ReferenceMVStackRequest, dims BlockDimensions, maxRowOffset int, maxColOffset int, lists *compoundReferenceLists) {
	miSize := referenceMVExtensionSize(req, dims)
	if req.HaveTop && absInt(maxRowOffset) >= 1 {
		x4 := int(req.X4)
		for off := 0; off < miSize; {
			slot := x4 + off
			step := c.aboveCandidateStep(slot, miSize-off)
			if c.AboveIntra[slot] == 0 && c.AboveMotionValid[slot] != 0 {
				lists.add(c.AboveInterMotion[slot], req.References.Ref, req.RefSignBias)
			}
			off += step
		}
	}
	if req.HaveLeft && absInt(maxColOffset) >= 1 {
		y4 := int(req.Y4)
		for off := 0; off < miSize; {
			slot := y4 + off
			step := c.leftCandidateStep(slot, miSize-off)
			if c.LeftIntra[slot] == 0 && c.LeftMotionValid[slot] != 0 {
				lists.add(c.LeftInterMotion[slot], req.References.Ref, req.RefSignBias)
			}
			off += step
		}
	}
}

func (c *BlockModeContext) aboveCandidateStep(slot int, remaining int) int {
	step := 1
	if c.AboveMotionValid[slot] != 0 {
		if dims, ok := c.AboveBlockSize[slot].Dimensions(); ok && int(dims.W4) > step {
			step = int(dims.W4)
		}
	}
	if step > remaining {
		step = remaining
	}
	return step
}

func (c *BlockModeContext) leftCandidateStep(slot int, remaining int) int {
	step := 1
	if c.LeftMotionValid[slot] != 0 {
		if dims, ok := c.LeftBlockSize[slot].Dimensions(); ok && int(dims.H4) > step {
			step = int(dims.H4)
		}
	}
	if step > remaining {
		step = remaining
	}
	return step
}

func validateReferenceMVStackRequest(req ReferenceMVStackRequest) (BlockDimensions, error) {
	dims, ok := req.Size.Dimensions()
	if !ok {
		return BlockDimensions{}, ErrInvalidDecodeState
	}
	x4 := int(req.X4)
	y4 := int(req.Y4)
	if err := validateBlockModeSlot(x4, y4); err != nil {
		return BlockDimensions{}, err
	}
	if x4+int(dims.W4) > MaxBlockModeSlots || y4+int(dims.H4) > MaxBlockModeSlots {
		return BlockDimensions{}, ErrInvalidDecodeState
	}
	if err := validateInterReferences(req.References); err != nil {
		return BlockDimensions{}, err
	}
	if req.TemporalMVSampleUnavailable && !req.UseRefFrameMVS {
		return BlockDimensions{}, ErrInvalidDecodeState
	}
	if req.TemporalMVs != nil && !req.UseRefFrameMVS {
		return BlockDimensions{}, ErrInvalidDecodeState
	}
	if req.TemporalMVs != nil &&
		(req.TileMIColEnd <= req.TileMIColStart || req.TileMIRowEnd <= req.TileMIRowStart ||
			req.MICol < req.TileMIColStart || req.MICol >= req.TileMIColEnd ||
			req.MIRow < req.TileMIRowStart || req.MIRow >= req.TileMIRowEnd) {
		return BlockDimensions{}, ErrInvalidDecodeState
	}
	return dims, nil
}

func validateIntrabcReferenceDVStackRequest(req ReferenceMVStackRequest) (BlockDimensions, error) {
	dims, ok := req.Size.Dimensions()
	if !ok {
		return BlockDimensions{}, ErrInvalidDecodeState
	}
	x4 := int(req.X4)
	y4 := int(req.Y4)
	if err := validateBlockModeSlot(x4, y4); err != nil {
		return BlockDimensions{}, err
	}
	if x4+int(dims.W4) > MaxBlockModeSlots || y4+int(dims.H4) > MaxBlockModeSlots {
		return BlockDimensions{}, ErrInvalidDecodeState
	}
	return dims, nil
}

func validateInterMotion(result InterMotionResult) error {
	if err := validateInterReferences(result.References); err != nil {
		return err
	}
	if result.Mode.Compound != result.References.Compound {
		return ErrInvalidDecodeState
	}
	if result.Mode.Compound {
		if !result.Mode.CompoundMode.Valid() {
			return ErrInvalidDecodeState
		}
		return nil
	}
	if !result.Mode.Mode.Valid() {
		return ErrInvalidDecodeState
	}
	return nil
}

func validateInterReferences(refs InterReferencesResult) error {
	if !refs.Ref[0].Valid() {
		return ErrInvalidDecodeState
	}
	if refs.Compound {
		if !refs.Ref[1].Valid() {
			return ErrInvalidDecodeState
		}
		return nil
	}
	if refs.Ref[1] != ReferenceFrameNone {
		return ErrInvalidDecodeState
	}
	return nil
}

func blockHasTopRight(sbSizeMIB uint8, block BlockVisit) bool {
	dims, ok := block.Size.Dimensions()
	if !ok || sbSizeMIB == 0 {
		return false
	}
	bs := maxInt(int(dims.W4), int(dims.H4))
	if bs <= 0 || bs > blockSizeWidth4(BlockSize64x64) {
		return false
	}
	sbSize := int(sbSizeMIB)
	maskRow := int(block.MIRow) & (sbSize - 1)
	maskCol := int(block.MICol) & (sbSize - 1)
	hasTopRight := !((maskRow&bs) != 0 && (maskCol&bs) != 0)
	for cur := bs; cur < sbSize; cur <<= 1 {
		if (maskCol & cur) == 0 {
			break
		}
		if (maskCol&(2*cur)) != 0 && (maskRow&(2*cur)) != 0 {
			hasTopRight = false
			break
		}
	}
	if dims.W4 < dims.H4 && !blockIsLastVerticalRect(block, dims) {
		hasTopRight = true
	}
	if dims.W4 > dims.H4 && !blockIsFirstHorizontalRect(block) {
		hasTopRight = false
	}
	return hasTopRight
}

func blockIsFirstHorizontalRect(block BlockVisit) bool {
	levelSize := int(block.Level.Size4x4())
	if levelSize <= 0 {
		return true
	}
	return (int(block.MIRow) & (levelSize - 1)) == 0
}

func blockIsLastVerticalRect(block BlockVisit, dims BlockDimensions) bool {
	levelSize := int(block.Level.Size4x4())
	if levelSize <= 0 {
		return true
	}
	return (int(block.MICol)&(levelSize-1))+int(dims.W4) >= levelSize
}

func (stack *ReferenceMVStack) addDirectCandidate(candidate InterMotionResult, candidateSize BlockSize, refs InterReferencesResult, weight uint16, globalMVs [2]motion.Vector, globalTypes [2]parser.GlobalMotionType) (int, int) {
	if refs.Compound {
		if !candidate.References.Compound ||
			candidate.References.Ref[0] != refs.Ref[0] ||
			candidate.References.Ref[1] != refs.Ref[1] {
			return 0, 0
		}
		this := candidate.MV[0]
		comp := candidate.MV[1]
		if isGlobalMVBlock(candidate.Mode, candidateSize, globalTypes[0]) {
			this = globalMVs[0]
		}
		if isGlobalMVBlock(candidate.Mode, candidateSize, globalTypes[1]) {
			comp = globalMVs[1]
		}
		stack.addOrWeight(ReferenceMVCandidate{This: this, Compound: comp}, weight)
		return 1, boolInt(candidate.Mode.usesNewMV())
	}

	matches := 0
	for ref := range 2 {
		if candidate.References.Ref[ref] != refs.Ref[0] {
			continue
		}
		mv := candidate.MV[ref]
		if isGlobalMVBlock(candidate.Mode, candidateSize, globalTypes[0]) {
			mv = globalMVs[0]
		}
		stack.addOrWeight(ReferenceMVCandidate{This: mv}, weight)
		matches++
	}
	if matches == 0 {
		return 0, 0
	}
	return matches, boolInt(candidate.Mode.usesNewMV())
}

// isGlobalMVBlock mirrors libaom's is_global_mv_block(): the candidate is
// treated as a global-motion block when its prediction mode is GLOBALMV or
// GLOBAL_GLOBALMV, the corresponding warp model is non-translational (RotZoom
// or Affine), and the candidate's smaller side is at least 8 luma samples
// (W4 >= 2 and H4 >= 2). libaom substitutes the global MV evaluated at the
// CURRENT decode block's position for such candidates so two neighbors decoded
// with the same affine model still contribute distinct ref-MV stack entries
// when the projection produces different sub-pel values at different positions.
// Without this substitution goav1 reuses the candidate's stored MV — evaluated
// at the candidate's own position — which collapses entries libaom keeps
// separate and undercounts ref_mv_count, e.g. cdf_update frame 1 block (12,4)
// where the left BLOCK_16X16 GLOBALMV neighbor dedups against the above
// BLOCK_16X8 NEARESTMV candidate.
func isGlobalMVBlock(mode InterModeResult, size BlockSize, gmType parser.GlobalMotionType) bool {
	if gmType <= parser.GlobalMotionTranslation {
		return false
	}
	if !isGlobalMode(mode) {
		return false
	}
	dims, ok := size.Dimensions()
	if !ok {
		return false
	}
	if dims.W4 < 2 || dims.H4 < 2 {
		return false
	}
	return true
}

func isGlobalMode(mode InterModeResult) bool {
	if mode.Compound {
		return mode.CompoundMode == CompoundInterModeGlobalGlobal
	}
	return mode.Mode == InterModeGlobalMV
}

func (stack *ReferenceMVStack) addSingleFallbackCandidate(candidate InterMotionResult, target ReferenceFrame, signBias [referenceFrameCount]bool) {
	// libaom's process_single_ref_mv_candidate (mvref_common.c) iterates BOTH of
	// the neighbor's reference slots unconditionally and appends each matching MV
	// to the stack with no MAX_MV_REF_CANDIDATES cap inside the helper — the
	// MAX_MV_REF_CANDIDATES gate lives only in setup_ref_mv_list's outer
	// per-neighbor loop (mirrored by extendSingleReferenceMVStack's `stack.Count <
	// MaxMVRefCandidates` loop guard). A single bi-predicted neighbor whose two
	// refs differ from the target can therefore push ref_mv_count from 1 to 3.
	// Capping this inner loop at MaxMVRefCandidates dropped the neighbor's second
	// reference, undercounting ref_mv_count by one and skipping a DRL symbol the
	// arithmetic decoder must still consume (deep alt-ref pyramids: park_joy
	// p720 q55 oh=42 mi=(16,96) NEARMV->GOLDEN read a left/above BWDREF neighbor
	// whose negated comp MV is libaom's third candidate). The stack array bound
	// (MaxRefMVStackSize) still applies via addUniqueFallback.
	for ref := 0; ref < 2; ref++ {
		candidateRef := candidate.References.Ref[ref]
		if !candidateRef.Valid() {
			continue
		}
		mv := candidate.MV[ref]
		if signBias[candidateRef] != signBias[target] {
			mv = negateMV(mv)
		}
		stack.addUniqueFallback(ReferenceMVCandidate{This: mv, Weight: 2})
	}
}

func (stack *ReferenceMVStack) addOrWeight(candidate ReferenceMVCandidate, weight uint16) {
	for i := 0; i < int(stack.Count); i++ {
		if stack.Candidates[i].This == candidate.This && stack.Candidates[i].Compound == candidate.Compound {
			stack.Candidates[i].Weight += weight
			return
		}
	}
	if stack.Count >= MaxRefMVStackSize {
		return
	}
	candidate.Weight = weight
	stack.Candidates[stack.Count] = candidate
	stack.Count++
}

func (stack *ReferenceMVStack) addUniqueFallback(candidate ReferenceMVCandidate) {
	for i := 0; i < int(stack.Count); i++ {
		if stack.Candidates[i].This == candidate.This && stack.Candidates[i].Compound == candidate.Compound {
			return
		}
	}
	if stack.Count >= MaxRefMVStackSize {
		return
	}
	stack.Candidates[stack.Count] = candidate
	stack.Count++
}

func (stack *ReferenceMVStack) setSingleRefMVs(globalMV motion.Vector) {
	for i := range MaxMVRefCandidates {
		stack.SingleRefMVs[i] = globalMV
	}
	for i := 0; i < MaxMVRefCandidates && i < int(stack.Count); i++ {
		stack.SingleRefMVs[i] = stack.Candidates[i].This
	}
	stack.SingleRefValid = true
}

func referenceMVModeContext(nearestMatch int, refMatchCount int, newMVCount int) uint16 {
	var ctx uint16
	switch nearestMatch {
	case 0:
		if refMatchCount >= 1 {
			ctx |= 1
		}
		if refMatchCount == 1 {
			ctx |= 1 << refMVOffset
		} else if refMatchCount >= 2 {
			ctx |= 2 << refMVOffset
		}
	case 1:
		if newMVCount > 0 {
			ctx |= 2
		} else {
			ctx |= 3
		}
		if refMatchCount == 1 {
			ctx |= 3 << refMVOffset
		} else if refMatchCount >= 2 {
			ctx |= 4 << refMVOffset
		}
	default:
		if newMVCount >= 1 {
			ctx |= 4
		} else {
			ctx |= 5
		}
		ctx |= 5 << refMVOffset
	}
	return ctx
}

func sortReferenceMVStack(stack *ReferenceMVStack, start int, end int) {
	if start < 0 {
		start = 0
	}
	count := int(stack.Count)
	if end > count {
		end = count
	}
	for n := end; n > start; {
		next := start
		for i := start + 1; i < n; i++ {
			if stack.Candidates[i-1].Weight < stack.Candidates[i].Weight {
				stack.Candidates[i-1], stack.Candidates[i] = stack.Candidates[i], stack.Candidates[i-1]
				next = i
			}
		}
		n = next
	}
}

func (mode InterModeResult) usesNewMV() bool {
	if mode.Compound {
		return mode.CompoundMode == CompoundInterModeNewNew ||
			mode.CompoundMode == CompoundInterModeNearestNew ||
			mode.CompoundMode == CompoundInterModeNewNearest ||
			mode.CompoundMode == CompoundInterModeNearNew ||
			mode.CompoundMode == CompoundInterModeNewNear
	}
	return mode.Mode == InterModeNewMV
}

type compoundReferenceLists struct {
	id        [2][MaxMVRefCandidates]motion.Vector
	diff      [2][MaxMVRefCandidates]motion.Vector
	idCount   [2]int
	diffCount [2]int
}

func (lists *compoundReferenceLists) add(candidate InterMotionResult, target [2]ReferenceFrame, signBias [referenceFrameCount]bool) {
	for refIdx := range 2 {
		candidateRef := candidate.References.Ref[refIdx]
		if !candidateRef.Valid() {
			continue
		}
		for cmpIdx := range 2 {
			if candidateRef == target[cmpIdx] {
				if lists.idCount[cmpIdx] < MaxMVRefCandidates {
					lists.id[cmpIdx][lists.idCount[cmpIdx]] = candidate.MV[refIdx]
					lists.idCount[cmpIdx]++
				}
				continue
			}
			if lists.diffCount[cmpIdx] < MaxMVRefCandidates {
				mv := candidate.MV[refIdx]
				if signBias[candidateRef] != signBias[target[cmpIdx]] {
					mv = negateMV(mv)
				}
				lists.diff[cmpIdx][lists.diffCount[cmpIdx]] = mv
				lists.diffCount[cmpIdx]++
			}
		}
	}
}

func (lists *compoundReferenceLists) compoundList(req ReferenceMVStackRequest) [MaxMVRefCandidates][2]motion.Vector {
	var out [MaxMVRefCandidates][2]motion.Vector
	for refIdx := range 2 {
		outIdx := 0
		for i := 0; i < lists.idCount[refIdx] && outIdx < MaxMVRefCandidates; i++ {
			out[outIdx][refIdx] = lists.id[refIdx][i]
			outIdx++
		}
		for i := 0; i < lists.diffCount[refIdx] && outIdx < MaxMVRefCandidates; i++ {
			out[outIdx][refIdx] = lists.diff[refIdx][i]
			outIdx++
		}
		for outIdx < MaxMVRefCandidates {
			out[outIdx][refIdx] = req.GlobalMVs[refIdx]
			outIdx++
		}
	}
	return out
}

func negateMV(v motion.Vector) motion.Vector {
	return motion.Vector{Row: -v.Row, Col: -v.Col}
}

func (stack ReferenceMVStack) validateCount(need int) error {
	if err := stack.validate(); err != nil {
		return err
	}
	if need < 0 || need > MaxRefMVStackSize || int(stack.Count) < need {
		return ErrInvalidDecodeState
	}
	return nil
}
