package tile

import "github.com/thesyncim/goav1/internal/av1/motion"

const (
	MaxMVRefCandidates   = 2
	MaxRefMVStackSize    = 8
	UsableRefMVStackSize = 4
	RefMVCategoryLevel   = 640
)

// InterMotionResult is the decoded inter mode plus its final motion vectors.
type InterMotionResult struct {
	References InterReferencesResult
	Mode       InterModeResult
	MV         [2]motion.Vector
}

// ReferenceMVCandidate mirrors libaom's CANDIDATE_MV/ref_mv_weight entry.
type ReferenceMVCandidate struct {
	This     motion.Vector
	Compound motion.Vector
	Weight   uint16
}

// ReferenceMVStack is the candidate stack generated by the reference-MV search.
type ReferenceMVStack struct {
	Candidates     [MaxRefMVStackSize]ReferenceMVCandidate
	Count          int
	SingleRefMVs   [MaxMVRefCandidates]motion.Vector
	SingleRefValid bool
}

// ReferenceMVStackRequest selects the spatial MV stack for one inter block.
type ReferenceMVStackRequest struct {
	Size       BlockSize
	References InterReferencesResult

	X4       int
	Y4       int
	HaveTop  bool
	HaveLeft bool

	GlobalMVs   [2]motion.Vector
	RefSignBias [referenceFrameCount]bool

	UseRefFrameMVS              bool
	TemporalMVSampleUnavailable bool
}

type ReferenceMVStackResult struct {
	Stack         ReferenceMVStack
	ModeContext   uint16
	NearestCount  int
	RowMatches    int
	ColumnMatches int
	NewMVMatches  int
}

// InterMVReferenceSet contains the stack-derived MV bases needed before MV
// residual syntax is applied.
type InterMVReferenceSet struct {
	Nearest  [2]motion.Vector
	Near     [2]motion.Vector
	Residual [2]motion.Vector
}

// DRLContext returns libaom's av1_drl_ctx()/dav1d's get_drl_context() value.
func (stack ReferenceMVStack) DRLContext(refIdx int) (int, error) {
	if err := stack.validate(); err != nil {
		return 0, err
	}
	if refIdx < 0 || refIdx+1 >= stack.Count {
		return 0, ErrInvalidDecodeState
	}
	cur := stack.Candidates[refIdx].Weight >= RefMVCategoryLevel
	next := stack.Candidates[refIdx+1].Weight >= RefMVCategoryLevel
	switch {
	case cur && next:
		return 0, nil
	case cur && !next:
		return 1, nil
	case !cur && !next:
		return 2, nil
	default:
		return 0, nil
	}
}

// DRLContexts returns the three contexts read_drl_idx may consult.
func (stack ReferenceMVStack) DRLContexts() ([3]int, error) {
	var contexts [3]int
	if err := stack.validate(); err != nil {
		return contexts, err
	}
	for i := range contexts {
		if i+1 >= stack.Count {
			break
		}
		ctx, err := stack.DRLContext(i)
		if err != nil {
			return contexts, err
		}
		contexts[i] = ctx
	}
	return contexts, nil
}

// DRLRequestForMode builds the DRL syntax request for a decoded inter mode.
func (stack ReferenceMVStack) DRLRequestForMode(mode InterModeResult) (DRLRequest, error) {
	if mode.Compound {
		if !mode.CompoundMode.Valid() {
			return DRLRequest{}, ErrInvalidDecodeState
		}
	} else if !mode.Mode.Valid() {
		return DRLRequest{}, ErrInvalidDecodeState
	}
	contexts, err := stack.DRLContexts()
	if err != nil {
		return DRLRequest{}, err
	}
	return DRLRequest{
		Mode:         mode.Mode,
		CompoundMode: mode.CompoundMode,
		Compound:     mode.Compound,
		RefMVCount:   stack.Count,
		Contexts:     contexts,
	}, nil
}

// BestSingleReferenceMVs returns av1_find_best_ref_mvs()'s nearest/near pair.
func (stack ReferenceMVStack) BestSingleReferenceMVs(allowHighPrecision bool, forceInteger bool) (motion.Vector, motion.Vector, error) {
	if stack.SingleRefValid {
		nearest := motion.LowerPrecision(stack.SingleRefMVs[0], allowHighPrecision, forceInteger)
		near := motion.LowerPrecision(stack.SingleRefMVs[1], allowHighPrecision, forceInteger)
		return nearest, near, nil
	}
	if err := stack.validateCount(MaxMVRefCandidates); err != nil {
		return motion.Vector{}, motion.Vector{}, err
	}
	nearest := motion.LowerPrecision(stack.Candidates[0].This, allowHighPrecision, forceInteger)
	near := motion.LowerPrecision(stack.Candidates[1].This, allowHighPrecision, forceInteger)
	return nearest, near, nil
}

// ResolveInterMVReferences ports the stack-selection part of libaom's
// read_inter_block_mode_info()/assign_mv() path before MV residual bits.
func (stack ReferenceMVStack) ResolveInterMVReferences(mode InterModeResult, refMVIndex int, allowHighPrecision bool, forceInteger bool) (InterMVReferenceSet, error) {
	if err := stack.validate(); err != nil {
		return InterMVReferenceSet{}, err
	}
	if refMVIndex < 0 || refMVIndex >= UsableRefMVStackSize {
		return InterMVReferenceSet{}, ErrInvalidDecodeState
	}
	if mode.Compound {
		return stack.resolveCompoundInterMVReferences(mode.CompoundMode, refMVIndex, allowHighPrecision, forceInteger)
	}
	return stack.resolveSingleInterMVReferences(mode.Mode, refMVIndex, allowHighPrecision, forceInteger)
}

func (stack ReferenceMVStack) resolveSingleInterMVReferences(mode InterMode, refMVIndex int, allowHighPrecision bool, forceInteger bool) (InterMVReferenceSet, error) {
	if !mode.Valid() || mode == InterModeGlobalMV {
		return InterMVReferenceSet{}, ErrInvalidDecodeState
	}
	nearest, near, err := stack.BestSingleReferenceMVs(allowHighPrecision, forceInteger)
	if err != nil {
		return InterMVReferenceSet{}, err
	}
	if mode == InterModeNearMV && refMVIndex > 0 {
		candidate, err := stack.candidate(1 + refMVIndex)
		if err != nil {
			return InterMVReferenceSet{}, err
		}
		near = candidate.This
	}
	refs := InterMVReferenceSet{
		Nearest:  [2]motion.Vector{nearest},
		Near:     [2]motion.Vector{near},
		Residual: [2]motion.Vector{nearest},
	}
	if mode == InterModeNewMV && stack.Count > 1 {
		candidate, err := stack.candidate(refMVIndex)
		if err != nil {
			return InterMVReferenceSet{}, err
		}
		refs.Residual[0] = candidate.This
	}
	return refs, nil
}

func (stack ReferenceMVStack) resolveCompoundInterMVReferences(mode CompoundInterMode, refMVIndex int, allowHighPrecision bool, forceInteger bool) (InterMVReferenceSet, error) {
	if !mode.Valid() || mode == CompoundInterModeGlobalGlobal {
		return InterMVReferenceSet{}, ErrInvalidDecodeState
	}
	nearestCandidate, err := stack.candidate(0)
	if err != nil {
		return InterMVReferenceSet{}, err
	}
	nearCandidate, err := stack.candidate(1 + refMVIndex)
	if err != nil {
		return InterMVReferenceSet{}, err
	}
	refs := InterMVReferenceSet{
		Nearest: [2]motion.Vector{
			motion.LowerPrecision(nearestCandidate.This, allowHighPrecision, forceInteger),
			motion.LowerPrecision(nearestCandidate.Compound, allowHighPrecision, forceInteger),
		},
		Near: [2]motion.Vector{
			motion.LowerPrecision(nearCandidate.This, allowHighPrecision, forceInteger),
			motion.LowerPrecision(nearCandidate.Compound, allowHighPrecision, forceInteger),
		},
	}
	refs.Residual = refs.Nearest

	components, err := mode.Components()
	if err != nil {
		return InterMVReferenceSet{}, err
	}
	residualIndex := refMVIndex
	if mode == CompoundInterModeNearNew || mode == CompoundInterModeNewNear {
		residualIndex = 1 + refMVIndex
	}
	residualCandidate, err := stack.candidate(residualIndex)
	if err != nil {
		return InterMVReferenceSet{}, err
	}
	if components.First == InterModeNewMV {
		refs.Residual[0] = residualCandidate.This
	}
	if components.Second == InterModeNewMV {
		refs.Residual[1] = residualCandidate.Compound
	}
	return refs, nil
}

func (stack ReferenceMVStack) candidate(index int) (ReferenceMVCandidate, error) {
	if err := stack.validate(); err != nil {
		return ReferenceMVCandidate{}, err
	}
	if index < 0 || index >= stack.Count {
		return ReferenceMVCandidate{}, ErrInvalidDecodeState
	}
	return stack.Candidates[index], nil
}

func (stack ReferenceMVStack) validate() error {
	if stack.Count < 0 || stack.Count > MaxRefMVStackSize {
		return ErrInvalidDecodeState
	}
	return nil
}

// MarkInterMotion updates the top/left context once a block's inter MVs are known.
func (c *BlockModeContext) MarkInterMotion(size BlockSize, x4 int, y4 int, result InterMotionResult) error {
	if err := validateInterMotion(result); err != nil {
		return err
	}
	if err := c.MarkInter(size, x4, y4, result.References); err != nil {
		return err
	}
	dims, ok := size.Dimensions()
	if !ok {
		return ErrInvalidDecodeState
	}
	for i := 0; i < int(dims.W4); i++ {
		c.AboveInterMotion[x4+i] = result
		c.AboveMotionValid[x4+i] = 1
		c.AboveBlockSize[x4+i] = size
	}
	for i := 0; i < int(dims.H4); i++ {
		c.LeftInterMotion[y4+i] = result
		c.LeftMotionValid[y4+i] = 1
		c.LeftBlockSize[y4+i] = size
	}
	return nil
}

// BuildReferenceMVStack ports the spatial part of libaom's setup_ref_mv_list()
// for the immediate above row and left column tracked by BlockModeContext.
func (c *BlockModeContext) BuildReferenceMVStack(req ReferenceMVStackRequest) (ReferenceMVStackResult, error) {
	if c == nil {
		return ReferenceMVStackResult{}, ErrInvalidDecodeState
	}
	dims, err := validateReferenceMVStackRequest(req)
	if err != nil {
		return ReferenceMVStackResult{}, err
	}

	var result ReferenceMVStackResult
	if req.HaveTop {
		c.scanAboveReferenceMVs(req, dims, &result)
	}
	if req.HaveLeft {
		c.scanLeftReferenceMVs(req, dims, &result)
	}
	nearestMatch := boolInt(result.RowMatches > 0) + boolInt(result.ColumnMatches > 0)
	refMatchCount := nearestMatch
	result.NearestCount = result.Stack.Count
	for i := 0; i < result.NearestCount; i++ {
		result.Stack.Candidates[i].Weight += RefMVCategoryLevel
	}
	result.ModeContext = referenceMVModeContext(nearestMatch, refMatchCount, result.NewMVMatches)
	if req.UseRefFrameMVS && req.TemporalMVSampleUnavailable {
		result.ModeContext |= 1 << globalMVOffset
	}
	sortReferenceMVStack(&result.Stack, 0, result.NearestCount)

	if req.References.Compound {
		c.extendCompoundReferenceMVStack(req, dims, &result.Stack)
	} else {
		c.extendSingleReferenceMVStack(req, dims, &result.Stack)
	}
	sortReferenceMVStack(&result.Stack, result.NearestCount, result.Stack.Count)
	return result, nil
}

func (c *BlockModeContext) scanAboveReferenceMVs(req ReferenceMVStackRequest, dims BlockDimensions, result *ReferenceMVStackResult) {
	for off := 0; off < int(dims.W4); {
		slot := req.X4 + off
		step := c.aboveCandidateStep(slot, int(dims.W4)-off)
		if c.AboveIntra[slot] == 0 && c.AboveMotionValid[slot] != 0 {
			matches, newMatches := result.Stack.addDirectCandidate(c.AboveInterMotion[slot], req.References, uint16(step*2))
			result.RowMatches += matches
			result.NewMVMatches += newMatches
		}
		off += step
	}
}

func (c *BlockModeContext) scanLeftReferenceMVs(req ReferenceMVStackRequest, dims BlockDimensions, result *ReferenceMVStackResult) {
	for off := 0; off < int(dims.H4); {
		slot := req.Y4 + off
		step := c.leftCandidateStep(slot, int(dims.H4)-off)
		if c.LeftIntra[slot] == 0 && c.LeftMotionValid[slot] != 0 {
			matches, newMatches := result.Stack.addDirectCandidate(c.LeftInterMotion[slot], req.References, uint16(step*2))
			result.ColumnMatches += matches
			result.NewMVMatches += newMatches
		}
		off += step
	}
}

func (c *BlockModeContext) extendSingleReferenceMVStack(req ReferenceMVStackRequest, dims BlockDimensions, stack *ReferenceMVStack) {
	if req.HaveTop {
		for off := 0; off < int(dims.W4) && stack.Count < MaxMVRefCandidates; {
			slot := req.X4 + off
			step := c.aboveCandidateStep(slot, int(dims.W4)-off)
			if c.AboveIntra[slot] == 0 && c.AboveMotionValid[slot] != 0 {
				stack.addSingleFallbackCandidate(c.AboveInterMotion[slot], req.References.Ref[0], req.RefSignBias)
			}
			off += step
		}
	}
	if req.HaveLeft {
		for off := 0; off < int(dims.H4) && stack.Count < MaxMVRefCandidates; {
			slot := req.Y4 + off
			step := c.leftCandidateStep(slot, int(dims.H4)-off)
			if c.LeftIntra[slot] == 0 && c.LeftMotionValid[slot] != 0 {
				stack.addSingleFallbackCandidate(c.LeftInterMotion[slot], req.References.Ref[0], req.RefSignBias)
			}
			off += step
		}
	}
	stack.setSingleRefMVs(req.GlobalMVs[0])
}

func (c *BlockModeContext) extendCompoundReferenceMVStack(req ReferenceMVStackRequest, dims BlockDimensions, stack *ReferenceMVStack) {
	if stack.Count >= MaxMVRefCandidates {
		return
	}
	var refs compoundReferenceLists
	c.collectCompoundReferenceLists(req, dims, &refs)
	comp := refs.compoundList(req)
	if stack.Count == 1 {
		candidate := ReferenceMVCandidate{This: comp[0][0], Compound: comp[0][1], Weight: 2}
		if stack.Candidates[0].This == candidate.This && stack.Candidates[0].Compound == candidate.Compound {
			candidate = ReferenceMVCandidate{This: comp[1][0], Compound: comp[1][1], Weight: 2}
		}
		stack.Candidates[stack.Count] = candidate
		stack.Count++
		return
	}
	for stack.Count < MaxMVRefCandidates {
		idx := stack.Count
		stack.Candidates[stack.Count] = ReferenceMVCandidate{This: comp[idx][0], Compound: comp[idx][1], Weight: 2}
		stack.Count++
	}
}

func (c *BlockModeContext) collectCompoundReferenceLists(req ReferenceMVStackRequest, dims BlockDimensions, lists *compoundReferenceLists) {
	if req.HaveTop {
		for off := 0; off < int(dims.W4); {
			slot := req.X4 + off
			step := c.aboveCandidateStep(slot, int(dims.W4)-off)
			if c.AboveIntra[slot] == 0 && c.AboveMotionValid[slot] != 0 {
				lists.add(c.AboveInterMotion[slot], req.References.Ref, req.RefSignBias)
			}
			off += step
		}
	}
	if req.HaveLeft {
		for off := 0; off < int(dims.H4); {
			slot := req.Y4 + off
			step := c.leftCandidateStep(slot, int(dims.H4)-off)
			if c.LeftIntra[slot] == 0 && c.LeftMotionValid[slot] != 0 {
				lists.add(c.LeftInterMotion[slot], req.References.Ref, req.RefSignBias)
			}
			off += step
		}
	}
}

func (c *BlockModeContext) aboveCandidateStep(slot int, remaining int) int {
	step := 1
	if c.AboveMotionValid[slot] != 0 {
		if dims, ok := c.AboveBlockSize[slot].Dimensions(); ok && int(dims.W4) > step {
			step = int(dims.W4)
		}
	}
	if step > remaining {
		step = remaining
	}
	return step
}

func (c *BlockModeContext) leftCandidateStep(slot int, remaining int) int {
	step := 1
	if c.LeftMotionValid[slot] != 0 {
		if dims, ok := c.LeftBlockSize[slot].Dimensions(); ok && int(dims.H4) > step {
			step = int(dims.H4)
		}
	}
	if step > remaining {
		step = remaining
	}
	return step
}

func validateReferenceMVStackRequest(req ReferenceMVStackRequest) (BlockDimensions, error) {
	dims, ok := req.Size.Dimensions()
	if !ok {
		return BlockDimensions{}, ErrInvalidDecodeState
	}
	if err := validateBlockModeSlot(req.X4, req.Y4); err != nil {
		return BlockDimensions{}, err
	}
	if req.X4+int(dims.W4) > MaxBlockModeSlots || req.Y4+int(dims.H4) > MaxBlockModeSlots {
		return BlockDimensions{}, ErrInvalidDecodeState
	}
	if err := validateInterReferences(req.References); err != nil {
		return BlockDimensions{}, err
	}
	if req.TemporalMVSampleUnavailable && !req.UseRefFrameMVS {
		return BlockDimensions{}, ErrInvalidDecodeState
	}
	return dims, nil
}

func validateInterMotion(result InterMotionResult) error {
	if err := validateInterReferences(result.References); err != nil {
		return err
	}
	if result.Mode.Compound != result.References.Compound {
		return ErrInvalidDecodeState
	}
	if result.Mode.Compound {
		if !result.Mode.CompoundMode.Valid() {
			return ErrInvalidDecodeState
		}
		return nil
	}
	if !result.Mode.Mode.Valid() {
		return ErrInvalidDecodeState
	}
	return nil
}

func validateInterReferences(refs InterReferencesResult) error {
	if !refs.Ref[0].Valid() {
		return ErrInvalidDecodeState
	}
	if refs.Compound {
		if !refs.Ref[1].Valid() {
			return ErrInvalidDecodeState
		}
		return nil
	}
	if refs.Ref[1] != ReferenceFrameNone {
		return ErrInvalidDecodeState
	}
	return nil
}

func (stack *ReferenceMVStack) addDirectCandidate(candidate InterMotionResult, refs InterReferencesResult, weight uint16) (int, int) {
	if refs.Compound {
		if !candidate.References.Compound ||
			candidate.References.Ref[0] != refs.Ref[0] ||
			candidate.References.Ref[1] != refs.Ref[1] {
			return 0, 0
		}
		stack.addOrWeight(ReferenceMVCandidate{This: candidate.MV[0], Compound: candidate.MV[1]}, weight)
		return 1, boolInt(candidate.Mode.usesNewMV())
	}

	matches := 0
	for ref := 0; ref < 2; ref++ {
		if candidate.References.Ref[ref] != refs.Ref[0] {
			continue
		}
		stack.addOrWeight(ReferenceMVCandidate{This: candidate.MV[ref]}, weight)
		matches++
	}
	if matches == 0 {
		return 0, 0
	}
	return matches, boolInt(candidate.Mode.usesNewMV())
}

func (stack *ReferenceMVStack) addSingleFallbackCandidate(candidate InterMotionResult, target ReferenceFrame, signBias [referenceFrameCount]bool) {
	for ref := 0; ref < 2 && stack.Count < MaxMVRefCandidates; ref++ {
		candidateRef := candidate.References.Ref[ref]
		if !candidateRef.Valid() {
			continue
		}
		mv := candidate.MV[ref]
		if signBias[candidateRef] != signBias[target] {
			mv = negateMV(mv)
		}
		stack.addUniqueFallback(ReferenceMVCandidate{This: mv, Weight: 2})
	}
}

func (stack *ReferenceMVStack) addOrWeight(candidate ReferenceMVCandidate, weight uint16) {
	for i := 0; i < stack.Count; i++ {
		if stack.Candidates[i].This == candidate.This && stack.Candidates[i].Compound == candidate.Compound {
			stack.Candidates[i].Weight += weight
			return
		}
	}
	if stack.Count >= MaxRefMVStackSize {
		return
	}
	candidate.Weight = weight
	stack.Candidates[stack.Count] = candidate
	stack.Count++
}

func (stack *ReferenceMVStack) addUniqueFallback(candidate ReferenceMVCandidate) {
	for i := 0; i < stack.Count; i++ {
		if stack.Candidates[i].This == candidate.This && stack.Candidates[i].Compound == candidate.Compound {
			return
		}
	}
	if stack.Count >= MaxRefMVStackSize {
		return
	}
	stack.Candidates[stack.Count] = candidate
	stack.Count++
}

func (stack *ReferenceMVStack) setSingleRefMVs(globalMV motion.Vector) {
	for i := 0; i < MaxMVRefCandidates; i++ {
		stack.SingleRefMVs[i] = globalMV
	}
	for i := 0; i < MaxMVRefCandidates && i < stack.Count; i++ {
		stack.SingleRefMVs[i] = stack.Candidates[i].This
	}
	stack.SingleRefValid = true
}

func referenceMVModeContext(nearestMatch int, refMatchCount int, newMVCount int) uint16 {
	var ctx uint16
	switch nearestMatch {
	case 0:
		if refMatchCount >= 1 {
			ctx |= 1
		}
		if refMatchCount == 1 {
			ctx |= 1 << refMVOffset
		} else if refMatchCount >= 2 {
			ctx |= 2 << refMVOffset
		}
	case 1:
		if newMVCount > 0 {
			ctx |= 2
		} else {
			ctx |= 3
		}
		if refMatchCount == 1 {
			ctx |= 3 << refMVOffset
		} else if refMatchCount >= 2 {
			ctx |= 4 << refMVOffset
		}
	default:
		if newMVCount >= 1 {
			ctx |= 4
		} else {
			ctx |= 5
		}
		ctx |= 5 << refMVOffset
	}
	return ctx
}

func sortReferenceMVStack(stack *ReferenceMVStack, start int, end int) {
	if start < 0 {
		start = 0
	}
	if end > stack.Count {
		end = stack.Count
	}
	for n := end; n > start; {
		next := start
		for i := start + 1; i < n; i++ {
			if stack.Candidates[i-1].Weight < stack.Candidates[i].Weight {
				stack.Candidates[i-1], stack.Candidates[i] = stack.Candidates[i], stack.Candidates[i-1]
				next = i
			}
		}
		n = next
	}
}

func (mode InterModeResult) usesNewMV() bool {
	if mode.Compound {
		return mode.CompoundMode == CompoundInterModeNewNew ||
			mode.CompoundMode == CompoundInterModeNearestNew ||
			mode.CompoundMode == CompoundInterModeNewNearest ||
			mode.CompoundMode == CompoundInterModeNearNew ||
			mode.CompoundMode == CompoundInterModeNewNear
	}
	return mode.Mode == InterModeNewMV
}

type compoundReferenceLists struct {
	id        [2][MaxMVRefCandidates]motion.Vector
	diff      [2][MaxMVRefCandidates]motion.Vector
	idCount   [2]int
	diffCount [2]int
}

func (lists *compoundReferenceLists) add(candidate InterMotionResult, target [2]ReferenceFrame, signBias [referenceFrameCount]bool) {
	for refIdx := 0; refIdx < 2; refIdx++ {
		candidateRef := candidate.References.Ref[refIdx]
		if !candidateRef.Valid() {
			continue
		}
		for cmpIdx := 0; cmpIdx < 2; cmpIdx++ {
			if candidateRef == target[cmpIdx] {
				if lists.idCount[cmpIdx] < MaxMVRefCandidates {
					lists.id[cmpIdx][lists.idCount[cmpIdx]] = candidate.MV[refIdx]
					lists.idCount[cmpIdx]++
				}
				continue
			}
			if lists.diffCount[cmpIdx] < MaxMVRefCandidates {
				mv := candidate.MV[refIdx]
				if signBias[candidateRef] != signBias[target[cmpIdx]] {
					mv = negateMV(mv)
				}
				lists.diff[cmpIdx][lists.diffCount[cmpIdx]] = mv
				lists.diffCount[cmpIdx]++
			}
		}
	}
}

func (lists *compoundReferenceLists) compoundList(req ReferenceMVStackRequest) [MaxMVRefCandidates][2]motion.Vector {
	var out [MaxMVRefCandidates][2]motion.Vector
	for refIdx := 0; refIdx < 2; refIdx++ {
		outIdx := 0
		for i := 0; i < lists.idCount[refIdx] && outIdx < MaxMVRefCandidates; i++ {
			out[outIdx][refIdx] = lists.id[refIdx][i]
			outIdx++
		}
		for i := 0; i < lists.diffCount[refIdx] && outIdx < MaxMVRefCandidates; i++ {
			out[outIdx][refIdx] = lists.diff[refIdx][i]
			outIdx++
		}
		for outIdx < MaxMVRefCandidates {
			out[outIdx][refIdx] = req.GlobalMVs[refIdx]
			outIdx++
		}
	}
	return out
}

func negateMV(v motion.Vector) motion.Vector {
	return motion.Vector{Row: -v.Row, Col: -v.Col}
}

func (stack ReferenceMVStack) validateCount(need int) error {
	if err := stack.validate(); err != nil {
		return err
	}
	if need < 0 || need > MaxRefMVStackSize || stack.Count < need {
		return ErrInvalidDecodeState
	}
	return nil
}
